### PR TITLE
etcdctl: handle empty key permission correctly

### LINKED ISSUE #8494: etcdctl role grant-permission --from-key '' is not effect
`etcdctl role grant-permission view --from-key read  ''` cause `etcdctl role get view` shows
```
Role view
KV Read:
	[, <open ended> (prefix )
KV Write:
```
But then I use `etcdctl --user view get '' --from-key` it alerts `Error:  etcdserver: permission denied`
So is it a bug, or I do something wrong for granting permission to read all keys?

### PR DESCRIPTION
**Pull request by mitake**
Current `etcdctl role grant-permission` doesn't handle an empty key
("") correctly. Because the range permissions are treated as
BytesAffineInterval internally, just specifying the empty key as a
beginning of range introduces an invalid permission which doesn't work
and betray users' intuition. This commit Fix the way of handling empty
key as a prefix or from key in permission granting.

Fix #8494 

/cc @zyf0330 @heyitsanthony

### CODE REVIEW

File: etcdctl/ctlv3/command/role_command.go [hunk 1]
```diff
@@ -170,11 +170,30 @@ func roleGrantPermissionCommandFunc(cmd *cobra.Command, args []string) {
 		ExitWithError(ExitBadArgs, err)
 	}
 
-	rangeEnd, rerr := rangeEndFromPermFlags(args[2:])
-	if rerr != nil {
-		ExitWithError(ExitBadArgs, rerr)
+	key := args[2]
```
Comment (heyitsanthony) [inline etcdctl/ctlv3/command/role_command.go]: dedup code into shared function?

```go
key, rangeEnd := permRange(args[2:])
```

Comment (mitake) [reply etcdctl/ctlv3/command/role_command.go]: ok, I'll dedup them. Thanks for the comment.

**Comment by mitake** [comment]
@heyitsanthony updated based on your comment, could you take a look?

File: etcdctl/ctlv3/command/role_command.go [hunk 2]
```diff
@@ -188,17 +185,41 @@ func roleRevokePermissionCommandFunc(cmd *cobra.Command, args []string) {
...
 
+func permRange(args []string) (string, string) {
+	key := args[0]
+	var rangeEnd string
+	if len(key) == 0 {
+		// Range permission is expressed as adt.BytesAffineInterval,
+		// so the empty prefix which should be matched with every key must be like this ["\x00", <end>).
+		key = "\x00"
+		if rolePermPrefix || rolePermFromKey {
+			if rolePermPrefix && rolePermFromKey {
```
Comment (gyuho) [inline etcdctl/ctlv3/command/role_command.go]: This `if rolePermPrefix && rolePermFromKey` block can be before `if rolePermPrefix || rolePermFromKey {`?

Comment (mitake) [reply etcdctl/ctlv3/command/role_command.go]: Yes, they should be swapped clearly... thanks for pointing out!

**Comment by mitake** [comment]
@heyitsanthony @gyuho updated based on @gyuho 's latest comment, could you take a look?

**Comment by mitake** [comment]
@heyitsanthony thanks, I'm merging it.
