### PR TITLE
etcdctl/v3: add keep alive time/timeout

### LINKED ISSUE #7941: etcd client v3 can switch addr in endpoints like v2?
etcd v2 will switch address in endpoints when request fail. But I use etcd v3, and it looks like not switch when fail.

Is there any parameter need set to open it?

### PR DESCRIPTION
**Pull request by YuleiXiao**
etcdctl: add keep alive time/timeout in etcdctl

client can switch from fault node to normal when keep alive is timeout

Fixes #7941

### CODE REVIEW

File: etcdctl/ctlv3/ctl.go [hunk 1]
```diff
@@ -51,6 +53,8 @@ func init() {
 
 	rootCmd.PersistentFlags().DurationVar(&globalFlags.DialTimeout, "dial-timeout", defaultDialTimeout, "dial timeout for client connections")
 	rootCmd.PersistentFlags().DurationVar(&globalFlags.CommandTimeOut, "command-timeout", defaultCommandTimeOut, "timeout for short running command (excluding dial timeout)")
+	rootCmd.PersistentFlags().DurationVar(&globalFlags.KeepAliveTime, "keep-alive-time", defaultKeepAliveTime, "keep alive time for client connections")
```
Comment (gyuho) [inline etcdctl/ctlv3/ctl.go]: `s/keep-alive/keepalive/` and `s/"keep alive/"keepalive/`

File: etcdctl/ctlv3/ctl.go [hunk 2]
```diff
@@ -51,6 +53,8 @@ func init() {
...
+	rootCmd.PersistentFlags().DurationVar(&globalFlags.KeepAliveTimeout, "keep-alive-timeout", defaultKeepAliveTimeOut, "keep alive timeout for client connections")
```
Comment (gyuho) [inline etcdctl/ctlv3/ctl.go]: `s/keep-alive/keepalive/` and `s/"keep alive/"keepalive/`

File: etcdctl/ctlv3/command/global.go [hunk 3]
```diff
@@ -207,6 +217,22 @@ func dialTimeoutFromCmd(cmd *cobra.Command) time.Duration {
 	return dialTimeout
 }
 
+func keepAliveTimeFromCmd(cmd *cobra.Command) time.Duration {
+	keepAliveTime, err := cmd.Flags().GetDuration("keep-alive-time")
```
Comment (gyuho) [inline etcdctl/ctlv3/command/global.go]: `s/keep-alive/keepalive/`

File: etcdctl/ctlv3/command/global.go [hunk 4]
```diff
@@ -207,6 +217,22 @@ func dialTimeoutFromCmd(cmd *cobra.Command) time.Duration {
...
+	if err != nil {
+		ExitWithError(ExitError, err)
+	}
+	return keepAliveTime
+}
+
+func keepAliveTimeoutFromCmd(cmd *cobra.Command) time.Duration {
+	keepAliveTimeout, err := cmd.Flags().GetDuration("keep-alive-timeout")
```
Comment (gyuho) [inline etcdctl/ctlv3/command/global.go]: `s/keep-alive/keepalive/`

File: etcdctl/ctlv3/ctl.go (hunk 1 above)
Comment (YuleiXiao) [reply etcdctl/ctlv3/ctl.go]: OK, I thought they are two words.

**Comment by xiang90** [comment]
lgtm

**Comment by xiang90** [comment]
defer to @gyuho.
