### PR TITLE
migrate/starter: fix --version output

### LINKED ISSUE #2211: --version is broken
```
alex@alex ~/trunk/src/scripts $ /build/amd64-usr/usr/libexec/etcd/internal_versions/2.0.0 --version
flag needs an argument: -version
Usage of full flagset:
  -addr=: 
  -advertise-client-urls=: 
  -bind-addr=: 
  -ca-file=: 
  -cert-file=: 
  -cluster-active-size=: 
  -cluster-remove-delay=: 
  -cluster-sync-interval=: 
  -config=: 
  -cors=: 
  -data-dir=: 
  -discovery=: 
  -discovery-fallback=: 
  -discovery-proxy=: 
  -discovery-srv=: 
  -election-timeout=: 
  -force=: 
  -force-new-cluster=: 
  -heartbeat-interval=: 
  -initial-advertise-peer-urls=: 
  -initial-cluster=: 
  -initial-cluster-state=: 
  -initial-cluster-token=: 
  -key-file=: 
  -listen-client-urls=: 
  -listen-peer-urls=: 
  -max-result-buffer=: 
  -max-retry-attempts=: 
  -max-snapshots=: 
  -max-wals=: 
  -name=: 
  -peer-addr=: 
  -peer-bind-addr=: 
  -peer-ca-file=: 
  -peer-cert-file=: 
  -peer-election-timeout=: 
  -peer-heartbeat-interval=: 
  -peer-key-file=: 
  -peers=: 
  -peers-file=: 
  -proxy=: 
  -retry-interval=: 
  -snapshot=: 
  -snapshot-count=: 
  -v=: 
  -version=: 
  -vv=: 
etcd version 2.0.0
```

```
alex@alex ~/trunk/src/scripts $ /build/amd64-usr/usr/libexec/etcd/internal_versions/2.0.0 --version=1
2015/02/02 17:13:57 migrate: please set ETCD_DATA_DIR for etcd
```

### PR DESCRIPTION
**Pull request by yichengq**
fixes #2211

### CODE REVIEW

File: migrate/starter/starter.go [hunk 1]
```diff
@@ -269,6 +275,8 @@ func (v *value) Set(s string) error {
 	return nil
 }
 
+func (v *value) IsBoolFlag() bool { return true }
```
Comment (xiang90) [inline migrate/starter/starter.go]: where do you use this func?

File: migrate/starter/starter.go [hunk 2]
```diff
@@ -61,6 +62,11 @@ func checkStartVersion(args []string) version {
 	if err != nil {
 		return internalV2
 	}
+	if fs.Lookup("version").Value.String() == "true" {
+		fmt.Println("etcd version:", etcdversion.Version, "(allow legacy mode)")
```
Comment (xiang90) [inline migrate/starter/starter.go]: hrm... why do you want to have `(...)`?

Comment (crawford) [inline migrate/starter/starter.go]: Why is "(allow legacy mode)" part of the version string?

File: migrate/starter/starter.go [hunk 3]
```diff
@@ -61,6 +62,11 @@ func checkStartVersion(args []string) version {
 	if err != nil {
 		return internalV2
 	}
+	if fs.Lookup("version").Value.String() == "true" {
```
Comment (crawford) [inline migrate/starter/starter.go]: Does this still evaluate true if I use `--version=foo`?

Comment (yichengq) [inline migrate/starter/starter.go]: No. standard flag doesn't parse it as true.
http://godoc.org/flag#Value

File: migrate/starter/starter.go (hunk 2 above)
Comment (yichengq) [inline migrate/starter/starter.go]: it is in a mixed state, which can use v2 in the following, or exec v0.4 if it doesn't upgrade. I have concerns that users have false thoughts that etcd v2.0 can run v0.4 data dir directly.

File: migrate/starter/starter.go (hunk 1 above)
Comment (yichengq) [inline migrate/starter/starter.go]: When this func is set, value is not necessary to be set for the flag(`--version` is accepted too). It helps to parse bool flags correctly.

File: migrate/starter/starter.go (hunk 2 above)
Comment (crawford) [inline migrate/starter/starter.go]: So the version number is dependent on the data dir?

Comment (crawford) [inline migrate/starter/starter.go]: That seems incorrect.

File: migrate/starter/starter.go (hunk 3 above)
Comment (crawford) [inline migrate/starter/starter.go]: OK. (I hate the golang flag implementation)

File: migrate/starter/starter.go (hunk 2 above)
Comment (yichengq) [inline migrate/starter/starter.go]: The version number in this mode is always '2.0.0 (allow legacy mode)'. It exec 2.0 for 2.0 data dir, and exec 0.4 for 0.4 data dir.

Comment (crawford) [inline migrate/starter/starter.go]: The `--version` flag should indicate the version of the binary.

>I have concerns that users have false thoughts that etcd v2.0 can run v0.4 data dir directly.

Is that not true? I thought the point of etcd v2.0 was that it could run both (by exec'ing the older etcd).

Comment (yichengq) [inline migrate/starter/starter.go]: @crawford It is a little different between these two. When running etcd v2.0, it autoupgrades the data dir and runs it in 2.0 way. While running etcd v2.0 (allow legacy mode), it syscall.Exec v0.4 binary to run v0.4 data dir in old way if not upgraded. It doesn't change the underlying data.

Comment (brianredbeard) [inline migrate/starter/starter.go]: It's important that `--version` reference the version number of the binary.  If a user needs to check the version of their data directory that's fine, but the standard flag is not (in my humble opinion) the place to be doing that.

Comment (yichengq) [inline migrate/starter/starter.go]: k. will change

**Comment by yichengq** [comment]
refreshed. /cc @crawford @brianredbeard

File: migrate/starter/starter.go [hunk 4]
```diff
@@ -89,6 +90,11 @@ func StartDesiredVersion(args []string) {
 }
 
 func checkInternalVersion(fs *flag.FlagSet) version {
+	if fs.Lookup("version").Value.String() == "true" {
```
Comment (crawford) [inline migrate/starter/starter.go]: Does it make more sense for this to be in StartDesiredVersion()?

Comment (yichengq) [inline migrate/starter/starter.go]: yep. moved.

**Comment by crawford** [comment]
lgtm
