### PR TITLE
*: fix snapshot sending cycle

### LINKED ISSUE #4055: do not compact log entries when sending large snapshot
For v3, the snapshot can be as large as 5GB. The end to end recovering time can be 60 seconds to 180 seconds.

Now etcd compacts its log entries when it applies 10k new entries and only 5k in memory.

https://github.com/coreos/etcd/blob/master/etcdserver/server.go#L1115-L1128.

This introduces issues with large snapshot sending. After receives a snapshot, the slow follower needs to get all the entries right after that snapshot sent to catch up. The log entries right after the snapshot sent might already be compacted, when the snapshot takes long time to send and save. This will trigger a snapshot sending cycle.

The simplest solution is to always keep a large number of entries in memory, which is avg_rate * 180s. We ca assume avg_rate is 1K/second. Then we need always to keep 180K. 

A better solution might be just keep more entries when we know there is a snapshot being sent. 

The issue can be reproduced by sending a large snapshot while still accepting high rate client request.

/cc @heyitsanthony

### PR DESCRIPTION
**Pull request by xiang90**
Fix #4055 

Now etcd can recover from 5GB snapshot even under high load!

### CODE REVIEW

File: etcdserver/server.go [hunk 1]
```diff
@@ -542,7 +552,29 @@ func (s *EtcdServer) run() {
...
+					// fails to catch up, it is probably just too slow to catch up.
+					// We cannot avoid the snapshot cycle anyway.
+					if ok {
+						time.Sleep(compactionDelayAfterSnapshot)
+					}
+					plog.Noticef("log compaction resumed")
+					s.cpMu.Lock()
+					s.compactionPaused = false
+					s.cpMu.Unlock()
+				case <-s.stop:
```
Comment (heyitsanthony) [inline etcdserver/server.go]: `case <-s.done` or it'll eat the signal intended for run()

Comment (xiang90) [inline etcdserver/server.go]: right. fixed.

File: snap/message.go [hunk 2]
```diff
@@ -27,8 +27,26 @@ import (
 // Message contains the ReadCloser field for handling large snapshot. This avoid
 // copying the entire snapshot into a byte array, which consumes a lot of memory.
 //
-// User of Message should close the ReadCloser after sending it.
+// User of Message should close the Message after sending it.
 type Message struct {
 	raftpb.Message
 	ReadCloser io.ReadCloser
+	Donec      chan bool
```
Comment (heyitsanthony) [inline snap/message.go]: `Donec` should probably be `donec` since I assume only `SucceededAndClose` and `FailedAndClose` should write to it. I think that means there needs to be a `snap.NewMessage` to setup the channel, then?

Comment (xiang90) [inline snap/message.go]: Yes. We need a NewMessage. I also feel that is better.

File: snap/message.go [hunk 3]
```diff
@@ -27,8 +27,26 @@ import (
...
+}
+
+// CloseNotify returns a channel that receives a single value
+// when the message sent is finished. true indicates the sent
+// is successful.
+func (m Message) CloseNotify() <-chan bool {
+	return m.Donec
+}
+
+func (m Message) SucceededAndClose() {
```
Comment (heyitsanthony) [inline snap/message.go]: Instead of `SucceededAndClose` and `FailedAndClose`, just `Close(error)` could be simpler (although I don't know what the error would be for the `transport.go` failure case).

Comment (xiang90) [inline snap/message.go]: How about CloseWithError(err error)?

Comment (xiang90) [inline snap/message.go]: We do not need to actually parse the error though, just need to now if it is nil or not.

File: etcdserver/server.go [hunk 4]
```diff
@@ -542,7 +552,29 @@ func (s *EtcdServer) run() {
 		case ep = <-etcdprogc:
 		case m := <-s.msgSnapC:
 			merged := s.createMergedSnapshotMessage(m, ep.appliedi, ep.confState)
+			plog.Noticef("log compaction paused when sending snapshot")
```
Comment (heyitsanthony) [inline etcdserver/server.go]: The sending logic is sophisticated enough that a `EtcdServer.sendSnapshot` function would be good now.

File: snap/message.go (hunk 3 above)
Comment (heyitsanthony) [inline snap/message.go]: Yeah, the error value doesn't matter aside from nil/not-nil. I was thinking `Close(error)` would be the only way to close since `Close(nil)` is less wordy than `SucceededAndClose`.

File: etcdserver/server.go (hunk 4 above)
Comment (xiang90) [inline etcdserver/server.go]: agree. will add.

File: etcdserver/server.go [hunk 5]
```diff
@@ -184,6 +186,14 @@ type EtcdServer struct {
...
 
 	msgSnapC chan raftpb.Message
+
+	cpMu sync.Mutex // guards compactionPaused
+	// When sending a snapshot, etcd will pause compaction.
+	// After receives a snapshot, the slow follower needs to get all the entries right after
+	// the snapshot sent to catch up. If we do not pause compaction, the log entries right after
+	// the snapshot sent might already be compacted. It happens when the snapshot takes long time
+	// to send and save. Pausing compaction avoids triggering a snapshot sending cycle.
+	compactionPaused bool
```
Comment (heyitsanthony) [inline etcdserver/server.go]: `compactionPaused` is really tracking whether a snapshot is being sent. Something like `isSendingSnapshot` would probably be a bit clearer since paused <=> sending at the moment (e.g., the sender just has to say it's sending, instead of worrying about whether it should pause compaction).

Is it possible to get another message on msgSnapC while another snapshot is getting sent out? If that's the case, the mutex stuff can be nuked for an atomic int (`inflightSnapshots`?).

Comment (xiang90) [inline etcdserver/server.go]: I agree. I will rework on this.

**Comment by xiang90** [comment]
@heyitsanthony All fixed. PTAL.

**Comment by heyitsanthony** [comment]
lgtm
