### PR TITLE
recipes: fix rwmutex locking

### LINKED ISSUE #6408: RWMutex recipe bug
ETCD version: v3.0.8

There is a bug in the current [RWMutex recipe](https://github.com/coreos/etcd/blob/master/contrib/recipes/rwmutex.go#L69-L70). If two processes try to lock the mutex at the same time, the second one starts spinning indefinitely after the first one unlocks the mutex. 

The problem appears to be in the way the previous key revision is taken from the server. It always returns the previous key which already has been deleted ( the watcher in 'waitonlowest' correctly returns that all the time ).

The code I have attached demonstrates the problem. Simply compile and run two instances at the same time.

```golang
package main

import (
	"fmt"
	"time"

	"github.com/coreos/etcd/clientv3"
	"github.com/coreos/etcd/clientv3/concurrency"
	"github.com/coreos/etcd/contrib/recipes"
)

var etcdEndpoint = "http://127.0.0.1:2379"

func main() {
	// etcd
	etcdClient, err := clientv3.New(clientv3.Config{
		Endpoints:   []string{etcdEndpoint},
		DialTimeout: 5 * time.Second,
	})
	if err != nil {
		fmt.Printf("Failed to create etcd client:%v", err)
		return
	}
	defer etcdClient.Close()

	session, err := concurrency.NewSession(etcdClient, concurrency.WithTTL(30))
	if err != nil {
		fmt.Printf("Failed to create etcd session:%v", err)
		return
	}

	mtx := recipe.NewRWMutex(session, "lock")
	mtx.Lock()
	fmt.Println("Critical section")
	time.Sleep(time.Second * 15)
	mtx.Unlock()
}
```

### PR DESCRIPTION
**Pull request by heyitsanthony**
Fixes #6408

### CODE REVIEW

File: integration/v3_lock_test.go [hunk 1]
```diff
@@ -133,7 +133,7 @@ func testRWMutex(t *testing.T, waiters int, chooseClient func() *clientv3.Client
 				t.Error(err)
 			}
 			rwm := recipe.NewRWMutex(session, "test-rwmutex")
-			if rand.Intn(1) == 0 {
```
Comment (xiang90) [inline integration/v3_lock_test.go]: so previously we always get 0 and try RLock but never Lock?

Comment (heyitsanthony) [inline integration/v3_lock_test.go]: yep, that's why this test wasn't triggering the bug

**Comment by xiang90** [comment]
lgtm
