### PR TITLE
etcdctl: fix quotes in txn and watch

### LINKED ISSUE #6315: etcdctl v3 txn value does not honor %q formatting
etcdctl txn key and value specs are given as:

```
<KEY> ::= (%q formatted string)
<VALUE> ::= (%q formatted string)
```

To me, it is not clear what `(%q formatted string)` exactly mean here. Running the very example given, i.e.

```
./etcdctl txn <<<'mod("key1") > "0"

put key1 "overwrote-key1"

put key1 "created-key1"
put key2 "some extra key"

'
FAILURE

OK

OK
```

When I do `etcdctl get key1` afterwards I get `"created-key1"` as a value with quotes intact. Shouldn't the value be `created-key1` without the enclosing quotes? Also, it does not seem to honor other standard %q formatting such as `\ ` space escaping.

### PR DESCRIPTION
**Pull request by heyitsanthony**
Fixes #6315

### CODE REVIEW

File: e2e/ctl_v3_txn_test.go [hunk 1]
```diff
@@ -39,15 +39,23 @@ func txnTestSuccess(cx ctlCtx) {
...
-		ifSucess: []string{"get key1", "get key2"},
-		ifFail:   []string{`put key1 "fail"`, `put key2 "fail"`},
-		results:  []string{"SUCCESS", "key1", "value1", "key2", "value2"},
-	}
-	if err := ctlV3Txn(cx, rqs); err != nil {
-		cx.t.Fatal(err)
+	rqs := []txnRequests{
+		txnRequests{
+			compare:  []string{`version("key1") = "1"`, `version("key2") = "1"`},
+			ifSucess: []string{"get key1", "get key2", `put "key \"with\" space" "value \x23"`},
```
Comment (gyuho) [inline e2e/ctl_v3_txn_test.go]: So this should fail without this patch?

Comment (heyitsanthony) [inline e2e/ctl_v3_txn_test.go]: yeah, the regex was completely broken

File: etcdctl/ctlv3/command/util.go [hunk 2]
```diff
@@ -48,8 +48,23 @@ func addHexPrefix(s string) string {
 }
 
 func argify(s string) []string {
-	r := regexp.MustCompile("'.+'|\".+\"|\\S+")
-	return r.FindAllString(s, -1)
+	r := regexp.MustCompile(`"(\\.|[^"])*"|'[^']*'|[^'"\s]\S*[^'"\s]?`)
```
Comment (xiang90) [inline etcdctl/ctlv3/command/util.go]: the single quote and non-quote one looks fine to me.

It seems like people use `/"(?:[^"\\]|\\.)*"/` for double quote to deal with backslash.

See http://stackoverflow.com/questions/249791/regex-for-quoted-string-with-escaping-quotes.

Not sure if it necessary for us though, since we will do scanf %q later.

**Comment by xiang90** [comment]
lgtm
