### PR TITLE
etcdctl/cluster_health: improve output if failed to get leader stats

### LINKED ISSUE #2650: etcdctl cluster-health  are not consistent
I run  two members of etcd cluseter on centos7. one of cluster run "etcdctl cluster-health" getting cluseter status is health, but another "etcdctl cluster-health" getting cluster status is unhealth. the cluster health is ok when etcd started. 

```
test-0-1:
# etcdctl cluster-health
cluster is unhealthy

test-0-2:
#etcdctl cluster-health
cluster is healthy
member 6fafd2d770d2396 is healthy
member f2882b486b73afb9 is healthy
```

the etcd version is 2.0.3, the config file is as follow:

test-0-1:/etc/etcd/etcd.conf:
```
[member]
ETCD_NAME=test-0-1
ETCD_SNAPSHOT_COUNTER="10000"
ETCD_HEARTBEAT_INTERVAL="100"
ETCD_ELECTION_TIMEOUT="1000"
ETCD_LISTEN_PEER_URLS="http://0.0.0.0:2380,http://0.0.0.0:7001"
ETCD_LISTEN_CLIENT_URLS="http://0.0.0.0:4001,http://0.0.0.0:2379"
ETCD_MAX_WALS="0"


[cluster]
ETCD_INITIAL_ADVERTISE_PEER_URLS="http://10.128.0.1:2380"
# if you use different ETCD_NAME (e.g. test), set ETCD_INITIAL_CLUSTER value for this name, i.e. "test=http://..."
ETCD_INITIAL_CLUSTER="test-0-1=http://10.128.0.1:2380,test-0-2=http://10.128.0.2:2380"
ETCD_INITIAL_CLUSTER_STATE="new"
ETCD_INITIAL_CLUSTER_TOKEN="test-etcd-cluster"
ETCD_ADVERTISE_CLIENT_URLS="http://0.0.0.0:2379,http://0.0.0.0:4001"
```

test-0-2:/etc/etcd/etcd.conf:
```
[member]
ETCD_NAME=test-0-2
ETCD_SNAPSHOT_COUNTER="10000"
ETCD_HEARTBEAT_INTERVAL="100"
ETCD_ELECTION_TIMEOUT="1000"
ETCD_LISTEN_PEER_URLS="http://0.0.0.0:2380,http://0.0.0.0:7001"
ETCD_LISTEN_CLIENT_URLS="http://0.0.0.0:4001,http://0.0.0.0:2379"
ETCD_MAX_WALS="0"

[cluster]
ETCD_INITIAL_ADVERTISE_PEER_URLS="http://10.128.0.2:2380"
# if you use different ETCD_NAME (e.g. test), set ETCD_INITIAL_CLUSTER value for this name, i.e. "test=http://..."
ETCD_INITIAL_CLUSTER="test-0-1=http://10.128.0.1:2380,test-0-2=http://10.128.0.2:2380"
ETCD_INITIAL_CLUSTER_STATE="new"
ETCD_INITIAL_CLUSTER_TOKEN="test-etcd-cluster"
ETCD_ADVERTISE_CLIENT_URLS="http://0.0.0.0:2379,http://0.0.0.0:4001"
```

thanks

### PR DESCRIPTION
**Pull request by yichengq**
When failing to get leader stats, it said 'cluster is unhealthy' before.
This is confusing when it cannot get stats because advertised client urls
are set wrong and the cluster is healthy.

I set wrong client urls intentionally and get this when failed to get leader stats:
```
cluster may be unhealthy: failed to connect [http://localhost:4001 http://localhost:4001 http://localhost:4001]
```

fixes the problem of #2650

### CODE REVIEW

File: etcdctl/command/cluster_health.go [hunk 1]
```diff
@@ -46,9 +46,10 @@ func handleClusterHealth(c *cli.Context) {
 	}
 
 	// do we have a leader?
-	ep, ls0, err := getLeaderStats(tr, client.GetCluster())
+	cl := client.GetCluster()
+	ep, ls0, err := getLeaderStats(tr, cl)
 	if err != nil {
-		fmt.Println("cluster is unhealthy")
+		fmt.Println("failed to get leader stats from cluster urls", cl)
```
Comment (xiang90) [inline etcdctl/command/cluster_health.go]: fmt.Println("cannot determine the health of the cluster: fail to connect to the leader")

Comment (xiang90) [inline etcdctl/command/cluster_health.go]: I am not sure if this can help... 

In fact, in this case they cluster might be unhealthy indeed. that is the reason you cannot contact the leader. 

Then this error message is misleading, since user might think the cluster is OK, the problem is the client by looking at `failed to get leader stats from cluster urls`.

There is no way to determine if a distributed system is OK from a 3rd party actually.

Comment (yichengq) [inline etcdctl/command/cluster_health.go]: I agree with you that it cannot determine the cluster's health reliably. And if the client urls is set correctly, there is large probability that the error indicates unhealthy cluster.
I think as long as this message has more context or reasoning, users could understand what it is talking about more.

What about this:

```
fail to connect to the leader through client urls [http://localhost:4001 http://localhost:4001 http://localhost:4001]
cluster is unhealthy
```

Comment (xiang90) [inline etcdctl/command/cluster_health.go]: for this uncertain case: can we say: cluster may be unhealthy: failed to connect xx 

we do not have to expose it is the leader, etc..

Comment (yichengq) [inline etcdctl/command/cluster_health.go]: `may be` sounds more accurate. have updated.

**Comment by xiang90** [comment]
lgtm
