### PR TITLE
etcdctl: refactor the way to check cluster health

### LINKED ISSUE #2711: etcdctl cluster-health and member list commands do not work correctly
etcd server version

```
/opt/bin/etcd --version
etcd version 2.0.9
```

etcd client version

```
/usr/local/bin/etcdctl --version
etcdctl version 2.0.9
```

Start a 3 node etcd cluster

```
vmrun list
Total running VMs: 3
/Users/kelseyhightower/Documents/Virtual Machines.localized/core0.vmwarevm/core0.vmx
/Users/kelseyhightower/Documents/Virtual Machines.localized/core1.vmwarevm/core1.vmx
/Users/kelseyhightower/Documents/Virtual Machines.localized/core2.vmwarevm/core2.vmx
```

```
etcdctl cluster-health
cluster is healthy
member 5ae3067007f7fb85 is healthy
member 7931e79c0d8b47c5 is healthy
member 987146e8925f10e5 is healthy
```

```
etcdctl member list
5ae3067007f7fb85: name=etcd2 peerURLs=http://192.168.12.52:2380 clientURLs=http://192.168.12.52:2379
7931e79c0d8b47c5: name=etcd0 peerURLs=http://192.168.12.50:2380 clientURLs=http://192.168.12.50:2379
987146e8925f10e5: name=etcd1 peerURLs=http://192.168.12.51:2380 clientURLs=http://192.168.12.51:2379
```

Poweroff one of the etcd members

```
vmrun stop /Users/kelseyhightower/Documents/Virtual\ Machines.localized/core0.vmwarevm/core0.vmx
```

```
vmrun list
Total running VMs: 2
/Users/kelseyhightower/Documents/Virtual Machines.localized/core1.vmwarevm/core1.vmx
/Users/kelseyhightower/Documents/Virtual Machines.localized/core2.vmwarevm/core2.vmx
```

The member list commands fails

```
etcdctl -C http://192.168.12.50:2379,http://192.168.12.51:2379,http://192.168.12.52:2379 member list
context deadline exceeded
```

The cluster is reported healthy, but no nodes are marked unhealthy even though member `7931e79c0d8b47c5` is powered off. 

```
etcdctl -C http://192.168.12.50:2379,http://192.168.12.51:2379,http://192.168.12.52:2379 cluster-health
cluster is healthy
member 5ae3067007f7fb85 is healthy
member 7931e79c0d8b47c5 is healthy
member 987146e8925f10e5 is healthy
```

### PR DESCRIPTION
**Pull request by yichengq**
This method uses raft status exposed at /debug/varz to determine the
health of the cluster. It uses whether commit index increases to
determine the cluster health, and uses whether match index increases to
determine the member health.

This could fix the bug that fails to detect follower is unhealthy
because it doesn't rely on whether message in long-polling connection is sent.

This health check is stricter than the old one, and reflects the
situation that whether followers are healthy in the view of the leader. One
example is that if the follower is receiving the snapshot, it will turns
out to be unhealthy because it doesn't move forward.

This will reflect the healthy view in the raft level, while connectivity checks reflects the healthy view in transport level.

This is a prototype, and I am wondering whether this fits our goal.

fixes #2711

### CODE REVIEW

**Comment by xiang90** [comment]
This is what I would expect to see as the first step. I am still working on the connectivity stuff.

File: etcdctl/command/cluster_health.go [hunk 1]
```diff
@@ -51,27 +50,30 @@ func handleClusterHealth(c *cli.Context) {
...
+	_, rs1, err := getLeaderStatus(tr, []string{ep})
 	if err != nil {
 		fmt.Println("cluster is unhealthy")
 		os.Exit(1)
 	}
 
-	fmt.Println("cluster is healthy")
-	// self is healthy
+	if rs1.Commit > rs0.Commit {
+		fmt.Println("cluster is healthy")
```
Comment (xiang90) [inline etcdctl/command/cluster_health.go]: cluster is healthy: raft is making progress [%v -> %v]

File: etcdctl/command/cluster_health.go [hunk 2]
```diff
@@ -51,27 +50,30 @@ func handleClusterHealth(c *cli.Context) {
...
+	} else {
+		fmt.Println("cluster is unhealthy")
```
Comment (xiang90) [inline etcdctl/command/cluster_health.go]: cluster is unhealthy: raft is not making progress [%v]

File: etcdctl/command/cluster_health.go [hunk 3]
```diff
@@ -51,27 +50,30 @@ func handleClusterHealth(c *cli.Context) {
...
+	for id, pr0 := range rs0.Progress {
+		pr1, ok := rs1.Progress[id]
 		if !ok {
 			fmt.Println("Cluster configuration changed during health checking. Please retry.")
 			os.Exit(1)
 		}
-		if fs1.Counts.Success <= fs0.Counts.Success {
-			prints = append(prints, fmt.Sprintf("member %s is unhealthy\n", name))
+		if pr1.Match <= pr0.Match {
+			prints = append(prints, fmt.Sprintf("member %s is unhealthy\n", id))
```
Comment (xiang90) [inline etcdctl/command/cluster_health.go]: can we also print out its progress?

File: etcdctl/command/cluster_health.go [hunk 4]
```diff
@@ -51,27 +50,30 @@ func handleClusterHealth(c *cli.Context) {
...
 		} else {
-			prints = append(prints, fmt.Sprintf("member %s is healthy\n", name))
+			prints = append(prints, fmt.Sprintf("member %s is healthy\n", id))
```
Comment (xiang90) [inline etcdctl/command/cluster_health.go]: same here

File: etcdctl/command/cluster_health.go (hunk 1 above)
Comment (xiang90) [inline etcdctl/command/cluster_health.go]: we can also print out who is the leader

**Comment by yichengq** [comment]
I updated the output:
```
all health:
$ ./bin/etcdctl cluster-health
cluster is healthy: raft is making progress [commit index: 12332->12334]
leader of the cluster is member 6e3bd23ae5f1eae0
member 6e3bd23ae5f1eae0 is healthy [match: 12334, next: 12335, state: ProgressStateProbe]
member 924e2e83e93f2560 is healthy [match: 12334, next: 12335, state: ProgressStateReplicate]
member a8266ecf031671f3 is healthy [match: 12334, next: 12335, state: ProgressStateReplicate]

2 out of 3 healthy:
$ ./bin/etcdctl cluster-health
cluster is healthy: raft is making progress [commit index: 12381->12383]
leader of the cluster is member 6e3bd23ae5f1eae0
member 6e3bd23ae5f1eae0 is healthy [match: 12383, next: 12384, state: ProgressStateProbe]
member 924e2e83e93f2560 is unhealthy [match: 12373, next: 12374, state: ProgressStateProbe]
member a8266ecf031671f3 is healthy [match: 12383, next: 12384, state: ProgressStateReplicate]
```

File: etcdctl/command/cluster_health.go [hunk 5]
```diff
@@ -51,27 +50,31 @@ func handleClusterHealth(c *cli.Context) {
...
 	}
 
-	fmt.Println("cluster is healthy")
-	// self is healthy
+	if rs1.Commit > rs0.Commit {
+		fmt.Printf("cluster is healthy: raft is making progress [commit index: %v->%v]\n", rs0.Commit, rs1.Commit)
+	} else {
+		fmt.Printf("cluster is unhealthy: raft is not making progress [commit index: %v]\n", rs0.Commit)
+	}
+	fmt.Printf("leader of the cluster is member %v\n", rs0.Lead)
```
Comment (xiang90) [inline etcdctl/command/cluster_health.go]: sounds too verbose. how about leader is ?

File: etcdctl/command/cluster_health.go [hunk 6]
```diff
@@ -51,27 +50,31 @@ func handleClusterHealth(c *cli.Context) {
...
+	for id, pr0 := range rs0.Progress {
+		pr1, ok := rs1.Progress[id]
 		if !ok {
 			fmt.Println("Cluster configuration changed during health checking. Please retry.")
 			os.Exit(1)
 		}
-		if fs1.Counts.Success <= fs0.Counts.Success {
-			prints = append(prints, fmt.Sprintf("member %s is unhealthy\n", name))
+		if pr1.Match <= pr0.Match {
+			prints = append(prints, fmt.Sprintf("member %s is unhealthy [match: %v, next: %v, state: %v]\n", id, pr1.Match, pr1.Next, pr1.State))
```
Comment (xiang90) [inline etcdctl/command/cluster_health.go]: i think we should tell user why do we think this member is unhealthy.

File: etcdctl/command/cluster_health.go [hunk 7]
```diff
@@ -51,27 +50,31 @@ func handleClusterHealth(c *cli.Context) {
...
 		} else {
-			prints = append(prints, fmt.Sprintf("member %s is healthy\n", name))
+			prints = append(prints, fmt.Sprintf("member %s is healthy [match: %v, next: %v, state: %v]\n", id, pr1.Match, pr1.Next, pr1.State))
```
Comment (xiang90) [inline etcdctl/command/cluster_health.go]: well... can we should the progress as line 60? we should try to make everything consistent.

File: etcdctl/command/cluster_health.go (hunk 5 above)
Comment (yichengq) [inline etcdctl/command/cluster_health.go]: ok

File: etcdctl/command/cluster_health.go (hunk 6 above)
Comment (yichengq) [inline etcdctl/command/cluster_health.go]: ok

File: etcdctl/command/cluster_health.go (hunk 7 above)
Comment (yichengq) [inline etcdctl/command/cluster_health.go]: I tried it but thought it was too verbosal:
```
member 6e3bd23ae5f1eae0 is healthy [match: 102->104, next: 105->105, state: ProgressStateReplicate->ProgressStateReplicate]
```
So i dumped state change if it doesn't change.

**Comment by yichengq** [comment]
i changed outputs based on comments and its current output is:
```
cluster is healthy: raft is making progress [commit index: 423->425]
leader is 924e2e83e93f2560
member 6e3bd23ae5f1eae0 is unhealthy because its match index is not catching up with commit index [match: 407->407, next: 408->408, state: ProgressStateProbe]
member 924e2e83e93f2560 is healthy [match: 423->425, next: 426->426, state: ProgressStateProbe]
member a8266ecf031671f3 is healthy [match: 423->425, next: 426->426, state: ProgressStateReplicate]
```
Look more informative?

File: etcdctl/command/cluster_health.go [hunk 8]
```diff
@@ -51,27 +50,43 @@ func handleClusterHealth(c *cli.Context) {
...
 		if !ok {
 			fmt.Println("Cluster configuration changed during health checking. Please retry.")
 			os.Exit(1)
 		}
-		if fs1.Counts.Success <= fs0.Counts.Success {
-			prints = append(prints, fmt.Sprintf("member %s is unhealthy\n", name))
+		if pr1.Match <= pr0.Match {
+			var msg string
+			if pr0.State == pr1.State {
+				msg = fmt.Sprintf("member %s is unhealthy because its match index is not catching up with commit index [match: %v->%v, next: %v->%v, state: %v]\n", id, pr0.Match, pr1.Match, pr0.Next, pr1.Next, pr1.State)
```
Comment (xiang90) [inline etcdctl/command/cluster_health.go]: can we make this consistent with the previous one? replace `because` with `:`?

File: etcdctl/command/cluster_health.go [hunk 9]
```diff
@@ -51,27 +50,43 @@ func handleClusterHealth(c *cli.Context) {
...
+			} else {
+				msg = fmt.Sprintf("member %s is unhealthy because its match index is not catching up with commit index [match: %v->%v, next: %v->%v, state: %v->%v]\n", id, pr0.Match, pr1.Match, pr0.Next, pr1.Next, pr0.State, pr1.State)
+			}
+			prints = append(prints, msg)
 		} else {
-			prints = append(prints, fmt.Sprintf("member %s is healthy\n", name))
+			var msg string
+			if pr0.State == pr1.State {
+				msg = fmt.Sprintf("member %s is healthy [match: %v->%v, next: %v->%v, state: %v]\n", id, pr0.Match, pr1.Match, pr1.Next, pr1.Next, pr1.State)
```
Comment (xiang90) [inline etcdctl/command/cluster_health.go]: can we make this consistent with the previous one? member %s is healthy: raft is making progress [match ...] (we do not need next and state)

**Comment by xiang90** [comment]
LGTM after making everything consistent and short.

**Comment by xiang90** [comment]
Also please manually test the previous issue (hard shutdown a member has a reporting delay). I will give a test too soon. Thanks.

**Comment by yichengq** [comment]
I have tested it on AWS and current way works well.

I addressed the comments and current log is as this:
```
cluster is healthy: raft is making progress [commit index: 848->850]
leader is 924e2e83e93f2560
member 6e3bd23ae5f1eae0 is unhealthy: its match index is not catching up with commit index [match: 839->839, next: 840->840, state: ProgressStateProbe]
member 924e2e83e93f2560 is healthy: raft is making progress [match: 848->850]
member a8266ecf031671f3 is healthy: raft is making progress [match: 848->850]
```

File: etcdctl/command/cluster_health.go [hunk 10]
```diff
@@ -51,27 +50,37 @@ func handleClusterHealth(c *cli.Context) {
...
+	for id, pr0 := range rs0.Progress {
+		pr1, ok := rs1.Progress[id]
 		if !ok {
 			fmt.Println("Cluster configuration changed during health checking. Please retry.")
 			os.Exit(1)
 		}
-		if fs1.Counts.Success <= fs0.Counts.Success {
-			prints = append(prints, fmt.Sprintf("member %s is unhealthy\n", name))
+		if pr1.Match <= pr0.Match {
+			var msg string
```
Comment (xiang90) [inline etcdctl/command/cluster_health.go]: can we simply say: raft is not making progress and print out match as before?

File: etcdctl/command/cluster_health.go [hunk 11]
```diff
@@ -99,13 +126,16 @@ func getLeaderStats(tr *http.Transport, endpoints []string) (string, *stats.Lead
...
 			continue
 		}
-		return ep, ls, nil
+		if vs.RaftStatus.Lead != vs.RaftStatus.ID {
+			continue
+		}
+		return ep, vs.RaftStatus, nil
 	}
-	return "", nil, errors.New("no leader")
+	return "", raftStatus{}, errors.New("no leader")
```
Comment (xiang90) [inline etcdctl/command/cluster_health.go]: well... if the given endpoint is not etcd 2.2 or not etcd, we will return no leader error. We can do better.

Comment (yichengq) [inline etcdctl/command/cluster_health.go]: agree. I could do it in the following-up PR. I don't plan to do it in this PR because I don't change related logic and the error is not printed out.

File: etcdctl/command/cluster_health.go [hunk 12]
```diff
@@ -82,15 +85,33 @@ func handleClusterHealth(c *cli.Context) {
...
+		State string `json:"state"`
+	} `json:"progress"`
+}
+
+type vars struct {
+	RaftStatus raftStatus `json:"raft.status"`
+}
+
+func getLeaderStatus(tr *http.Transport, endpoints []string) (string, raftStatus, error) {
 	// go-etcd does not support cluster stats, use http client for now
```
Comment (xiang90) [inline etcdctl/command/cluster_health.go]: can we remove this irrelevant comment at line 107?

Comment (yichengq) [inline etcdctl/command/cluster_health.go]: done.

**Comment by xiang90** [comment]
LGTM.
