### PR TITLE
etcdserver: better warning when initial-cluster doesn't match advertise urls

### LINKED ISSUE #8079: Why am I failing that check?
Hi,

I'm following [this guide](https://coreos.com/etcd/docs/latest/v2/docker_guide.html) in trying to set up a small etcd cluster with docker.

The following is my shell script:

    #!/bin/bash
    docker network rm etcd
    docker network create etcd --subnet=172.28.0.0/16 --ip-range=172.28.0.0/16
    
    docker stop etcd01
    docker rm etcd01
    docker run -d \
        --network="etcd" \
        --ip 172.28.0.4 \
        -v $(pwd)/etcd01:/etc/ssl/certs \
        -p 4001:4001 -p 2380:2380 -p 2379:2379 \
        --hostname etcd01 \
        --name etcd01 quay.io/coreos/etcd:latest \
        etcd \
        -name etcd01 \
        -advertise-client-urls http://172.28.0.4:2379,http://172.28.0.4:4001 \
        -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 \
        -initial-advertise-peer-urls http://172.28.0.4:2380 \
        -listen-peer-urls http://0.0.0.0:2380 \
        -initial-cluster-token etcd01 \
        -initial-cluster etcd01=http://172.28.0.4:2380,etcd01=http://172.28.0.2:2380,etcd02=http://172.28.0.3:2380 \
        -initial-cluster-state new
    
    docker stop etcd02
    docker rm etcd02
    docker run -d \
        --network="etcd" \
        --ip 172.28.0.2 \
        -v $(pwd)/etcd02:/etc/ssl/certs \
        -p 4001:4001 -p 2380:2380 -p 2379:2379 \
        --hostname etcd02 \
        --name etcd02 quay.io/coreos/etcd:latest \
        etcd \
        -name etcd02 \
        -advertise-client-urls http://172.28.0.2:2379,http://172.28.0.2:4001 \
        -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 \
        -initial-advertise-peer-urls http://172.28.0.2:2380 \
        -listen-peer-urls http://0.0.0.0:2380 \
        -initial-cluster-token etcd02 \
        -initial-cluster etcd01=http://172.28.0.4:2380,etcd01=http://172.28.0.2:2380,etcd02=http://172.28.0.3:2380 \
        -initial-cluster-state new
    
    docker stop etcd03
    docker rm etcd03
    docker run -d \
        --network="etcd" \
        --ip 172.28.0.3 \
        -v $(pwd)/etcd03:/etc/ssl/certs \
        -p 4001:4001 -p 2380:2380 -p 2379:2379 \
        --hostname etcd03 \
        --name etcd03 quay.io/coreos/etcd:latest \
        etcd \
        -name etcd03 \
        -advertise-client-urls http://172.28.0.3:2379,http://172.28.0.3:4001 \
        -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 \
        -initial-advertise-peer-urls http://172.28.0.3:2380 \
        -listen-peer-urls http://0.0.0.0:2380 \
        -initial-cluster-token etcd03 \
        -initial-cluster etcd01=http://172.28.0.4:2380,etcd01=http://172.28.0.2:2380,etcd02=http://172.28.0.3:2380 \
        -initial-cluster-state new

The containers always die with logs like this:

```
2017-06-10 03:56:20.274281 I | etcdmain: etcd Version: 3.1.8
2017-06-10 03:56:20.277344 I | etcdmain: Git SHA: d267ca9
2017-06-10 03:56:20.277401 I | etcdmain: Go Version: go1.7.5
2017-06-10 03:56:20.277438 I | etcdmain: Go OS/Arch: linux/amd64
2017-06-10 03:56:20.277488 I | etcdmain: setting maximum number of CPUs to 2, total number of available CPUs is 2
2017-06-10 03:56:20.277537 W | etcdmain: no data-dir provided, using default data-dir ./etcd01.etcd
2017-06-10 03:56:20.277764 I | embed: listening for peers on http://0.0.0.0:2380
2017-06-10 03:56:20.277864 I | embed: listening for client requests on 0.0.0.0:2379
2017-06-10 03:56:20.278641 I | embed: listening for client requests on 0.0.0.0:4001
2017-06-10 03:56:20.405664 I | etcdmain: --initial-cluster must include etcd01=http://172.28.0.4:2380 given --initial-advertise-peer-urls=http://172.28.0.4:2380
```

For some reason the first container even worked for some time. So I probably added a spelling error somewhere or something. Sorry that I can't find it. Can you see it?

Btw. is it a bug that the final log message is of type `info` and not `error` as [indicated in the code](https://github.com/coreos/etcd/blob/master/etcdserver/config.go#L122)? Also I have to admit that I don't really understand it. At first it says one variable doesn't seem to contain the expected content, but then it shows the contents of another variable. Shouldn't it show what is currently in `--initial-cluster` instead so that I can check what the difference is?

Please also note that there need to be quite a few changes to get this to run at all. The guide is not really sufficient yet. For instance that it just expects to use static IPs but doesn't show how static IPs are set up with docker, or that the developer probably used another image (as mentioned in #8078).

All this is not to say that etcd would be bad. It's a pillar of modern cluster management and I'm very happy that it exists. That's why I want to learn to use it even outside of k8s. I'd appreciate any help.

### PR DESCRIPTION
**Pull request by heyitsanthony**
The old error was not clear about what URLs needed to be added, sometimes
truncating the list. To make it clearer, print out the missing entries
for --initial-cluster and print the full list of initial advertise peers.

Fixes #8079 and #7927

Old output:
```
etcdmain: --initial-cluster must include etcd01=http://172.28.0.4:2380 given --initial-advertise-peer-urls=http://172.28.0.4:2380
```

New output:
```
etcdmain: --initial-cluster has etcd01=http://172.28.0.2:2380 but missing from --initial-advertise-peer-urls=http://172.28.0.4:2380
```

### CODE REVIEW

File: etcdserver/config.go [hunk 1]
```diff
@@ -117,11 +117,35 @@ func (c *ServerConfig) advertiseMatchesCluster() error {
...
+	apStr := strings.Join(apurls, ",")
+	if len(missing) > 0 {
+		for i := range missing {
+			missing[i] = c.Name + "=" + missing[i]
+		}
+		mstr := strings.Join(missing, ",")
+		return fmt.Errorf("--initial-cluster has %s but missing from --initial-advertise-peer-urls=%s ", mstr, apStr)
+	}
+	umap := types.URLsMap(map[string]types.URLs{c.Name: c.PeerURLs})
+	return fmt.Errorf("--initial-advertise-peer-urls=%s but missing from --initial-cluster=%s", apStr, umap.String())
```
Comment (xiang90) [inline etcdserver/config.go]: is this accurate? apStr are all the urls, not just the missing ones as what we do for line 145?

Comment (heyitsanthony) [inline etcdserver/config.go]: yeah, dumping all of them now; will scan for the missing entries

**Comment by xiang90** [comment]
lgtm
