### PR TITLE
rafthttp: fix TestStream uses outdated stream

### LINKED ISSUE #2961: test stream failed
```
--- FAIL: TestStream-4 (1.02s)
	stream_test.go:297: #0: failed to receive message from the channel
	stream_test.go:300: #0: message = {Type:MsgHup To:0 From:0 Term:0 LogTerm:0 Index:0 Entries:[] Commit:0 Snapshot:{Data:[] Metadata:{ConfState:{Nodes:[] XXX_unrecognized:[]} Index:0 Term:0 XXX_unrecognized:[]} XXX_unrecognized:[]} Reject:false RejectHint:0 XXX_unrecognized:[]}, want {Type:MsgProp To:2 From:0 Term:0 LogTerm:0 Index:0 Entries:[] Commit:0 Snapshot:{Data:[] Metadata:{ConfState:{Nodes:[] XXX_unrecognized:[]} Index:0 Term:0 XXX_unrecognized:[]} XXX_unrecognized:[]} Reject:false RejectHint:0 XXX_unrecognized:[]}
```

/cc @yichengq

### PR DESCRIPTION
**Pull request by yichengq**
rafthttp: expose streamWriter.msgAppTerm() …
So upper level could know msgAppTerm of streamWriter, which is
determined by the connection from the remote.

rafthttp: fix TestStream uses outdated stream …
The original code doesn't work because reader side may update the
stream, while writer side writes message to the old stream and fails.

fixes #2961

### CODE REVIEW

**Comment by yichengq** [comment]
Have tested it 50 times on travis

**Comment by yichengq** [comment]
Updated to change the code at reader side:

rafthttp: give init term for streamReader, and fix TestStream …

The original code doesn't work because reader side may update the
stream, while writer side writes message to the old stream and fails.

Set init term for streamReader now, so the writer will receive only one
stream.

File: rafthttp/peer.go [hunk 1]
```diff
@@ -143,8 +143,8 @@ func startPeer(tr http.RoundTripper, urls types.URLs, local, to, cid types.ID, r
 		}
 	}()
 
-	p.msgAppReader = startStreamReader(tr, picker, streamTypeMsgAppV2, local, to, cid, status, p.recvc, p.propc, errorc)
-	reader := startStreamReader(tr, picker, streamTypeMessage, local, to, cid, status, p.recvc, p.propc, errorc)
+	p.msgAppReader = startStreamReader(tr, picker, streamTypeMsgAppV2, local, to, cid, status, p.recvc, p.propc, errorc, 0)
```
Comment (xiang90) [inline rafthttp/peer.go]: why do we initialize this to 0 instead of current term?

Comment (yichengq) [inline rafthttp/peer.go]: Good call. I plan to just fix the test in this PR, and change the behavior in a following one.

Comment (xiang90) [inline rafthttp/peer.go]: This pull request changed the pervious behavior. I think we should fix them together. I am fine with fixing the issue first then test.

**Comment by yichengq** [comment]
Updated based on change made in #3069 

rafthttp: avoid TestStream to use outdated stream …

The original test code before fb4b0b5
doesn't work because reader side may update the
stream, while writer side writes message to the old stream and fails.

This PR removes unnecessary call to set term, and avoids this problem to
happen on term > 1 in the future.

**Comment by xiang90** [comment]
LGTM
