### PR TITLE
rafthttp: use buffered channel as recv/prop chan

### LINKED ISSUE #2961: test stream failed
```
--- FAIL: TestStream-4 (1.02s)
	stream_test.go:297: #0: failed to receive message from the channel
	stream_test.go:300: #0: message = {Type:MsgHup To:0 From:0 Term:0 LogTerm:0 Index:0 Entries:[] Commit:0 Snapshot:{Data:[] Metadata:{ConfState:{Nodes:[] XXX_unrecognized:[]} Index:0 Term:0 XXX_unrecognized:[]} XXX_unrecognized:[]} Reject:false RejectHint:0 XXX_unrecognized:[]}, want {Type:MsgProp To:2 From:0 Term:0 LogTerm:0 Index:0 Entries:[] Commit:0 Snapshot:{Data:[] Metadata:{ConfState:{Nodes:[] XXX_unrecognized:[]} Index:0 Term:0 XXX_unrecognized:[]} XXX_unrecognized:[]} Reject:false RejectHint:0 XXX_unrecognized:[]}
```

/cc @yichengq

### PR DESCRIPTION
**Pull request by yichengq**
So it ensures that the message will not be discarded because the receive
side has not been ready, which happens easily in multiple core test.

Use log.fatal instead of log.error. The test exits when there is
something wrong because the error may affect following test cases.

fixes #2961

### CODE REVIEW

File: rafthttp/stream_test.go [hunk 1]
```diff
@@ -221,8 +221,8 @@ func TestStreamReaderDialDetectUnsupport(t *testing.T) {
 // TestStream tests that streamReader and streamWriter can build stream to
 // send messages between each other.
 func TestStream(t *testing.T) {
-	recvc := make(chan raftpb.Message)
-	propc := make(chan raftpb.Message)
+	recvc := make(chan raftpb.Message, 1)
```
Comment (xiang90) [inline rafthttp/stream_test.go]: can we use the const in stream.go? 
```
streamBufSize = 4096
```

Comment (yichengq) [inline rafthttp/stream_test.go]: yep. that sounds more general. done

**Comment by xiang90** [comment]
LGTM
