### PR TITLE
fix unintended deadlock on key prefixes

### LINKED ISSUE #6278: etcdctl elect results in deadlock: won election never reported to winner, if key is a prefix of existing key
It appears that a lone candidate cannot win some elections.

```
go1.7
osx 10.11.6 El Capitan
export ETCDCTL_API=3 in the env
etcd at tip, as of this writing, tip was: c388b2f22f1285e0a686d0594c85a053016df010

# terminal 1: start etcd
$ etcd
...

# terminal 2: create a key 'xyz'
$ etcdctl put xyz hello

# terminal 2: and run an election on key xy (note that xy is a prefix of xyz)
$ etcdctl elect xy xy-should-win
observed result: <hangs, no output, as if the election was lost>

expected result: output that the value xy-should-win is now the value of xy, so we know that we've won the election.

terminal 3: query all values, notice that xy-should-win has one the elction, but was never notified of this fact
jaten@jatens-MacBook-Pro ~ $ etcdctl get a z
xy/694d56cc2663a25c
xy-should-win
xyz
hello
jaten@jatens-MacBook-Pro ~ $ 


additional note: when reproducing this under 3 etcd servers in a cluster, the following is a typical 2-line complainst also issued in the etcd logs. Several examples follow:

------------------
14:59:16 etcd2 | 2016-08-27 14:59:16.233151 W | etcdserver: apply entries took too long [17.5324\
48ms for 1 entries]
14:59:16 etcd2 | 2016-08-27 14:59:16.233171 W | etcdserver: avoid queries with large range/delet\
e range!
-===============
15:04:24 etcd3 | 2016-08-27 15:04:24.750401 W | etcdserver: apply entries took too long [11.377838ms for 1 entries]
15:04:24 etcd3 | 2016-08-27 15:04:24.750421 W | etcdserver: avoid queries with large range/delete range!
-------------
15:04:58 etcd2 | 2016-08-27 15:04:58.998189 W | etcdserver: apply entries took too long [17.416764ms for 1 entries]
15:04:58 etcd2 | 2016-08-27 15:04:58.998202 W | etcdserver: avoid queries with large range/delete range!
==================
15:05:53 etcd3 | 2016-08-27 15:05:53.874651 W | etcdserver: apply entries took too long [11.660702ms for 1 entries]
15:05:53 etcd3 | 2016-08-27 15:05:53.874676 W | etcdserver: avoid queries with large range/delete range!
```

### PR DESCRIPTION
**Pull request by glycerine**
After winning a campaign, the call to waitDeletes() was missing a
slash after the key prefix. The result was deadlock due to
waiting on wrong keys; if a prior key exists that has the new key
as a prefix.

Fixes #6278

### CODE REVIEW

**Comment by glycerine** [comment]
@xiang90, @heyitsanthony
Could you take a look.

The CI tests seem to fail for "package not found" reasons I don't understand, and seem unrelated to the patch.

**Comment by xiang90** [comment]
@glycerine Sorry for the inconvenience. The current master is broken due to a testing issue. We first need to get that first tomorrow.

**Comment by glycerine** [comment]
@xiang90 -- no worries. As for the patch, I was wondering -- would it be better to push the change into the function waitDeletes(), so that any other future caller wouldn't make the same mistake? I didn't see any other uses of waitDeletes(), but I also can't tell if there are other expectations/legacy users I'm unaware of.

**Comment by xiang90** [comment]
@glycerine

I think we can actually add `/` or any other hard to conflict char to the end of the `keyPrefix`. So users will not accidentally pollute the key space used for election or locking. Right now, not only waitDeletes watches on raw prefix but also some other functions (https://github.com/coreos/etcd/blob/master/clientv3/concurrency/election.go#L147-L158) too.

I even think we probably should add prefixes like `/lock/xy/`. But that can break existing users :(. 

It would be helpful if you can also write a test case for this in https://github.com/coreos/etcd/blob/master/integration/v3_election_test.go.

With all that being side, @heyitsanthony knows this part better than me and might provide better opinions.

**Comment by heyitsanthony** [comment]
@glycerine thanks for the patch. I agree with @xiang90 that it'd be cleaner to add the "/" to the prefix in `NewMutex/NewElection` constructors up front and replacing the `Sprintf("%s/%s"...)` with `Sprintf("%s%s")`. 

Also please fix the commit title or CI won't accept it (the error is `Expected commit title format '<package>{", "<package>}: <description>'`).

@xiang90 I feel like prefixing with `/lock/xy` breaks etcd3's clean keyspace guarantee since it reserves `/lock/` from the start as having some additional meaning.

**Comment by glycerine** [comment]
Done:
1. title in commit changed to include package clientv3/concurrency.
2. test added to integration/v3_election_test.go.
3. slash added to prefix during NewElection and NewMutex construction, per suggestion.

**Comment by glycerine** [comment]
TravisCI passes. Semaphoreci points out that TestTxnReadRetry and TestWatchReconnRequest are flakey tests, independent of this change.

@xiang90, @heyitsanthony: ready to merge?

File: integration/v3_election_test.go [hunk 1]
```diff
@@ -197,3 +197,182 @@ func TestElectionSessionRecampaign(t *testing.T) {
...
+
+// TestElectionOnPrefixOfExistingKey checks that a single
+// candidate can be elected on a new key that is a prefix
+// of an existing key. To wit, check for regression
+// of bug #6278. https://github.com/coreos/etcd/issues/6278
+//
+// Also a good basic test of single candidate election
+// and simultaneous correct observation of an election.
+//
+func TestElectionOnPrefixOfExistingKey(t *testing.T) {
```
Comment (heyitsanthony) [inline integration/v3_election_test.go]: This test is more complicated than it needs to be. I think this should trigger the old, broken behavior with a lot less code:
```sh
clus := NewClusterV3(t, &ClusterConfig{Size : 1})
defer clus.Terminate(t)

cli := clus.RandClient()
if _, err := cli.Put(context.TODO(), "testa"); err != nil {
    t.Fatal(err)
}
s, serr :=  concurrency.NewSession(cli)
if serr != nil {
    return serr
}
e := concurrency.NewElection(s, "test")
ctx, cancel := context.WithTimeout(context.TODO(), 5*time.Second)
err := e.Campaign(ctx, "abc")
cancel()
if err != nil {
    t.Fatal(err)
}
```

**Comment by xiang90** [comment]
@glycerine Can you rebase with the master? We just fixed the CI issue on master. Sorry about the inconvenience.

**Comment by glycerine** [comment]
@heyitsanthony Cool. This is really a pretty small change and obviously you know the code much better than me. Why do you go ahead and merge your test version and fix per your preference.

**Comment by heyitsanthony** [comment]
@glycerine are you abandoning this PR or what? Just update the test and I can merge this...?

**Comment by glycerine** [comment]
@heyitsanthony :Okay, rebased and updated test.

**Comment by heyitsanthony** [comment]
lgtm

**Comment by xiang90** [comment]
@glycerine Thanks for the contribution!

**Comment by glycerine** [comment]
cool -- @heyitsanthony one quick question for future reference so I understand how these tests and context interact -- why is cancel() called after the Campaign() call? -- the Campaign() has already succeeded or timed-out by that point, so why is it needed?

> e := concurrency.NewElection(s, "test")
> ctx, cancel := context.WithTimeout(context.TODO(), 5*time.Second)
> err := e.Campaign(ctx, "abc") // pauses for 5 seconds without the bug fix
> cancel()  // what does this do?
> if err != nil {

**Comment by xiang90** [comment]
@glycerine That is the intended behavior for releasing the resource associated with the context. See the doc in context pkg: https://godoc.org/golang.org/x/net/context#WithCancel
