### PR TITLE
clientv3: ensure KeepAlive channel is closed or error is returned

### LINKED ISSUE #6922: client: user may freeze on KeepAlive
**etcd client version:** `3.1.0-rc.0` (git hash: 83347907)

**Issue can be reproduced in following way:**
1) Create an etcdv3 client.
2) Make `lessor.recvKeepAliveLoop()` fail with any server-side error (we got `"lease: unknown error(not a primary lessor )"`).
3) Create a new lease.
4) Try to keep it alive with `KeepAlive`.

**Expected behavior:**
We expected client to recover from `recvKeepAliveLoop` error after some time and continue to process leases. Alternatively we expected `KeepAlive` to return error immediately due to broken `recvKeepAliveLoop`, so we can restart client manually, at least.

**Observed behavior:**
User of `KeepAlive` freezes because returned channel is never closed, after `keepAliveCtxCloser` exits on [`<-l.donec`](https://github.com/coreos/etcd/blob/83347907774bf36cbb261c594a32fd7b0f5dd9f6/clientv3/lease.go#L275) case in select due to `recvKeepAliveLoop` [signal](https://github.com/coreos/etcd/blob/83347907774bf36cbb261c594a32fd7b0f5dd9f6/clientv3/lease.go#L333). User code assumes that keep alive still works and expects responses or close of the channel, but none of these events happens.

**Side notes**
We used `concurrency.Session` to control the lease, and in this case it leads to [goroutine leak](https://github.com/coreos/etcd/blob/83347907774bf36cbb261c594a32fd7b0f5dd9f6/clientv3/concurrency/session.go#L59) and freeze of `session.Close` (or more precisely [session.Orphan](https://github.com/coreos/etcd/blob/83347907774bf36cbb261c594a32fd7b0f5dd9f6/clientv3/concurrency/session.go#L84)).

### PR DESCRIPTION
**Pull request by dennwc**
After `recvKeepAliveLoop` exits client might call `KeepAlive`, adding request channel that will not be closed.
This fix makes sure that `recvKeepAliveLoop` is running before adding request to lessor's list and returns error otherwise.

Fixes #6922

### CODE REVIEW

File: clientv3/lease.go [hunk 1]
```diff
@@ -216,6 +217,13 @@ func (l *lessor) KeepAlive(ctx context.Context, id LeaseID) (<-chan *LeaseKeepAl
 	ch := make(chan *LeaseKeepAliveResponse, leaseResponseChSize)
 
 	l.mu.Lock()
+	// ensure that recvKeepAliveLoop is still running
+	select {
+	case <-l.donec:
+		l.mu.Unlock()
+		return nil, errors.New("keep alive loop exited")
```
Comment (heyitsanthony) [inline clientv3/lease.go]: make this a constant `var ErrLeaseHalted = errors.New("etcdclient: leases halted")` at the top of the file?

Also `close(ch)` and return that instead of `nil` as well?

Comment (dennwc) [inline clientv3/lease.go]: Done.

**Comment by heyitsanthony** [comment]
Squash `expose error and return closed channel ` into the first patch so it passes the CI commit message checks? After that, lgtm. Thanks!

/cc @xiang90

**Comment by xiang90** [comment]
The code change looks good. Some suggestions on the error naming.

**Comment by xiang90** [comment]
lgtm
