### PR TITLE
clientv3/integration: fix TestTxnWriteFail

### LINKED ISSUE #4424: test: TestTxnWriteFail fails
```
=== RUN TestTxnWriteFail
...
timeout after 10minutes
```

### PR DESCRIPTION
**Pull request by xiang90**
It might take client request more than dialtimeout to fail when
we kill the connection when the client is sending request.

Fix #4424 

/cc @heyitsanthony

### CODE REVIEW

File: clientv3/integration/txn_test.go [hunk 1]
```diff
@@ -45,8 +45,9 @@ func TestTxnWriteFail(t *testing.T) {
 		donec <- struct{}{}
 	}()
 
+	dialTimeout := 5 * time.Second
 	select {
-	case <-time.After(5 * time.Second):
+	case <-time.After(dialTimeout + time.Second):
```
Comment (heyitsanthony) [inline clientv3/integration/txn_test.go]: maybe 2x the dial timeout just in case there are funny timing issues with CI

**Comment by heyitsanthony** [comment]
lgtm

**Comment by xiang90** [comment]
@heyitsanthony Fixed. Merging on green.
