### PR TITLE
integration: l-read before Put in TestWatchReconnRequest

### LINKED ISSUE #6314: TestWatchReconnRequest: request timed out
via semaphore on #6310

```
--- FAIL: TestWatchReconnRequest (7.62s)
	watch_test.go:327: etcdserver: request timed out, possibly due to previous leader failure
```

### PR DESCRIPTION
**Pull request by heyitsanthony**
TestWatchReconnRequest occasionally triggers elections because it spins on
drop connections, eating up CPU. In case there's an election, submit an
l-read to wait for the cluster to settle down.

Fixes #6314

/cc @xiang90

### CODE REVIEW

File: clientv3/integration/watch_test.go [hunk 1]
```diff
@@ -211,6 +211,14 @@ func testWatchReconnRequest(t *testing.T, wctx *watchctx) {
 	stopc <- struct{}{}
 	<-donec
 
+	// spinning on dropping connections may trigger a leader election
+	// due to resource starvation; l-read to ensure the cluster is stable
+	ctx, cancel := context.WithTimeout(30 * time.Second)
+	if _, err := wctx.kv.Get(ctx, "_"); err != nil {
```
Comment (xiang90) [inline clientv3/integration/watch_test.go]: this wont help. l-read would fail too. now we might drop proposals when there is a leader election :(

Comment (heyitsanthony) [inline clientv3/integration/watch_test.go]: huh? the client will retry the l-read if there's a leader election

Comment (xiang90) [inline clientv3/integration/watch_test.go]: Oh. The cancel timeout now is 30 seconds. It should fix this problem then, though not ideal.

**Comment by xiang90** [comment]
LGTM
