### PR TITLE
etcdserver: Fix panic for v3 transaction compares on non-existent keys

### LINKED ISSUE #3920: etcdv3: panic & cannot test existence of a key in a txn
My only compare options are on certain fields, not the existence itself. This seems okay API-wise; I was expecting to test Compare_VERSION and see if the key version was 0 or -1 or somesuch. 

However, this kills the etcd (on HEAD):

```
echo "foo ver e 0\n\n\n" | ./etcdctlv3 txn
```

```
16:22:15 etcd | panic: 
16:22:15 etcd | runtime error: index out of range
16:22:15 etcd | goroutine 86 [running]:
16:22:15 etcd | github.com/coreos/etcd/etcdserver.applyCompare(0x3d84722b4d3f8837, 0x7ff519cfafb0, 0xc820208fc0, 0xc8203ad270, 0x3d84722b4d3f8837, 0xe32e40)
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/v3demo_server.go:305 +0x3e8
16:22:15 etcd | github.com/coreos/etcd/etcdserver.applyTxn(0x7ff519cfafb0, 0xc820208fc0, 0xc8203ad220, 0x0, 0x0, 0x0)
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/v3demo_server.go:219 +0x134
16:22:15 etcd | github.com/coreos/etcd/etcdserver.(*EtcdServer).applyV3Request(0xc820174480, 0xc8204ff940, 0x0, 0x0)
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/v3demo_server.go:126 +0x550
16:22:15 etcd | github.com/coreos/etcd/etcdserver.(*EtcdServer).apply(0xc820174480, 0xc8203ad180, 0x1, 0x1, 0xc8200b3b68, 0x24, 0x0)
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:869 +0x57a
16:22:15 etcd | github.com/coreos/etcd/etcdserver.(*EtcdServer).run(0xc820174480)
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go
16:22:15 etcd | :558 +0x1130
16:22:15 etcd | created by github.com/coreos/etcd/etcdserver.(*EtcdServer).start
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:422 +0x49a
16:22:15 etcd | goroutine 1 [runnable]:
16:22:15 etcd | github.com/coreos/etcd/etcdmain.Main()
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:193 +0x195b
16:22:15 etcd | main.main()
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/main.go:29 +0x14
16:22:15 etcd | goroutine 12 [chan receive]:
16:22:15 etcd | github.com/coreos/etcd/Godeps/_workspace/src/github.com/golang/glog.(*loggingT).flushDaemon(0x12bd420)
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x67
16:22:15 etcd | created by github.com/coreos/etcd/Godeps/_workspace/src/github.com/golang/glog.init.1
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x297
16:22:15 etcd | goroutine 13 [chan receive]:
16:22:15 etcd | github.com/coreos/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc8200fc940)
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/logutil/merge_logger.go:171 +0x7c
16:22:15 etcd | created by github.com/coreos/etcd/pkg/logutil.NewMergeLogger
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/logutil/merge_logger.go:89 +0xc0
16:22:15 etcd | goroutine 62 [syscall]:
16:22:15 etcd | os/signal.loop()
16:22:15 etcd | 	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
16:22:15 etcd | created by os/signal.init.1
16:22:15 etcd | 	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37
16:22:15 etcd | goroutine 84 [select]:
16:22:15 etcd | github.com/coreos/etcd/storage/backend.(*backend).run(0xc82018dcc0)
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/storage/backend/backend.go:138 +0x151
16:22:15 etcd | created by github.com/coreos/etcd/storage/backend.newBackend
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/storage/backend/backend.go:79 +0x31a
16:22:15 etcd | goroutine 85 [select]:
16:22:15 etcd | github.com/coreos/etcd/storage.(*watchableStore).syncWatchingsLoop(0xc82018de40)
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/storage/watchable_store.go:236 +0x175
16:22:15 etcd | created by github.com/coreos/etcd/storage.newWatchableStore
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/storage/watchable_store.go:63 +0x1ab
16:22:15 etcd | goroutine 88 [runnable]:
16:22:15 etcd | github.com/coreos/etcd/etcdserver.(*EtcdServer).purgeFile(0xc820174480)
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:433 +0x4bf
16:22:15 etcd | created by github.com/coreos/etcd/etcdserver.(*EtcdServer).Start
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:399 +0x88
16:22:15 etcd | goroutine 89 [runnable]:
16:22:15 etcd | github.com/coreos/etcd/etcdserver.monitorFileDescriptor(0xc82019b5c0)
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/metrics.go:81 +0x536
16:22:15 etcd | created by github.com/coreos/etcd/etcdserver.(*EtcdServer).Start
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:400 +0xb1
16:22:15 etcd | goroutine 90 [runnable]:
16:22:15 etcd | github.com/coreos/etcd/etcdserver.(*EtcdServer).monitorVersions(0xc820174480)
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:1094 +0x444
16:22:15 etcd | created by github.com/coreos/etcd/etcdserver.(*EtcdServer).Start
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:401 +0xd3
16:22:15 etcd | goroutine 91 [runnable]:
16:22:15 etcd | github.com/coreos/etcd/etcdserver/etcdhttp.capabilityLoop(0xc820174480)
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/etcdhttp/capability.go:68 +0x1ad
16:22:15 etcd | created by github.com/coreos/etcd/etcdserver/etcdhttp.NewClientHandler
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/etcdhttp/client.go:61 +0x59
16:22:15 etcd | goroutine 19 [runnable]:
16:22:15 etcd | github.com/coreos/etcd/pkg/fileutil.PurgeFile.func1(0xc8200fd520, 0x15, 0xc82000ade0, 0xdff8f0, 0x4, 0x5, 0x6fc23ac00, 0xc82019b5c0)
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/fileutil/purge.go:72 +0x5aa
16:22:15 etcd | created by github.com/coreos/etcd/pkg/fileutil.PurgeFile
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/fileutil/purge.go:78 +0xa6
16:22:15 etcd | goroutine 20 [runnable]:
16:22:15 etcd | github.com/coreos/etcd/pkg/fileutil.PurgeFile.func1(0xc8200fd560, 0x14, 0xc82000ae40, 0xe00788, 
16:22:15 etcd | 0x3, 0x5, 0x6fc23ac00, 0xc82019b5c0)
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/fileutil/purge.go:72 +0x5aa
16:22:15 etcd | created by github.com/coreos/etcd/pkg/fileutil.PurgeFile
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/fileutil/purge.go:78 +0xa6
16:22:15 etcd | goroutine 96 [IO wait]:
16:22:15 etcd | net.runtime_pollWait(0x7ff519d3f368, 0x72, 0xc82000e260)
16:22:15 etcd | 	/usr/local/go/src/runtime/netpoll.go:157 +0x60
16:22:15 etcd | net.(*pollDesc).Wait(0xc8201e6290, 0x72, 0x0, 0x0)
16:22:15 etcd | 	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
16:22:15 etcd | net.(*pollDesc).WaitRead(0xc8201e6290, 0x0, 0x0)
16:22:15 etcd | 	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
16:22:15 etcd | net.(*netFD).accept(0xc8201e6230, 0x0, 0x7ff519d40500, 0xc8202098e0)
16:22:15 etcd | 	/usr/local/go/src/net/fd_unix.go:408 +0x27c
16:22:15 etcd | net.(*TCPListener).AcceptTCP(0xc820190048, 0x0, 0x0, 0x0)
16:22:15 etcd | 	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
16:22:15 etcd | net.(*TCPListener).Accept(0xc820190048, 0x0, 0x0, 0x0, 0x0)
16:22:15 etcd | 	/usr/local/go/src/net/tcpsock_posix.go:264 +0x3d
16:22:15 etcd | github.com/coreos/etcd/pkg/transport.(*rwTimeoutListener).Accept(0xc8201f79a0, 0x0, 0x0, 0x0, 0x0)
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/transport/timeout_listener.go:44 +0x70
16:22:15 etcd | net/http.(*Server).Serve(0xc82019b980, 0x7ff519cfa510, 0xc8201f79a0, 0x0, 0x0)
16:22:15 etcd | 	/usr/local/go/src/net/http/server.go:1887 +0xb3
16:22:15 etcd | github.com/coreos/etcd/etcdmain.serveHTTP(0x7ff519cfa510, 0xc8201f79a0, 0x7ff519cfb518, 0xc820203830, 0x45d964b800, 0x0, 0x0)
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdmain/http.go:36 +0x167
16:22:15 etcd | github.com/coreos/etcd/etcdmain.startEtcd.func3(0x7ff519cfb518, 0xc820203830, 0x7ff519cfa510, 0xc8201f79a0)
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:309 +0x61
16:22:15 etcd | created by github.com/coreos/etcd/etcdmain.startEtcd
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:310 +0x1e7f
16:22:15 etcd | goroutine 97 [IO wait]:
16:22:15 etcd | net.runtime_pollWait(0x7ff519d3f2a8, 0x72, 0xc82000e260)
16:22:15 etcd | 	/usr/local/go/src/runtime/netpoll.go:157 +0x60
16:22:15 etcd | net.(*pollDesc).Wait(0xc8201e6370, 0x72, 0x0, 0x0)
16:22:15 etcd | 	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
16:22:15 etcd | net.(*pollDesc).WaitRead(0xc8201e6370, 0x0, 0x0)
16:22:15 etcd | 	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
16:22:15 etcd | net.(*netFD).accept(0xc8201e6310, 0x0, 0x7ff519d40500, 0xc8200fda00)
16:22:15 etcd | 	/usr/local/go/src/net/fd_unix.go:408 +0x27c
16:22:15 etcd | net.(*TCPListener).AcceptTCP(0xc820190050, 0x0, 0x0, 0x0)
16:22:15 etcd | 	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
16:22:15 etcd | net.(*TCPListener).Accept(0xc820190050, 0x0, 0x0, 0x0, 0x0)
16:22:15 etcd | 	/usr/local/go/src/net/tcpsock_posix.go:264 +0x3d
16:22:15 etcd | github.com/coreos/etcd/pkg/transport.(*rwTimeoutListener).Accept(0xc8201f7a80, 0x0, 0x0, 0x0, 0x0)
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/transport/timeout_listener.go:44 +0x70
16:22:15 etcd | net/http.(*Server).Serve(0xc82000b1a0, 0x7ff519cfa510, 0xc8201f7a80, 0x0, 0x0)
16:22:15 etcd | 	/usr/local/go/src/net/http/server.go:1887 +0xb3
16:22:15 etcd | github.com/coreos/etcd/etcdmain.serveHTTP(0x7ff519cfa510, 0xc8201f7a80, 0x7ff519cfb518, 0xc820203830, 0x45d964b800, 0x0, 0x0)
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdmain/http.go:36 +0x167
16:22:15 etcd | github.com/coreos/etcd/etcdmain.startEtcd.func3(0x7ff519cfb518, 0xc820203830, 0x7ff519cfa510, 0xc8201f7a80)
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:309 +0x61
16:22:15 etcd | created by github.com/coreos/etcd/etcdmain.startEtcd
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:310 +0x1e7f
16:22:15 etcd | goroutine 98 [IO wait]:
16:22:15 etcd | net.runtime_pollWait(0x7ff519d3f1e8, 0x72, 0xc82000e260)
16:22:15 etcd | 	/usr/local/go/src/runtime/netpoll.go:157 +0x60
16:22:15 etcd | net.(*pollDesc).Wait(0xc8201e6450, 0x72, 0x0, 0x0)
16:22:15 etcd | 	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
16:22:15 etcd | net.(*pollDesc).WaitRead(0xc8201e6450, 0x0, 0x0)
16:22:15 etcd | 	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
16:22:15 etcd | net.(*netFD).accept(0xc8201e63f0, 0x0, 0x7ff519d40500, 0xc8200fda20)
16:22:15 etcd | 	/usr/local/go/src/net/fd_unix.go:408 +0x27c
16:22:15 etcd | net.(*TCPListener).AcceptTCP(0xc820190058, 0x0, 0x0, 0x0)
16:22:15 etcd | 	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
16:22:15 etcd | net.(*TCPListener).Accept(0xc820190058, 0x0, 0x0, 0x0, 0x0)
16:22:15 etcd | 	/usr/local/go/src/net/tcpsock_posix.go:264 +0x3d
16:22:15 etcd | github.com/coreos/etcd/pkg/transport.(*keepaliveListener).Accept(0xc8201fe220, 0x0, 0x0, 0x0, 0x0)
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/transport/keepalive_listener.go:52 +0x62
16:22:15 etcd | github.com/coreos/etcd/Godeps/_workspace/src/golang.org/x/net/netutil.(*limitListener).Accept(0xc8201f7b80, 0x0, 0x0, 0x0, 0x0)
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/golang.org/x/net/netutil/listen.go:30 +0x8c
16:22:15 etcd | net/http.(*Server).Serve(0xc82000b200, 0x7ff519cfa580, 0xc8201f7b80, 0x0, 0x0)
16:22:15 etcd | 	/usr/local/go/src/net/http/server.go:1887 +0xb3
16:22:15 etcd | github.com/coreos/etcd/etcdmain.serveHTTP(0x7ff519cfa580, 0xc8201f7b80, 0x7ff519d404d8, 0xc820209780, 0x0, 0x0, 0x0)
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdmain/http.go:36 +0x167
16:22:15 etcd | github.com/coreos/etcd/etcdmain.startEtcd.func4(0xc820209780, 0x7ff519cfa580, 0xc8201f7b80)
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:317 +0x7e
16:22:15 etcd | created by github.com/coreos/etcd/etcdmain.startEtcd
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:318 +0x1f65
16:22:15 etcd | goroutine 99 [IO wait]:
16:22:15 etcd | net.runtime_pollWait(0x7ff519d3f128, 0x72, 0xc82000e260)
16:22:15 etcd | 	/usr/local/go/src/runtime/netpoll.go:157 +0x60
16:22:15 etcd | net.(*pollDesc).Wait(0xc8201e6530, 0x72, 0x0, 0x0)
16:22:15 etcd | 	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
16:22:15 etcd | net.(*pollDesc).WaitRead(0xc8201e6530, 0x0, 0x0)
16:22:15 etcd | 	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
16:22:15 etcd | net.(*netFD).accept(0xc8201e64d0, 0x0, 0x7ff519d40500, 0xc8200fd9e0)
16:22:15 etcd | 	/usr/local/go/src/net/fd_unix.go:408 +0x27c
16:22:15 etcd | net.(*TCPListener).AcceptTCP(0xc820190060, 0x0, 0x0, 0x0)
16:22:15 etcd | 	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
16:22:15 etcd | net.(*TCPListener).Accept(0xc820190060, 0x0, 0x0, 0x0, 0x0)
16:22:15 etcd | 	/usr/local/go/src/net/tcpsock_posix.go:264 +0x3d
16:22:15 etcd | github.com/coreos/etcd/pkg/transport.(*keepaliveListener).Accept(0xc8201fe2f0, 0x0, 0x0, 0x0, 0x0)
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/transport/keepalive_listener.go:52 +0x62
16:22:15 etcd | github.com/coreos/etcd/Godeps/_workspace/src/golang.org/x/net/netutil.(*limitListener).Accept(0xc8201f7c60, 0x0, 0x0, 0x0, 0x0)
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/golang.org/x/net/netutil/listen.go:30 +0x8c
16:22:15 etcd | net/http.(*Server).Serve(0xc82000b140, 0x7ff519cfa580, 0xc8201f7c60, 0x0, 0x0)
16:22:15 etcd | 	/usr/local/go/src/net/http/server.go:1887 +0xb3
16:22:15 etcd | github.com/coreos/etcd/etcdmain.serveHTTP(0x7ff519cfa580, 0xc8201f7c60, 0x7ff519d404d8, 0xc820209780, 0x0, 0x0, 0x0)
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdmain/http.go:36 +0x167
16:22:15 etcd | github.com/coreos/etcd/etcdmain.startEtcd.func4(0xc820209780, 0x7ff519cfa580, 0xc8201f7c60)
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:317 +0x7e
16:22:15 etcd | created by github.com/coreos/etcd/etcdmain.startEtcd
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:318 +0x1f65
16:22:15 etcd | goroutine 100 [IO wait]:
16:22:15 etcd | net.runtime_pollWait(0x7ff519d3f068, 0x72, 0xc82000e260)
16:22:15 etcd | 	/usr/local/go/src/runtime/netpoll.go:157 +0x60
16:22:15 etcd | net.(*pollDesc).Wait(0xc8201e6610, 0x72, 0x0, 0x0)
16:22:15 etcd | 	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
16:22:15 etcd | net.(*pollDesc).WaitRead(0xc8201e6610, 0x0, 0x0)
16:22:15 etcd | 	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
16:22:15 etcd | net.(*netFD).accept(0xc8201e65b0, 0x0, 0x7ff519d40500, 0xc820522d60)
16:22:15 etcd | 	/usr/local/go/src/net/fd_unix.go:408 +0x27c
16:22:15 etcd | net.(*TCPListener).AcceptTCP(0xc820190068, 0xc820396e30, 0x0, 0x0)
16:22:15 etcd | 	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
16:22:15 etcd | net.(*TCPListener).Accept(0xc820190068, 0x0, 0x0, 0x0, 0x0)
16:22:15 etcd | 	/usr/local/go/src/net/tcpsock_posix.go:264 +0x3d
16:22:15 etcd | github.com/coreos/etcd/Godeps/_workspace/src/google.golang.org/grpc.(*Server).Serve(0xc820187e00, 0x7ff519cfa468, 0xc820190068, 0x0, 0x0)
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/google.golang.org/grpc/server.go:194 +0x187
16:22:15 etcd | github.com/coreos/etcd/etcdmain.startEtcd.func5(0xc820187e00, 0x7ff519cfa468, 0xc820190068)
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:326 +0x3f
16:22:15 etcd | created by github.com/coreos/etcd/etcdmain.startEtcd
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:326 +0x22f8
16:22:15 etcd | goroutine 101 [select, locked to thread]:
16:22:15 etcd | runtime.gopark(0xfb0a60, 0xc820376f28, 0xdff5d0, 0x6, 0x18, 0x2)
16:22:15 etcd | 	/usr/local/go/src/runtime/proc.go:185 +0x163
16:22:15 etcd | runtime.selectgoImpl(0xc820376f28, 0x0, 0x18)
16:22:15 etcd | 	/usr/local/go/src/runtime/select.go:392 +0xa64
16:22:15 etcd | runtime.selectgo(0xc820376f28)
16:22:15 etcd | 	/usr/local/go/src/runtime/select.go:212 +0x12
16:22:15 etcd | runtime.ensureSigM.func1()
16:22:15 etcd | 	/usr/local/go/src/runtime/signal1_unix.go:227 +0x353
16:22:15 etcd | runtime.goexit()
16:22:15 etcd | 	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
16:22:15 etcd | goroutine 102 [chan receive]:
16:22:15 etcd | github.com/coreos/etcd/pkg/osutil.HandleInterrupts.func1(0xc82019b800)
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/osutil/interrupt_unix.go:51 +0x5b
16:22:15 etcd | created by github.com/coreos/etcd/pkg/osutil.HandleInterrupts
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/osutil/interrupt_unix.go:72 +0x1b7
16:22:15 etcd | goroutine 116 [select]:
16:22:15 etcd | github.com/coreos/etcd/Godeps/_workspace/src/google.golang.org/grpc/transport.(*http2Server).controller(0xc820192f80)
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/google.golang.org/grpc/transport/http2_server.go:591 +0x5db
16:22:15 etcd | created by github.com/coreos/etcd/Godeps/_workspace/src/google.golang.org/grpc/transport.newHTTP2Server
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/google.golang.org/grpc/transport/http2_server.go:132 +0x819
16:22:15 etcd | goroutine 117 [IO wait]:
16:22:15 etcd | net.runtime_pollWait(0x7ff519d3efa8, 0x72, 0xc82000e260)
16:22:15 etcd | 	/usr/local/go/src/runtime/netpoll.go:157 +0x60
16:22:15 etcd | net.(*pollDesc).Wait(0xc8204c48b0, 0x72, 0x0, 0x0)
16:22:15 etcd | 	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
16:22:15 etcd | net.(*pollDesc).WaitRead(0xc8204c48b0, 0x0, 0x0)
16:22:15 etcd | 	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
16:22:15 etcd | net.(*netFD).Read(0xc8204c4850, 0xc82053c6e4, 0x9, 0x9, 0x0, 0x7ff519d3a050, 0xc82000e260)
16:22:15 etcd | 	/usr/local/go/src/net/fd_unix.go:232 +0x23a
16:22:15 etcd | net.(*conn).Read(0xc820190360, 0xc82053c6e4, 0x9, 0x9, 0x0, 0x0, 0x0)
16:22:15 etcd | 	/usr/local/go/src/net/net.go:172 +0xe4
16:22:15 etcd | io.ReadAtLeast(0x7ff519cfb8c0, 0xc820190360, 0xc82053c6e4, 0x9, 0x9, 0x9, 0x0, 0x0, 0x0)
16:22:15 etcd | 	/usr/local/go/src/io/io.go:298 +0xe6
16:22:15 etcd | io.ReadFull(0x7ff519cfb8c0, 0xc820190360, 0xc82053c6e4, 0x9, 0x9, 0xcdf8785b358dd801, 0x0, 0x0)
16:22:15 etcd | 	/usr/local/go/src/io/io.go:316 +0x62
16:22:15 etcd | github.com/coreos/etcd/Godeps/_workspace/src/github.com/bradfitz/http2.readFrameHeader(0xc82053c6e4, 0x9, 0x9, 0x7ff519cfb8c0, 0xc820190360, 0x19000000, 0xc800000000, 0x0, 0x0)
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/bradfitz/http2/frame.go:228 +0xa5
16:22:15 etcd | github.com/coreos/etcd/Godeps/_workspace/src/github.com/bradfitz/http2.(*Framer).ReadFrame(0xc82053c6c0, 0x0, 0x0, 0x0, 0x0)
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/bradfitz/http2/frame.go:373 +0xe6
16:22:15 etcd | github.com/coreos/etcd/Godeps/_workspace/src/google.golang.org/grpc/transport.(*framer).readFrame(0xc8204bfdd0, 0x0, 0x0, 0x0, 0x0)
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/google.golang.org/grpc/transport/http_util.go:436 +0x3d
16:22:15 etcd | github.com/coreos/etcd/Godeps/_workspace/src/google.golang.org/grpc/transport.(*http2Server).HandleStreams(0xc820192f80, 0xc820522d80)
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/google.golang.org/grpc/transport/http2_server.go:244 +0x6be
16:22:15 etcd | github.com/coreos/etcd/Godeps/_workspace/src/google.golang.org/grpc.(*Server).Serve.func2(0x7ff519cfb910, 0xc820192f80, 0xc820187e00)
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/google.golang.org/grpc/server.go:224 +0x89
16:22:15 etcd | created by github.com/coreos/etcd/Godeps/_workspace/src/google.golang.org/grpc.(*Server).Serve
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/google.golang.org/grpc/server.go:228 +0x6e4
16:22:15 etcd | goroutine 118 [runnable]:
16:22:15 etcd | github.com/coreos/etcd/etcdserver.(*EtcdServer).processInternalRaftRequest(0xc820174480, 0x7ff519cfbab8, 0xc8204bff20, 0xca513b5fe37a0023, 0x0, 0x0, 0x0, 0x0, 0xc8203ad090, 0x0, ...)
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/v3demo_server.go:92 +0x3ec
16:22:15 etcd | github.com/coreos/etcd/etcdserver.(*EtcdServer).Txn(0xc820174480, 0x7ff519cfbab8, 0xc8204bff20, 0xc8203ad090, 0xc8203ad090, 0x0, 0x0)
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/v3demo_server.go:61 +0xbf
16:22:15 etcd | github.com/coreos/etcd/etcdserver/api/v3rpc.(*kvServer).Txn(0xc8201ff8b0, 0x7ff519cfbab8, 0xc8204bff20, 0xc8203ad090, 0xd9a140, 0x0, 0x0)
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/api/v3rpc/key.go:79 +0xc3
16:22:15 etcd | github.com/coreos/etcd/etcdserver/etcdserverpb._KV_Txn_Handler(0xd17160, 0xc8201ff8b0, 0x7ff519cfbab8, 0xc8204bff20, 0x7ff519cfb630, 0x12e6348, 0xc8204d5380, 0x7, 0x7, 0x0, ...)
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.go:544 +0x16a
16:22:15 etcd | github.com/coreos/etcd/Godeps/_workspace/src/google.golang.org/grpc.(*Server).processUnaryRPC(0xc820187e00, 0x7ff519cfb910, 0xc820192f80, 0xc82031a180, 0xc820209820, 0x12b45e8)
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/google.golang.org/grpc/server.go:272 +0x68e
16:22:15 etcd | github.com/coreos/etcd/Godeps/_workspace/src/google.golang.org/grpc.(*Server).handleStream(0xc820187e00, 0x7ff519cfb910, 0xc820192f80, 0xc82031a180)
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/google.golang.org/grpc/server.go:351 +0x72a
16:22:15 etcd | github.com/coreos/etcd/Godeps/_workspace/src/google.golang.org/grpc.(*Server).Serve.func2.1(0xc82031a180)
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/google.golang.org/grpc/server.go:223 +0x49
16:22:15 etcd | github.com/coreos/etcd/Godeps/_workspace/src/google.golang.org/grpc/transport.(*http2Server).operateHeaders.func3(0xc820522d80, 0xc82031a180, 0xc8204d5260)
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/google.golang.org/grpc/transport/http2_server.go:203 +0x26
16:22:15 etcd | created by github.com/coreos/etcd/Godeps/_workspace/src/google.golang.org/grpc/transport.(*http2Server).operateHeaders
16:22:15 etcd | 	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/google.golang.org/grpc/transport/http2_server.go:205 +0xd5e
16:22:15 etcd | Terminating etcd
```

### PR DESCRIPTION
**Pull request by barakmich**
Fixes #3920

### CODE REVIEW

File: etcdserver/v3demo_server.go [hunk 1]
```diff
@@ -301,8 +301,19 @@ func applyCompare(txnID int64, kv dstorage.KV, c *pb.Compare) (int64, bool) {
...
 		return rev, false
 	}
-
-	ckv := ckvs[0]
+	var ckv storagepb.KeyValue
+	if len(ckvs) != 0 {
+		ckv = ckvs[0]
+	} else {
+		// Use the zero value of ckv normally. However...
+		if c.Target == pb.Compare_VALUE {
```
Comment (xiang90) [inline etcdserver/v3demo_server.go]: I think we do not have to do this. If we want to compare the existence, we can always compare the version, right?

**Comment by barakmich** [comment]
True, for pure existence. However, there's a more subtle version, ie, checking a known value. If the key has been deleted before I get back to it, it's a very helpful shortcut.

**Comment by xiang90** [comment]
> However, there's a more subtle version, ie, checking a known value. If the key has been deleted before I get back to it, it's a very helpful shortcut.

In this case, the checking always fails since you compare a known value against an empty kv whose value is empty. Or probably I did not understand it correct. Can you provide an example?

**Comment by barakmich** [comment]
There are two options, both reasonable.

One, the empty value compares against  the default empty value, the zero
length byte array.

My argument is more subtle:

Suppose, however, my key is present to be a sentinel. Its known value is
the zero length byte array. I can't (using value comparison alone) tell the
difference between a key that is there with my sentinel value and a key
which isn't there at all. I'd have to do two checks.

You'll notice this is not true with versions; all keys have version number
fields from [1,maxint] and therefore 0 is a perfect "doesn't exist" value.

This isn't true of the empty byte array, because I can actually write the
empty byte array as a value if I so choose. (Put{Key: []byte("foo"), Value:
[]byte{}})

So we need a valid comparison function to delineate between "existing and
zero value" and "not existing".

I chose here to always fail comparison, like NaN does. Another perfectly
sound answer is to make non-existence "less than" all values, including the
empty byte array -- this would maintain the values being a total order.

It sounds like I'm overthinking it, but I'm really refusing the temptation
to alias the two things.

**Comment by barakmich** [comment]
Put another way:

In Go, we use map[T]struct{} (or sometimes bool) to represent a simple set. We can support this notion in etcd, so long as we can tell non-existence from existence. (Yes, you can write "true" as your value everywhere, by why store the bits?)

**Comment by xiang90** [comment]
@barakmich OK. Sounds reasonable to me.

**Comment by xiang90** [comment]
LGTM. Thanks.
