### PR TITLE
etcdserver: fix TestSnap

### LINKED ISSUE #5797: TestSnapshot fails
```
--- FAIL: TestSnapshot (0.18s)
	server_test.go:874: len(action) = 0, want 1
2016-06-28 21:23:04.485486 I | etcdserver: saved snapshot at index 1
2016-06-28 21:23:04.485552 I | etcdserver: compacted raft log at 1
2016-06-28 21:23:04.486929 I | etcdserver: starting server... [version: 3.0.0-beta.0+git, cluster version: to_be_decided]
2016-06-28 21:23:04.488963 I | etcdserver: start to snapshot (applied: 11, lastsnap: 0)
2016-06-28 21:23:04.490315 I | etcdserver: saved snapshot at index 11
2016-06-28 21:23:04.490425 I | etcdserver: compacted raft log at 1
2016-06-28 21:23:04.504073 I | etcdserver: set snapshot count to default 10000
2016-06-28 21:23:04.504175 I | etcdserver: starting server... [version: 3.0.0-beta.0+git, cluster version: to_be_decided]
2016-06-28 21:23:04.507096 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:04.507858 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:04.508094 I | etcdserver: raft applied incoming snapshot at index 3
2016-06-28 21:23:04.508696 I | etcdserver: applying snapshot at index 0...
2016-06-28 21:23:04.510731 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:04.510953 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:04.511055 I | etcdserver: recovering alarms...
2016-06-28 21:23:04.511757 I | etcdserver: closing old backend...
2016-06-28 21:23:04.518122 I | etcdserver: finished recovering alarms
2016-06-28 21:23:04.518193 I | etcdserver: recovering store v2...
2016-06-28 21:23:04.522034 I | etcdserver: finished recovering store v2
2016-06-28 21:23:04.522165 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:04.522323 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:04.522369 I | etcdserver: removing old peers from network...
2016-06-28 21:23:04.522435 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:04.522473 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:04.522520 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:04.522592 I | etcdserver: finished applying incoming snapshot at index 0
2016-06-28 21:23:04.524503 I | etcdserver: finished closing old backend
2016-06-28 21:23:04.532940 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:04.533799 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:04.533997 I | etcdserver: raft applied incoming snapshot at index 6
2016-06-28 21:23:04.534112 I | etcdserver: applying snapshot at index 3...
2016-06-28 21:23:04.534372 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:04.534622 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:04.534741 I | etcdserver: recovering alarms...
2016-06-28 21:23:04.535054 I | etcdserver: closing old backend...
2016-06-28 21:23:04.537776 I | etcdserver: finished recovering alarms
2016-06-28 21:23:04.537817 I | etcdserver: recovering store v2...
2016-06-28 21:23:04.540882 I | etcdserver: finished recovering store v2
2016-06-28 21:23:04.540938 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:04.541035 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:04.541061 I | etcdserver: removing old peers from network...
2016-06-28 21:23:04.541083 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:04.541104 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:04.541129 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:04.541157 I | etcdserver: finished applying incoming snapshot at index 3
2016-06-28 21:23:04.542282 I | etcdserver: finished closing old backend
2016-06-28 21:23:04.544393 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:04.545190 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:04.545411 I | etcdserver: raft applied incoming snapshot at index 9
2016-06-28 21:23:04.545523 I | etcdserver: applying snapshot at index 6...
2016-06-28 21:23:04.545806 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:04.546043 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:04.546191 I | etcdserver: recovering alarms...
2016-06-28 21:23:04.546344 I | etcdserver: closing old backend...
2016-06-28 21:23:04.547406 I | etcdserver: finished recovering alarms
2016-06-28 21:23:04.547451 I | etcdserver: recovering store v2...
2016-06-28 21:23:04.550548 I | etcdserver: finished recovering store v2
2016-06-28 21:23:04.550742 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:04.550849 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:04.550906 I | etcdserver: removing old peers from network...
2016-06-28 21:23:04.550944 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:04.550976 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:04.551011 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:04.551049 I | etcdserver: finished applying incoming snapshot at index 6
2016-06-28 21:23:04.551213 I | etcdserver: finished closing old backend
2016-06-28 21:23:04.554086 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:04.554791 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:04.554955 I | etcdserver: raft applied incoming snapshot at index 12
2016-06-28 21:23:04.555140 I | etcdserver: applying snapshot at index 9...
2016-06-28 21:23:04.555381 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:04.555585 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:04.555716 I | etcdserver: recovering alarms...
2016-06-28 21:23:04.555868 I | etcdserver: closing old backend...
2016-06-28 21:23:04.558287 I | etcdserver: finished recovering alarms
2016-06-28 21:23:04.558332 I | etcdserver: recovering store v2...
2016-06-28 21:23:04.558679 I | etcdserver: finished closing old backend
2016-06-28 21:23:04.561448 I | etcdserver: finished recovering store v2
2016-06-28 21:23:04.561509 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:04.561617 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:04.561687 I | etcdserver: removing old peers from network...
2016-06-28 21:23:04.561724 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:04.561756 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:04.561792 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:04.561833 I | etcdserver: finished applying incoming snapshot at index 9
2016-06-28 21:23:04.565181 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:04.565960 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:04.566079 I | etcdserver: raft applied incoming snapshot at index 15
2016-06-28 21:23:04.566159 I | etcdserver: applying snapshot at index 12...
2016-06-28 21:23:04.566394 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:04.566601 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:04.566717 I | etcdserver: recovering alarms...
2016-06-28 21:23:04.567008 I | etcdserver: closing old backend...
2016-06-28 21:23:04.568609 I | etcdserver: finished closing old backend
2016-06-28 21:23:04.569021 I | etcdserver: finished recovering alarms
2016-06-28 21:23:04.569065 I | etcdserver: recovering store v2...
2016-06-28 21:23:04.572125 I | etcdserver: finished recovering store v2
2016-06-28 21:23:04.572180 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:04.572282 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:04.572318 I | etcdserver: removing old peers from network...
2016-06-28 21:23:04.572351 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:04.572385 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:04.572420 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:04.572458 I | etcdserver: finished applying incoming snapshot at index 12
2016-06-28 21:23:04.575073 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:04.575832 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:04.576041 I | etcdserver: raft applied incoming snapshot at index 18
2016-06-28 21:23:04.576135 I | etcdserver: applying snapshot at index 15...
2016-06-28 21:23:04.576353 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:04.576530 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:04.576643 I | etcdserver: recovering alarms...
2016-06-28 21:23:04.576774 I | etcdserver: closing old backend...
2016-06-28 21:23:04.578081 I | etcdserver: finished closing old backend
2016-06-28 21:23:04.578206 I | etcdserver: finished recovering alarms
2016-06-28 21:23:04.578241 I | etcdserver: recovering store v2...
2016-06-28 21:23:04.581280 I | etcdserver: finished recovering store v2
2016-06-28 21:23:04.581323 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:04.581414 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:04.581439 I | etcdserver: removing old peers from network...
2016-06-28 21:23:04.581461 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:04.581485 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:04.581509 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:04.581536 I | etcdserver: finished applying incoming snapshot at index 15
2016-06-28 21:23:04.585435 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:04.586161 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:04.586271 I | etcdserver: raft applied incoming snapshot at index 21
2016-06-28 21:23:04.586484 I | etcdserver: applying snapshot at index 18...
2016-06-28 21:23:04.586781 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:04.586967 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:04.587147 I | etcdserver: recovering alarms...
2016-06-28 21:23:04.587391 I | etcdserver: closing old backend...
2016-06-28 21:23:04.588472 I | etcdserver: finished closing old backend
2016-06-28 21:23:04.588720 I | etcdserver: finished recovering alarms
2016-06-28 21:23:04.588763 I | etcdserver: recovering store v2...
2016-06-28 21:23:04.591828 I | etcdserver: finished recovering store v2
2016-06-28 21:23:04.591885 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:04.591995 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:04.592031 I | etcdserver: removing old peers from network...
2016-06-28 21:23:04.592066 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:04.592097 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:04.592132 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:04.592171 I | etcdserver: finished applying incoming snapshot at index 18
2016-06-28 21:23:04.594968 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:04.595827 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:04.595934 I | etcdserver: raft applied incoming snapshot at index 24
2016-06-28 21:23:04.596184 I | etcdserver: applying snapshot at index 21...
2016-06-28 21:23:04.596439 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:04.596629 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:04.596807 I | etcdserver: closing old backend...
2016-06-28 21:23:04.596945 I | etcdserver: recovering alarms...
2016-06-28 21:23:04.598011 I | etcdserver: finished closing old backend
2016-06-28 21:23:04.598496 I | etcdserver: finished recovering alarms
2016-06-28 21:23:04.598541 I | etcdserver: recovering store v2...
2016-06-28 21:23:04.601588 I | etcdserver: finished recovering store v2
2016-06-28 21:23:04.601644 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:04.601750 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:04.601787 I | etcdserver: removing old peers from network...
2016-06-28 21:23:04.601826 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:04.601856 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:04.601892 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:04.601933 I | etcdserver: finished applying incoming snapshot at index 21
2016-06-28 21:23:04.605099 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:04.605879 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:04.606079 I | etcdserver: raft applied incoming snapshot at index 27
2016-06-28 21:23:04.606266 I | etcdserver: applying snapshot at index 24...
2016-06-28 21:23:04.606500 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:04.606685 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:04.606779 I | etcdserver: recovering alarms...
2016-06-28 21:23:04.607130 I | etcdserver: closing old backend...
2016-06-28 21:23:04.608622 I | etcdserver: finished closing old backend
2016-06-28 21:23:04.608760 I | etcdserver: finished recovering alarms
2016-06-28 21:23:04.608797 I | etcdserver: recovering store v2...
2016-06-28 21:23:04.611851 I | etcdserver: finished recovering store v2
2016-06-28 21:23:04.611896 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:04.611995 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:04.612021 I | etcdserver: removing old peers from network...
2016-06-28 21:23:04.612043 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:04.612064 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:04.612088 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:04.612116 I | etcdserver: finished applying incoming snapshot at index 24
2016-06-28 21:23:04.614851 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:04.615596 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:04.615760 I | etcdserver: raft applied incoming snapshot at index 30
2016-06-28 21:23:04.615918 I | etcdserver: applying snapshot at index 27...
2016-06-28 21:23:04.616247 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:04.616446 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:04.616560 I | etcdserver: recovering alarms...
2016-06-28 21:23:04.616718 I | etcdserver: closing old backend...
2016-06-28 21:23:04.618873 I | etcdserver: finished closing old backend
2016-06-28 21:23:04.619097 I | etcdserver: finished recovering alarms
2016-06-28 21:23:04.619141 I | etcdserver: recovering store v2...
2016-06-28 21:23:04.622202 I | etcdserver: finished recovering store v2
2016-06-28 21:23:04.622262 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:04.622364 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:04.622401 I | etcdserver: removing old peers from network...
2016-06-28 21:23:04.622433 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:04.622464 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:04.622500 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:04.622538 I | etcdserver: finished applying incoming snapshot at index 27
2016-06-28 21:23:04.625501 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:04.626310 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:04.626410 I | etcdserver: raft applied incoming snapshot at index 33
2016-06-28 21:23:04.626620 I | etcdserver: applying snapshot at index 30...
2016-06-28 21:23:04.626915 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:04.627111 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:04.627275 I | etcdserver: closing old backend...
2016-06-28 21:23:04.627418 I | etcdserver: recovering alarms...
2016-06-28 21:23:04.628792 I | etcdserver: finished closing old backend
2016-06-28 21:23:04.629430 I | etcdserver: finished recovering alarms
2016-06-28 21:23:04.629473 I | etcdserver: recovering store v2...
2016-06-28 21:23:04.632509 I | etcdserver: finished recovering store v2
2016-06-28 21:23:04.632565 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:04.632665 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:04.632724 I | etcdserver: removing old peers from network...
2016-06-28 21:23:04.632760 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:04.632791 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:04.632825 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:04.632868 I | etcdserver: finished applying incoming snapshot at index 30
2016-06-28 21:23:04.635612 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:04.636540 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:04.636650 I | etcdserver: raft applied incoming snapshot at index 36
2016-06-28 21:23:04.636851 I | etcdserver: applying snapshot at index 33...
2016-06-28 21:23:04.637145 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:04.637359 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:04.637461 I | etcdserver: recovering alarms...
2016-06-28 21:23:04.637539 I | etcdserver: closing old backend...
2016-06-28 21:23:04.638626 I | etcdserver: finished closing old backend
2016-06-28 21:23:04.638845 I | etcdserver: finished recovering alarms
2016-06-28 21:23:04.638888 I | etcdserver: recovering store v2...
2016-06-28 21:23:04.641929 I | etcdserver: finished recovering store v2
2016-06-28 21:23:04.641985 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:04.642085 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:04.642124 I | etcdserver: removing old peers from network...
2016-06-28 21:23:04.642156 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:04.642187 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:04.642221 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:04.642259 I | etcdserver: finished applying incoming snapshot at index 33
2016-06-28 21:23:04.645126 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:04.645998 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:04.646106 I | etcdserver: raft applied incoming snapshot at index 39
2016-06-28 21:23:04.646342 I | etcdserver: applying snapshot at index 36...
2016-06-28 21:23:04.646622 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:04.646803 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:04.646957 I | etcdserver: closing old backend...
2016-06-28 21:23:04.647095 I | etcdserver: recovering alarms...
2016-06-28 21:23:04.651632 I | etcdserver: finished closing old backend
2016-06-28 21:23:04.651731 I | etcdserver: finished recovering alarms
2016-06-28 21:23:04.651773 I | etcdserver: recovering store v2...
2016-06-28 21:23:04.654815 I | etcdserver: finished recovering store v2
2016-06-28 21:23:04.654871 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:04.654973 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:04.655010 I | etcdserver: removing old peers from network...
2016-06-28 21:23:04.655044 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:04.655078 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:04.655119 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:04.655159 I | etcdserver: finished applying incoming snapshot at index 36
2016-06-28 21:23:04.658705 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:04.661520 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:04.661623 I | etcdserver: raft applied incoming snapshot at index 42
2016-06-28 21:23:04.661868 I | etcdserver: applying snapshot at index 39...
2016-06-28 21:23:04.662170 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:04.662362 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:04.662539 I | etcdserver: closing old backend...
2016-06-28 21:23:04.662682 I | etcdserver: recovering alarms...
2016-06-28 21:23:04.666709 I | etcdserver: finished closing old backend
2016-06-28 21:23:04.667164 I | etcdserver: finished recovering alarms
2016-06-28 21:23:04.667211 I | etcdserver: recovering store v2...
2016-06-28 21:23:04.670239 I | etcdserver: finished recovering store v2
2016-06-28 21:23:04.670295 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:04.670399 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:04.670436 I | etcdserver: removing old peers from network...
2016-06-28 21:23:04.670468 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:04.670499 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:04.670533 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:04.670572 I | etcdserver: finished applying incoming snapshot at index 39
2016-06-28 21:23:04.673517 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:04.674439 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:04.674541 I | etcdserver: raft applied incoming snapshot at index 45
2016-06-28 21:23:04.674747 I | etcdserver: applying snapshot at index 42...
2016-06-28 21:23:04.675035 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:04.675266 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:04.675393 I | etcdserver: recovering alarms...
2016-06-28 21:23:04.675685 I | etcdserver: closing old backend...
2016-06-28 21:23:04.676680 I | etcdserver: finished closing old backend
2016-06-28 21:23:04.676910 I | etcdserver: finished recovering alarms
2016-06-28 21:23:04.676953 I | etcdserver: recovering store v2...
2016-06-28 21:23:04.679995 I | etcdserver: finished recovering store v2
2016-06-28 21:23:04.680052 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:04.680150 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:04.680186 I | etcdserver: removing old peers from network...
2016-06-28 21:23:04.680218 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:04.680253 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:04.680288 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:04.680326 I | etcdserver: finished applying incoming snapshot at index 42
2016-06-28 21:23:04.683269 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:04.684178 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:04.684387 I | etcdserver: raft applied incoming snapshot at index 48
2016-06-28 21:23:04.684499 I | etcdserver: applying snapshot at index 45...
2016-06-28 21:23:04.684812 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:04.684982 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:04.685171 I | etcdserver: recovering alarms...
2016-06-28 21:23:04.685387 I | etcdserver: closing old backend...
2016-06-28 21:23:04.687877 I | etcdserver: finished closing old backend
2016-06-28 21:23:04.688123 I | etcdserver: finished recovering alarms
2016-06-28 21:23:04.688165 I | etcdserver: recovering store v2...
2016-06-28 21:23:04.691172 I | etcdserver: finished recovering store v2
2016-06-28 21:23:04.691265 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:04.691368 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:04.691404 I | etcdserver: removing old peers from network...
2016-06-28 21:23:04.691437 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:04.691468 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:04.691503 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:04.691541 I | etcdserver: finished applying incoming snapshot at index 45
2016-06-28 21:23:04.697510 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:04.698341 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:04.698542 I | etcdserver: raft applied incoming snapshot at index 51
2016-06-28 21:23:04.698663 I | etcdserver: applying snapshot at index 48...
2016-06-28 21:23:04.698879 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:04.699072 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:04.699217 I | etcdserver: recovering alarms...
2016-06-28 21:23:04.699365 I | etcdserver: closing old backend...
2016-06-28 21:23:04.700403 I | etcdserver: finished closing old backend
2016-06-28 21:23:04.700504 I | etcdserver: finished recovering alarms
2016-06-28 21:23:04.700538 I | etcdserver: recovering store v2...
2016-06-28 21:23:04.703564 I | etcdserver: finished recovering store v2
2016-06-28 21:23:04.703607 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:04.703699 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:04.703725 I | etcdserver: removing old peers from network...
2016-06-28 21:23:04.703748 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:04.703768 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:04.703793 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:04.703820 I | etcdserver: finished applying incoming snapshot at index 48
2016-06-28 21:23:04.706555 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:04.707336 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:04.707454 I | etcdserver: raft applied incoming snapshot at index 54
2016-06-28 21:23:04.707685 I | etcdserver: applying snapshot at index 51...
2016-06-28 21:23:04.707940 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:04.708141 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:04.708273 I | etcdserver: recovering alarms...
2016-06-28 21:23:04.708626 I | etcdserver: closing old backend...
2016-06-28 21:23:04.711948 I | etcdserver: finished recovering alarms
2016-06-28 21:23:04.712019 I | etcdserver: recovering store v2...
2016-06-28 21:23:04.712486 I | etcdserver: finished closing old backend
2016-06-28 21:23:04.715238 I | etcdserver: finished recovering store v2
2016-06-28 21:23:04.715300 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:04.715404 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:04.715443 I | etcdserver: removing old peers from network...
2016-06-28 21:23:04.715476 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:04.715509 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:04.715546 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:04.715585 I | etcdserver: finished applying incoming snapshot at index 51
2016-06-28 21:23:04.718276 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:04.719183 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:04.719373 I | etcdserver: raft applied incoming snapshot at index 57
2016-06-28 21:23:04.719516 I | etcdserver: applying snapshot at index 54...
2016-06-28 21:23:04.719828 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:04.720017 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:04.720163 I | etcdserver: recovering alarms...
2016-06-28 21:23:04.720436 I | etcdserver: closing old backend...
2016-06-28 21:23:04.721435 I | etcdserver: finished closing old backend
2016-06-28 21:23:04.721663 I | etcdserver: finished recovering alarms
2016-06-28 21:23:04.721706 I | etcdserver: recovering store v2...
2016-06-28 21:23:04.724783 I | etcdserver: finished recovering store v2
2016-06-28 21:23:04.724839 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:04.724938 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:04.724975 I | etcdserver: removing old peers from network...
2016-06-28 21:23:04.725007 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:04.725037 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:04.725077 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:04.725116 I | etcdserver: finished applying incoming snapshot at index 54
2016-06-28 21:23:04.727663 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:04.728440 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:04.728611 I | etcdserver: raft applied incoming snapshot at index 60
2016-06-28 21:23:04.728808 I | etcdserver: applying snapshot at index 57...
2016-06-28 21:23:04.729059 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:04.729233 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:04.729378 I | etcdserver: recovering alarms...
2016-06-28 21:23:04.729488 I | etcdserver: closing old backend...
2016-06-28 21:23:04.733052 I | etcdserver: finished closing old backend
2016-06-28 21:23:04.733545 I | etcdserver: finished recovering alarms
2016-06-28 21:23:04.733589 I | etcdserver: recovering store v2...
2016-06-28 21:23:04.736647 I | etcdserver: finished recovering store v2
2016-06-28 21:23:04.736701 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:04.736799 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:04.736836 I | etcdserver: removing old peers from network...
2016-06-28 21:23:04.736868 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:04.736899 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:04.736934 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:04.736971 I | etcdserver: finished applying incoming snapshot at index 57
2016-06-28 21:23:04.739604 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:04.740429 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:04.740605 I | etcdserver: raft applied incoming snapshot at index 63
2016-06-28 21:23:04.740683 I | etcdserver: applying snapshot at index 60...
2016-06-28 21:23:04.740890 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:04.741101 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:04.741213 I | etcdserver: recovering alarms...
2016-06-28 21:23:04.741342 I | etcdserver: closing old backend...
2016-06-28 21:23:04.742361 I | etcdserver: finished closing old backend
2016-06-28 21:23:04.742461 I | etcdserver: finished recovering alarms
2016-06-28 21:23:04.742495 I | etcdserver: recovering store v2...
2016-06-28 21:23:04.745526 I | etcdserver: finished recovering store v2
2016-06-28 21:23:04.745569 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:04.745654 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:04.745682 I | etcdserver: removing old peers from network...
2016-06-28 21:23:04.745704 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:04.745724 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:04.745748 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:04.745774 I | etcdserver: finished applying incoming snapshot at index 60
2016-06-28 21:23:04.748527 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:04.749447 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:04.749631 I | etcdserver: raft applied incoming snapshot at index 66
2016-06-28 21:23:04.749768 I | etcdserver: applying snapshot at index 63...
2016-06-28 21:23:04.750012 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:04.750188 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:04.750315 I | etcdserver: recovering alarms...
2016-06-28 21:23:04.750680 I | etcdserver: closing old backend...
2016-06-28 21:23:04.751468 I | etcdserver: finished closing old backend
2016-06-28 21:23:04.751973 I | etcdserver: finished recovering alarms
2016-06-28 21:23:04.752016 I | etcdserver: recovering store v2...
2016-06-28 21:23:04.755021 I | etcdserver: finished recovering store v2
2016-06-28 21:23:04.755076 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:04.755175 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:04.755237 I | etcdserver: removing old peers from network...
2016-06-28 21:23:04.755271 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:04.755301 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:04.755335 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:04.755375 I | etcdserver: finished applying incoming snapshot at index 63
2016-06-28 21:23:04.758081 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:04.758831 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:04.759011 I | etcdserver: raft applied incoming snapshot at index 69
2016-06-28 21:23:04.759212 I | etcdserver: applying snapshot at index 66...
2016-06-28 21:23:04.759463 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:04.759627 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:04.759721 I | etcdserver: recovering alarms...
2016-06-28 21:23:04.759856 I | etcdserver: closing old backend...
2016-06-28 21:23:04.760790 I | etcdserver: finished recovering alarms
2016-06-28 21:23:04.760827 I | etcdserver: recovering store v2...
2016-06-28 21:23:04.763851 I | etcdserver: finished recovering store v2
2016-06-28 21:23:04.763894 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:04.763978 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:04.764008 I | etcdserver: removing old peers from network...
2016-06-28 21:23:04.764030 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:04.764051 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:04.764074 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:04.764101 I | etcdserver: finished applying incoming snapshot at index 66
2016-06-28 21:23:04.766668 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:04.766917 I | etcdserver: finished closing old backend
2016-06-28 21:23:04.767494 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:04.767675 I | etcdserver: raft applied incoming snapshot at index 72
2016-06-28 21:23:04.767805 I | etcdserver: applying snapshot at index 69...
2016-06-28 21:23:04.768033 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:04.768208 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:04.768330 I | etcdserver: recovering alarms...
2016-06-28 21:23:04.768630 I | etcdserver: closing old backend...
2016-06-28 21:23:04.769766 I | etcdserver: finished recovering alarms
2016-06-28 21:23:04.769810 I | etcdserver: recovering store v2...
2016-06-28 21:23:04.772863 I | etcdserver: finished recovering store v2
2016-06-28 21:23:04.773084 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:04.773193 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:04.773250 I | etcdserver: removing old peers from network...
2016-06-28 21:23:04.773287 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:04.773318 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:04.773353 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:04.773397 I | etcdserver: finished applying incoming snapshot at index 69
2016-06-28 21:23:04.774729 I | etcdserver: finished closing old backend
2016-06-28 21:23:04.776335 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:04.777281 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:04.777466 I | etcdserver: raft applied incoming snapshot at index 75
2016-06-28 21:23:04.777609 I | etcdserver: applying snapshot at index 72...
2016-06-28 21:23:04.777848 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:04.778038 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:04.778176 I | etcdserver: recovering alarms...
2016-06-28 21:23:04.778319 I | etcdserver: closing old backend...
2016-06-28 21:23:04.779605 I | etcdserver: finished closing old backend
2016-06-28 21:23:04.779709 I | etcdserver: finished recovering alarms
2016-06-28 21:23:04.779755 I | etcdserver: recovering store v2...
2016-06-28 21:23:04.782762 I | etcdserver: finished recovering store v2
2016-06-28 21:23:04.782815 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:04.782913 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:04.782951 I | etcdserver: removing old peers from network...
2016-06-28 21:23:04.782983 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:04.783014 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:04.783048 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:04.783086 I | etcdserver: finished applying incoming snapshot at index 72
2016-06-28 21:23:04.785887 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:04.786692 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:04.786874 I | etcdserver: raft applied incoming snapshot at index 78
2016-06-28 21:23:04.786966 I | etcdserver: applying snapshot at index 75...
2016-06-28 21:23:04.787206 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:04.787379 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:04.787507 I | etcdserver: recovering alarms...
2016-06-28 21:23:04.787662 I | etcdserver: closing old backend...
2016-06-28 21:23:04.788602 I | etcdserver: finished recovering alarms
2016-06-28 21:23:04.788646 I | etcdserver: recovering store v2...
2016-06-28 21:23:04.789106 I | etcdserver: finished closing old backend
2016-06-28 21:23:04.791732 I | etcdserver: finished recovering store v2
2016-06-28 21:23:04.791790 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:04.791890 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:04.791927 I | etcdserver: removing old peers from network...
2016-06-28 21:23:04.791959 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:04.791990 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:04.792025 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:04.792062 I | etcdserver: finished applying incoming snapshot at index 75
2016-06-28 21:23:04.794551 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:04.795316 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:04.795496 I | etcdserver: raft applied incoming snapshot at index 81
2016-06-28 21:23:04.795620 I | etcdserver: applying snapshot at index 78...
2016-06-28 21:23:04.795869 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:04.796053 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:04.796183 I | etcdserver: recovering alarms...
2016-06-28 21:23:04.797410 I | etcdserver: finished recovering alarms
2016-06-28 21:23:04.797453 I | etcdserver: recovering store v2...
2016-06-28 21:23:04.800498 I | etcdserver: finished recovering store v2
2016-06-28 21:23:04.800554 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:04.800658 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:04.800695 I | etcdserver: removing old peers from network...
2016-06-28 21:23:04.800728 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:04.800759 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:04.800793 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:04.800832 I | etcdserver: finished applying incoming snapshot at index 78
2016-06-28 21:23:04.800987 I | etcdserver: closing old backend...
2016-06-28 21:23:04.805623 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:04.805897 I | etcdserver: finished closing old backend
2016-06-28 21:23:04.806541 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:04.806719 I | etcdserver: raft applied incoming snapshot at index 84
2016-06-28 21:23:04.806802 I | etcdserver: applying snapshot at index 81...
2016-06-28 21:23:04.807022 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:04.807264 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:04.807382 I | etcdserver: recovering alarms...
2016-06-28 21:23:04.807530 I | etcdserver: closing old backend...
2016-06-28 21:23:04.808895 I | etcdserver: finished closing old backend
2016-06-28 21:23:04.809042 I | etcdserver: finished recovering alarms
2016-06-28 21:23:04.809089 I | etcdserver: recovering store v2...
2016-06-28 21:23:04.812116 I | etcdserver: finished recovering store v2
2016-06-28 21:23:04.812159 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:04.812248 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:04.812275 I | etcdserver: removing old peers from network...
2016-06-28 21:23:04.812297 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:04.812317 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:04.812341 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:04.812367 I | etcdserver: finished applying incoming snapshot at index 81
2016-06-28 21:23:04.816826 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:04.818512 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:04.818698 I | etcdserver: raft applied incoming snapshot at index 87
2016-06-28 21:23:04.818834 I | etcdserver: applying snapshot at index 84...
2016-06-28 21:23:04.819079 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:04.819274 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:04.819402 I | etcdserver: recovering alarms...
2016-06-28 21:23:04.819543 I | etcdserver: closing old backend...
2016-06-28 21:23:04.820880 I | etcdserver: finished closing old backend
2016-06-28 21:23:04.823762 I | etcdserver: finished recovering alarms
2016-06-28 21:23:04.823834 I | etcdserver: recovering store v2...
2016-06-28 21:23:04.827867 I | etcdserver: finished recovering store v2
2016-06-28 21:23:04.827931 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:04.828034 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:04.828071 I | etcdserver: removing old peers from network...
2016-06-28 21:23:04.828104 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:04.828136 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:04.828171 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:04.828210 I | etcdserver: finished applying incoming snapshot at index 84
2016-06-28 21:23:04.835374 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:04.836541 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:04.836748 I | etcdserver: raft applied incoming snapshot at index 90
2016-06-28 21:23:04.836892 I | etcdserver: applying snapshot at index 87...
2016-06-28 21:23:04.837153 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:04.837333 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:04.837484 I | etcdserver: recovering alarms...
2016-06-28 21:23:04.837580 I | etcdserver: closing old backend...
2016-06-28 21:23:04.838877 I | etcdserver: finished closing old backend
2016-06-28 21:23:04.839107 I | etcdserver: finished recovering alarms
2016-06-28 21:23:04.839151 I | etcdserver: recovering store v2...
2016-06-28 21:23:04.842174 I | etcdserver: finished recovering store v2
2016-06-28 21:23:04.842230 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:04.842331 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:04.842368 I | etcdserver: removing old peers from network...
2016-06-28 21:23:04.855823 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:04.855872 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:04.855947 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:04.855997 I | etcdserver: finished applying incoming snapshot at index 87
2016-06-28 21:23:04.862773 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:04.863662 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:04.863864 I | etcdserver: raft applied incoming snapshot at index 93
2016-06-28 21:23:04.864007 I | etcdserver: applying snapshot at index 90...
2016-06-28 21:23:04.864268 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:04.864562 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:04.864732 I | etcdserver: recovering alarms...
2016-06-28 21:23:04.864909 I | etcdserver: closing old backend...
2016-06-28 21:23:04.867621 I | etcdserver: finished closing old backend
2016-06-28 21:23:04.867778 I | etcdserver: finished recovering alarms
2016-06-28 21:23:04.867822 I | etcdserver: recovering store v2...
2016-06-28 21:23:04.870875 I | etcdserver: finished recovering store v2
2016-06-28 21:23:04.870931 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:04.871059 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:04.871096 I | etcdserver: removing old peers from network...
2016-06-28 21:23:04.871130 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:04.871162 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:04.871222 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:04.871261 I | etcdserver: finished applying incoming snapshot at index 90
2016-06-28 21:23:04.878634 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:04.881188 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:04.881286 I | etcdserver: raft applied incoming snapshot at index 96
2016-06-28 21:23:04.881524 I | etcdserver: applying snapshot at index 93...
2016-06-28 21:23:04.881812 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:04.881987 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:04.882154 I | etcdserver: closing old backend...
2016-06-28 21:23:04.882300 I | etcdserver: recovering alarms...
2016-06-28 21:23:04.886800 I | etcdserver: finished closing old backend
2016-06-28 21:23:04.889223 I | etcdserver: finished recovering alarms
2016-06-28 21:23:04.889269 I | etcdserver: recovering store v2...
2016-06-28 21:23:04.892330 I | etcdserver: finished recovering store v2
2016-06-28 21:23:04.892393 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:04.892503 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:04.892543 I | etcdserver: removing old peers from network...
2016-06-28 21:23:04.892577 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:04.892608 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:04.892644 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:04.892683 I | etcdserver: finished applying incoming snapshot at index 93
2016-06-28 21:23:04.896027 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:04.897250 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:04.897456 I | etcdserver: raft applied incoming snapshot at index 99
2016-06-28 21:23:04.897601 I | etcdserver: applying snapshot at index 96...
2016-06-28 21:23:04.897897 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:04.898083 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:04.898269 I | etcdserver: recovering alarms...
2016-06-28 21:23:04.898492 I | etcdserver: closing old backend...
2016-06-28 21:23:04.901916 I | etcdserver: finished closing old backend
2016-06-28 21:23:04.904101 I | etcdserver: finished recovering alarms
2016-06-28 21:23:04.904146 I | etcdserver: recovering store v2...
2016-06-28 21:23:04.907296 I | etcdserver: finished recovering store v2
2016-06-28 21:23:04.907353 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:04.907465 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:04.907506 I | etcdserver: removing old peers from network...
2016-06-28 21:23:04.907539 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:04.907570 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:04.907605 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:04.907645 I | etcdserver: finished applying incoming snapshot at index 96
2016-06-28 21:23:04.916025 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:04.919873 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:04.919992 I | etcdserver: raft applied incoming snapshot at index 102
2016-06-28 21:23:04.920232 I | etcdserver: applying snapshot at index 99...
2016-06-28 21:23:04.920490 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:04.920673 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:04.920874 I | etcdserver: recovering alarms...
2016-06-28 21:23:04.921093 I | etcdserver: closing old backend...
2016-06-28 21:23:04.925472 I | etcdserver: finished closing old backend
2016-06-28 21:23:04.925580 I | etcdserver: finished recovering alarms
2016-06-28 21:23:04.925624 I | etcdserver: recovering store v2...
2016-06-28 21:23:04.928739 I | etcdserver: finished recovering store v2
2016-06-28 21:23:04.928797 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:04.928908 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:04.928945 I | etcdserver: removing old peers from network...
2016-06-28 21:23:04.929009 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:04.929040 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:04.929078 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:04.929117 I | etcdserver: finished applying incoming snapshot at index 99
2016-06-28 21:23:04.935332 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:04.937667 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:04.937885 I | etcdserver: raft applied incoming snapshot at index 105
2016-06-28 21:23:04.937970 I | etcdserver: applying snapshot at index 102...
2016-06-28 21:23:04.938197 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:04.938375 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:04.938494 I | etcdserver: recovering alarms...
2016-06-28 21:23:04.938895 I | etcdserver: closing old backend...
2016-06-28 21:23:04.943704 I | etcdserver: finished recovering alarms
2016-06-28 21:23:04.943743 I | etcdserver: recovering store v2...
2016-06-28 21:23:04.946791 I | etcdserver: finished recovering store v2
2016-06-28 21:23:04.946837 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:04.946934 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:04.946960 I | etcdserver: removing old peers from network...
2016-06-28 21:23:04.946982 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:04.947003 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:04.947027 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:04.947055 I | etcdserver: finished applying incoming snapshot at index 102
2016-06-28 21:23:04.947427 I | etcdserver: finished closing old backend
2016-06-28 21:23:04.953887 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:04.955717 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:04.955916 I | etcdserver: raft applied incoming snapshot at index 108
2016-06-28 21:23:04.956054 I | etcdserver: applying snapshot at index 105...
2016-06-28 21:23:04.956319 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:04.956508 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:04.956642 I | etcdserver: recovering alarms...
2016-06-28 21:23:04.956788 I | etcdserver: closing old backend...
2016-06-28 21:23:04.960016 I | etcdserver: finished closing old backend
2016-06-28 21:23:04.960665 I | etcdserver: finished recovering alarms
2016-06-28 21:23:04.960715 I | etcdserver: recovering store v2...
2016-06-28 21:23:04.963889 I | etcdserver: finished recovering store v2
2016-06-28 21:23:04.963947 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:04.964057 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:04.964096 I | etcdserver: removing old peers from network...
2016-06-28 21:23:04.964131 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:04.964162 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:04.964199 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:04.964238 I | etcdserver: finished applying incoming snapshot at index 105
2016-06-28 21:23:04.970652 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:04.971529 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:04.971728 I | etcdserver: raft applied incoming snapshot at index 111
2016-06-28 21:23:04.971840 I | etcdserver: applying snapshot at index 108...
2016-06-28 21:23:04.972086 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:04.972355 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:04.972498 I | etcdserver: recovering alarms...
2016-06-28 21:23:04.972655 I | etcdserver: closing old backend...
2016-06-28 21:23:04.977896 I | etcdserver: finished closing old backend
2016-06-28 21:23:04.982899 I | etcdserver: finished recovering alarms
2016-06-28 21:23:04.982951 I | etcdserver: recovering store v2...
2016-06-28 21:23:04.986019 I | etcdserver: finished recovering store v2
2016-06-28 21:23:04.986080 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:04.986191 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:04.986228 I | etcdserver: removing old peers from network...
2016-06-28 21:23:04.986269 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:04.986300 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:04.986335 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:04.986374 I | etcdserver: finished applying incoming snapshot at index 108
2016-06-28 21:23:04.989205 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:04.990741 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:04.990940 I | etcdserver: raft applied incoming snapshot at index 114
2016-06-28 21:23:04.991074 I | etcdserver: applying snapshot at index 111...
2016-06-28 21:23:04.991345 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:04.991528 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:04.991658 I | etcdserver: recovering alarms...
2016-06-28 21:23:04.992031 I | etcdserver: closing old backend...
2016-06-28 21:23:04.993098 I | etcdserver: finished recovering alarms
2016-06-28 21:23:04.993154 I | etcdserver: recovering store v2...
2016-06-28 21:23:04.993407 I | etcdserver: finished closing old backend
2016-06-28 21:23:04.996395 I | etcdserver: finished recovering store v2
2016-06-28 21:23:04.996454 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:04.996559 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:04.996596 I | etcdserver: removing old peers from network...
2016-06-28 21:23:04.996630 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:04.996661 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:04.996695 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:04.996737 I | etcdserver: finished applying incoming snapshot at index 111
2016-06-28 21:23:05.007671 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:05.012248 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:05.012453 I | etcdserver: raft applied incoming snapshot at index 117
2016-06-28 21:23:05.012588 I | etcdserver: applying snapshot at index 114...
2016-06-28 21:23:05.012858 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:05.013062 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:05.013196 I | etcdserver: recovering alarms...
2016-06-28 21:23:05.013555 I | etcdserver: closing old backend...
2016-06-28 21:23:05.018349 I | etcdserver: finished recovering alarms
2016-06-28 21:23:05.018396 I | etcdserver: recovering store v2...
2016-06-28 21:23:05.019798 I | etcdserver: finished closing old backend
2016-06-28 21:23:05.021779 I | etcdserver: finished recovering store v2
2016-06-28 21:23:05.021837 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:05.021953 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:05.021992 I | etcdserver: removing old peers from network...
2016-06-28 21:23:05.022024 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:05.022055 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:05.022090 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:05.022131 I | etcdserver: finished applying incoming snapshot at index 114
2016-06-28 21:23:05.024721 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:05.025489 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:05.025614 I | etcdserver: raft applied incoming snapshot at index 120
2016-06-28 21:23:05.025866 I | etcdserver: applying snapshot at index 117...
2016-06-28 21:23:05.026110 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:05.026297 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:05.026445 I | etcdserver: recovering alarms...
2016-06-28 21:23:05.026765 I | etcdserver: closing old backend...
2016-06-28 21:23:05.029471 I | etcdserver: finished closing old backend
2016-06-28 21:23:05.029966 I | etcdserver: finished recovering alarms
2016-06-28 21:23:05.030011 I | etcdserver: recovering store v2...
2016-06-28 21:23:05.033080 I | etcdserver: finished recovering store v2
2016-06-28 21:23:05.033137 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:05.033240 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:05.033277 I | etcdserver: removing old peers from network...
2016-06-28 21:23:05.033315 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:05.033348 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:05.033383 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:05.033421 I | etcdserver: finished applying incoming snapshot at index 117
2016-06-28 21:23:05.036991 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:05.037893 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:05.038094 I | etcdserver: raft applied incoming snapshot at index 123
2016-06-28 21:23:05.038197 I | etcdserver: applying snapshot at index 120...
2016-06-28 21:23:05.038431 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:05.038603 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:05.038696 I | etcdserver: recovering alarms...
2016-06-28 21:23:05.039042 I | etcdserver: closing old backend...
2016-06-28 21:23:05.043997 I | etcdserver: finished closing old backend
2016-06-28 21:23:05.044105 I | etcdserver: finished recovering alarms
2016-06-28 21:23:05.044140 I | etcdserver: recovering store v2...
2016-06-28 21:23:05.047227 I | etcdserver: finished recovering store v2
2016-06-28 21:23:05.047271 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:05.047367 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:05.047392 I | etcdserver: removing old peers from network...
2016-06-28 21:23:05.047416 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:05.047436 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:05.047460 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:05.047486 I | etcdserver: finished applying incoming snapshot at index 120
2016-06-28 21:23:05.054900 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:05.057469 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:05.057647 I | etcdserver: raft applied incoming snapshot at index 126
2016-06-28 21:23:05.057773 I | etcdserver: applying snapshot at index 123...
2016-06-28 21:23:05.058045 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:05.058227 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:05.058363 I | etcdserver: recovering alarms...
2016-06-28 21:23:05.058733 I | etcdserver: closing old backend...
2016-06-28 21:23:05.062024 I | etcdserver: finished recovering alarms
2016-06-28 21:23:05.062076 I | etcdserver: recovering store v2...
2016-06-28 21:23:05.064881 I | etcdserver: finished closing old backend
2016-06-28 21:23:05.065436 I | etcdserver: finished recovering store v2
2016-06-28 21:23:05.065495 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:05.065610 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:05.065648 I | etcdserver: removing old peers from network...
2016-06-28 21:23:05.065681 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:05.065712 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:05.065749 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:05.065790 I | etcdserver: finished applying incoming snapshot at index 123
2016-06-28 21:23:05.069080 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:05.072532 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:05.072765 I | etcdserver: raft applied incoming snapshot at index 129
2016-06-28 21:23:05.072929 I | etcdserver: applying snapshot at index 126...
2016-06-28 21:23:05.073226 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:05.073512 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:05.073664 I | etcdserver: recovering alarms...
2016-06-28 21:23:05.073928 I | etcdserver: closing old backend...
2016-06-28 21:23:05.079497 I | etcdserver: finished closing old backend
2016-06-28 21:23:05.080017 I | etcdserver: finished recovering alarms
2016-06-28 21:23:05.080063 I | etcdserver: recovering store v2...
2016-06-28 21:23:05.083159 I | etcdserver: finished recovering store v2
2016-06-28 21:23:05.083258 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:05.083394 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:05.083432 I | etcdserver: removing old peers from network...
2016-06-28 21:23:05.083464 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:05.083509 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:05.083546 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:05.083584 I | etcdserver: finished applying incoming snapshot at index 126
2016-06-28 21:23:05.101294 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:05.103528 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:05.119860 I | etcdserver: raft applied incoming snapshot at index 132
2016-06-28 21:23:05.119975 I | etcdserver: applying snapshot at index 129...
2016-06-28 21:23:05.120267 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:05.120473 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:05.120572 I | etcdserver: recovering alarms...
2016-06-28 21:23:05.120842 I | etcdserver: closing old backend...
2016-06-28 21:23:05.123547 I | etcdserver: finished recovering alarms
2016-06-28 21:23:05.123592 I | etcdserver: recovering store v2...
2016-06-28 21:23:05.125787 I | etcdserver: finished closing old backend
2016-06-28 21:23:05.126719 I | etcdserver: finished recovering store v2
2016-06-28 21:23:05.126774 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:05.126882 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:05.126917 I | etcdserver: removing old peers from network...
2016-06-28 21:23:05.126946 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:05.126974 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:05.127005 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:05.127047 I | etcdserver: finished applying incoming snapshot at index 129
2016-06-28 21:23:05.144150 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:05.148472 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:05.148618 I | etcdserver: raft applied incoming snapshot at index 135
2016-06-28 21:23:05.148854 I | etcdserver: applying snapshot at index 132...
2016-06-28 21:23:05.149170 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:05.149415 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:05.149550 I | etcdserver: recovering alarms...
2016-06-28 21:23:05.149605 I | etcdserver: closing old backend...
2016-06-28 21:23:05.154654 I | etcdserver: finished recovering alarms
2016-06-28 21:23:05.154700 I | etcdserver: recovering store v2...
2016-06-28 21:23:05.154743 I | etcdserver: finished closing old backend
2016-06-28 21:23:05.157778 I | etcdserver: finished recovering store v2
2016-06-28 21:23:05.157824 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:05.157926 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:05.157952 I | etcdserver: removing old peers from network...
2016-06-28 21:23:05.157976 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:05.157997 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:05.158021 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:05.158048 I | etcdserver: finished applying incoming snapshot at index 132
2016-06-28 21:23:05.163695 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:05.164650 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:05.164856 I | etcdserver: raft applied incoming snapshot at index 138
2016-06-28 21:23:05.164947 I | etcdserver: applying snapshot at index 135...
2016-06-28 21:23:05.165175 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:05.165353 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:05.165506 I | etcdserver: recovering alarms...
2016-06-28 21:23:05.165775 I | etcdserver: closing old backend...
2016-06-28 21:23:05.172767 I | etcdserver: finished recovering alarms
2016-06-28 21:23:05.172814 I | etcdserver: recovering store v2...
2016-06-28 21:23:05.173342 I | etcdserver: finished closing old backend
2016-06-28 21:23:05.175900 I | etcdserver: finished recovering store v2
2016-06-28 21:23:05.175958 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:05.176070 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:05.176103 I | etcdserver: removing old peers from network...
2016-06-28 21:23:05.176133 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:05.176161 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:05.176192 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:05.176228 I | etcdserver: finished applying incoming snapshot at index 135
2016-06-28 21:23:05.183280 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:05.185990 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:05.186107 I | etcdserver: raft applied incoming snapshot at index 141
2016-06-28 21:23:05.186323 I | etcdserver: applying snapshot at index 138...
2016-06-28 21:23:05.186583 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:05.186794 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:05.186949 I | etcdserver: recovering alarms...
2016-06-28 21:23:05.187117 I | etcdserver: closing old backend...
2016-06-28 21:23:05.191186 I | etcdserver: finished closing old backend
2016-06-28 21:23:05.191834 I | etcdserver: finished recovering alarms
2016-06-28 21:23:05.191897 I | etcdserver: recovering store v2...
2016-06-28 21:23:05.194971 I | etcdserver: finished recovering store v2
2016-06-28 21:23:05.195027 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:05.195137 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:05.195175 I | etcdserver: removing old peers from network...
2016-06-28 21:23:05.195233 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:05.195265 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:05.195302 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:05.195341 I | etcdserver: finished applying incoming snapshot at index 138
2016-06-28 21:23:05.198297 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:05.199779 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:05.200101 I | etcdserver: raft applied incoming snapshot at index 144
2016-06-28 21:23:05.200343 I | etcdserver: applying snapshot at index 141...
2016-06-28 21:23:05.200683 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:05.200871 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:05.201052 I | etcdserver: closing old backend...
2016-06-28 21:23:05.201194 I | etcdserver: recovering alarms...
2016-06-28 21:23:05.202540 I | etcdserver: finished closing old backend
2016-06-28 21:23:05.204005 I | etcdserver: finished recovering alarms
2016-06-28 21:23:05.204051 I | etcdserver: recovering store v2...
2016-06-28 21:23:05.207092 I | etcdserver: finished recovering store v2
2016-06-28 21:23:05.207147 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:05.207277 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:05.207315 I | etcdserver: removing old peers from network...
2016-06-28 21:23:05.207352 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:05.207383 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:05.207418 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:05.207456 I | etcdserver: finished applying incoming snapshot at index 141
2016-06-28 21:23:05.211741 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:05.212668 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:05.212868 I | etcdserver: raft applied incoming snapshot at index 147
2016-06-28 21:23:05.213047 I | etcdserver: applying snapshot at index 144...
2016-06-28 21:23:05.213336 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:05.213524 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:05.213703 I | etcdserver: closing old backend...
2016-06-28 21:23:05.213847 I | etcdserver: recovering alarms...
2016-06-28 21:23:05.215533 I | etcdserver: finished closing old backend
2016-06-28 21:23:05.215807 I | etcdserver: finished recovering alarms
2016-06-28 21:23:05.215851 I | etcdserver: recovering store v2...
2016-06-28 21:23:05.218873 I | etcdserver: finished recovering store v2
2016-06-28 21:23:05.218929 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:05.219033 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:05.219069 I | etcdserver: removing old peers from network...
2016-06-28 21:23:05.219102 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:05.219133 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:05.219170 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:05.219233 I | etcdserver: finished applying incoming snapshot at index 144
2016-06-28 21:23:05.222089 I | etcdserver: wrote database snapshot out [total bytes: 24576]
2016-06-28 21:23:05.222966 I | snap: saved database snapshot to disk [total bytes: 24576]
2016-06-28 21:23:05.223162 I | etcdserver: raft applied incoming snapshot at index 150
2016-06-28 21:23:05.223330 I | etcdserver: applying snapshot at index 147...
2016-06-28 21:23:05.223606 I | etcdserver: restoring mvcc store...
2016-06-28 21:23:05.223787 I | etcdserver: finished restoring mvcc store
2016-06-28 21:23:05.223965 I | etcdserver: closing old backend...
2016-06-28 21:23:05.224105 I | etcdserver: recovering alarms...
2016-06-28 21:23:05.225367 I | etcdserver: finished closing old backend
2016-06-28 21:23:05.225856 I | etcdserver: finished recovering alarms
2016-06-28 21:23:05.225900 I | etcdserver: recovering store v2...
2016-06-28 21:23:05.228955 I | etcdserver: finished recovering store v2
2016-06-28 21:23:05.229012 I | etcdserver: recovering cluster configuration...
2016-06-28 21:23:05.229119 I | etcdserver: finished recovering cluster configuration
2016-06-28 21:23:05.229155 I | etcdserver: removing old peers from network...
2016-06-28 21:23:05.229188 I | etcdserver: finished removing old peers from network
2016-06-28 21:23:05.229218 I | etcdserver: adding peers from new cluster configuration into network...
2016-06-28 21:23:05.229253 I | etcdserver: finished adding peers from new cluster configuration into network...
2016-06-28 21:23:05.229291 I | etcdserver: finished applying incoming snapshot at index 147
2016-06-28 21:23:05.231487 I | etcdserver: set snapshot count to default 10000
2016-06-28 21:23:05.231544 I | etcdserver: starting server... [version: 3.0.0-beta.0+git, cluster version: to_be_decided]
2016-06-28 21:23:05.233241 I | membership: added member 4d2 [foo] to cluster 0
2016-06-28 21:23:05.233695 I | membership: added member 4d2 [] to cluster 0
2016-06-28 21:23:05.233740 I | etcdserver: set snapshot count to default 10000
2016-06-28 21:23:05.233786 I | etcdserver: starting server... [version: 3.0.0-beta.0+git, cluster version: to_be_decided]
2016-06-28 21:23:05.234453 I | membership: removed member 4d2 from cluster 0
2016-06-28 21:23:05.234940 I | membership: added member 4d2 [] to cluster 0
2016-06-28 21:23:05.234996 I | etcdserver: set snapshot count to default 10000
2016-06-28 21:23:05.235048 I | etcdserver: starting server... [version: 3.0.0-beta.0+git, cluster version: to_be_decided]
2016-06-28 21:23:05.235844 N | membership: updated member 4d2 [http://127.0.0.1:1] in cluster 0
2016-06-28 21:23:05.236325 I | etcdserver: published {Name:node1 ClientURLs:[http://a http://b]} to cluster 0
2016-06-28 21:23:05.236647 I | etcdserver: aborting publish because server is stopped
2016-06-28 21:23:05.236966 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.237048 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.237122 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.237196 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.237272 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.237346 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.237417 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.237486 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.237562 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.237634 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.237701 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.237768 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.237834 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.237905 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.237972 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.238038 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.238112 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.238180 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.238247 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.238316 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.238384 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.238449 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.238515 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.238582 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.238647 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.238711 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.238776 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.238842 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.238908 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.238978 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.239043 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.239104 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.239176 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.239261 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.239322 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.239381 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.239451 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.239513 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.239577 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.239638 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.239698 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.239757 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.239816 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.239875 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.239934 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.239993 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.240054 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.240114 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.240177 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.240238 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.240298 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.240356 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.240416 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.240476 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.240537 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.240597 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.240659 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.240717 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.240784 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.240848 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.240907 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.240967 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.241026 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.241085 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.241149 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.241210 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.241269 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.241344 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.241409 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.241469 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.241530 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.241590 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.241650 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.241709 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.241768 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.241827 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.241887 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.241948 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.242009 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.242067 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.242126 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.242185 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.242244 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.242304 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.242364 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.242431 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.242491 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.242554 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.242613 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.242672 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.242731 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.242793 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.242855 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.242914 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.242980 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.243039 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.243099 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.243162 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.243252 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.243312 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.243372 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.243432 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.243490 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.243549 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.243609 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.243671 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.243730 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.243793 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.243854 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.243912 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.243975 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.244034 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.244093 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.244212 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.244272 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.244348 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.244415 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.244480 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.244540 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.244600 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.244660 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.244751 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.244814 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.244873 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.244932 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.244990 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.245052 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.245112 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.245171 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.245230 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.245289 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.245348 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.245408 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.245467 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.245537 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.245599 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.245663 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.245723 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.245781 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.245841 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.245900 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.245959 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.246018 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.246078 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.246139 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.246198 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.246264 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.246324 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.246385 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.246445 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.246504 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.246567 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.246627 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.246716 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.246782 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.246846 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.246907 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.247110 E | etcdserver: publish error: etcdserver: request timed out
2016-06-28 21:23:05.247174 I | etcdserver: aborting publish because server is stopped
2016-06-28 21:23:05.247434 I | etcdserver: setting up the initial cluster version to 2.0
FAIL
```

### PR DESCRIPTION
**Pull request by xiang90**
Fix #5797.

We introduce the kv.commit call in the snapshot path, which slows down the go routine. Using wait to reliably wait for the actual snap event to happen.

### CODE REVIEW

**Comment by gyuho** [comment]
lgtm.

File: etcdserver/server_test.go [hunk 1]
```diff
@@ -869,7 +869,7 @@ func TestSnapshot(t *testing.T) {
 	if !reflect.DeepEqual(gaction[1], testutil.Action{Name: "SaveNoCopy"}) {
 		t.Errorf("action = %s, want SaveNoCopy", gaction[1])
 	}
-	gaction = p.Action()
+	gaction, _ = p.Wait(1)
```
Comment (heyitsanthony) [inline etcdserver/server_test.go]: This is still racey. p would need to be NewStorageRecorderStream for this to be reliable.

Comment (xiang90) [inline etcdserver/server_test.go]: i will change.

**Comment by xiang90** [comment]
@heyitsanthony fixed.
