### PR TITLE
ctlv2: report unhealthy in cluster-health if any node is unavailable

### LINKED ISSUE #8061: `etcdctl cluster-health` shows each node is health while one node is not working
Hi. I find a problem.When I build my etcd cluster and want to verify whether everything is ok. I use `etcdctl member list` command and it shows as below:
  1f31b23c41b42e33: name=infra2 peerURLs=http://IP_2:2380 clientURLs=http://127.0.0.1:2379,http://IP_2:2379 isLeader=false
6f7bfee130f3c5e6: name=infra0 peerURLs=http://IP_0:2380 clientURLs=http://127.0.0.1:2379,http://IP_0:2379 isLeader=true
b05fda0c29c5a1d2: name=infra1 peerURLs=http://IP_1:2380 clientURLs=http://127.0.0.1:2379,http://IP_1:2379 isLeader=false
And when I run `etcdctl cluster-health` and it shows as below:
member 1f31b23c41b42e33 is healthy: got healthy result from http://127.0.0.1:2379
member 6f7bfee130f3c5e6 is healthy: got healthy result from http://127.0.0.1:2379
member b05fda0c29c5a1d2 is healthy: got healthy result from http://127.0.0.1:2379
But in fact, I do not run etcd on the other two nodes, so I think the health check is just on 127.0.0.1:2379, how can I use it on the IP_1/IP_2/IP_3?  I think it may be related with **clientURLs=http://127.0.0.1:2379,http://IP_2:2379**, health check is just on the first URL. And how can I change the order of it? 
My **--listen-client-urls** flag is written as **http://172.31.55.27:2379,http://127.0.0.1:2379**

### PR DESCRIPTION
**Pull request by heyitsanthony**
Fixes #8061 and #7032

### CODE REVIEW

**Comment by xiang90** [comment]
lgtm

File: etcdctl/ctlv2/command/cluster_health.go [hunk 1]
```diff
@@ -116,19 +116,20 @@ func handleClusterHealth(c *cli.Context) error {
 				fmt.Printf("member %s is unreachable: %v are all unreachable\n", m.ID, m.ClientURLs)
 			}
 		}
-		if health {
+		switch healthyMembers {
+		case len(ms):
 			fmt.Println("cluster is healthy")
-		} else {
+		case 0:
+			fmt.Println("cluster is unavailable")
```
Comment (xiang90) [inline etcdctl/ctlv2/command/cluster_health.go]: degraded is more descriptive?

**Comment by discordianfish** [comment]
Was this somehow reverted in a recent change? I depend on this behavior here: https://github.com/itskoko/kubecfn/blob/master/kubernetes.yaml#L1049

And cluster-health currently returns 0 even if there are unhealthy/unreachable members:
```
May 22 10:21:08 ip-172-20-181-238 etcd-signal-health[1894]: member f96dcaf66e42e5 is healthy: got healthy result from https://ip-172-20-182-16.ec2.internal:2379
May 22 10:21:08 ip-172-20-181-238 etcd-signal-health[1894]: member 3117c78e122ac7cb is healthy: got healthy result from https://ip-172-20-184-45.ec2.internal:2379
May 22 10:21:09 ip-172-20-181-238 etcd-signal-health[1894]: failed to check the health of member 96a7254e2e1542e1 on https://ip-172-20-180-128.ec2.internal:2379: Get https://ip-172-20-180-128.ec2.internal:2379/health: dial tcp 172.20.180.128:2379: getsockopt: no r
May 22 10:21:09 ip-172-20-181-238 etcd-signal-health[1894]: member 96a7254e2e1542e1 is unreachable: [https://ip-172-20-180-128.ec2.internal:2379] are all unreachable
May 22 10:21:09 ip-172-20-181-238 etcd-signal-health[1894]: member a2d7a63532026c28 is healthy: got healthy result from https://ip-172-20-181-238.ec2.internal:2379
May 22 10:21:09 ip-172-20-181-238 etcd-signal-health[1894]: cluster is healthy
```

"Container Linux by CoreOS 1688.5.3 (Rhyolite)"
etcdctl version: 3.2.15
API version: 2
