### PR TITLE
etcd: server SSL and client cert auth configuration is more explicit

### LINKED ISSUE #2499: The `--ca-file` flag should not enable client auth by default
When configuring etcd for SSL using the following instructions:

https://github.com/kelseyhightower/etcd-production-setup/tree/multinode#configuring-etcd-for-ssl

I get the following errors in the etcd logs: 

```
2015/03/12 15:55:19 rafthttp: roundtripping error: error roundtripping to https://etcd1.example.com:2380/raft/stream/message/689d213e8fdfef61: x509: certificate signed by unknown authority
```

The only way to make it work was to set the `--ca-file`, which also has the side effect of enabling client auth. This was not what I wanted in this case. 

My only option at this point is to figure out how to get my OS to trust the CA cert. Ideally the --ca-flag can be used to trust the CA cert and another flag would enable client-auth.

### PR DESCRIPTION
**Pull request by kelseyhightower**
etcd does not provide enough flexibility to configure server SSL and
client authentication separately. When configuring server SSL the
`--ca-file` flag is required to trust self-signed SSL certificates
used to service client requests.

The `--ca-file` has the side effect of enabling client cert
authentication. This can be surprising for those looking to simply
secure communication between an etcd server and client.

Resolve this issue by introducing four new flags:

    --client-cert-auth
    --peer-client-cert-auth
    --trusted-ca-file
    --peer-trusted-ca-file

These new flags will allow etcd to support a more explicit SSL
configuration for both etcd clients and peers.

Example usage:

Start etcd with server SSL and no client cert authentication:

    etcd -name etcd0 \
    --advertise-client-urls https://etcd0.example.com:2379 \
    --cert-file etcd0.example.com.crt \
    --key-file etcd0.example.com.key \
    --trusted-ca-file ca.crt

Start etcd with server SSL and enable client cert authentication:

    etcd -name etcd0 \
    --advertise-client-urls https://etcd0.example.com:2379 \
    --cert-file etcd0.example.com.crt \
    --key-file etcd0.example.com.key \
    --trusted-ca-file ca.crt \
    --client-cert-auth

Start etcd with server SSL and client cert authentication for both
peer and client endpoints:

    etcd -name etcd0 \
    --advertise-client-urls https://etcd0.example.com:2379 \
    --cert-file etcd0.example.com.crt \
    --key-file etcd0.example.com.key \
    --trusted-ca-file ca.crt \
    --client-cert-auth \
    --peer-cert-file etcd0.example.com.crt \
    --peer-key-file etcd0.example.com.key \
    --peer-trusted-ca-file ca.crt \
    --peer-client-cert-auth

This change is backwards compatible with etcd versions 2.0.0+. The
current behavior of the `--ca-file` flag is preserved.

Fixes #2499.

### CODE REVIEW

**Comment by yichengq** [comment]
Several design questions:

1. In `Start etcd with server SSL and no client cert authentication` example, it sets `--trusted-ca-file`, which(ca-file) is not necessary in the code. Do we recommend, or even force, user to always set `--trusted-ca-file`?

2. For peer communication, all examples i see so far always use client-cert-auth. Do we want to support the mode that peer-client-cert-auth is not required?

**Comment by kelseyhightower** [comment]
@yichengq Those where just some examples, you can mix and match the flags any way you like.

1. The user will use the `--trusted-ca-file` if they want to be explicit about which CA they trust for client auth. The user has the option of relying on current behavior and rely on self-signed CA trusted in the OS bundle.

2. The flags work in any combo the users want. This PR supports the mode where `peer-client-cert-auth` is not required.

File: pkg/transport/listener.go [hunk 1]
```diff
@@ -115,29 +117,47 @@ func (info TLSInfo) baseConfig() (*tls.Config, error) {
...
+// ServerConfig generates a tls.Config object for use by an HTTP server.
 func (info TLSInfo) ServerConfig() (*tls.Config, error) {
 	cfg, err := info.baseConfig()
 	if err != nil {
 		return nil, err
 	}
 
-	if info.CAFile != "" {
+	cfg.ClientAuth = tls.NoClientCert
+	if info.CAFile != "" || info.ClientCertAuth {
```
Comment (yichengq) [inline pkg/transport/listener.go]: could we add a comment on this? It is hard to remember why `info.CAFile != ""` -> `RequireAndVerifyClientCert`

**Comment by yichengq** [comment]
lgtm if you have tested it. We don't have TLS testing now.

I think we need some follow-up to deprecate -ca-file and -peer-ca-file.

**Comment by barakmich** [comment]
Just to make sure I get it -- instead of using exactly one cert for every machine, one can now use a cert for every machine and trust the other ones as well?

(Along with separating the enabling of ca checking from the use of the flag, an easy win)

**Comment by yichengq** [comment]
/cc @philips @xiang90 
We will also deprecate `-ca-file` and `-peer-ca-file` because they do the same thing as new flags.

**Comment by kelseyhightower** [comment]
@barakmich Well, nothing really changes except the ability explicitly enable client cert auth and trust CA certs without enabling client cert auth.

You cloud always do what you describe regarding one cert per host, the new flag names just make it a little more obvious that you can do it.

**Comment by barakmich** [comment]
The fact I didn't know goes to show you...

LGTm

**Comment by kelseyhightower** [comment]
@yichengq I will follow up with another PR to deprecate the  `-ca-file` and `-peer-ca-file` flags. and some additional docs on how to use these flags.

**Comment by xiang90** [comment]
@kelseyhightower @yichengq LGTM
