### PR TITLE
wal: fix tail corruption

### LINKED ISSUE #4903: functional-tester: walpb: crc mismatch
Got `etcdserver: read wal error (walpb: crc mismatch) and cannot be repaired`

```
2016-03-30 06:16:39.777137 I | etcdmain: etcd Version: 2.3.0+git
2016-03-30 06:16:39.777212 I | etcdmain: Git SHA: Not provided (use ./build instead of go build)
2016-03-30 06:16:39.777219 I | etcdmain: Go Version: go1.6
2016-03-30 06:16:39.777225 I | etcdmain: Go OS/Arch: linux/amd64
2016-03-30 06:16:39.777236 I | etcdmain: setting maximum number of CPUs to 4, total number of available CPUs is 4
2016-03-30 06:16:39.777287 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2016-03-30 06:16:39.777404 I | etcdmain: listening for peers on http://10.240.0.2:2380
2016-03-30 06:16:39.777445 I | etcdmain: listening for client requests on 10.240.0.2:2379
2016-03-30 06:16:39.777693 W | snap: skipped unexpected non snapshot file db
2016-03-30 06:16:39.790777 I | etcdserver: recovered store from snapshot at index 378538793
2016-03-30 06:16:39.790821 I | etcdserver: name = etcd-0
2016-03-30 06:16:39.790829 I | etcdserver: data dir = agent.etcd
2016-03-30 06:16:39.790837 I | etcdserver: member dir = agent.etcd/member
2016-03-30 06:16:39.790843 I | etcdserver: heartbeat = 100ms
2016-03-30 06:16:39.790848 I | etcdserver: election = 1000ms
2016-03-30 06:16:39.790854 I | etcdserver: snapshot count = 10000
2016-03-30 06:16:39.790866 I | etcdserver: advertise client URLs = http://10.240.0.2:2379
2016-03-30 06:16:39.791413 C | etcdserver: read wal error (walpb: crc mismatch) and cannot be repaired

```

### PR DESCRIPTION
**Pull request by heyitsanthony**
On ReadAll, WAL seeks to the end of the last record in the tail. If the tail did not
end with preallocated space, the decoder would report 0 as the last offset and begin
writing at offset 0 of the tail.

Fixes #4903

### CODE REVIEW

File: wal/wal.go [hunk 1]
```diff
@@ -57,7 +57,6 @@ var (
 	ErrCRCMismatch      = errors.New("wal: crc mismatch")
 	ErrSnapshotMismatch = errors.New("wal: snapshot mismatch")
 	ErrSnapshotNotFound = errors.New("wal: snapshot not found")
-	ErrZeroTrailer      = errors.New("wal: zero trailer")
```
Comment (xiang90) [inline wal/wal.go]: so this was never used (returned) before?

**Comment by xiang90** [comment]
Can we cover this case by a unit test?

File: wal/wal.go (hunk 1 above)
Comment (heyitsanthony) [inline wal/wal.go]: Yeah, vestigial remains from the original preallocation patch.

**Comment by heyitsanthony** [comment]
@xiang90 will add test

**Comment by xiang90** [comment]
LGTM

**Comment by gyuho** [comment]
lgtm. Thanks!

**Comment by gyuho** [comment]
@heyitsanthony Ah mis-clicked the `Close` button. Sorry.

LGTM.

Thanks!

**Comment by heyitsanthony** [comment]
added test case; confirmed fail without patch. merging on green
