### PR TITLE
clientv3: respect up/down notifications from grpc

### LINKED ISSUE #5842: clientv3: won't connect if any endpoint is down
How to reproduce: start one etcd server on `2379`, then `ETCDCTL_API=3 etcdctl put abc def`. It will fail to connect to `127.0.0.1:{2,3}2379` and never send the command.

### PR DESCRIPTION
**Pull request by heyitsanthony**
Partial patch; will need to revendor grpc once the fix on that end is merged.

Fixes #5842

### CODE REVIEW

File: clientv3/balancer.go [hunk 1]
```diff
@@ -26,10 +26,17 @@ import (
...
+	// addrs are the client's endpoints for grpc
+	addrs []grpc.Address
+
+	ch chan []grpc.Address
+
+	// upEps contains the endpoints grpc says are up
+	upEps map[string]struct{}
+	// numGets chooses the next endpoint
 	numGets uint32
+	// mu protects upEps, downEps, and numGets
```
Comment (gyuho) [inline clientv3/balancer.go]: Maybe `mu sync.Mutex` on the top of upEps and numGets?

And what is `downEps`? I don't see it in the struct fields?

Comment (heyitsanthony) [inline clientv3/balancer.go]: comment was outdated; fixed

**Comment by heyitsanthony** [comment]
fixed up to use balancer for this functionality since withblock patch was rejected PTAL /cc @xiang90

File: clientv3/balancer.go [hunk 2]
```diff
@@ -26,28 +26,66 @@ import (
...
+	}
 }
 
-func (b *simpleBalancer) Start(target string) error        { return nil }
-func (b *simpleBalancer) Up(addr grpc.Address) func(error) { return func(error) {} }
 func (b *simpleBalancer) Get(ctx context.Context, opts grpc.BalancerGetOptions) (grpc.Address, func(), error) {
-	v := atomic.AddUint32(&b.numGets, 1)
-	ep := b.eps[v%uint32(len(b.eps))]
-	return grpc.Address{Addr: getHost(ep)}, func() {}, nil
+	b.mu.Lock()
```
Comment (xiang90) [inline clientv3/balancer.go]: it seems that we need to do more work here?

see comments on Get at https://godoc.org/google.golang.org/grpc#Balancer 

Also: https://github.com/grpc/grpc-go/blob/master/balancer.go#L272-L364

File: clientv3/balancer.go [hunk 3]
```diff
@@ -26,28 +26,66 @@ import (
...
+	return func(error) {
+		b.mu.Lock()
+		delete(b.upEps, addr.Addr)
+		b.mu.Unlock()
+	}
 }
 
-func (b *simpleBalancer) Start(target string) error        { return nil }
-func (b *simpleBalancer) Up(addr grpc.Address) func(error) { return func(error) {} }
 func (b *simpleBalancer) Get(ctx context.Context, opts grpc.BalancerGetOptions) (grpc.Address, func(), error) {
```
Comment (xiang90) [inline clientv3/balancer.go]: it seems like get will be called for each rpc? we should be stick to an endpoint until it fails? so we should not increase numgets for each get unless there is a failure?

File: clientv3/balancer.go (hunk 2 above)
Comment (heyitsanthony) [inline clientv3/balancer.go]: I think most of that complication is from making it as general as possible. It's safe to assume FailFast is false so there's no need to implement the suggested convoluted blocking logic.

File: clientv3/balancer.go (hunk 3 above)
Comment (heyitsanthony) [inline clientv3/balancer.go]: OK, I'll add pinning.

File: clientv3/balancer.go [hunk 4]
```diff
@@ -15,39 +15,108 @@
...
-	v := atomic.AddUint32(&b.numGets, 1)
-	ep := b.eps[v%uint32(len(b.eps))]
-	return grpc.Address{Addr: getHost(ep)}, func() {}, nil
+	b.mu.Lock()
+	defer b.mu.Unlock()
+
+	if b.pinAddr != nil {
+		if _, ok := b.upEps[b.pinAddr.Addr]; ok || time.Since(b.pinTime) < b.pinWait {
```
Comment (xiang90) [inline clientv3/balancer.go]: i am not very clear about this. why do we need to have a pinWait? if one pined address is still up, should we use it until it fails? current pinWait is 500ms, so a new rpc coming after 500ms will choose a new endpoint now?

File: clientv3/balancer.go (hunk 2 above)
Comment (xiang90) [inline clientv3/balancer.go]: do we expose the failfast option to user now?

File: clientv3/balancer.go (hunk 4 above)
Comment (heyitsanthony) [inline clientv3/balancer.go]: OK, this code is bad; the dial timeout is already in the grpc dialer and there should only be one connecting / up endpoint at a time. I can simplify it.

File: clientv3/balancer.go (hunk 2 above)
Comment (heyitsanthony) [inline clientv3/balancer.go]: no

Comment (xiang90) [inline clientv3/balancer.go]: ok. good.

**Comment by heyitsanthony** [comment]
@xiang90 all fixed PTAL

File: clientv3/balancer.go [hunk 5]
```diff
@@ -26,32 +27,89 @@ import (
...
+	b.upEps[addr.Addr] = struct{}{}
+	if b.pinAddr == "" {
+		// pin first connected address
+		b.pinAddr = addr.Addr
+		b.connAddr = ""
+	}
+	b.mu.Unlock()
+	// notify client that a connection is up
+	select {
+	case b.upc <- struct{}{}:
```
Comment (xiang90) [inline clientv3/balancer.go]: it seems like we only needs to send this once when we create the client? should we rename this to ready? and wrap it with sync.Once?

File: clientv3/balancer.go [hunk 6]
```diff
@@ -26,32 +27,89 @@ import (
...
+	upc chan struct{}
+
+	// mu protects upEps, pinAddr, and connAddr
+	mu sync.Mutex
+	// upEps holds the current endpoints that have an active connection
+	upEps map[string]struct{}
+	// pinAddr is the currently pinned connected address
+	pinAddr string
+	// connAddr is the address proposed for the next connection
+	connAddr string
```
Comment (xiang90) [inline clientv3/balancer.go]: connetctingAddr? Once we return this to gRPC, grpc will start to connecting this addr. Right?

Comment (heyitsanthony) [inline clientv3/balancer.go]: yes

File: clientv3/balancer.go (hunk 5 above)
Comment (heyitsanthony) [inline clientv3/balancer.go]: ok

**Comment by xiang90** [comment]
LGTM

**Comment by heyitsanthony** [comment]
There may be a subtle bug in this if `connectingAddr`'s host is down but other endpoints are available; I'll see if I can trigger it with a test case.

**Comment by heyitsanthony** [comment]
Added a test for the failover case. Now blocked on https://github.com/grpc/grpc-go/pull/810

File: clientv3/retry.go [hunk 7]
```diff
@@ -0,0 +1,243 @@
...
+)
+
+type rpcFunc func(ctx context.Context) error
+type retryRpcFunc func(context.Context, rpcFunc)
+
+func (c *Client) newRetryWrapper() retryRpcFunc {
+	return func(rpcCtx context.Context, f rpcFunc) {
+		for {
+			err := f(rpcCtx)
+			// ignore grpc conn closing on fail-fast calls; they are transient errors
```
Comment (xiang90) [inline clientv3/retry.go]: is there a dial failure error? can connclosing happen after writing the request?

Comment (heyitsanthony) [inline clientv3/retry.go]: There is no explicit dial failure error; the closest thing is the helpfully unexported `errConnClosing` (which gets grpc.Errorf()'d into a grpc formatted error). Transport errors seem to either go through `ConnectionErrorf` or prefixed with "transport:". I guess the safest policy is retry only on `isConnClosing(err)` and bail out otherwise?

**Comment by heyitsanthony** [comment]
OK, changed the retry logic to bail if `err != closing`. CI seems to be happy. PTAL /cc @xiang90

**Comment by xiang90** [comment]
lgtm
