### PR TITLE
e2e: quorum cleanup

### LINKED ISSUE #4694: testing: TestBasicOpsPeerTLS
```
--- FAIL: TestBasicOpsPeerTLS (2.58s)
	etcd_test.go:117: failed get with curl (expected "{\"action\":\"get\",\"node\":{\"key\":\"/testKey\",\"value\":\"foo\",\"", got "\x00{\"errorCode\":100,\"message\":\"Key not found\",\"cause\":\"/testKey\",\"index\":6}\r")
```

/cc @gyuho

### PR DESCRIPTION
**Pull request by heyitsanthony**
If a test gets data without quorum, it should only have one node in the
test cluster to avoid reading stale data.

Fixes #4694

### CODE REVIEW

**Comment by xiang90** [comment]
let's fix merge conflict.

File: e2e/etcd_test.go [hunk 1]
```diff
@@ -86,17 +86,27 @@ var (
...
 )
 
-func TestBasicOpsNoTLS(t *testing.T)        { testBasicOpsPutGet(t, &defaultConfig) }
-func TestBasicOpsAllTLS(t *testing.T)       { testBasicOpsPutGet(t, &defaultConfigTLS) }
-func TestBasicOpsPeerTLS(t *testing.T)      { testBasicOpsPutGet(t, &defaultConfigPeerTLS) }
-func TestBasicOpsClientTLS(t *testing.T)    { testBasicOpsPutGet(t, &defaultConfigClientTLS) }
-func TestBasicOpsProxyNoTLS(t *testing.T)   { testBasicOpsPutGet(t, &defaultConfigWithProxy) }
-func TestBasicOpsProxyTLS(t *testing.T)     { testBasicOpsPutGet(t, &defaultConfigWithProxyTLS) }
-func TestBasicOpsProxyPeerTLS(t *testing.T) { testBasicOpsPutGet(t, &defaultConfigWithProxyPeerTLS) }
+func configLeader(cfg etcdProcessClusterConfig) *etcdProcessClusterConfig {
```
Comment (xiang90) [inline e2e/etcd_test.go]: configStandalone?

**Comment by xiang90** [comment]
LGTM.

**Comment by gyuho** [comment]
Lgtm. Thanks

**Comment by gyuho** [comment]
Closed by mistake

**Comment by gyuho** [comment]
@heyitsanthony Should we merge? I think tester failure is not related to this.

```
grpc: Server.Serve failed to complete security handshake from "@": tls...
```

This happens pretty often when gRPC connection just keeps waiting on state change, but when the change never happens. Not sure if it's just CI issue or gRPC issue.

**Comment by heyitsanthony** [comment]
I wanted to greenlight it but the insecure reject test keeps failing. Pretty sure it's a grpc issue. Merging anyway since unrelated.
