### PR TITLE
fix the problem of StoreKeysPrefix key in store

### LINKED ISSUE #2223: etcd API Backward Compatibility
I tested etcd 2.0 yesterday, and just found a little bit problem: when you call `curl -L http://127.0.0.1:4001/v2/keys/` within etcd 0.4.6, you will get such response: `{"action":"get","node":{"key":"/","dir":true}}`, but with the same call in etcd 2.0, you will get different response: `{"errorCode":100,"message":"Key not found","index":2}`, it seems there is no way to fetch all the keys in etcd. I don't whether this is right or not.

### PR DESCRIPTION
**Pull request by yichengq**
fixes #2223

### CODE REVIEW

File: store/store_test.go [hunk 1]
```diff
@@ -433,22 +442,24 @@ func TestStoreDeleteDiretoryFailsIfNonRecursiveAndDir(t *testing.T) {
...
 
-	_, err := s.Set("/", true, "", Permanent)
-	assert.NotNil(t, err, "")
+	for _, tt := range []string{"/", "/0"} {
+		_, err := s.Set(tt, true, "", Permanent)
+		assert.NotNil(t, err, "")
 
-	_, err = s.Delete("/", true, true)
-	assert.NotNil(t, err, "")
+		_, err = s.Delete(tt, true, true)
```
Comment (xiang90) [inline store/store_test.go]: indentation problem?

**Comment by xiang90** [comment]
lgtm

File: store/store_test.go (hunk 1 above)
Comment (yichengq) [inline store/store_test.go]: it is correct.
