### PR TITLE
etcdmain: fix that advertise-client-urls is required in proxy mode

### LINKED ISSUE #2947: advertise-client-urls required in proxy mode?
In the proxy documentation it mentions it just requires -listen-client-urls, this worked fine on 2.0.10 , now seems beta in AWS is set to 2.0.11 , which breaks many of our configs that are missing advertise-client-urls in the cloud-config setup for proxy boxes.

Is advertise-client-urls really required in proxy mode?

### PR DESCRIPTION
**Pull request by yichengq**
etcd proxy doesn't need to set advertise-client-urls because the flag is
not used.

fixes #2947

### CODE REVIEW

File: etcdmain/config.go [hunk 1]
```diff
@@ -269,8 +269,13 @@ func (cfg *config) Parse(arguments []string) error {
 	if err != nil {
 		return err
 	}
-	if flags.IsSet(cfg.FlagSet, "listen-client-urls") && !flags.IsSet(cfg.FlagSet, "advertise-client-urls") {
-		return errUnsetAdvertiseClientURLsFlag
+
+	// user needs to set -advertise-client-urls if -listen-client-urls is set
+	// when etcd runs in member mode.
```
Comment (xiang90) [inline etcdmain/config.go]: when etcd runs in member mode user...

Comment (yichengq) [inline etcdmain/config.go]: done.

**Comment by xiang90** [comment]
LGTM
