### PR TITLE
etcdctl: fix mk command with PrevNoExist

### LINKED ISSUE #3676: Make new key updates the key if it already exists
Documentation says that `mk` will create a new key /foo/bar, only if the key did not previously exist. Is this a bug? Or is there a way to create a new key with a value, only if it doesn't already exist?

```sh
core@node02 ~ $ etcdctl mk /foo bar
bar
core@node02 ~ $ etcdctl get /foo
bar
core@node02 ~ $ etcdctl mk /foo baz
baz
core@node02 ~ $ etcdctl get /foo
baz
core@node02 ~ $ etcdctl --version
etcdctl version 2.2.0
core@node02 ~ $ etcd --version
etcd version 0.4.9
```

### PR DESCRIPTION
**Pull request by gyuho**
This attempts to fix #3676. `PrevNoExist` checks if the key previously exists and if so, it returns an error, which is how `mk` command is supposed to work. The previous code ignores the previous key and overwrites with the later value.

/cc @yichengq

### CODE REVIEW

**Comment by gyuho** [comment]
yichen says:

> Create is just a wrapper around Set for simplicity, and you could use Set with PrevNoExist in etcdctl to make it fixed.

Will change it to use `Set` now.

**Comment by yichengq** [comment]
@gyuho Have you manually tested that it could resolve the bug in #3676 ?

Moreover, I would appreciate if you could write about problem and how it is fixed in the commit message, instead of writing too much context around API or previous PR.

**Comment by gyuho** [comment]
Yes, in my local machine, I ran the following command:

```
export INFRA_IP=127.0.0.1;

etcd -name infra0 \
	-initial-cluster-token my-infra \
	-initial-cluster infra0=http://$INFRA_IP:2380 \
	-initial-cluster-state new \
	-initial-advertise-peer-urls http://$INFRA_IP:2380 \
	-listen-peer-urls http://$INFRA_IP:2380 \
	-listen-client-urls http://$INFRA_IP:2379 \
	-advertise-client-urls http://$INFRA_IP:2379;

```

And use `etcdctl`:

```
$ etcdctl mk /foo hello
hello

$ etcdctl mk /foo hello
Error:  105: Key already exists (/foo) [8]
```

Please let me know if we need more tests. Thanks

File: etcdctl/command/mk_command.go [hunk 1]
```diff
@@ -51,7 +51,12 @@ func mkCommandFunc(c *cli.Context, ki client.KeysAPI) {
 	ttl := c.Int("ttl")
 
 	ctx, cancel := contextWithTotalTimeout(c)
-	resp, err := ki.Set(ctx, key, value, &client.SetOptions{TTL: time.Duration(ttl) * time.Second, PrevExist: client.PrevIgnore})
+	// client.PrevIgnore would ignore the previous key.
+	// By passing client.PrevNoExist the Set method checks if
+	// the key had existed previously, and returns error when
+	// it tries to overwrite the key, which is how mk command
+	// is supposed to work.
```
Comment (yichengq) [inline etcdctl/command/mk_command.go]: There is no need to mention `PrevIgnore` here because we don't use `PrevIgnore` here.

It would be better if you could make the second sentence more concrete.

**Comment by gyuho** [comment]
I agree. I made some changes on comments. Please let me know if you have any other feedback.

File: etcdctl/command/mk_command.go [hunk 2]
```diff
@@ -51,7 +51,9 @@ func mkCommandFunc(c *cli.Context, ki client.KeysAPI) {
 	ttl := c.Int("ttl")
 
 	ctx, cancel := contextWithTotalTimeout(c)
-	resp, err := ki.Set(ctx, key, value, &client.SetOptions{TTL: time.Duration(ttl) * time.Second, PrevExist: client.PrevIgnore})
+	// PrevNoExist means that the Node must not exist.
+	// Set method returns error if the key already exists.
```
Comment (yichengq) [inline etcdctl/command/mk_command.go]: `Set method returns error if the key already exists.` This sentence is not true if Set method doesn't use PrevNoExist.

Also the comments miss the part that why you explain how Set returns error here.

**Comment by gyuho** [comment]
@yichengq Sorry. I should have made it clear that the Set method in this case.

Is it clear now?

```
// Since PrevNoExist means that the Node must not exist,
// this Set method would return error if the key already exists.
```

File: etcdctl/command/mk_command.go [hunk 3]
```diff
@@ -51,7 +51,9 @@ func mkCommandFunc(c *cli.Context, ki client.KeysAPI) {
 	ttl := c.Int("ttl")
 
 	ctx, cancel := contextWithTotalTimeout(c)
-	resp, err := ki.Set(ctx, key, value, &client.SetOptions{TTL: time.Duration(ttl) * time.Second, PrevExist: client.PrevIgnore})
+	// Since PrevNoExist means that the Node must not exist,
```
Comment (yichengq) [inline etcdctl/command/mk_command.go]: `must not exist previously`

File: etcdctl/command/mk_command.go [hunk 4]
```diff
@@ -51,7 +51,9 @@ func mkCommandFunc(c *cli.Context, ki client.KeysAPI) {
...
+	// this Set method would return error if the key already exists.
```
Comment (yichengq) [inline etcdctl/command/mk_command.go]: `this Set method always creates a new key.` Write about its benefits, which matches what `mk` command does.

**Comment by gyuho** [comment]
```
Since PrevNoExist means that the Node must not exist previously,
this Set method always creates a new key. Therefore, mk command
succeeds only if the key did not previously exist, and the command
prevents one from overwriting values accidentally.
```

This is the reason I think one would need use `mk` command for.
Please let me know if you have any other correction. Thanks!

**Comment by yichengq** [comment]
The comment is a little verbosal IMO, but it is good enough. :+1: 

LGTM. Thanks for fixing it!

**Comment by gyuho** [comment]
Thanks!
