### PR TITLE
lease: force leader to apply its pending committed index for lease op…

### LINKED ISSUE #6978: TTL=0 too soon
via irc,

Version: 3.0.15

Code: https://github.com/immesys/wdd/blob/dev/actionRunner.go#L237-L253

Client-side logs:
```
began actionRunner at 2016-12-09 20:44:20.410794237 +0000 UTC
lease ID: 1713998858250880988 &clientv3.LeaseGrantResponse{ResponseHeader:(*etcdserverpb.ResponseHeader)(0xc4206934e0), ID:1713998858250880988, TTL:60, Error:""}
lease problem (resp= &clientv3.LeaseKeepAliveResponse{ResponseHeader:(*etcdserverpb.ResponseHeader)(0xc4205cc440), ID:1713998858250880988, TTL:0}) at 2016-12-09 20:44:20.449213404 +0000 UTC (1713998858250880988)
panic: etcdserver: requested lease not found
```

So it's triggering the TTL == 0 path in the client to report the lease is gone. However, given that there's a minute-length TTL, the TTL shouldn't be 0 so soon.

About 1/1000 chance of happening.

### PR DESCRIPTION
**Pull request by fanminshi**
suppose a lease granting request from a follower goes through and followed by a lease look up or renewal, the leader might not apply the lease grant request locally. So the leader might not find the lease from the lease look up or renewal request which will result lease not found error. To fix this issue, we force the leader to apply its pending committed index before looking up lease.

FIX #6978

### CODE REVIEW

File: etcdserver/api/v2http/peer.go [hunk 1]
```diff
@@ -31,8 +31,10 @@ const (
 // NewPeerHandler generates an http.Handler to handle etcd peer requests.
 func NewPeerHandler(s *etcdserver.EtcdServer) http.Handler {
 	var lh http.Handler
-	if l := s.Lessor(); l != nil {
-		lh = leasehttp.NewHandler(l)
+	l := s.Lessor()
+	w := s.ApplyWait()
+	if l != nil && w != nil {
```
Comment (gyuho) [inline etcdserver/api/v2http/peer.go]: when do we get `applyWait == nil`?

Comment (fanminshi) [inline etcdserver/api/v2http/peer.go]: we will have a nil pointer exception in leaseHTTP. Probably need to add an extra check.

File: integration/v3_lease_test.go [hunk 2]
```diff
@@ -233,6 +234,106 @@ func TestV3LeaseExists(t *testing.T) {
...
+			return kerr
+		}
+	}
+	return nil
+}
+
+// TestV3LeaseTimeToLiveStress keeps creating lease and retriving it immediately to ensure the lease can be retrived.
+// it was oberserved that the immediate lease retrival after granting a lease from follower resulted lease not found.
+// related issue https://github.com/coreos/etcd/issues/6978
+func TestV3LeaseTimeToLiveStress(t *testing.T) {
```
Comment (heyitsanthony) [inline integration/v3_lease_test.go]: this is nearly the same thing as the other test, the only difference is whether it calls `stressLeaseTimeToLive` or `stressLeaseRenew`; this can be simplified into a generic test `func testLeaseStress(stresser func(context.Context, leaseClient))` which would be called by both `TestV3Lease` functions

File: etcdserver/server.go [hunk 3]
```diff
@@ -1613,6 +1615,10 @@ func (s *EtcdServer) getCommittedIndex() uint64 {
 	return atomic.LoadUint64(&s.committedIndex)
 }
 
+func (s *EtcdServer) GetCommittedIndex() uint64 {
```
Comment (heyitsanthony) [inline etcdserver/server.go]: exporting internal details (e.g., indexes) like this really should be avoided; it leads high coupling and poor cohesion

File: etcdserver/server.go [hunk 4]
```diff
@@ -565,6 +565,8 @@ func (s *EtcdServer) RaftHandler() http.Handler { return s.r.transport.Handler()
 
 func (s *EtcdServer) Lessor() lease.Lessor { return s.lessor }
 
+func (s *EtcdServer) ApplyWait() wait.WaitTime { return s.applyWait }
```
Comment (heyitsanthony) [inline etcdserver/server.go]: this shouldn't be exported to the outside world if possible, it's an internal implementation detail. Try
```go
func (s* EtcdServer) ApplyNotify() <-chan {
    return s.applyWait.Wait(atomic.LoadUint64(&s.committedIndex)) }
}
```

File: etcdserver/api/v2http/peer.go (hunk 1 above)
Comment (fanminshi) [inline etcdserver/api/v2http/peer.go]: ignore my previous comment, i mis-read it. applyWait == nil happens if we don't call EtcdServer.Start() from here https://github.com/coreos/etcd/blob/master/etcdserver/server.go#L526

File: lease/leasehttp/http.go [hunk 5]
```diff
@@ -19,25 +19,37 @@ import (
...
 var (
 	LeasePrefix         = "/leases"
 	LeaseInternalPrefix = "/leases/internal"
+	applyTimeout        = time.Second
 )
 
 // NewHandler returns an http Handler for lease renewals
-func NewHandler(l lease.Lessor) http.Handler {
-	return &leaseHandler{l}
+func NewHandler(l lease.Lessor, w wait.WaitTime, i Indexer) http.Handler {
```
Comment (heyitsanthony) [inline lease/leasehttp/http.go]: This is a bad interface; forces the handler to reason to know about indexes and WaitTime and introduces a lot of interfaces to pretend it's an appropriate abstraction. Having `func NewHandler(l lease.Lessor, waitch func() <-chan)` instead would be so much simpler; it can be called like `NewHandler(l, func() <-chan { return s.ApplyNotify()})`.

File: lease/leasehttp/http.go [hunk 6]
```diff
@@ -59,6 +71,13 @@ func (h *leaseHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
 			http.Error(w, "error unmarshalling request", http.StatusBadRequest)
 			return
 		}
+		cci := h.i.GetCommittedIndex()
+		select {
+		case <-h.w.Wait(cci):
+		case <-time.After(applyTimeout):
+			http.Error(w, "waiting for node to catch up its applied index has timed out", http.StatusInternalServerError)
```
Comment (heyitsanthony) [inline lease/leasehttp/http.go]: should be an actual error code like the other errors; otherwise, this will cause the client lease to shutdown despite this most likely being a transient error

File: lease/leasehttp/http_test.go [hunk 7]
```diff
@@ -76,3 +122,32 @@ func TestTimeToLiveHTTP(t *testing.T) {
 		t.Fatalf("granted TTL expected 5, got %d", resp.LeaseTimeToLiveResponse.GrantedTTL)
 	}
 }
+
+func TestTimeToLiveHTTPTimeout(t *testing.T) {
```
Comment (heyitsanthony) [inline lease/leasehttp/http_test.go]: this is very similar to `TestRenewHTTPTimeout` both should probably call into a common function that has Renew/TimeToLive passed in

File: etcdserver/server.go (hunk 4 above)
Comment (fanminshi) [inline etcdserver/server.go]: that's is much better. will change.

File: integration/v3_lease_test.go (hunk 2 above)
Comment (xiang90) [inline integration/v3_lease_test.go]: what is the reproducibility of this test? can this reproduce the issue every time?

File: integration/v3_lease_test.go [hunk 8]
```diff
@@ -233,6 +233,83 @@ func TestV3LeaseExists(t *testing.T) {
...
+		if rresp.TTL == 0 {
+			return fmt.Errorf("TTL shouldn't be 0 so soon")
+		}
+	}
+	return nil
+}
+
+func stressLeaseTimeToLive(tctx context.Context, lc pb.LeaseClient) error {
+	for tctx.Err() == nil {
+		resp, gerr := lc.LeaseGrant(context.Background(), &pb.LeaseGrantRequest{TTL: 60})
```
Comment (fanminshi) [inline integration/v3_lease_test.go]: I couldn't use `tctx` because tctx is associated with a timeout. i don't want `LeaseGrant` and `LeaseTimeToLive` to throw err due to timed out context.

File: integration/v3_lease_test.go [hunk 9]
```diff
@@ -233,6 +233,83 @@ func TestV3LeaseExists(t *testing.T) {
...
+
+	for i := 0; i < 90; i++ {
+		if err := <-errc; err != nil {
+			t.Fatal(err)
+		}
+	}
+}
+
+func stressLeaseRenew(tctx context.Context, lc pb.LeaseClient) error {
+	cctx, cancel := context.WithCancel(context.Background())
```
Comment (fanminshi) [inline integration/v3_lease_test.go]: I couldn't use `tctx` because tctx is associated with a timeout. i don't want `LeaseGrant`, `Send()`, `Recv()`and  to throw err due to timed out context.

**Comment by fanminshi** [comment]
All fixed. PLTAL @heyitsanthony

File: etcdserver/api/v3rpc/rpctypes/error.go [hunk 10]
```diff
@@ -31,6 +31,8 @@ var (
 	ErrGRPCLeaseNotFound = grpc.Errorf(codes.NotFound, "etcdserver: requested lease not found")
 	ErrGRPCLeaseExist    = grpc.Errorf(codes.FailedPrecondition, "etcdserver: lease already exists")
 
+	ErrGRPCLeaseHTTPTimeout = grpc.Errorf(codes.Unavailable, "etcdserver: lease http request timed out")
```
Comment (heyitsanthony) [inline etcdserver/api/v3rpc/rpctypes/error.go]: After looking through EtcdServer.LeaseRenew and EtcdServer.LeaseTimeToLive again, it seems like this error can't possibly be returned to the client, so I was wrong about the client shutdown problem. Probably better not to define it as an rpc error if it won't leave the etcd server.

File: integration/v3_lease_test.go (hunk 9 above)
Comment (fanminshi) [inline integration/v3_lease_test.go]: that's nice. good to know.

File: etcdserver/api/v3rpc/rpctypes/error.go (hunk 10 above)
Comment (fanminshi) [inline etcdserver/api/v3rpc/rpctypes/error.go]: if the LeaseHTTPTimeout do happen, how should the error being handled? right now, i have it set up so that the error will propagate to client as a grpc error with codes.Unavailable. then the client should retry the request on this error.

Comment (heyitsanthony) [inline etcdserver/api/v3rpc/rpctypes/error.go]: Huh? How is propagating to the grpc client? It goes through LeaseRenew/LeaseTimeToLive in EtcdServer which will retry so long as the request context hasn't timed out. If the context times out, EtcdServer will return `ErrTimeout` back to the client.

Comment (fanminshi) [inline etcdserver/api/v3rpc/rpctypes/error.go]: @heyitsanthony, you are right. i didn't see the loop logic in EtcdServer LeaseRenew. I'll get rid of the grpc error then.

**Comment by fanminshi** [comment]
All Fixed. PTAL @heyitsanthony

**Comment by fanminshi** [comment]
All fixed. PTAL @xiang90 @heyitsanthony. CI passed.

File: etcdserver/raft.go [hunk 11]
```diff
@@ -188,6 +188,8 @@ func (r *raftNode) start(rh *raftReadyHandler) {
 					return
 				}
 
+				updateCommittedIndex(&ap, rh)
```
Comment (xiang90) [inline etcdserver/raft.go]: move this before line 184? or the etcd routine might apply entries before we update commit index. then applied index might be greater than commit index.

File: etcdserver/server.go [hunk 12]
```diff
@@ -596,7 +598,8 @@ type etcdProgress struct {
 // and helps decouple state machine logic from Raft algorithms.
 // TODO: add a state machine interface to apply the commit entries and do snapshot/recover
 type raftReadyHandler struct {
-	leadershipUpdate func()
+	leadershipUpdate   func()
+	committedIdxUpdate func(uint64)
```
Comment (xiang90) [inline etcdserver/server.go]: updateCommittedIndex.

File: etcdserver/raft.go (hunk 11 above)
Comment (fanminshi) [inline etcdserver/raft.go]: good catch! will change

File: etcdserver/server.go (hunk 12 above)
Comment (fanminshi) [inline etcdserver/server.go]: that's better. I also like to keep a consistent naming convention. should I also make `leadershipUpdate -> updateLeadership`?

Comment (xiang90) [inline etcdserver/server.go]: probably. we should do it in another pr though.

Comment (fanminshi) [inline etcdserver/server.go]: make sense. will do!

**Comment by fanminshi** [comment]
All fixed. PTAL @xiang90

**Comment by xiang90** [comment]
defer to @heyitsanthony

**Comment by heyitsanthony** [comment]
lgtm
