### PR TITLE
store: check sorted order in TestStoreGetSorted

### LINKED ISSUE #6910: Test case TestStoreGetSorted in store/store_test.go doesn't check sorted result properly
# Bug reporting

`TestStoreGetSorted()` in `store/store_test.go` doesn't check sorted result properly, see here:

https://github.com/coreos/etcd/blob/master/store/store_test.go#L118

Even if I changed the order of elements in `e.Node.Nodes`, 

```
// Ensure that the store can retrieve a directory in sorted order.
func TestStoreGetSorted(t *testing.T) {
	s := newStore()
	s.Create("/foo", true, "", false, TTLOptionSet{ExpireTime: Permanent})
	s.Create("/foo/x", false, "0", false, TTLOptionSet{ExpireTime: Permanent})
	s.Create("/foo/z", false, "0", false, TTLOptionSet{ExpireTime: Permanent})
	s.Create("/foo/y", true, "", false, TTLOptionSet{ExpireTime: Permanent})
	s.Create("/foo/y/a", false, "0", false, TTLOptionSet{ExpireTime: Permanent})
	s.Create("/foo/y/b", false, "0", false, TTLOptionSet{ExpireTime: Permanent})
	var eidx uint64 = 6
	e, err := s.Get("/foo", true, true)
	assert.Nil(t, err, "")
	assert.Equal(t, e.EtcdIndex, eidx, "")
	var yNodes NodeExterns

        ///////// Change order of elements in e.Node.Nodes by hand!
        tmp := e.Node.Nodes[0]
        e.Node.Nodes[0] = e.Node.Nodes[1]
	e.Node.Nodes[1] = tmp
	for _, n := range e.Node.Nodes {
		fmt.Printf("%v\n", n)
        }
        ////////////

	for _, node := range e.Node.Nodes {
		switch node.Key {
		case "/foo/x":
		case "/foo/y":
			yNodes = node.Nodes
		case "/foo/z":
		default:
			t.Errorf("key = %s, not matched", node.Key)
		}
	}
	for _, node := range yNodes {
		switch node.Key {
		case "/foo/y/a":
		case "/foo/y/b":
		default:
			t.Errorf("key = %s, not matched", node.Key)
		}
	}
}
```

this case still passed!

I assume it's a bug?

### PR DESCRIPTION
**Pull request by m1093782566**
# What?

Fix #6910

### CODE REVIEW

File: store/store_test.go [hunk 1]
```diff
@@ -127,23 +127,23 @@ func TestStoreGetSorted(t *testing.T) {
...
 		}
 	}
-	for _, node := range yNodes {
-		switch node.Key {
-		case "/foo/y/a":
-		case "/foo/y/b":
-		default:
-			t.Errorf("key = %s, not matched", node.Key)
+
+	e, err = s.Get("/foo/y", true, true)
```
Comment (heyitsanthony) [inline store/store_test.go]: This seems to differ from the intent of the original test, shouldn't the data for `/foo/y` come from the `s.Get("/foo", true, true)` request to check that the subtrees from a sorted request are also sorted?

Comment (m1093782566) [inline store/store_test.go]: Yes, the original test doesn't check if the subtrees of `/foo/y` are sorted. But I assume the intent of this case is to check if the keys of subtrees are sorted.

I check the subtrees of `/foo/y` to make use of `/foo/y/a` and `/foo/y/b`.

Comment (heyitsanthony) [inline store/store_test.go]: right, but instead of fetching "/foo/y" with `Get` I think it needs to be something like:
```go
var yNodes NodeExterns
for _, node := range e.Node.Nodes {
   if node.Key == "/foo/y" {
       yNodes = node.Nodes
       break
   }
}
sortedStrings = []string{"/foo/y/a", "/foo/y/b"}
for i := range yNodes {
    if yNodes[i].Key != sortedStrings[i] {
        t.Errorf(...)
    }
}
```

Otherwise, it's not testing the full tree from the response to "/foo".

**Comment by heyitsanthony** [comment]
@m1093782566 lgtm; one last thing-- please update the commit title from `fix TestStoreGetSorted in store_test.go` to `store: check sorted order in TestStoreGetSorted` so it passes the CI commit title format check. After that it should be good to merge. Thanks!

**Comment by m1093782566** [comment]
Title changed

**Comment by heyitsanthony** [comment]
@m1093782566 still failing CI. The commit title in the commit message needs to be changed, not the PR title.

**Comment by m1093782566** [comment]
@heyitsanthony Thanks for your guide.

CI passed.
