### PR TITLE
security: Lazily create the security directories. Fixes #2755.

### LINKED ISSUE #2755: etcd uses 10s to construct the 3-member cluster in localhost
Here is the log:
```
14:39:47 etcd3 | Starting etcd3 on port 5002
14:39:47 proxy | Starting proxy on port 5003
14:39:47 etcd1 | Starting etcd1 on port 5000
14:39:47 etcd2 | Starting etcd2 on port 5001
14:39:47 etcd3 | 2015/04/24 14:39:47 etcd: no data-dir provided, using default data-dir ./infra3.etcd
14:39:47 proxy | 2015/04/24 14:39:47 etcd: no data-dir provided, using default data-dir ./proxy1.etcd
14:39:47 etcd2 | 2015/04/24 14:39:47 etcd: no data-dir provided, using default data-dir ./infra2.etcd
14:39:47 etcd1 | 2015/04/24 14:39:47 etcd: no data-dir provided, using default data-dir ./infra1.etcd
14:39:47 etcd3 | 2015/04/24 14:39:47 etcd: listening for peers on http://localhost:7003
14:39:47 etcd3 | 2015/04/24 14:39:47 etcd: listening for client requests on http://localhost:4003
14:39:47 etcd3 | 2015/04/24 14:39:47 etcdserver: datadir is valid for the 2.0.1 format
14:39:47 proxy | 2015/04/24 14:39:47 proxy: using peer urls [http://localhost:7001 http://localhost:7002 http://localhost:7003]
14:39:47 etcd2 | 2015/04/24 14:39:47 etcd: listening for peers on http://localhost:7002
14:39:47 etcd2 | 2015/04/24 14:39:47 etcd: listening for client requests on http://localhost:4002
14:39:47 etcd2 | 2015/04/24 14:39:47 etcdserver: datadir is valid for the 2.0.1 format
14:39:47 etcd1 | 2015/04/24 14:39:47 etcd: listening for peers on http://localhost:7001
14:39:47 etcd1 | 2015/04/24 14:39:47 etcd: listening for client requests on http://localhost:4001
14:39:47 etcd1 | 2015/04/24 14:39:47 etcdserver: datadir is valid for the 2.0.1 format
14:39:48 proxy | 2015/04/24 14:39:48 etcdserver: could not get cluster response from http://localhost:7001: Get http://localhost:7001/members: read tcp 127.0.0.1:7001: use of closed network connection
14:39:49 etcd3 | 2015/04/24 14:39:49 etcdserver: name = infra3
14:39:49 etcd3 | 2015/04/24 14:39:49 etcdserver: data dir = infra3.etcd
14:39:49 etcd3 | 2015/04/24 14:39:49 etcdserver: member dir = infra3.etcd/member
14:39:49 etcd3 | 2015/04/24 14:39:49 etcdserver: heartbeat = 100ms
14:39:49 etcd3 | 2015/04/24 14:39:49 etcdserver: election = 1000ms
14:39:49 etcd3 | 2015/04/24 14:39:49 etcdserver: snapshot count = 10000
14:39:49 etcd3 | 2015/04/24 14:39:49 etcdserver: advertise client URLs = http://localhost:4003
14:39:49 etcd3 | 2015/04/24 14:39:49 etcdserver: initial advertise peer URLs = http://localhost:7003
14:39:49 etcd3 | 2015/04/24 14:39:49 etcdserver: initial cluster = infra1=http://localhost:7001,infra2=http://localhost:7002,infra3=http://localhost:7003
14:39:49 proxy | 2015/04/24 14:39:49 etcdserver: could not get cluster response from http://localhost:7002: Get http://localhost:7002/members: read tcp 127.0.0.1:7002: use of closed network connection
14:39:49 etcd1 | 2015/04/24 14:39:49 etcdserver: name = infra1
14:39:49 etcd1 | 2015/04/24 14:39:49 etcdserver: data dir = infra1.etcd
14:39:49 etcd1 | 2015/04/24 14:39:49 etcdserver: member dir = infra1.etcd/member
14:39:49 etcd1 | 2015/04/24 14:39:49 etcdserver: heartbeat = 100ms
14:39:49 etcd1 | 2015/04/24 14:39:49 etcdserver: election = 1000ms
14:39:49 etcd1 | 2015/04/24 14:39:49 etcdserver: snapshot count = 10000
14:39:49 etcd1 | 2015/04/24 14:39:49 etcdserver: advertise client URLs = http://localhost:4001
14:39:49 etcd1 | 2015/04/24 14:39:49 etcdserver: initial advertise peer URLs = http://localhost:7001
14:39:49 etcd1 | 2015/04/24 14:39:49 etcdserver: initial cluster = infra1=http://localhost:7001,infra2=http://localhost:7002,infra3=http://localhost:7003
14:39:49 etcd2 | 2015/04/24 14:39:49 etcdserver: name = infra2
14:39:49 etcd2 | 2015/04/24 14:39:49 etcdserver: data dir = infra2.etcd
14:39:49 etcd2 | 2015/04/24 14:39:49 etcdserver: member dir = infra2.etcd/member
14:39:49 etcd2 | 2015/04/24 14:39:49 etcdserver: heartbeat = 100ms
14:39:49 etcd2 | 2015/04/24 14:39:49 etcdserver: election = 1000ms
14:39:49 etcd2 | 2015/04/24 14:39:49 etcdserver: snapshot count = 10000
14:39:49 etcd2 | 2015/04/24 14:39:49 etcdserver: advertise client URLs = http://localhost:4002
14:39:49 etcd2 | 2015/04/24 14:39:49 etcdserver: initial advertise peer URLs = http://localhost:7002
14:39:49 etcd2 | 2015/04/24 14:39:49 etcdserver: initial cluster = infra1=http://localhost:7001,infra2=http://localhost:7002,infra3=http://localhost:7003
14:39:49 etcd1 | 2015/04/24 14:39:49 etcdserver: start member a8266ecf031671f3 in cluster e9c7614f68f35fb2
14:39:49 etcd1 | 2015/04/24 14:39:49 INFO: raft: a8266ecf031671f3 became follower at term 0
14:39:49 etcd1 | 2015/04/24 14:39:49 INFO: raft: newRaft a8266ecf031671f3 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
14:39:49 etcd1 | 2015/04/24 14:39:49 INFO: raft: a8266ecf031671f3 became follower at term 1
14:39:49 etcd2 | 2015/04/24 14:39:49 etcdserver: start member 6e3bd23ae5f1eae0 in cluster e9c7614f68f35fb2
14:39:49 etcd2 | 2015/04/24 14:39:49 INFO: raft: 6e3bd23ae5f1eae0 became follower at term 0
14:39:49 etcd2 | 2015/04/24 14:39:49 INFO: raft: newRaft 6e3bd23ae5f1eae0 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
14:39:49 etcd2 | 2015/04/24 14:39:49 INFO: raft: 6e3bd23ae5f1eae0 became follower at term 1
14:39:49 etcd3 | 2015/04/24 14:39:49 etcdserver: start member 924e2e83e93f2560 in cluster e9c7614f68f35fb2
14:39:49 etcd3 | 2015/04/24 14:39:49 INFO: raft: 924e2e83e93f2560 became follower at term 0
14:39:49 etcd3 | 2015/04/24 14:39:49 INFO: raft: newRaft 924e2e83e93f2560 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
14:39:49 etcd3 | 2015/04/24 14:39:49 INFO: raft: 924e2e83e93f2560 became follower at term 1
14:39:49 etcd2 | 2015/04/24 14:39:49 etcdserver: cannot monitor file descriptor usage (cannot get FDUsage on darwin)
14:39:49 etcd1 | 2015/04/24 14:39:49 etcdserver: cannot monitor file descriptor usage (cannot get FDUsage on darwin)
14:39:49 etcd3 | 2015/04/24 14:39:49 etcdserver: cannot monitor file descriptor usage (cannot get FDUsage on darwin)
14:39:49 etcd3 | 2015/04/24 14:39:49 etcdserver: added member 6e3bd23ae5f1eae0 [http://localhost:7002] to cluster e9c7614f68f35fb2
14:39:49 etcd1 | 2015/04/24 14:39:49 etcdserver: added member 6e3bd23ae5f1eae0 [http://localhost:7002] to cluster e9c7614f68f35fb2
14:39:49 etcd3 | 2015/04/24 14:39:49 etcdserver: added local member 924e2e83e93f2560 [http://localhost:7003] to cluster e9c7614f68f35fb2
14:39:49 etcd1 | 2015/04/24 14:39:49 etcdserver: added member 924e2e83e93f2560 [http://localhost:7003] to cluster e9c7614f68f35fb2
14:39:49 etcd3 | 2015/04/24 14:39:49 etcdserver: added member a8266ecf031671f3 [http://localhost:7001] to cluster e9c7614f68f35fb2
14:39:49 etcd2 | 2015/04/24 14:39:49 etcdserver: added local member 6e3bd23ae5f1eae0 [http://localhost:7002] to cluster e9c7614f68f35fb2
14:39:49 etcd2 | 2015/04/24 14:39:49 etcdserver: added member 924e2e83e93f2560 [http://localhost:7003] to cluster e9c7614f68f35fb2
14:39:49 etcd2 | 2015/04/24 14:39:49 etcdserver: added member a8266ecf031671f3 [http://localhost:7001] to cluster e9c7614f68f35fb2
14:39:49 etcd1 | 2015/04/24 14:39:49 etcdserver: added local member a8266ecf031671f3 [http://localhost:7001] to cluster e9c7614f68f35fb2
14:39:50 proxy | 2015/04/24 14:39:50 etcdserver: could not get cluster response from http://localhost:7003: Get http://localhost:7003/members: read tcp 127.0.0.1:7003: use of closed network connection
14:39:50 proxy | 2015/04/24 14:39:50 proxy: etcdserver: could not retrieve cluster information from the given urls
14:39:50 proxy | 2015/04/24 14:39:50 proxy: listening for client requests on 127.0.0.1:8080
14:39:50 etcd3 | 2015/04/24 14:39:50 INFO: raft: 924e2e83e93f2560 is starting a new election at term 1
14:39:50 etcd3 | 2015/04/24 14:39:50 INFO: raft: 924e2e83e93f2560 became candidate at term 2
14:39:50 etcd3 | 2015/04/24 14:39:50 INFO: raft: 924e2e83e93f2560 received vote from 924e2e83e93f2560 at term 2
14:39:50 etcd3 | 2015/04/24 14:39:50 INFO: raft: 924e2e83e93f2560 [logterm: 1, index: 3] sent vote request to 6e3bd23ae5f1eae0 at term 2
14:39:50 etcd3 | 2015/04/24 14:39:50 INFO: raft: 924e2e83e93f2560 [logterm: 1, index: 3] sent vote request to a8266ecf031671f3 at term 2
14:39:51 etcd2 | 2015/04/24 14:39:51 INFO: raft: 6e3bd23ae5f1eae0 is starting a new election at term 1
14:39:51 etcd2 | 2015/04/24 14:39:51 INFO: raft: 6e3bd23ae5f1eae0 became candidate at term 2
14:39:51 etcd2 | 2015/04/24 14:39:51 INFO: raft: 6e3bd23ae5f1eae0 received vote from 6e3bd23ae5f1eae0 at term 2
14:39:51 etcd2 | 2015/04/24 14:39:51 INFO: raft: 6e3bd23ae5f1eae0 [logterm: 1, index: 3] sent vote request to 924e2e83e93f2560 at term 2
14:39:51 etcd2 | 2015/04/24 14:39:51 INFO: raft: 6e3bd23ae5f1eae0 [logterm: 1, index: 3] sent vote request to a8266ecf031671f3 at term 2
14:39:51 etcd1 | 2015/04/24 14:39:51 INFO: raft: a8266ecf031671f3 is starting a new election at term 1
14:39:51 etcd1 | 2015/04/24 14:39:51 INFO: raft: a8266ecf031671f3 became candidate at term 2
14:39:51 etcd1 | 2015/04/24 14:39:51 INFO: raft: a8266ecf031671f3 received vote from a8266ecf031671f3 at term 2
14:39:51 etcd1 | 2015/04/24 14:39:51 INFO: raft: a8266ecf031671f3 [logterm: 1, index: 3] sent vote request to 6e3bd23ae5f1eae0 at term 2
14:39:51 etcd1 | 2015/04/24 14:39:51 INFO: raft: a8266ecf031671f3 [logterm: 1, index: 3] sent vote request to 924e2e83e93f2560 at term 2
14:39:52 etcd3 | 2015/04/24 14:39:52 INFO: raft: 924e2e83e93f2560 is starting a new election at term 2
14:39:52 etcd3 | 2015/04/24 14:39:52 INFO: raft: 924e2e83e93f2560 became candidate at term 3
14:39:52 etcd3 | 2015/04/24 14:39:52 INFO: raft: 924e2e83e93f2560 received vote from 924e2e83e93f2560 at term 3
14:39:52 etcd3 | 2015/04/24 14:39:52 INFO: raft: 924e2e83e93f2560 [logterm: 1, index: 3] sent vote request to a8266ecf031671f3 at term 3
14:39:52 etcd3 | 2015/04/24 14:39:52 INFO: raft: 924e2e83e93f2560 [logterm: 1, index: 3] sent vote request to 6e3bd23ae5f1eae0 at term 3
14:39:52 etcd2 | 2015/04/24 14:39:52 INFO: raft: 6e3bd23ae5f1eae0 is starting a new election at term 2
14:39:52 etcd2 | 2015/04/24 14:39:52 INFO: raft: 6e3bd23ae5f1eae0 became candidate at term 3
14:39:52 etcd2 | 2015/04/24 14:39:52 INFO: raft: 6e3bd23ae5f1eae0 received vote from 6e3bd23ae5f1eae0 at term 3
14:39:52 etcd2 | 2015/04/24 14:39:52 INFO: raft: 6e3bd23ae5f1eae0 [logterm: 1, index: 3] sent vote request to 924e2e83e93f2560 at term 3
14:39:52 etcd2 | 2015/04/24 14:39:52 INFO: raft: 6e3bd23ae5f1eae0 [logterm: 1, index: 3] sent vote request to a8266ecf031671f3 at term 3
14:39:52 etcd1 | 2015/04/24 14:39:52 INFO: raft: a8266ecf031671f3 is starting a new election at term 2
14:39:52 etcd1 | 2015/04/24 14:39:52 INFO: raft: a8266ecf031671f3 became candidate at term 3
14:39:52 etcd1 | 2015/04/24 14:39:52 INFO: raft: a8266ecf031671f3 received vote from a8266ecf031671f3 at term 3
14:39:52 etcd1 | 2015/04/24 14:39:52 INFO: raft: a8266ecf031671f3 [logterm: 1, index: 3] sent vote request to 6e3bd23ae5f1eae0 at term 3
14:39:52 etcd1 | 2015/04/24 14:39:52 INFO: raft: a8266ecf031671f3 [logterm: 1, index: 3] sent vote request to 924e2e83e93f2560 at term 3
14:39:53 etcd3 | 2015/04/24 14:39:53 INFO: raft: 924e2e83e93f2560 is starting a new election at term 3
14:39:53 etcd3 | 2015/04/24 14:39:53 INFO: raft: 924e2e83e93f2560 became candidate at term 4
14:39:53 etcd3 | 2015/04/24 14:39:53 INFO: raft: 924e2e83e93f2560 received vote from 924e2e83e93f2560 at term 4
14:39:53 etcd3 | 2015/04/24 14:39:53 INFO: raft: 924e2e83e93f2560 [logterm: 1, index: 3] sent vote request to 6e3bd23ae5f1eae0 at term 4
14:39:53 etcd3 | 2015/04/24 14:39:53 INFO: raft: 924e2e83e93f2560 [logterm: 1, index: 3] sent vote request to a8266ecf031671f3 at term 4
14:39:53 etcd2 | 2015/04/24 14:39:53 INFO: raft: 6e3bd23ae5f1eae0 is starting a new election at term 3
14:39:53 etcd2 | 2015/04/24 14:39:53 INFO: raft: 6e3bd23ae5f1eae0 became candidate at term 4
14:39:53 etcd2 | 2015/04/24 14:39:53 INFO: raft: 6e3bd23ae5f1eae0 received vote from 6e3bd23ae5f1eae0 at term 4
14:39:53 etcd2 | 2015/04/24 14:39:53 INFO: raft: 6e3bd23ae5f1eae0 [logterm: 1, index: 3] sent vote request to 924e2e83e93f2560 at term 4
14:39:53 etcd2 | 2015/04/24 14:39:53 INFO: raft: 6e3bd23ae5f1eae0 [logterm: 1, index: 3] sent vote request to a8266ecf031671f3 at term 4
14:39:53 etcd1 | 2015/04/24 14:39:53 INFO: raft: a8266ecf031671f3 is starting a new election at term 3
14:39:53 etcd1 | 2015/04/24 14:39:53 INFO: raft: a8266ecf031671f3 became candidate at term 4
14:39:53 etcd1 | 2015/04/24 14:39:53 INFO: raft: a8266ecf031671f3 received vote from a8266ecf031671f3 at term 4
14:39:53 etcd1 | 2015/04/24 14:39:53 INFO: raft: a8266ecf031671f3 [logterm: 1, index: 3] sent vote request to 6e3bd23ae5f1eae0 at term 4
14:39:53 etcd1 | 2015/04/24 14:39:53 INFO: raft: a8266ecf031671f3 [logterm: 1, index: 3] sent vote request to 924e2e83e93f2560 at term 4
14:39:54 etcd1 | 2015/04/24 14:39:54 etcdserver: publish error: etcdserver: request timed out
14:39:54 etcd2 | 2015/04/24 14:39:54 etcdserver: publish error: etcdserver: request timed out
14:39:54 etcd3 | 2015/04/24 14:39:54 etcdserver: publish error: etcdserver: request timed out
14:39:54 etcd3 | 2015/04/24 14:39:54 rafthttp: roundtripping error: error roundtripping to http://localhost:7002/raft/stream/message/924e2e83e93f2560: read tcp 127.0.0.1:7002: i/o timeout
14:39:54 etcd3 | 2015/04/24 14:39:54 rafthttp: roundtripping error: error roundtripping to http://localhost:7002/raft/stream/msgapp/924e2e83e93f2560: read tcp 127.0.0.1:7002: i/o timeout
14:39:54 etcd3 | 2015/04/24 14:39:54 rafthttp: roundtripping error: error roundtripping to http://localhost:7001/raft/stream/message/924e2e83e93f2560: read tcp 127.0.0.1:7001: i/o timeout
14:39:54 etcd1 | 2015/04/24 14:39:54 rafthttp: roundtripping error: error roundtripping to http://localhost:7002/raft/stream/msgapp/a8266ecf031671f3: read tcp 127.0.0.1:7002: i/o timeout
14:39:54 etcd1 | 2015/04/24 14:39:54 rafthttp: roundtripping error: error roundtripping to http://localhost:7003/raft/stream/message/a8266ecf031671f3: read tcp 127.0.0.1:7003: i/o timeout
14:39:54 etcd1 | 2015/04/24 14:39:54 rafthttp: roundtripping error: error roundtripping to http://localhost:7003/raft/stream/msgapp/a8266ecf031671f3: read tcp 127.0.0.1:7003: i/o timeout
14:39:54 etcd1 | 2015/04/24 14:39:54 rafthttp: roundtripping error: error roundtripping to http://localhost:7002/raft/stream/message/a8266ecf031671f3: read tcp 127.0.0.1:7002: i/o timeout
14:39:54 etcd2 | 2015/04/24 14:39:54 rafthttp: roundtripping error: error roundtripping to http://localhost:7003/raft/stream/msgapp/6e3bd23ae5f1eae0: read tcp 127.0.0.1:7003: i/o timeout
14:39:54 etcd2 | 2015/04/24 14:39:54 rafthttp: roundtripping error: error roundtripping to http://localhost:7001/raft/stream/message/6e3bd23ae5f1eae0: read tcp 127.0.0.1:7001: i/o timeout
14:39:54 etcd2 | 2015/04/24 14:39:54 rafthttp: roundtripping error: error roundtripping to http://localhost:7001/raft/stream/msgapp/6e3bd23ae5f1eae0: read tcp 127.0.0.1:7001: i/o timeout
14:39:54 etcd2 | 2015/04/24 14:39:54 rafthttp: roundtripping error: error roundtripping to http://localhost:7003/raft/stream/message/6e3bd23ae5f1eae0: read tcp 127.0.0.1:7003: i/o timeout
14:39:54 etcd3 | 2015/04/24 14:39:54 rafthttp: roundtripping error: error roundtripping to http://localhost:7001/raft/stream/msgapp/924e2e83e93f2560: read tcp 127.0.0.1:7001: i/o timeout
14:39:55 etcd3 | 2015/04/24 14:39:55 INFO: raft: 924e2e83e93f2560 is starting a new election at term 4
14:39:55 etcd3 | 2015/04/24 14:39:55 INFO: raft: 924e2e83e93f2560 became candidate at term 5
14:39:55 etcd3 | 2015/04/24 14:39:55 INFO: raft: 924e2e83e93f2560 received vote from 924e2e83e93f2560 at term 5
14:39:55 etcd3 | 2015/04/24 14:39:55 INFO: raft: 924e2e83e93f2560 [logterm: 1, index: 3] sent vote request to 6e3bd23ae5f1eae0 at term 5
14:39:55 etcd3 | 2015/04/24 14:39:55 INFO: raft: 924e2e83e93f2560 [logterm: 1, index: 3] sent vote request to a8266ecf031671f3 at term 5
14:39:55 etcd2 | 2015/04/24 14:39:55 INFO: raft: 6e3bd23ae5f1eae0 is starting a new election at term 4
14:39:55 etcd2 | 2015/04/24 14:39:55 INFO: raft: 6e3bd23ae5f1eae0 became candidate at term 5
14:39:55 etcd2 | 2015/04/24 14:39:55 INFO: raft: 6e3bd23ae5f1eae0 received vote from 6e3bd23ae5f1eae0 at term 5
14:39:55 etcd2 | 2015/04/24 14:39:55 INFO: raft: 6e3bd23ae5f1eae0 [logterm: 1, index: 3] sent vote request to 924e2e83e93f2560 at term 5
14:39:55 etcd2 | 2015/04/24 14:39:55 INFO: raft: 6e3bd23ae5f1eae0 [logterm: 1, index: 3] sent vote request to a8266ecf031671f3 at term 5
14:39:55 etcd1 | 2015/04/24 14:39:55 INFO: raft: a8266ecf031671f3 is starting a new election at term 4
14:39:55 etcd1 | 2015/04/24 14:39:55 INFO: raft: a8266ecf031671f3 became candidate at term 5
14:39:55 etcd1 | 2015/04/24 14:39:55 INFO: raft: a8266ecf031671f3 received vote from a8266ecf031671f3 at term 5
14:39:55 etcd1 | 2015/04/24 14:39:55 INFO: raft: a8266ecf031671f3 [logterm: 1, index: 3] sent vote request to 924e2e83e93f2560 at term 5
14:39:55 etcd1 | 2015/04/24 14:39:55 INFO: raft: a8266ecf031671f3 [logterm: 1, index: 3] sent vote request to 6e3bd23ae5f1eae0 at term 5
14:39:55 etcd2 | 2015/04/24 14:39:55 security: Trying to create security directories in the store; failed: etcdserver: request timed out
14:39:55 etcd2 | 2015/04/24 14:39:55 security: Trying to detect security settings failed: Key not found (/2)
14:39:55 etcd1 | 2015/04/24 14:39:55 security: Trying to create security directories in the store; failed: etcdserver: request timed out
14:39:55 etcd1 | 2015/04/24 14:39:55 security: Trying to detect security settings failed: Key not found (/2)
14:39:55 etcd3 | 2015/04/24 14:39:55 security: Trying to create security directories in the store; failed: etcdserver: request timed out
14:39:55 etcd3 | 2015/04/24 14:39:55 security: Trying to detect security settings failed: Key not found (/2)
14:39:55 etcd1 | 2015/04/24 14:39:55 INFO: raft: a8266ecf031671f3 [term: 5] ignored a MsgVote message with lower term from 924e2e83e93f2560 [term: 2]
14:39:55 etcd1 | 2015/04/24 14:39:55 INFO: raft: a8266ecf031671f3 [term: 5] ignored a MsgVote message with lower term from 6e3bd23ae5f1eae0 [term: 2]
14:39:55 etcd1 | 2015/04/24 14:39:55 INFO: raft: a8266ecf031671f3 [term: 5] ignored a MsgVote message with lower term from 924e2e83e93f2560 [term: 3]
14:39:55 etcd1 | 2015/04/24 14:39:55 INFO: raft: a8266ecf031671f3 [term: 5] ignored a MsgVote message with lower term from 6e3bd23ae5f1eae0 [term: 3]
14:39:55 etcd1 | 2015/04/24 14:39:55 INFO: raft: a8266ecf031671f3 [term: 5] ignored a MsgVote message with lower term from 924e2e83e93f2560 [term: 4]
14:39:55 etcd1 | 2015/04/24 14:39:55 INFO: raft: a8266ecf031671f3 [term: 5] ignored a MsgVote message with lower term from 6e3bd23ae5f1eae0 [term: 4]
14:39:55 etcd1 | 2015/04/24 14:39:55 INFO: raft: a8266ecf031671f3 [logterm: 1, index: 3, vote: a8266ecf031671f3] rejected vote from 924e2e83e93f2560 [logterm: 1, index: 3] at term 5
14:39:55 etcd1 | 2015/04/24 14:39:55 INFO: raft: a8266ecf031671f3 [logterm: 1, index: 3, vote: a8266ecf031671f3] rejected vote from 6e3bd23ae5f1eae0 [logterm: 1, index: 3] at term 5
14:39:55 etcd2 | 2015/04/24 14:39:55 INFO: raft: 6e3bd23ae5f1eae0 [term: 5] ignored a MsgVote message with lower term from 924e2e83e93f2560 [term: 2]
14:39:55 etcd2 | 2015/04/24 14:39:55 INFO: raft: 6e3bd23ae5f1eae0 [term: 5] ignored a MsgVote message with lower term from a8266ecf031671f3 [term: 2]
14:39:55 etcd2 | 2015/04/24 14:39:55 INFO: raft: 6e3bd23ae5f1eae0 [term: 5] ignored a MsgVote message with lower term from 924e2e83e93f2560 [term: 3]
14:39:55 etcd2 | 2015/04/24 14:39:55 INFO: raft: 6e3bd23ae5f1eae0 [term: 5] ignored a MsgVote message with lower term from a8266ecf031671f3 [term: 3]
14:39:55 etcd2 | 2015/04/24 14:39:55 INFO: raft: 6e3bd23ae5f1eae0 [term: 5] ignored a MsgVote message with lower term from 924e2e83e93f2560 [term: 4]
14:39:55 etcd2 | 2015/04/24 14:39:55 INFO: raft: 6e3bd23ae5f1eae0 [term: 5] ignored a MsgVote message with lower term from a8266ecf031671f3 [term: 4]
14:39:55 etcd2 | 2015/04/24 14:39:55 INFO: raft: 6e3bd23ae5f1eae0 [logterm: 1, index: 3, vote: 6e3bd23ae5f1eae0] rejected vote from 924e2e83e93f2560 [logterm: 1, index: 3] at term 5
14:39:55 etcd2 | 2015/04/24 14:39:55 INFO: raft: 6e3bd23ae5f1eae0 [logterm: 1, index: 3, vote: 6e3bd23ae5f1eae0] rejected vote from a8266ecf031671f3 [logterm: 1, index: 3] at term 5
14:39:55 etcd3 | 2015/04/24 14:39:55 INFO: raft: 924e2e83e93f2560 [term: 5] ignored a MsgVote message with lower term from 6e3bd23ae5f1eae0 [term: 2]
14:39:55 etcd3 | 2015/04/24 14:39:55 INFO: raft: 924e2e83e93f2560 [term: 5] ignored a MsgVote message with lower term from a8266ecf031671f3 [term: 2]
14:39:55 etcd3 | 2015/04/24 14:39:55 INFO: raft: 924e2e83e93f2560 [term: 5] ignored a MsgVote message with lower term from 6e3bd23ae5f1eae0 [term: 3]
14:39:55 etcd3 | 2015/04/24 14:39:55 INFO: raft: 924e2e83e93f2560 [term: 5] ignored a MsgVote message with lower term from a8266ecf031671f3 [term: 3]
14:39:55 etcd3 | 2015/04/24 14:39:55 INFO: raft: 924e2e83e93f2560 [term: 5] ignored a MsgVote message with lower term from 6e3bd23ae5f1eae0 [term: 4]
14:39:55 etcd3 | 2015/04/24 14:39:55 INFO: raft: 924e2e83e93f2560 [term: 5] ignored a MsgVote message with lower term from a8266ecf031671f3 [term: 4]
14:39:55 etcd3 | 2015/04/24 14:39:55 INFO: raft: 924e2e83e93f2560 [logterm: 1, index: 3, vote: 924e2e83e93f2560] rejected vote from 6e3bd23ae5f1eae0 [logterm: 1, index: 3] at term 5
14:39:55 etcd3 | 2015/04/24 14:39:55 INFO: raft: 924e2e83e93f2560 [logterm: 1, index: 3, vote: 924e2e83e93f2560] rejected vote from a8266ecf031671f3 [logterm: 1, index: 3] at term 5
14:39:55 etcd2 | 2015/04/24 14:39:55 INFO: raft: 6e3bd23ae5f1eae0 received vote rejection from 924e2e83e93f2560 at term 5
14:39:55 etcd2 | 2015/04/24 14:39:55 INFO: raft: 6e3bd23ae5f1eae0 [q:2] has received 1 votes and 1 vote rejections
14:39:55 etcd2 | 2015/04/24 14:39:55 INFO: raft: 6e3bd23ae5f1eae0 received vote rejection from a8266ecf031671f3 at term 5
14:39:55 etcd2 | 2015/04/24 14:39:55 INFO: raft: 6e3bd23ae5f1eae0 [q:2] has received 1 votes and 2 vote rejections
14:39:55 etcd2 | 2015/04/24 14:39:55 INFO: raft: 6e3bd23ae5f1eae0 became follower at term 5
14:39:55 etcd1 | 2015/04/24 14:39:55 INFO: raft: a8266ecf031671f3 received vote rejection from 6e3bd23ae5f1eae0 at term 5
14:39:55 etcd1 | 2015/04/24 14:39:55 INFO: raft: a8266ecf031671f3 [q:2] has received 1 votes and 1 vote rejections
14:39:55 etcd1 | 2015/04/24 14:39:55 INFO: raft: a8266ecf031671f3 received vote rejection from 924e2e83e93f2560 at term 5
14:39:55 etcd1 | 2015/04/24 14:39:55 INFO: raft: a8266ecf031671f3 [q:2] has received 1 votes and 2 vote rejections
14:39:55 etcd1 | 2015/04/24 14:39:55 INFO: raft: a8266ecf031671f3 became follower at term 5
14:39:55 etcd3 | 2015/04/24 14:39:55 INFO: raft: 924e2e83e93f2560 received vote rejection from 6e3bd23ae5f1eae0 at term 5
14:39:55 etcd3 | 2015/04/24 14:39:55 INFO: raft: 924e2e83e93f2560 [q:2] has received 1 votes and 1 vote rejections
14:39:55 etcd3 | 2015/04/24 14:39:55 INFO: raft: 924e2e83e93f2560 received vote rejection from a8266ecf031671f3 at term 5
14:39:55 etcd3 | 2015/04/24 14:39:55 INFO: raft: 924e2e83e93f2560 [q:2] has received 1 votes and 2 vote rejections
14:39:55 etcd3 | 2015/04/24 14:39:55 INFO: raft: 924e2e83e93f2560 became follower at term 5
14:39:57 etcd1 | 2015/04/24 14:39:57 INFO: raft: a8266ecf031671f3 is starting a new election at term 5
14:39:57 etcd1 | 2015/04/24 14:39:57 INFO: raft: a8266ecf031671f3 became candidate at term 6
14:39:57 etcd1 | 2015/04/24 14:39:57 INFO: raft: a8266ecf031671f3 received vote from a8266ecf031671f3 at term 6
14:39:57 etcd1 | 2015/04/24 14:39:57 INFO: raft: a8266ecf031671f3 [logterm: 1, index: 3] sent vote request to 6e3bd23ae5f1eae0 at term 6
14:39:57 etcd1 | 2015/04/24 14:39:57 INFO: raft: a8266ecf031671f3 [logterm: 1, index: 3] sent vote request to 924e2e83e93f2560 at term 6
14:39:57 etcd2 | 2015/04/24 14:39:57 INFO: raft: 6e3bd23ae5f1eae0 is starting a new election at term 5
14:39:57 etcd2 | 2015/04/24 14:39:57 INFO: raft: 6e3bd23ae5f1eae0 became candidate at term 6
14:39:57 etcd2 | 2015/04/24 14:39:57 INFO: raft: 6e3bd23ae5f1eae0 received vote from 6e3bd23ae5f1eae0 at term 6
14:39:57 etcd2 | 2015/04/24 14:39:57 INFO: raft: 6e3bd23ae5f1eae0 [logterm: 1, index: 3] sent vote request to 924e2e83e93f2560 at term 6
14:39:57 etcd2 | 2015/04/24 14:39:57 INFO: raft: 6e3bd23ae5f1eae0 [logterm: 1, index: 3] sent vote request to a8266ecf031671f3 at term 6
14:39:57 etcd3 | 2015/04/24 14:39:57 INFO: raft: 924e2e83e93f2560 [term: 5] received a MsgVote message with higher term from 6e3bd23ae5f1eae0 [term: 6]
14:39:57 etcd3 | 2015/04/24 14:39:57 INFO: raft: 924e2e83e93f2560 became follower at term 6
14:39:57 etcd3 | 2015/04/24 14:39:57 INFO: raft: 924e2e83e93f2560 [logterm: 1, index: 3, vote: 0] voted for 6e3bd23ae5f1eae0 [logterm: 1, index: 3] at term 6
14:39:57 etcd2 | 2015/04/24 14:39:57 INFO: raft: 6e3bd23ae5f1eae0 [logterm: 1, index: 3, vote: 6e3bd23ae5f1eae0] rejected vote from a8266ecf031671f3 [logterm: 1, index: 3] at term 6
14:39:57 etcd2 | 2015/04/24 14:39:57 INFO: raft: 6e3bd23ae5f1eae0 received vote rejection from a8266ecf031671f3 at term 6
14:39:57 etcd2 | 2015/04/24 14:39:57 INFO: raft: 6e3bd23ae5f1eae0 [q:2] has received 1 votes and 1 vote rejections
14:39:57 etcd3 | 2015/04/24 14:39:57 INFO: raft: 924e2e83e93f2560 [logterm: 1, index: 3, vote: 6e3bd23ae5f1eae0] rejected vote from a8266ecf031671f3 [logterm: 1, index: 3] at term 6
14:39:57 etcd2 | 2015/04/24 14:39:57 INFO: raft: 6e3bd23ae5f1eae0 received vote from 924e2e83e93f2560 at term 6
14:39:57 etcd2 | 2015/04/24 14:39:57 INFO: raft: 6e3bd23ae5f1eae0 [q:2] has received 2 votes and 1 vote rejections
14:39:57 etcd1 | 2015/04/24 14:39:57 INFO: raft: a8266ecf031671f3 [logterm: 1, index: 3, vote: a8266ecf031671f3] rejected vote from 6e3bd23ae5f1eae0 [logterm: 1, index: 3] at term 6
14:39:57 etcd1 | 2015/04/24 14:39:57 INFO: raft: a8266ecf031671f3 received vote rejection from 6e3bd23ae5f1eae0 at term 6
14:39:57 etcd1 | 2015/04/24 14:39:57 INFO: raft: a8266ecf031671f3 [q:2] has received 1 votes and 1 vote rejections
14:39:57 etcd1 | 2015/04/24 14:39:57 INFO: raft: a8266ecf031671f3 received vote rejection from 924e2e83e93f2560 at term 6
14:39:57 etcd1 | 2015/04/24 14:39:57 INFO: raft: a8266ecf031671f3 [q:2] has received 1 votes and 2 vote rejections
14:39:57 etcd1 | 2015/04/24 14:39:57 INFO: raft: a8266ecf031671f3 became follower at term 6
14:39:57 etcd2 | 2015/04/24 14:39:57 INFO: raft: 6e3bd23ae5f1eae0 became leader at term 6
14:39:57 etcd2 | 2015/04/24 14:39:57 INFO: raft.node: 6e3bd23ae5f1eae0 elected leader 6e3bd23ae5f1eae0 at term 6
14:39:57 etcd3 | 2015/04/24 14:39:57 INFO: raft.node: 924e2e83e93f2560 elected leader 6e3bd23ae5f1eae0 at term 6
14:39:57 etcd1 | 2015/04/24 14:39:57 INFO: raft.node: a8266ecf031671f3 elected leader 6e3bd23ae5f1eae0 at term 6
14:39:57 etcd2 | 2015/04/24 14:39:57 rafthttp: failed to send message on stream msgappv2 due to write tcp 127.0.0.1:61522: broken pipe. waiting for a new stream to be established.
14:39:57 etcd2 | 2015/04/24 14:39:57 INFO: raft: 6e3bd23ae5f1eae0 failed to send message to 924e2e83e93f2560 because it is unreachable [next = 5, match = 4, state = ProgressStateProbe, waiting = false, pendingSnapshot = 0]
14:39:57 etcd2 | 2015/04/24 14:39:57 rafthttp: failed to send message on stream msgappv2 due to write tcp 127.0.0.1:61518: broken pipe. waiting for a new stream to be established.
14:39:57 etcd2 | 2015/04/24 14:39:57 INFO: raft: 6e3bd23ae5f1eae0 failed to send message to a8266ecf031671f3 because it is unreachable [next = 5, match = 4, state = ProgressStateProbe, waiting = false, pendingSnapshot = 0]
14:39:57 etcd2 | 2015/04/24 14:39:57 etcdserver: published {Name:infra2 ClientURLs:[http://localhost:4002]} to cluster e9c7614f68f35fb2
14:39:57 etcd1 | 2015/04/24 14:39:57 etcdserver: published {Name:infra1 ClientURLs:[http://localhost:4001]} to cluster e9c7614f68f35fb2
14:39:57 etcd3 | 2015/04/24 14:39:57 etcdserver: published {Name:infra3 ClientURLs:[http://localhost:4003]} to cluster e9c7614f68f35fb2
```

I have git bisect the commits, and the first bad commit is `security: Improve the security api as per the suggestions list in #2384`

/cc @barakmich

### PR DESCRIPTION
**Pull request by barakmich**
May find new instances for #2741

### CODE REVIEW

File: etcdserver/security/security_requests.go [hunk 1]
```diff
@@ -111,6 +120,7 @@ func (s *Store) createResource(res string, value interface{}) (etcdserver.Respon
 	return s.setResource(res, value, false)
 }
 func (s *Store) setResource(res string, value interface{}, prevexist bool) (etcdserver.Response, error) {
+	s.ensureSecurityDirectories()
```
Comment (xiang90) [inline etcdserver/security/security_requests.go]: can we add a cached result for this? if this is created, we do not have to send a raft command.

File: etcdserver/security/security.go [hunk 2]
```diff
@@ -116,7 +116,6 @@ func NewStore(server doer, timeout time.Duration) *Store {
 		server:  server,
 		timeout: timeout,
 	}
-	s.ensureSecurityDirectories()
 	s.enabled = s.detectSecurity()
```
Comment (xiang90) [inline etcdserver/security/security.go]: hmm... this is not super reliable today. etcdserver applies all the previous commands after it starts. And the security new happens concurrently with the starting of etcdserver as far as i can see.

Comment (xiang90) [inline etcdserver/security/security.go]: /cc @yichengq

Comment (yichengq) [inline etcdserver/security/security.go]: Yes. And it is hard to tell when it catches up with the cluster progress. Getting it from store each time is one method to ensure its correctness.

File: etcdserver/security/security.go [hunk 3]
```diff
@@ -239,16 +243,20 @@ func (s *Store) UpdateUser(user User) (User, error) {
 }
 
 func (s *Store) AllRoles() ([]string, error) {
+	nodes := []string{GuestRoleName, RootRoleName}
 	resp, err := s.requestResource("/roles/", false)
 	if err != nil {
+		if e, ok := err.(*etcderr.Error); ok {
+			if e.ErrorCode == etcderr.EcodeKeyNotFound {
+				return nodes, nil
```
Comment (yichengq) [inline etcdserver/security/security.go]: The doc says that guest role will not be created until security is enabled. https://github.com/coreos/etcd/blob/master/Documentation/security_api.md#roles

File: etcdserver/security/security.go (hunk 2 above)
Comment (barakmich) [inline etcdserver/security/security.go]: Sure. It could be fetched from the store each time, sans quorum=true -- it'll be pretty fast.

**Comment by xiang90** [comment]
@barakmich Have you tested it? Looks like it will work... I think we really need to improve test coverage around security. :)

**Comment by yichengq** [comment]
lgtm after addressing xiang's concerns.

**Comment by xiang90** [comment]
@barakmich Can we merge this now?

**Comment by barakmich** [comment]
Yep! Merging
