### PR TITLE
rafthttp: fix pipeline.stop may block

### LINKED ISSUE #2888: etcd2 cluster goes unhealthy when removing an unhealthy node
I am seeing something similar to #2834. I'm running 3 CoreOS alpha 695 (etcd 2.0.11) machines on AWS. 

If I hard kill etcd on one of the machines, the cluster remains healthy with 1 unhealthy member. At this point I am successfully able to remove the machine from the cluster.

If instead I stop an entire machine, I still see a healthy cluster with 1 unhealthy member. However, if I try to remove the unhealthy node at this point I get ```context deadline exceeded``` if using etcdctl member remove or a  ```{"message":"Internal Server Error"}``` if using the etcd2 endpoint directly. The cluster remains in this state for ~ 5 minutes before it returns back to a healthy state with only 2 nodes as expected. Looking at the leader logs I see:

```
May 29 17:57:29 ip-10-183-0-120.ec2.internal etcd2[9679]: 2015/05/29 17:57:29 sender: error posting to a429f0ef0f2d2a80: dial tcp 10.183.2.42:2380: connection refused
May 29 17:57:29 ip-10-183-0-120.ec2.internal etcd2[9679]: 2015/05/29 17:57:29 sender: the connection with a429f0ef0f2d2a80 became inactive
May 29 17:57:30 ip-10-183-0-120.ec2.internal etcd2[9679]: 2015/05/29 17:57:30 rafthttp: encountered error writing to server log stream: write tcp 10.183.2.42:39814: broken pipe
May 29 17:57:30 ip-10-183-0-120.ec2.internal etcd2[9679]: 2015/05/29 17:57:30 rafthttp: server streaming to a429f0ef0f2d2a80 at term 862 has been stopped
May 29 17:57:30 ip-10-183-0-120.ec2.internal etcd2[9679]: 2015/05/29 17:57:30 stream: error sending message: stopped
May 29 17:57:30 ip-10-183-0-120.ec2.internal etcd2[9679]: 2015/05/29 17:57:30 stream: stopping the stream server...
May 29 17:59:19 ip-10-183-0-120.ec2.internal etcd2[9679]: 2015/05/29 17:59:19 raft: 11b2f73f68ab6ea6 [term: 862] received a MsgVote message with higher term from af20822d7afb109f [term: 863]
May 29 17:59:19 ip-10-183-0-120.ec2.internal etcd2[9679]: 2015/05/29 17:59:19 raft: 11b2f73f68ab6ea6 became follower at term 863
May 29 17:59:19 ip-10-183-0-120.ec2.internal etcd2[9679]: 2015/05/29 17:59:19 raft: 11b2f73f68ab6ea6 [logterm: 862, index: 21697, vote: 0] rejected vote from af20822d7afb109f [logterm: 862, index: 21696] at term 863
May 29 17:59:19 ip-10-183-0-120.ec2.internal etcd2[9679]: 2015/05/29 17:59:19 raft.node: 11b2f73f68ab6ea6 lost leader 11b2f73f68ab6ea6 at term 863
May 29 17:59:21 ip-10-183-0-120.ec2.internal etcd2[9679]: 2015/05/29 17:59:21 raft: 11b2f73f68ab6ea6 [term: 863] received a MsgVote message with higher term from af20822d7afb109f [term: 864]
May 29 17:59:21 ip-10-183-0-120.ec2.internal etcd2[9679]: 2015/05/29 17:59:21 raft: 11b2f73f68ab6ea6 became follower at term 864
May 29 17:59:21 ip-10-183-0-120.ec2.internal etcd2[9679]: 2015/05/29 17:59:21 raft: 11b2f73f68ab6ea6 [logterm: 862, index: 21697, vote: 0] rejected vote from af20822d7afb109f [logterm: 862, index: 21696] at term 864
May 29 17:59:23 ip-10-183-0-120.ec2.internal etcd2[9679]: 2015/05/29 17:59:23 raft: 11b2f73f68ab6ea6 [term: 864] received a MsgVote message with higher term from af20822d7afb109f [term: 865]
May 29 17:59:23 ip-10-183-0-120.ec2.internal etcd2[9679]: 2015/05/29 17:59:23 raft: 11b2f73f68ab6ea6 became follower at term 865
May 29 17:59:23 ip-10-183-0-120.ec2.internal etcd2[9679]: 2015/05/29 17:59:23 raft: 11b2f73f68ab6ea6 [logterm: 862, index: 21697, vote: 0] rejected vote from af20822d7afb109f [logterm: 862, index: 21696] at term 865
May 29 17:59:24 ip-10-183-0-120.ec2.internal etcd2[9679]: 2015/05/29 17:59:24 etcdhttp: error removing node a429f0ef0f2d2a80: etcdserver: request timed out
May 29 17:59:24 ip-10-183-0-120.ec2.internal etcd2[9679]: 2015/05/29 17:59:24 etcdhttp: unexpected error: etcdserver: request timed out
May 29 17:59:24 ip-10-183-0-120.ec2.internal etcd2[9679]: 2015/05/29 17:59:24 etcdhttp: unexpected error: etcdserver: request timed out
```

### PR DESCRIPTION
**Pull request by yichengq**
This PR makes pipeline.stop stop quickly. It cancels inflight requests,
and stops sending messages in the buffer.

fixes #2888 

I have manually tested the case that is described, and it has been fixed.
@tj-corrigan Give this branch a try if you have time?

### CODE REVIEW

**Comment by tj-corrigan** [comment]
I tested this branch and the behavior is now exactly what I was hoping for. We are able to remove an unhealthy client from an otherwise healthy cluster without any interruption to the cluster. Thanks!

**Comment by yichengq** [comment]
@xiang90 remove the goroutine and double check. PTAL

**Comment by yichengq** [comment]
hope this one can be more clear.

File: rafthttp/pipeline.go [hunk 1]
```diff
@@ -132,7 +146,15 @@ func (p *pipeline) handle() {
 
 // post POSTs a data payload to a url. Returns nil if the POST succeeds,
 // error on any failure.
-func (p *pipeline) post(data []byte) error {
+func (p *pipeline) post(data []byte) (err error) {
+	defer func() {
```
Comment (xiang90) [inline rafthttp/pipeline.go]: var canceled bool

Comment (xiang90) [inline rafthttp/pipeline.go]: move this close to the go func

File: rafthttp/pipeline.go [hunk 2]
```diff
@@ -132,7 +146,15 @@ func (p *pipeline) handle() {
...
+		select {
+		case <-p.stopped:
+			err = errRequestCanceled
```
Comment (xiang90) [inline rafthttp/pipeline.go]: we need to add one line comment for this error rewrite

File: rafthttp/pipeline.go [hunk 3]
```diff
@@ -41,6 +42,13 @@ const (
 	pipelineBufSize = 64
 )
 
+var errRequestCanceled = errors.New("request canceled")
```
Comment (xiang90) [inline rafthttp/pipeline.go]: errStopped

**Comment by xiang90** [comment]
LGTM

File: rafthttp/pipeline.go [hunk 4]
```diff
@@ -41,6 +42,13 @@ const (
 	pipelineBufSize = 64
 )
 
+var errStopped = errors.New("stopped")
+
+type CancelableTransport interface {
```
Comment (xiang90) [inline rafthttp/pipeline.go]: canceler is better i think. also we do not need the roundtripper.

File: rafthttp/pipeline_test.go [hunk 5]
```diff
@@ -77,7 +79,7 @@ func TestPipelineExceedMaximalServing(t *testing.T) {
 	}
 
 	// unblock the senders and force them to send out the data
-	tr.unblock()
+	tr.CancelRequest(&http.Request{})
```
Comment (xiang90) [inline rafthttp/pipeline_test.go]: can we change this back to unblock for better readability? we want to have a tr that can blocks the requests until we unblock it. After the unblock, it should be able to accept and send requests in the future.

File: rafthttp/pipeline_test.go [hunk 6]
```diff
@@ -199,8 +222,8 @@ func (t *roundTripperBlocker) RoundTrip(req *http.Request) (*http.Response, erro
 	<-t.c
 	return &http.Response{StatusCode: http.StatusNoContent, Body: &nopReadCloser{}}, nil
 }
-func (t *roundTripperBlocker) unblock() {
-	close(t.c)
+func (t *roundTripperBlocker) CancelRequest(req *http.Request) {
```
Comment (xiang90) [inline rafthttp/pipeline_test.go]: this the request is canceled, RoundTrip needs to return an error.

File: rafthttp/pipeline_test.go [hunk 7]
```diff
@@ -188,6 +191,26 @@ func TestPipelinePostErrorc(t *testing.T) {
 	}
 }
 
+func TestPipelineStopBlockedRequest(t *testing.T) {
```
Comment (xiang90) [inline rafthttp/pipeline_test.go]: TestStopBlockedPipeline

File: rafthttp/pipeline_test.go [hunk 8]
```diff
@@ -188,20 +191,56 @@ func TestPipelinePostErrorc(t *testing.T) {
...
 func (t *roundTripperBlocker) unblock() {
+	t.mu.Lock()
+	t.unblocked = true
+	t.mu.Unlock()
 	close(t.c)
 }
+func (t *roundTripperBlocker) CancelRequest(req *http.Request) {
+	t.mu.Lock()
+	defer t.mu.Unlock()
+	if t.unblocked {
```
Comment (xiang90) [inline rafthttp/pipeline_test.go]: There is trickier way to only use the chan to implement the same thing. I think it is good enough now.

But we should be aware of this impl is still not perfect. It can cancel a wrong request or a future request(we never check the req pointer). I think it is also good enough for now.

**Comment by xiang90** [comment]
LGTM

File: rafthttp/pipeline_test.go (hunk 8 above)
Comment (yichengq) [inline rafthttp/pipeline_test.go]: agree

**Comment by yichengq** [comment]
will be more cautious in the future. thx for figuring these points out!
