### PR TITLE
clientv3: don't deadlock on Close with broken connection

### LINKED ISSUE #4679: TestTLSGRPCRejectInsecureClient fail
https://semaphoreci.com/coreos/etcd/branches/pull-request-4678/builds/12

```
2016/03/04 03:21:31 grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial unix localhost:node507431623247589594.sock: connect: no such file or directory"; Reconnecting to "localhost:node507431623247589594.sock"
2016/03/04 03:21:31 grpc: Conn.transportMonitor exits due to: grpc: timed out trying to connect
2016/03/04 03:21:31 grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial unix localhost:node507431623247589594.sock: connect: no such file or directory"; Reconnecting to "localhost:node507431623247589594.sock"
2016/03/04 03:21:31 grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial unix localhost:node507431623247589594.sock: connect: no such file or directory"; Reconnecting to "localhost:node507431623247589594.sock"
2016/03/04 03:21:31 grpc: Conn.transportMonitor exits due to: grpc: timed out trying to connect
2016/03/04 03:21:31 grpc: Server.Serve failed to complete security handshake from "@": tls: first record does not look like a TLS handshake
2016/03/04 03:21:31 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
...
2016/03/04 03:21:32 grpc: Server.Serve failed to complete security handshake from "@": tls: first record does not look like a TLS handshake
2016/03/04 03:21:32 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/03/04 03:21:32 grpc: Server.Serve failed to complete security handshake from "@": tls: first record does not look like a TLS handshake
2016/03/04 03:21:32 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/03/04 03:21:32 grpc: Server.Serve failed to complete security handshake from "@": tls: first record does not look like a TLS handshake
2016/03/04 03:21:32 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/03/04 03:21:32 grpc: Server.Serve failed to complete security handshake from "@": tls: first record does not look like a TLS handshake
2016/03/04 03:21:32 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/03/04 03:21:32 grpc: Server.Serve failed to complete security handshake from "@": tls: first record does not look like a TLS handshake
2016/03/04 03:21:32 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/03/04 03:21:32 grpc: Server.Serve failed to complete security handshake from "@": tls: first record does not look like a TLS handshake
2016/03/04 03:21:32 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/03/04 03:21:32 grpc: Server.Serve failed to complete security handshake from "@": tls: first record does not look like a TLS handshake
2016/03/04 03:21:32 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/03/04 03:21:32 grpc: Server.Serve failed to complete security handshake from "@": tls: first record does not look like a TLS handshake
2016/03/04 03:21:32 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/03/04 03:21:32 grpc: Server.Serve failed to complete security handshake from "@": tls: first record does not look like a TLS handshake
2016/03/04 03:21:32 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/03/04 03:21:32 grpc: Server.Serve failed to complete security handshake from "@": tls: first record does not look like a TLS handshake
2016/03/04 03:21:32 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/03/04 03:21:32 grpc: Server.Serve failed to complete security handshake from "@": tls: first record does not look like a TLS handshake
2016/03/04 03:21:32 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/03/04 03:21:32 grpc: Server.Serve failed to complete security handshake from "@": tls: first record does not look like a TLS handshake
2016/03/04 03:21:32 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/03/04 03:21:32 grpc: Server.Serve failed to complete security handshake from "@": tls: first record does not look like a TLS handshake
2016/03/04 03:21:32 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/03/04 03:21:32 grpc: Server.Serve failed to complete security handshake from "@": tls: first record does not look like a TLS handshake
2016/03/04 03:21:32 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/03/04 03:21:32 grpc: Server.Serve failed to complete security handshake from "@": tls: first record does not look like a TLS handshake
2016/03/04 03:21:32 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/03/04 03:21:32 grpc: Server.Serve failed to complete security handshake from "@": tls: first record does not look like a TLS handshake
2016/03/04 03:21:32 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/03/04 03:21:32 grpc: Server.Serve failed to complete security handshake from "@": tls: first record does not look like a TLS handshake
2016/03/04 03:21:32 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/03/04 03:21:32 grpc: Server.Serve failed to complete security handshake from "@": tls: first record does not look like a TLS handshake
2016/03/04 03:21:32 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/03/04 03:21:32 grpc: Server.Serve failed to complete security handshake from "@": tls: first record does not look like a TLS handshake
2016/03/04 03:21:32 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/03/04 03:21:32 grpc: Server.Serve failed to complete security handshake from "@": tls: first record does not look like a TLS handshake
2016/03/04 03:21:32 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/03/04 03:21:32 grpc: Server.Serve failed to complete security handshake from "@": tls: first record does not look like a TLS handshake
2016/03/04 03:21:32 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/03/04 03:21:38 grpc: Conn.transportMonitor exits due to: grpc: timed out trying to connect
2016/03/04 03:21:33 grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial unix localhost:node507431623247589594.sock: connect: no such file or directory"; Reconnecting to "localhost:node507431623247589594.sock"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x10 pc=0x73679f]

goroutine 18552 [running]:
github.com/coreos/etcd/contrib/recipes.(*DoubleBarrier).Leave(0xc821727f40, 0x0, 0x0)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/contrib/recipes/double_barrier.go:77 +0x1af
github.com/coreos/etcd/contrib/recipes.(*DoubleBarrier).Leave(0xc821727f40, 0x0, 0x0)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/contrib/recipes/double_barrier.go:130 +0x70c
github.com/coreos/etcd/integration.TestDoubleBarrierFailover.func2(0xc8232f77a0, 0xa, 0xc820178c60, 0xc82b73e540)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/integration/v3_double_barrier_test.go:109 +0x2b1
created by github.com/coreos/etcd/integration.TestDoubleBarrierFailover
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/integration/v3_double_barrier_test.go:111 +0x1a6

```

### PR DESCRIPTION
**Pull request by heyitsanthony**
Fixes #4679

### CODE REVIEW

File: clientv3/client.go [hunk 1]
```diff
@@ -126,14 +127,22 @@ func (c *Client) Dial(endpoint string) (*grpc.ClientConn, error) {
...
 		endpoint = url.Host
-		opts = append(opts, grpc.WithDialer(f))
 	}
+	f := func(a string, t time.Duration) (net.Conn, error) {
+		select {
+		case <-c.ctx.Done():
+			return nil, c.ctx.Err()
+		default:
+		}
+		return net.DialTimeout(proto, a, t)
```
Comment (xiang90) [inline clientv3/client.go]: shall we get the deadline of ctx? if ctx' deadline is short we should use that one instead of using the passed in t?

**Comment by gyuho** [comment]
lgtm. defer to @xiang90 

Thanks!

File: clientv3/client.go [hunk 2]
```diff
@@ -198,6 +207,13 @@ func (c *Client) retryConnection(oldConn *grpc.ClientConn, err error) (*grpc.Cli
 		// conn has already been updated
 		return c.conn, nil
 	}
+
+	oldConn.Close()
+	if st, _ := oldConn.State(); st != grpc.Shutdown {
+		// wait for shutdown so grpc doesn't leak sleeping goroutines
+		oldConn.WaitForStateChange(c.ctx, st)
```
Comment (xiang90) [inline clientv3/client.go]: this is an EXPERIMENTAL API. see https://godoc.org/google.golang.org/grpc#ClientConn.WaitForStateChange

File: clientv3/client.go (hunk 1 above)
Comment (heyitsanthony) [inline clientv3/client.go]: There's no deadline-- the ctx check is so it won't dial once the client is closed. I'm not sure if a per-request ctx (with a deadline) makes sense because the connection is a shared resource.

File: clientv3/client.go (hunk 2 above)
Comment (heyitsanthony) [inline clientv3/client.go]: I know, but it seems stable enough to use here.

File: clientv3/client.go (hunk 1 above)
Comment (xiang90) [inline clientv3/client.go]: sorry. agree.

**Comment by xiang90** [comment]
LGTM

**Comment by songlh** [comment]
Really sorry to bother! How does the deadlock happens? It looks to me that Client.Close() will release the lock.
