### PR TITLE
etcdserver: always check if the data dir is writable before starting

### LINKED ISSUE #3173: etcd is running, but not bind 4001, 7001
I've installed CoreOS on 3 nodes. Two nodes are fine but one node is going wrong.

```
$ sudo systemctl status etcd
● etcd.service - etcd
   Loaded: loaded (/usr/lib64/systemd/system/etcd.service; static; vendor preset: disabled)
  Drop-In: /run/systemd/system/etcd.service.d
           └─20-cloudinit.conf
   Active: active (running) since Thu 2015-07-23 02:02:13 UTC; 8s ago
 Main PID: 1708 (etcd)
   Memory: 1.8M
      CPU: 15ms
   CGroup: /system.slice/etcd.service
           └─1708 /usr/bin/etcd

Jul 23 02:02:13 deis2 systemd[1]: Started etcd.
Jul 23 02:02:13 deis2 systemd[1]: Starting etcd...
Jul 23 02:02:13 deis2 etcd[1708]: [etcd] Jul 23 02:02:13.086 INFO      | Discovery via https://discovery.etcd....b689b.
Jul 23 02:02:14 deis2 etcd[1708]: [etcd] Jul 23 02:02:14.280 INFO      | Discovery found peers [http://129.254...:7001]
Jul 23 02:02:14 deis2 etcd[1708]: [etcd] Jul 23 02:02:14.280 INFO      | Discovery fetched back peer list: [12...:7001]
Jul 23 02:02:14 deis2 etcd[1708]: [etcd] Jul 23 02:02:14.281 INFO      | Send Join Request to http://129.254.1...1/join
Jul 23 02:02:18 deis2 etcd[1708]: [etcd] Jul 23 02:02:18.782 INFO      | fac687b5306b4d6d8cf680a42b36e284 atte...aders)
Jul 23 02:02:18 deis2 etcd[1708]: [etcd] Jul 23 02:02:18.783 INFO      | Send Join Request to http://129.254.1...1/join
Hint: Some lines were ellipsized, use -l to show in full.
```

```
$ sudo netstat -lntp
sudo netstat -lntp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:5355            0.0.0.0:*               LISTEN      887/systemd-resolve
tcp6       0      0 :::22                   :::*                    LISTEN      1/systemd
tcp6       0      0 :::2375                 :::*                    LISTEN      1/systemd
tcp6       0      0 :::5355                 :::*                    LISTEN      887/systemd-resolve
```

### LINKED ISSUE #3713: etcd2 2.2.0 check dir writable before starting etcdserver
/cc @xiang90  @yichengq 

I'm not sure if it is a feature but some customers were confused that etcd2 complains on "etcdmain: member "e7044ee52bb0a430c9cc7c85814af47e" has previously registered with discovery service token (https://discovery.etcd.io/c534b23f9d3e094e77cea8a901119b7f)." instead of nonexistent directory.

steps to reproduce:

* systemct stop etcd2
* mv /var/lib/etcd2 /var/lib/etcd2_
* 

```
ETCD_DATA_DIR=/var/lib/etcd2 ETCD_DISCOVERY=https://discovery.etcd.io/c534b23f9d3e094e77cea8a901119b7f ETCD_INITIAL_ADVERTISE_PEER_URLS=http://coreos3:2380 ETCD_ADVERTISE_CLIENT_URLS=http://coreos3:2379 ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380 ETCD_NAME=e7044ee52bb0a430c9cc7c85814af47e ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379 etcd2
```

And you will see:

```
ETCD_DATA_DIR=/var/lib/etcd2 ETCD_DISCOVERY=https://discovery.etcd.io/c534b23f9d3e094e77cea8a901119b7f ETCD_INITIAL_ADVERTISE_PEER_URLS=http://coreos3:2380 ETCD_ADVERTISE_CLIENT_URLS=http://coreos3:2379 ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380 ETCD_NAME=e7044ee52bb0a430c9cc7c85814af47e ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379 etcd2
2015-10-19 17:01:46.724194 I | flags: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=http://coreos3:2379
2015-10-19 17:01:46.724541 I | flags: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd2
2015-10-19 17:01:46.724870 I | flags: recognized and used environment variable ETCD_DISCOVERY=https://discovery.etcd.io/c534b23f9d3e094e77cea8a901119b7f
2015-10-19 17:01:46.725694 I | flags: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=http://coreos3:2380
2015-10-19 17:01:46.726014 I | flags: recognized and used environment variable ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
2015-10-19 17:01:46.726353 I | flags: recognized and used environment variable ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
2015-10-19 17:01:46.726623 I | flags: recognized and used environment variable ETCD_NAME=e7044ee52bb0a430c9cc7c85814af47e
2015-10-19 17:01:46.727057 I | etcdmain: etcd Version: 2.2.0
2015-10-19 17:01:46.727180 I | etcdmain: Git SHA: e4561dd
2015-10-19 17:01:46.727306 I | etcdmain: Go Version: go1.5.1
2015-10-19 17:01:46.727612 I | etcdmain: Go OS/Arch: linux/amd64
2015-10-19 17:01:46.727986 I | etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 1
2015-10-19 17:01:46.728335 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2015-10-19 17:01:46.728817 I | etcdmain: listening for peers on http://0.0.0.0:2380
2015-10-19 17:01:46.729124 I | etcdmain: listening for client requests on http://0.0.0.0:2379
2015-10-19 17:01:46.730477 I | netutil: resolving coreos3:2380 to 192.168.122.251:2380
2015-10-19 17:01:46.731175 I | netutil: resolving coreos3:2380 to 192.168.122.251:2380
2015-10-19 17:01:47.954732 I | etcdmain: stopping listening for client requests on http://0.0.0.0:2379
2015-10-19 17:01:47.954967 I | etcdmain: stopping listening for peers on http://0.0.0.0:2380
2015-10-19 17:01:47.955330 E | etcdmain: member "e7044ee52bb0a430c9cc7c85814af47e" has previously registered with discovery service token (https://discovery.etcd.io/c534b23f9d3e094e77cea8a901119b7f).
2015-10-19 17:01:47.955550 E | etcdmain: But etcd could not find valid cluster configuration in the given data dir (/var/lib/etcd2).
2015-10-19 17:01:47.955782 I | etcdmain: Please check the given data dir path if the previous bootstrap succeeded
2015-10-19 17:01:47.956015 I | etcdmain: or use a new discovery token if the previous bootstrap failed.
```

Other members receive following error messages:

```
Oct 19 17:03:48 coreos2 etcd2[658]: 2015/10/19 17:03:48 rafthttp: failed to dial 57278c9eaf5ca969 on stream Message (read tcp 192.168.122.251:2380: connection reset by peer)
Oct 19 17:03:48 coreos2 etcd2[658]: 2015/10/19 17:03:48 rafthttp: failed to dial 57278c9eaf5ca969 on stream MsgApp v2 (read tcp 192.168.122.251:2380: connection reset by peer)
Oct 19 17:03:48 coreos2 etcd2[658]: 2015/10/19 17:03:48 rafthttp: failed to dial 57278c9eaf5ca969 on stream MsgApp v2 (dial tcp 192.168.122.251:2380: connection refused)
Oct 19 17:03:48 coreos2 etcd2[658]: 2015/10/19 17:03:48 rafthttp: failed to dial 57278c9eaf5ca969 on stream Message (dial tcp 192.168.122.251:2380: connection refused)
```

Probably etcd should check for valid datadir first and then communicate with other members?

### PR DESCRIPTION
**Pull request by xiang90**
Fix #3713

#3713 also mentions another issue that etcd should not auto create data-dir if not exist. I do not think that is a good suggestion. I feel it is just OK to create a non-existing data dir for user.

/cc @heyitsanthony

### CODE REVIEW

File: pkg/fileutil/fileutil.go [hunk 1]
```diff
@@ -57,6 +59,16 @@ func ReadDir(dirpath string) ([]string, error) {
 	return names, nil
 }
 
+// MkdirAllIfNotExist is simliar to os.MkdirAll, but will not return ErrExist
+// if the dir exsits before.
+func MkdirAllIfNotExist(dir string) error {
```
Comment (heyitsanthony) [inline pkg/fileutil/fileutil.go]: Unwieldy function name-- at first glance I expected it to fail if the directory exists. Possible alternatives (not necessarily good): `MkdirAllClobber`, `MkdirAllAlways`, `TouchDirAll`

Comment (xiang90) [inline pkg/fileutil/fileutil.go]: Switched to `mkdirAllAlways`. If you still do not feel good about the naming, it probably means that helper func itself is unnecessary . We can just handle the error in main path.

**Comment by xiang90** [comment]
PTAL

File: etcdserver/server.go [hunk 2]
```diff
@@ -204,6 +204,13 @@ func NewServer(cfg *ServerConfig) (*EtcdServer, error) {
 		cl *cluster
 	)
 
+	if mkerr := fileutil.MkdirAllIfNotExist(cfg.DataDir); mkerr != nil {
+		return nil, fmt.Errorf("cannot create data directory: %v", mkerr)
+	}
+	if wderr := fileutil.IsDirWriteable(cfg.DataDir); wderr != nil {
```
Comment (heyitsanthony) [inline etcdserver/server.go]: The `IsDirWriteable` check probably belongs in the `MkdirAllIfNotExist` since every call will probably be followed by the the writeable test otherwise.

Comment (xiang90) [inline etcdserver/server.go]: I had a hard time to think of a good name for it.

Basically there are 4 cases:

1. the dir does not exist; a dir is made; the dir must be writable

2. the dir does not exist; a dir fails to be made; the dir must be not writable

3. the dir exists, check the dir and it is writable

4. the dir exists, check the dir and it is not writable

I cannot come up with a good func name to summary these functionality.

File: etcdserver/server.go [hunk 3]
```diff
@@ -323,9 +326,8 @@ func NewServer(cfg *ServerConfig) (*EtcdServer, error) {
 		return nil, fmt.Errorf("unsupported bootstrap config")
 	}
 
-	err = os.MkdirAll(cfg.MemberDir(), privateDirMode)
-	if err != nil && err != os.ErrExist {
-		return nil, err
+	if mkerr := fileutil.MkdirAllAlways(cfg.MemberDir()); mkerr != nil {
```
Comment (heyitsanthony) [inline etcdserver/server.go]: I think there's a bug here if there's no `IsDirWriteableTest` associated with the `MkdirAllAlways`

Comment (xiang90) [inline etcdserver/server.go]: In theory, it should not. 

If the member dir does not exist before, it must be writable after we create it.

If the member dir does exist before, we checked at line 294.

But it is no harm to check again and make the code more readable, I will add.

File: etcdserver/server.go (hunk 2 above)
Comment (heyitsanthony) [inline etcdserver/server.go]: It's like the directory equivalent of `touch` (ignoring atime/mtime stuff), isn't it? Create if not present, otherwise return true if writeable.

Comment (xiang90) [inline etcdserver/server.go]: i feel touch is used to change time... But after ignoring that, sounds good to me.

**Comment by heyitsanthony** [comment]
Agreed on the auto-creation, I'd rather have the program auto-create a directory than have it ask me to create it myself. No-create would catch misconfiguration (which would manifest elsewhere anyway), of course, but it doesn't seem to be worth the inconvenience.

**Comment by xiang90** [comment]
@heyitsanthony All fixed. Please take a look again.

File: etcdserver/server.go (hunk 2 above)
Comment (heyitsanthony) [inline etcdserver/server.go]: If it does the `IsDirWriteable` test it'll change the mtime of the directory because of that ".touch" file business, so it all works out.

Comment (xiang90) [inline etcdserver/server.go]: right...

**Comment by heyitsanthony** [comment]
lgtm
