### PR TITLE
v2http: submit QGET in health endpoint if no progress

### LINKED ISSUE #6985: etcd cluster unhealthy state on SLES 12
# Bug reporting

I am setting up a three-nodes etcd cluster on SuSE Linux Enterprise Server 12 by following the instructions at https://github.com/coreos/etcd/blob/master/Documentation/op-guide/clustering.md. The cluster is up and running, I could use etcdctl set /foo bar to add entries. But the etcdctl cluster-health shows unhealthy.

**Cluster Nodes**

10.4.35.10 c910f04x35k10 SLES 12
10.4.35.11 c910f04x35k11 SLES 12
10.4.35.12 c910f04x35k12 SLES 12

The etcd service is managed by systemd

**etcd version:**

```
c910f04x35k10:~ # etcd --version
etcd Version: 3.1.0-rc.1+git
Git SHA: b713113
Go Version: go1.7.4
Go OS/Arch: linux/amd64
c910f04x35k10:~ # 
```

**on 10.4.35.10:**
```
c910f04x35k10:~ # ps -ef | grep -i etcd
root      2554     1  1 02:39 ?        00:00:04 /opt/bin/etcd --name infra0 --data-dir /var/lib/etcd/default.etcd --listen-peer-urls http://10.4.35.10:2380 --listen-client-urls http://10.4.35.10:2379,http://127.0.0.1:2379 --initial-cluster infra0=http://10.4.35.10:2380,infra1=http://10.4.35.11:2380,infra2=http://10.4.35.12:2380 --advertise-client-urls http://10.4.35.10:2379 --initial-advertise-peer-urls http://10.4.35.10:2380 --initial-cluster-token kube-etcd --initial-cluster-state new
c910f04x35k10:~ # 
```
**on 10.4.35.11:**

```
c910f04x35k11:~ # ps -ef | grep -i etcd
root      1767     1  1 02:40 ?        00:00:04 /opt/bin/etcd --name infra1 --data-dir /var/lib/etcd/default.etcd --listen-peer-urls http://10.4.35.11:2380 --listen-client-urls http://10.4.35.11:2379,http://127.0.0.1:2379 --initial-cluster infra0=http://10.4.35.10:2380,infra1=http://10.4.35.11:2380,infra2=http://10.4.35.12:2380 --advertise-client-urls http://10.4.35.11:2379 --initial-advertise-peer-urls http://10.4.35.11:2380 --initial-cluster-token kube-etcd --initial-cluster-state new
c910f04x35k11:~ # 
```
**on 10.4.35.12:**

```
c910f04x35k12:~ # ps -ef | grep -i etcd
root      1612     1  1 02:40 ?        00:00:04 /opt/bin/etcd --name infra2 --data-dir /var/lib/etcd/default.etcd --listen-peer-urls http://10.4.35.12:2380 --listen-client-urls http://10.4.35.12:2379,http://127.0.0.1:2379 --initial-cluster infra0=http://10.4.35.10:2380,infra1=http://10.4.35.11:2380,infra2=http://10.4.35.12:2380 --advertise-client-urls http://10.4.35.12:2379 --initial-advertise-peer-urls http://10.4.35.12:2380 --initial-cluster-token kube-etcd --initial-cluster-state new
c910f04x35k12:~ # 
```

**When the cluster is up and running:**

**etcdctl member list shows the members correctly:**

```
c910f04x35k11:~ # etcdctl member list
1cd3725776a8ad50: name=infra0 peerURLs=http://10.4.35.10:2380 clientURLs=http://10.4.35.10:2379 isLeader=false
cb83eda8a3eae07c: name=infra1 peerURLs=http://10.4.35.11:2380 clientURLs=http://10.4.35.11:2379 isLeader=true
ea6f85a7a2683731: name=infra2 peerURLs=http://10.4.35.12:2380 clientURLs=http://10.4.35.12:2379 isLeader=false
c910f04x35k11:~ # 
```
**etcdctl set /foo bar works:**

```
c910f04x35k11:~ # etcdctl set /foo bar
bar
c910f04x35k11:~ # 

c910f04x35k12:~ # etcdctl get /foo
bar
c910f04x35k12:~ # 
```

**But the ectdctl cluster-health shows unhealthy:**

```
c910f04x35k11:~ # etcdctl cluster-health
member 1cd3725776a8ad50 is unhealthy: got unhealthy result from http://10.4.35.10:2379
member cb83eda8a3eae07c is unhealthy: got unhealthy result from http://10.4.35.11:2379
member ea6f85a7a2683731 is unhealthy: got unhealthy result from http://10.4.35.12:2379
cluster is unhealthy
c910f04x35k11:~ # 
```

When the cluster starts up, there is no obvious error in the log:

```
Dec 12 02:49:10 c910f04x35k12 etcd[1733]: recognized environment variable ETCD_INITIAL_CLUSTER_STATE, but unused: shadowed by corresponding flag 
Dec 12 02:49:10 c910f04x35k12 etcd[1733]: recognized environment variable ETCD_INITIAL_CLUSTER, but unused: shadowed by corresponding flag 
Dec 12 02:49:10 c910f04x35k12 etcd[1733]: recognized environment variable ETCD_INITIAL_CLUSTER_TOKEN, but unused: shadowed by corresponding flag 
Dec 12 02:49:10 c910f04x35k12 etcd[1733]: recognized environment variable ETCD_LISTEN_PEER_URLS, but unused: shadowed by corresponding flag 
Dec 12 02:49:10 c910f04x35k12 etcd[1733]: recognized environment variable ETCD_NAME, but unused: shadowed by corresponding flag 
Dec 12 02:49:10 c910f04x35k12 etcd[1733]: recognized environment variable ETCD_ADVERTISE_CLIENT_URLS, but unused: shadowed by corresponding flag 
Dec 12 02:49:10 c910f04x35k12 etcd[1733]: recognized environment variable ETCD_DATA_DIR, but unused: shadowed by corresponding flag 
Dec 12 02:49:10 c910f04x35k12 etcd[1733]: recognized environment variable ETCD_LISTEN_CLIENT_URLS, but unused: shadowed by corresponding flag 
Dec 12 02:49:10 c910f04x35k12 etcd[1733]: etcd Version: 3.1.0-rc.1+git
Dec 12 02:49:10 c910f04x35k12 etcd[1733]: Git SHA: b713113
Dec 12 02:49:10 c910f04x35k12 etcd[1733]: Go Version: go1.7.4
Dec 12 02:49:10 c910f04x35k12 etcd[1733]: Go OS/Arch: linux/amd64
Dec 12 02:49:10 c910f04x35k12 etcd[1733]: setting maximum number of CPUs to 4, total number of available CPUs is 4
Dec 12 02:49:10 c910f04x35k12 etcd[1733]: advertising using detected default host "10.4.35.12"
Dec 12 02:49:10 c910f04x35k12 etcd[1733]: listening for peers on http://10.4.35.12:2380
Dec 12 02:49:10 c910f04x35k12 etcd[1733]: listening for client requests on 10.4.35.12:2379
Dec 12 02:49:10 c910f04x35k12 etcd[1733]: listening for client requests on 127.0.0.1:2379
Dec 12 02:49:12 c910f04x35k12 etcd[1733]: name = infra2
Dec 12 02:49:12 c910f04x35k12 etcd[1733]: data dir = /var/lib/etcd/default.etcd
Dec 12 02:49:12 c910f04x35k12 etcd[1733]: member dir = /var/lib/etcd/default.etcd/member
Dec 12 02:49:12 c910f04x35k12 etcd[1733]: heartbeat = 100ms
Dec 12 02:49:12 c910f04x35k12 etcd[1733]: election = 1000ms
Dec 12 02:49:12 c910f04x35k12 etcd[1733]: snapshot count = 10000
Dec 12 02:49:12 c910f04x35k12 etcd[1733]: advertise client URLs = http://10.4.35.12:2379
Dec 12 02:49:12 c910f04x35k12 etcd[1733]: initial advertise peer URLs = http://10.4.35.12:2380
Dec 12 02:49:12 c910f04x35k12 etcd[1733]: initial cluster = infra0=http://10.4.35.10:2380,infra1=http://10.4.35.11:2380,infra2=http://10.4.35.12:2380
Dec 12 02:49:12 c910f04x35k12 etcd[1733]: starting member ea6f85a7a2683731 in cluster d4fc8521585a3ec1
Dec 12 02:49:12 c910f04x35k12 etcd[1733]: ea6f85a7a2683731 became follower at term 0
Dec 12 02:49:12 c910f04x35k12 etcd[1733]: newRaft ea6f85a7a2683731 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
Dec 12 02:49:12 c910f04x35k12 etcd[1733]: ea6f85a7a2683731 became follower at term 1
Dec 12 02:49:13 c910f04x35k12 etcd[1733]: starting peer 1cd3725776a8ad50...
Dec 12 02:49:13 c910f04x35k12 etcd[1733]: started HTTP pipelining with peer 1cd3725776a8ad50
Dec 12 02:49:13 c910f04x35k12 etcd[1733]: started streaming with peer 1cd3725776a8ad50 (writer)
Dec 12 02:49:13 c910f04x35k12 etcd[1733]: started peer 1cd3725776a8ad50
Dec 12 02:49:13 c910f04x35k12 etcd[1733]: added peer 1cd3725776a8ad50
Dec 12 02:49:13 c910f04x35k12 etcd[1733]: starting peer cb83eda8a3eae07c...
Dec 12 02:49:13 c910f04x35k12 etcd[1733]: started HTTP pipelining with peer cb83eda8a3eae07c
Dec 12 02:49:13 c910f04x35k12 etcd[1733]: started streaming with peer 1cd3725776a8ad50 (writer)
Dec 12 02:49:13 c910f04x35k12 etcd[1733]: started streaming with peer 1cd3725776a8ad50 (stream MsgApp v2 reader)
Dec 12 02:49:13 c910f04x35k12 etcd[1733]: started peer cb83eda8a3eae07c
Dec 12 02:49:13 c910f04x35k12 etcd[1733]: added peer cb83eda8a3eae07c
Dec 12 02:49:13 c910f04x35k12 etcd[1733]: starting server... [version: 3.1.0-rc.1+git, cluster version: to_be_decided]
Dec 12 02:49:13 c910f04x35k12 etcd[1733]: started streaming with peer 1cd3725776a8ad50 (stream Message reader)
Dec 12 02:49:13 c910f04x35k12 etcd[1733]: started streaming with peer cb83eda8a3eae07c (writer)
Dec 12 02:49:13 c910f04x35k12 etcd[1733]: started streaming with peer cb83eda8a3eae07c (writer)
Dec 12 02:49:13 c910f04x35k12 etcd[1733]: peer 1cd3725776a8ad50 became active
Dec 12 02:49:13 c910f04x35k12 etcd[1733]: established a TCP streaming connection with peer 1cd3725776a8ad50 (stream MsgApp v2 writer)
Dec 12 02:49:13 c910f04x35k12 etcd[1733]: started streaming with peer cb83eda8a3eae07c (stream Message reader)
Dec 12 02:49:13 c910f04x35k12 etcd[1733]: peer cb83eda8a3eae07c became active
Dec 12 02:49:13 c910f04x35k12 etcd[1733]: established a TCP streaming connection with peer cb83eda8a3eae07c (stream Message writer)
Dec 12 02:49:13 c910f04x35k12 etcd[1733]: started streaming with peer cb83eda8a3eae07c (stream MsgApp v2 reader)
Dec 12 02:49:13 c910f04x35k12 etcd[1733]: established a TCP streaming connection with peer cb83eda8a3eae07c (stream MsgApp v2 writer)
Dec 12 02:49:13 c910f04x35k12 etcd[1733]: established a TCP streaming connection with peer 1cd3725776a8ad50 (stream Message writer)
Dec 12 02:49:13 c910f04x35k12 etcd[1733]: added member 1cd3725776a8ad50 [http://10.4.35.10:2380] to cluster d4fc8521585a3ec1
Dec 12 02:49:13 c910f04x35k12 etcd[1733]: added member cb83eda8a3eae07c [http://10.4.35.11:2380] to cluster d4fc8521585a3ec1
Dec 12 02:49:13 c910f04x35k12 etcd[1733]: added member ea6f85a7a2683731 [http://10.4.35.12:2380] to cluster d4fc8521585a3ec1
Dec 12 02:49:13 c910f04x35k12 etcd[1733]: established a TCP streaming connection with peer 1cd3725776a8ad50 (stream MsgApp v2 reader)
Dec 12 02:49:13 c910f04x35k12 etcd[1733]: established a TCP streaming connection with peer 1cd3725776a8ad50 (stream Message reader)
Dec 12 02:49:13 c910f04x35k12 etcd[1733]: established a TCP streaming connection with peer cb83eda8a3eae07c (stream MsgApp v2 reader)
Dec 12 02:49:13 c910f04x35k12 etcd[1733]: established a TCP streaming connection with peer cb83eda8a3eae07c (stream Message reader)
Dec 12 02:49:14 c910f04x35k12 etcd[1733]: ea6f85a7a2683731 [term: 1] received a MsgVote message with higher term from cb83eda8a3eae07c [term: 2]
Dec 12 02:49:14 c910f04x35k12 etcd[1733]: ea6f85a7a2683731 became follower at term 2
Dec 12 02:49:14 c910f04x35k12 etcd[1733]: ea6f85a7a2683731 [logterm: 1, index: 3, vote: 0] cast MsgVote for cb83eda8a3eae07c [logterm: 1, index: 3] at term 2
Dec 12 02:49:14 c910f04x35k12 etcd[1733]: raft.node: ea6f85a7a2683731 elected leader cb83eda8a3eae07c at term 2
Dec 12 02:49:15 c910f04x35k12 etcd[1733]: apply entries took too long [352.194175ms for 1 entries]
Dec 12 02:49:15 c910f04x35k12 etcd[1733]: avoid queries with large range/delete range!
Dec 12 02:49:15 c910f04x35k12 etcd[1733]: published {Name:infra2 ClientURLs:[http://10.4.35.12:2379]} to cluster d4fc8521585a3ec1
Dec 12 02:49:15 c910f04x35k12 etcd[1733]: ready to serve client requests
Dec 12 02:49:15 c910f04x35k12 etcd[1733]: ready to serve client requests
Dec 12 02:49:15 c910f04x35k12 etcd[1733]: serving insecure client requests on 127.0.0.1:2379, this is strongly discouraged!
Dec 12 02:49:15 c910f04x35k12 etcd[1733]: serving insecure client requests on 10.4.35.12:2379, this is strongly discouraged!
Dec 12 02:49:15 c910f04x35k12 etcd[1733]: set the initial cluster version to 3.1
Dec 12 02:49:15 c910f04x35k12 etcd[1733]: enabled capabilities for version 3.1
```

### PR DESCRIPTION
**Pull request by heyitsanthony**
Removing the periodic SYNC calls broke the health endpoint since the
raft index stops updating. Instead, if there is no activity after 250ms, issue
a QGET to force some raft traffic.
    
Fixes #6985

### CODE REVIEW

File: etcdserver/api/v2http/client.go [hunk 1]
```diff
@@ -346,32 +346,49 @@ func serveVars(w http.ResponseWriter, r *http.Request) {
...
+			case <-server.StopNotify():
+				return
+			}
+			if ok = server.Index() > index; ok {
 				return
 			}
+			if errc == nil {
+				errc = make(chan error, 1)
+				// try to force progress
+				go func() {
```
Comment (xiang90) [inline etcdserver/api/v2http/client.go]: maybe we can always force a qget to simplify the code logic?

**Comment by xiang90** [comment]
LGTM

File: etcdserver/api/v2http/client.go [hunk 2]
```diff
@@ -346,32 +346,49 @@ func serveVars(w http.ResponseWriter, r *http.Request) {
...
 	return func(w http.ResponseWriter, r *http.Request) {
 		if !allowMethod(w, r.Method, "GET") {
 			return
 		}
 
-		if uint64(server.Leader()) == raft.None {
-			http.Error(w, `{"health": "false"}`, http.StatusServiceUnavailable)
-			return
-		}
+		ctx, cancel := context.WithCancel(context.Background())
```
Comment (xiang90) [inline etcdserver/api/v2http/client.go]: withTimeout = 250ms * 3?

**Comment by xiang90** [comment]
lgtm
