### PR TITLE
mvcc: store.restore taking too long triggering snapshot cycle fix

### LINKED ISSUE #5317: mvcc.store.restore taking too long triggers snapshot cycle
#### Problem

functional-tester etcd-tester's `setHealthKey` gets `context timeout deadline exceeded`, while etcd servers are getting `etcdserver: publish error: etcdserver: request timed out`.

<br>

#### How to reproduce
1. Set up 3 node cluster
2. Write 8M keys
3. Kill one of the follower
4. In parallel, write more keys to other two members _(10K~15K QPS)_
5. Wait until +10K more keys are written (just enough to trigger snapshot)
6. Recover the follower
7. Then the follower reads the `db` file from the disk, and rebuilds index of 8M keys, by calling kvstore.Restore
8. Follower is now available again (able to talk to leader)
9. Follower fell behind as much the entries as were written in the leader while the follower was down
10. Leader sends snapshot to this follower
11. Follower receives this snapshot, which requires to rebuild index of 8M + 10K keys
12. While follower restores from this snapshot, it returns 'etcdserver: publish error: etcdserver:'
13. Stresser has been writing to leader in parallel, and it triggers another snapshot
14. Repeats from step 10.

It will be either compaction timeout or recovery timeout in functional-tests.

For example, use this benchmark command to stress etcd cluster:

```
benchmark --endpoints=${HOST_1}:2379,${HOST_2}:2379,${HOST_3}:2379 \
    --conns=100 --clients=1000 \
    put --key-size=10 --val-size=1 --total=3000000
```

And when the snapshot is triggered, one can see these in leader's logs:

```
2016-06-07 17:29:32.776501 I | etcdserver: wrote database snapshot out [total bytes: 235487232]
2016-06-07 17:29:33.649890 I | rafthttp: database snapshot [index: 3552177, to: 5fbb5cbbbef242b7] sent out successfully
```

And follower logs will be something like:

```
2016-06-07 17:29:33.649748 I | snap: saved database snapshot to disk [total bytes: 235487232]
2016-06-07 17:29:33.649800 I | rafthttp: received and saved database snapshot [index: 3552177, from: b88fca7fa2ea1289] successfully
2016-06-07 17:29:33.650026 I | raft: 5fbb5cbbbef242b7 [commit: 3000778, lastindex: 3000778, lastterm: 5] starts to restore snapshot [index: 3552177, term: 5]
2016-06-07 17:29:33.650089 I | raft: log [committed=3000778, applied=3000778, unstable.offset=3000779, len(unstable.Entries)=0] starts to restore snapshot [index: 3552177, term: 5]
2016-06-07 17:29:33.650129 I | raft: 5fbb5cbbbef242b7 restored progress of 5fbb5cbbbef242b7 [next = 3552178, match = 3552177, state = ProgressStateProbe, waiting = false, pendingSnapshot = 0]
2016-06-07 17:29:33.650148 I | raft: 5fbb5cbbbef242b7 restored progress of b88fca7fa2ea1289 [next = 3552178, match = 0, state = ProgressStateProbe, waiting = false, pendingSnapshot = 0]
2016-06-07 17:29:33.650163 I | raft: 5fbb5cbbbef242b7 restored progress of c4268f53965ad024 [next = 3552178, match = 0, state = ProgressStateProbe, waiting = false, pendingSnapshot = 0]
2016-06-07 17:29:33.650179 I | raft: 5fbb5cbbbef242b7 [commit: 3552177] restored snapshot [index: 3552177, term: 5]
2016-06-07 17:29:33.650323 I | etcdserver: applying snapshot at index 3000641...
2016-06-07 17:29:33.653349 I | etcdserver: raft applied incoming snapshot at index 3552177
2016-06-07 17:29:33.664600 I | etcdserver: restoring mvcc store...
2016-06-07 17:29:57.641605 I | etcdserver: finished restoring mvcc store
...
```

<br>

#### Root Cause

The root cause was the writes being too intensive, with the follower keep falling behind. When an etcd node recovers, it needs to rebuild the key-index from disk. Reading the backend file itself doesn't take long. Iterating 10M keys in boltdb takes only about 3 seconds in SSD.

Rebuilding the key-index from scratch takes long time.

Restoring 8M keys from scratch can take more than 30 seconds. And if there were concurrent writes _(10K~15K QPS)_ in other nodes, the recovering node will need to receive snapshot right after key-index rebuild, and the snapshot will trigger another index rebuilding. And this cycle repeats, as long as there are ongoing concurrent writes, with restoring keys taking longer and longer.

<br>

#### Conclusion

This only happens with extremely intense writes (large number of keys to rebuild btree). And we believe that this will rarely happen in production. Even with this high workload, etcd leader kept operating. If anyone is hitting this issue, please check your workload, try slowing down the workload, or consider compacting your database.

**There was nothing wrong in etcd correctness.**

We mark this as unplanned.

In the future, we will make the `restore` operation faster.

<br>

#### More details

Did more timing:

```
var kv mvccpb.KeyValue
st1 := time.Now()
if err := kv.Unmarshal(vals[i]); err != nil {
    plog.Fatalf("cannot unmarshal event: %v", err)
}
dTime += time.Since(st1)

st2 := time.Now()
s.kvindex.Restore(kv.Key, revision{kv.CreateRevision, 0}, rev, kv.Version)
rTime += time.Since(st2)

mvcc: [DEBUG]
store.restore took 36.38789088s
decode took 2.106427628s
kvindex.restore took 31.230108334s
```

So it's not the decode that take much time, it's `kvindex.Restore` that takes most of the time.

<br>
/cc @heyitsanthony @xiang90

### PR DESCRIPTION
**Pull request by sinsharat**
#5317 

@xiang90 Currently i have commented the test cases. Will fix all the test cases and also add the benchmark test case for this in this PR. There are too many test cases dependent on this. Will start fixing them one by one.
Thank you!

### CODE REVIEW

**Comment by heyitsanthony** [comment]
Please don't comment out so many tests, it makes the PR difficult to read. Most (e.g., the e2e ones) should work as-is if the fix is good...

**Comment by sinsharat** [comment]
@heyitsanthony its still initial phase will be un-commenting all these cases in this PR itself after fixing them all. Or shall i remove all these commented code and keep it as original itself?

**Comment by sinsharat** [comment]
@heyitsanthony as you suggested will keep only the changes here. Once the all test cases have been fixed, this PR should automatically pass.

File: mvcc/kvstore_test.go [hunk 1]
```diff
@@ -405,10 +405,17 @@ func TestStoreRestore(t *testing.T) {
 	if g := b.tx.Action(); !reflect.DeepEqual(g, wact) {
 		t.Errorf("tx actions = %+v, want %+v", g, wact)
 	}
+
+	gens := []generation{
+		generation{created: revision{4, 0}, ver: 2, revs: []revision{revision{3, 0}, revision{5, 0}}},
+		generation{created: revision{0, 0}, ver: 0, revs: nil},
+	}
+	key1 := []byte{0, 0, 0, 0, 0, 0, 0, 3, 95, 0, 0, 0, 0, 0, 0, 0, 0}
```
Comment (sinsharat) [inline mvcc/kvstore_test.go]: @xiang90 As you see here the key is not matching with []byte("foo"), but coming as byte value []byte{0, 0, 0, 0, 0, 0, 0, 3, 95, 0, 0, 0, 0, 0, 0, 0, 0} which comes as some junk character. All the other data is coming as expected except for the key which is coming as junk value. Not able to figure out the reason for this. Request for your support.
Thank you!

Comment (sinsharat) [inline mvcc/kvstore_test.go]: @xiang90 I had tried printing the values, as even though the values were coming same DeepEqual comparison was failing. Later i tried printing the type and the above is the reason they we failing. Attaching the difference between received value and expected value:
```
Got:
[{Name:insert Params:[g: created[{4 0}] ver[2], revs []mvcc.revision{mvcc.revision{main:3, sub:0}, mvcc.revision{main:5, sub:0}} g: created[{0 0}] ver[0], revs []mvcc.revision(nil)]}], 
Expected:
[{Name:insert Params:[g: created[{4 0}] ver[2], revs []mvcc.revision{mvcc.revision{main:3, sub:0}, mvcc.revision{main:5, sub:0}} g: created[{0 0}] ver[0], revs []mvcc.revision(nil)]}], 
Got:
type : [{%!t(string=insert) [%!t(*mvcc.keyIndex=&{[0 0 0 0 0 0 0 3 95 0 0 0 0 0 0 0 0] {5 0} [{2 {4 0} [{3 0} {5 0}]} {0 {0 0} []}]})]}] 
Expected
type : [{%!t(string=insert) [%!t(*mvcc.keyIndex=&{[102 111 111] {0 0}                        [{2 {4 0} [{3 0} {5 0}]} {0 {0 0} []}]})]}]
```

**Comment by sinsharat** [comment]
@xiang90 @heyitsanthony PTAL.
Thank you!

**Comment by sinsharat** [comment]
Benchmark results:

benchmark_sore_restore

**Comment by xiang90** [comment]
@sinsharat Do you have the result before this PR?

**Comment by sinsharat** [comment]
@xiang90 No i don't have the result. I had done the changes based on you suggestion. If you want will take the benchmark result for the older one.

**Comment by sinsharat** [comment]
@xiang90 sure will do it and post the before change PR result here.

**Comment by sinsharat** [comment]
@xiang90 The bench test case i had written was not working with old code. So i had to modify the code as below:
```
st := time.Now()
s = NewStore(be, &lease.FakeLessor{}, &i)
b.Logf("Took %v for restoring %v keys\n", time.Since(st), b.N)
```
After modifying the bench test, the following were the readings with old and new code:
**Old Code:**
```
BenchmarkStoreRestoreRevs10-4             	   50000	     25233 ns/op
--- BENCH: BenchmarkStoreRestoreRevs10-4
	kvstore_bench_test.go:117: Took 43.911ms for restoring 10 keys
	kvstore_bench_test.go:117: Took 67.0137ms for restoring 200 keys
	kvstore_bench_test.go:117: Took 150.127ms for restoring 2000 keys
	kvstore_bench_test.go:117: Took 81.0395ms for restoring 20000 keys
	kvstore_bench_test.go:117: Took 563.2987ms for restoring 200000 keys
	kvstore_bench_test.go:117: Took 1.1537436s for restoring 500000 keys
```

**New Code:**
```
BenchmarkStoreRestoreRevs10-4             	  100000	     17500 ns/op
--- BENCH: BenchmarkStoreRestoreRevs10-4
	kvstore_bench_test.go:117: Took 58.8606ms for restoring 10 keys
	kvstore_bench_test.go:117: Took 93.2865ms for restoring 100 keys
	kvstore_bench_test.go:117: Took 96.471ms for restoring 1000 keys
	kvstore_bench_test.go:117: Took 81.7109ms for restoring 10000 keys
	kvstore_bench_test.go:117: Took 412.4868ms for restoring 100000 keys
	kvstore_bench_test.go:117: Took 566.0508ms for restoring 300000 keys
	kvstore_bench_test.go:117: Took 1.5504294s for restoring 1000000 keys
```

**Comment by xiang90** [comment]
@sinsharat Can you also try 1 rev per key case?

**Comment by sinsharat** [comment]
@xiang90 sure will do it.

**Comment by sinsharat** [comment]
@xiang90 Please find below the result for 1 rev per key case:
**Old Code:**
```
BenchmarkStoreRestoreRevs1-4              	  200000	      5922 ns/op
--- BENCH: BenchmarkStoreRestoreRevs1-4
	kvstore_bench_test.go:116: Took 43.6651ms for restoring 1 keys
	kvstore_bench_test.go:116: Took 76.5179ms for restoring 10 keys
	kvstore_bench_test.go:116: Took 64.1562ms for restoring 100 keys
	kvstore_bench_test.go:116: Took 138.4179ms for restoring 1000 keys
	kvstore_bench_test.go:116: Took 134.2355ms for restoring 10000 keys
	kvstore_bench_test.go:116: Took 584.6538ms for restoring 100000 keys
	kvstore_bench_test.go:116: Took 1.0278762s for restoring 200000 keys
```

**New Code:**
```
BenchmarkStoreRestoreRevs1-4              	  200000	      5472 ns/op
--- BENCH: BenchmarkStoreRestoreRevs1-4
	kvstore_bench_test.go:116: Took 61.997ms for restoring 1 keys
	kvstore_bench_test.go:116: Took 57.2608ms for restoring 10 keys
	kvstore_bench_test.go:116: Took 66.9507ms for restoring 100 keys
	kvstore_bench_test.go:116: Took 105.1183ms for restoring 1000 keys
	kvstore_bench_test.go:116: Took 119.1674ms for restoring 10000 keys
	kvstore_bench_test.go:116: Took 541.6184ms for restoring 100000 keys
	kvstore_bench_test.go:116: Took 998.8248ms for restoring 200000 keys
```

**Comment by xiang90** [comment]
@sinsharat OK. I thought 1 rev case should be slower. But it seems that the overhead is minimum.

Does these result make sense to you? I will give this a closer look today or early tomorrow.

**Comment by sinsharat** [comment]
@xiang90 yes what i can figure out is that the new code, for smaller number of keys takes slight;y more time, but as the keys to restore grows, the restoration becomes faster than the old code. Also if you see the operation time, overall its quite less for newer code for both 10rev/key(17500 ns/op) and 1rev/key(5472 ns/op) as opposed to older code having10rev/key(25233 ns/op) and 1rev/key(5922 ns/op).

File: mvcc/kvstore.go [hunk 2]
```diff
@@ -402,11 +407,20 @@ func (s *store) restore() error {
...
 		switch {
 		case isTombstone(key):
-			s.kvindex.Tombstone(kv.Key, rev)
+			if ki, ok := unordered[string(kv.Key)]; ok {
+				ki.tombstone(rev.main, rev.sub)
+			}
 			delete(keyToLease, string(kv.Key))
 
 		default:
-			s.kvindex.Restore(kv.Key, revision{kv.CreateRevision, 0}, rev, kv.Version)
```
Comment (xiang90) [inline mvcc/kvstore.go]: do we still use restore somewhere else?

Comment (sinsharat) [inline mvcc/kvstore.go]: i don't think so. we are using key-index directly now.

Comment (sinsharat) [inline mvcc/kvstore.go]: sure will do that.

Comment (sinsharat) [inline mvcc/kvstore.go]: Not removing it in this PR because TestIndexCompact and TestIndexRestore in index_test.go are using it. So if we remove it we need to modify these test cases accordingly. Hence better to raise it in separate PR once this gets merged.

Comment (xiang90) [inline mvcc/kvstore.go]: ok.  fine with me.

File: mvcc/kvstore.go [hunk 3]
```diff
@@ -444,7 +463,6 @@ func (s *store) restore() error {
 			scheduledCompact = 0
 		}
 	}
-
```
Comment (xiang90) [inline mvcc/kvstore.go]: revert this change?

File: mvcc/kvstore_bench_test.go [hunk 4]
```diff
@@ -85,3 +86,36 @@ func BenchmarkStoreTxnPut(b *testing.B) {
...
+			id := s.TxnBegin()
+			if _, err := s.TxnPut(id, keys[i], vals[i], lease.NoLease); err != nil {
+				plog.Fatalf("txn put error: %v", err)
+			}
+			s.TxnEnd(id)
+		}
+	}
+	b.ResetTimer()
+	st := time.Now()
+	s.restore()
```
Comment (xiang90) [inline mvcc/kvstore_bench_test.go]: create a new store with the same backend, and the call restore? it reads better. calling restore on a existing store seems strange.

File: mvcc/kvstore_bench_test.go [hunk 5]
```diff
@@ -85,3 +86,36 @@ func BenchmarkStoreTxnPut(b *testing.B) {
...
+	b.Logf("Took %v for restoring %v keys \n", time.Since(st), revPerKey*b.N)
```
Comment (xiang90) [inline mvcc/kvstore_bench_test.go]: remove this debugging line?

File: mvcc/kvstore_bench_test.go [hunk 6]
```diff
@@ -85,3 +86,36 @@ func BenchmarkStoreTxnPut(b *testing.B) {
...
+}
+
+func BenchmarkStoreRestoreRevs10(b *testing.B) {
```
Comment (xiang90) [inline mvcc/kvstore_bench_test.go]: also add Revs1, Revs 20?

**Comment by xiang90** [comment]
Defer to @heyitsanthony

File: mvcc/kvstore_bench_test.go (hunk 4 above)
Comment (sinsharat) [inline mvcc/kvstore_bench_test.go]: @xiang90 sure will do it. In the new benchmark with which i had tested i am doing the same. Will push it through.

File: mvcc/kvstore.go (hunk 3 above)
Comment (sinsharat) [inline mvcc/kvstore.go]: sure will revert it.

File: mvcc/kvstore_bench_test.go (hunk 5 above)
Comment (sinsharat) [inline mvcc/kvstore_bench_test.go]: @xiang90 so we should not calculate the duration for restore?

File: mvcc/kvstore_bench_test.go (hunk 6 above)
Comment (sinsharat) [inline mvcc/kvstore_bench_test.go]: sure will do it.

File: mvcc/kvstore_bench_test.go (hunk 4 above)
Comment (xiang90) [inline mvcc/kvstore_bench_test.go]: we can remove `st` since we do not need the logging. but we should still reset the benchmark timer here and make sure the benchmark tool set working as expected.

File: mvcc/kvstore_bench_test.go (hunk 5 above)
Comment (xiang90) [inline mvcc/kvstore_bench_test.go]: we can remove `st` since we do not need the logging. but we should still reset the benchmark timer here and make sure the benchmark tool set working as expected.

**Comment by sinsharat** [comment]
@xiang90 I have done the changes as per your suggestion. PTAL.
Thank you!

**Comment by heyitsanthony** [comment]
lgtm

**Comment by sinsharat** [comment]
@xiang90 Request you to provide feedback on this.
Thank you!
