### PR TITLE
test: Deflake TestV3LeasePrmote integration test

### LINKED ISSUE #8740: test: TestV3LeasePrmote flake
--- FAIL: TestV3LeasePrmote (10.51s)
	v3_lease_test.go:76: unexpected lease exists

### PR DESCRIPTION
**Pull request by jpbetz**
Fixes #8740

Previously the test would wait for ~1s after the renewed lease should expire, check if it had expired, and hard fail the test if it had not. This can easily flake if the operations that must occur in the etcd cluster during the wait take longer than expected and push out the renewal of the lease. I've replace the check with a polling check that waits for the renewed lease to be released, waiting up to 10 seconds.

Also, the sleeps between events in the test have no reference frames so can accumulate skew from the operations that occur between them. To firm up the timing, I've added a couple time references before/after important events and updated the sleeps to wait relative to those time references. I've also tightened up the timing of the test a bit to reduce the expected test run time from ~10s to about ~5s.

Many testing frameworks already provide some sort of `waitFor` or `pollUntil` utility function. Do we have one somewhere already I can use? If so I'll update this PR to use it instead of the one I added to `util_test.go`

### CODE REVIEW

File: integration/util_test.go [hunk 1]
```diff
@@ -60,3 +61,26 @@ func copyFile(src, dst string) error {
 	}
 	return w.Sync()
 }
+
+type conditionFunc func() (bool, error)
+
+// poll calls a condition function repeatedly on a polling interval until it returns true, returns an error
+// or the timeout is reached. If the condition function returns true or an error before the timeout, poll
+// immediately returns with the true value or the error. If the timeout is exceeded, poll returns false.
+func poll(interval time.Duration, timeout time.Duration, condition conditionFunc) (bool, error) {
```
Comment (xiang90) [inline integration/util_test.go]: can you move this to pkg/testutil/testutil.go?

**Comment by xiang90** [comment]
I am fine with this change if the long wait time is somewhat expected (for example, the cause is just slow CPU). My worry is that something bad was temporarily blocking the lease expire.

**Comment by xiang90** [comment]
lgtm after moving the util func to testutil pkg. 

thanks @jpbetz!

File: integration/util_test.go (hunk 1 above)
Comment (jpbetz) [reply integration/util_test.go]: Ah, yes, that's what I need.

File: integration/v3_lease_test.go [hunk 2]
```diff
@@ -45,10 +47,11 @@ func TestV3LeasePrmote(t *testing.T) {
 	}
 
 	// wait until the lease is going to expire.
-	time.Sleep(time.Duration(lresp.TTL-1) * time.Second)
+	time.Sleep(time.Until(afterGrant.Add(ttl - 1*time.Second)))
```
Comment (fanminshi) [inline integration/v3_lease_test.go]: `time.Sleep(time.Until(afterGrant.Add(ttl - 1*time.Second)))` -> 
`time.Sleep(time.Until(afterGrant.Add(ttl - time.Second)))`?

File: integration/v3_lease_test.go [hunk 3]
```diff
@@ -60,19 +63,29 @@ func TestV3LeasePrmote(t *testing.T) {
 	clus.waitLeader(t, toWait)
 	clus.Members[toStop].Restart(t)
 	clus.waitLeader(t, clus.Members)
+	afterReelect := time.Now()
 
 	// ensure lease is refreshed by waiting for a "long" time.
 	// it was going to expire anyway.
-	time.Sleep(3 * time.Second)
+	time.Sleep(time.Until(beforeStop.Add(ttl - 1*time.Second)))
```
Comment (fanminshi) [inline integration/v3_lease_test.go]: `time.Sleep(time.Until(beforeStop.Add(ttl - 1*time.Second)))` ->
`time.Sleep(time.Until(beforeStop.Add(ttl - time.Second)))`?

**Comment by fanminshi** [comment]
lgtm

File: pkg/testutil/testutil.go [hunk 4]
```diff
@@ -55,3 +55,27 @@ func FatalStack(t *testing.T, s string) {
 	t.Error(string(stackTrace[:n]))
 	t.Fatalf(s)
 }
+
+type ConditionFunc func() (bool, error)
```
Comment (xiang90) [inline pkg/testutil/testutil.go]: need a doc string on public func.

Comment (jpbetz) [reply pkg/testutil/testutil.go]: Added

**Comment by gyuho** [comment]
@jpbetz One last nit.

```
pkg/testutil/testutil.go:67:21: using time.Tick leaks the underlying ticker, consider using it only in endless functions, tests and the main package, and use time.NewTicker here (SA1015)
```

Should we use `time.NewTicker` and call `Stop` at the end?

**Comment by gyuho** [comment]
Btw, it's from our CI https://travis-ci.org/coreos/etcd/jobs/293396251#L829. We can ignore all others :)

**Comment by jpbetz** [comment]
@gyuho Yes, `time.NewTicker` is clearly better, even if only to reduce the log noise, I'll switch.

**Comment by xiang90** [comment]
CI failed on known flake. So merging.

**Comment by xiang90** [comment]
@jpbetz thanks!
