### PR TITLE
functional-tester: always clean up if tester encouters an error

### LINKED ISSUE #6743: functional-tester: mvcc database space exceeded and tester kept running
screenshot from 2016-10-27 10-50-47

tester kept getting `mvcc: database space exceeded` errors, and the tester just kept retrying the first failure case `kill all members`. It starts around round 349. We should just mark it as error or stop the tester. Since this happens, no other case is run. Just `kill all members` counting keeps increasing.

```
2016-10-27 07:04:15.830866 W | etcd-tester: #38 setHealthKey error (etcdserver: mvcc: database space exceeded (http://10.240.0.2:2379))
2016-10-27 07:04:16.834728 W | etcd-tester: #39 setHealthKey error (etcdserver: mvcc: database space exceeded (http://10.240.0.2:2379))
2016-10-27 07:04:17.838512 W | etcd-tester: #40 setHealthKey error (etcdserver: mvcc: database space exceeded (http://10.240.0.2:2379))
2016-10-27 07:04:18.845227 W | etcd-tester: #41 setHealthKey error (etcdserver: mvcc: database space exceeded (http://10.240.0.2:2379))
2016-10-27 07:04:19.864146 W | etcd-tester: #42 setHealthKey error (etcdserver: mvcc: database space exceeded (http://10.240.0.2:2379))
2016-10-27 07:04:20.874420 W | etcd-tester: #43 setHealthKey error (etcdserver: mvcc: database space exceeded (http://10.240.0.2:2379))
2016-10-27 07:04:21.878229 W | etcd-tester: #44 setHealthKey error (etcdserver: mvcc: database space exceeded (http://10.240.0.2:2379))
2016-10-27 07:04:22.882214 W | etcd-tester: #45 setHealthKey error (etcdserver: mvcc: database space exceeded (http://10.240.0.2:2379))
2016-10-27 07:04:23.886160 W | etcd-tester: #46 setHealthKey error (etcdserver: mvcc: database space exceeded (http://10.240.0.2:2379))
2016-10-27 07:04:24.890366 W | etcd-tester: #47 setHealthKey error (etcdserver: mvcc: database space exceeded (http://10.240.0.2:2379))
2016-10-27 07:04:25.929590 W | etcd-tester: #48 setHealthKey error (etcdserver: mvcc: database space exceeded (http://10.240.0.2:2379))
2016-10-27 07:04:26.946588 W | etcd-tester: #49 setHealthKey error (etcdserver: mvcc: database space exceeded (http://10.240.0.2:2379))
2016-10-27 07:04:27.950237 W | etcd-tester: #50 setHealthKey error (etcdserver: mvcc: database space exceeded (http://10.240.0.2:2379))
2016-10-27 07:04:28.954109 W | etcd-tester: #51 setHealthKey error (etcdserver: mvcc: database space exceeded (http://10.240.0.2:2379))
2016-10-27 07:04:29.989237 W | etcd-tester: #52 setHealthKey error (etcdserver: mvcc: database space exceeded (http://10.240.0.2:2379))
2016-10-27 07:04:30.993481 W | etcd-tester: #53 setHealthKey error (etcdserver: mvcc: database space exceeded (http://10.240.0.2:2379))
2016-10-27 07:04:31.997697 W | etcd-tester: #54 setHealthKey error (etcdserver: mvcc: database space exceeded (http://10.240.0.2:2379))
2016-10-27 07:04:33.001455 W | etcd-tester: #55 setHealthKey error (etcdserver: mvcc: database space exceeded (http://10.240.0.2:2379))
2016-10-27 07:04:34.013551 W | etcd-tester: #56 setHealthKey error (etcdserver: mvcc: database space exceeded (http://10.240.0.2:2379))
2016-10-27 07:04:35.018662 W | etcd-tester: #57 setHealthKey error (etcdserver: mvcc: database space exceeded (http://10.240.0.2:2379))
2016-10-27 07:04:36.034003 W | etcd-tester: #58 setHealthKey error (etcdserver: mvcc: database space exceeded (http://10.240.0.2:2379))
2016-10-27 07:04:37.052432 W | etcd-tester: #59 setHealthKey error (etcdserver: mvcc: database space exceeded (http://10.240.0.2:2379))
2016-10-27 07:04:38.052602 I | etcd-tester: [round#359 case#0] wait full health error: etcdserver: mvcc: database space exceeded (http://10.240.0.2:2379)

...

until the end
```

### PR DESCRIPTION
**Pull request by fanminshi**
The current tester doesn't not clean up if any of the failure injection/recovery fails. if tester fails to recover a dead node, tester hangs in the next round because the tester will keep waiting until cluster becomes healthy which is impossible since a node is down. To fix this issue, we will always clean up if any error happens during each round so that cluster will be healthy for next round.

FIX #6743

### CODE REVIEW

**Comment by fanminshi** [comment]
PTAL cc/ @gyuho @heyitsanthony

File: tools/functional-tester/etcd-tester/tester.go [hunk 1]
```diff
@@ -80,45 +79,40 @@ func (tt *tester) runLoop() {
...
-			plog.Printf("%s wait full health error: %v", tt.logPrefix(), err)
-			return false, nil
+			return fmt.Errorf("wait full health error: %v", err)
 		}
-		plog.Printf("%s injecting failure %q", tt.logPrefix(), f.Desc())
+		plog.Infof("%s injecting failure %q", tt.logPrefix(), f.Desc())
 		if err := f.Inject(tt.cluster, round); err != nil {
-			plog.Printf("%s injection error: %v", tt.logPrefix(), err)
-			return false, nil
+			return fmt.Errorf("injection error: %v", err)
```
Comment (gyuho) [inline tools/functional-tester/etcd-tester/tester.go]: Previous, we were able to keep running tests while failure happens in `Inject`. Now one failure would stop the whole tester, right?

@xiang90 Do you remember why we allowed the tester to keep running with failures?

File: tools/functional-tester/etcd-tester/tester.go [hunk 2]
```diff
@@ -80,45 +79,40 @@ func (tt *tester) runLoop() {
...
 		caseTotalCounter.WithLabelValues(f.Desc()).Inc()
 		tt.status.setCase(j)
 
 		if err := tt.cluster.WaitHealth(); err != nil {
-			plog.Printf("%s wait full health error: %v", tt.logPrefix(), err)
-			return false, nil
+			return fmt.Errorf("wait full health error: %v", err)
 		}
-		plog.Printf("%s injecting failure %q", tt.logPrefix(), f.Desc())
+		plog.Infof("%s injecting failure %q", tt.logPrefix(), f.Desc())
```
Comment (gyuho) [inline tools/functional-tester/etcd-tester/tester.go]: Shouldn't be `Warningf`?

Comment (fanminshi) [inline tools/functional-tester/etcd-tester/tester.go]: I think it is just a info statement telling us that we are about to inject failure. Not sure why we need to have a Warningf. I think Warningf is used when a returned error might be problem.

http://stackoverflow.com/questions/2031163/when-to-use-the-different-log-levels

File: tools/functional-tester/etcd-tester/tester.go (hunk 1 above)
Comment (fanminshi) [inline tools/functional-tester/etcd-tester/tester.go]: I think we should reset the tester if any failure injection or recovery has failed because we don't really know the state of the system if those operation fail.  So resetting the system state through clean up will before next round of testing.

**Comment by xiang90** [comment]
Can we change printf -> infof in another pr?

**Comment by fanminshi** [comment]
@xiang90 i'll create a different pr for Printf -> Infof

**Comment by fanminshi** [comment]
All fixed. PTAL @xiang90 @gyuho

**Comment by gyuho** [comment]
lgtm

**Comment by xiang90** [comment]
lgtm

**Comment by xiang90** [comment]
tools/functional-tester/etcd-tester/tester.go:48: syntax error: unexpected err, expecting comma or )

we need to fix error reported by ci

**Comment by fanminshi** [comment]
@xiang90 good catch.

**Comment by fanminshi** [comment]
All fixed.
