### PR TITLE
raft: introduce/fix TestNodeWithSmallerTermCanCompleteElection

### LINKED ISSUE #8243: Node with smaller term can get stuck in election when PreVote is true
Hi, 

When playing with the etcd Raft library, I noticed the following issue when PreVote is enabled. 

For a three nodes Raft cluster with node A, B and C, let's say C is isolated from both A and B due to network partition, so it is expected to keep the initial Term value 1. A and B had a few elections and thus moved their terms to a higher value, say 5. Let's also assume that B is the current leader and A is a follower. 

Now if C is recovered from the network partition and the leader B crash at roughly the same time, we end up having A at term 5 and C at term 1. When they start to do preVote, C's MsgPreVote and MsgPreVoteResp messages will carry term values lower than A's term, they will be both ignored by A, [code here](https://github.com/coreos/etcd/blob/master/raft/raft.go?ts=2#L743). For C, it is expected to receive MsgPreVote from A carrying a higher term value, but C's term will not change in response to a MsgPreVote, [see comments here](https://github.com/coreos/etcd/blob/master/raft/raft.go?ts=2#L712). There is currently no leader, so no MsgHeartbeat message in the system.  

It seems to me that the cluster thus get stuck as no node can complete the PreVote phase. @bdarnell and @xiang90, could you please have a look and shed some light on it? Did I miss something? Many thanks! 

I hacked a quick test for what is described above. 

```
func TestNodeWithSmallerTermCanCompleteElection(t *testing.T) {
  a := newTestRaft(1, []uint64{1, 2, 3}, 10, 1, NewMemoryStorage())
  b := newTestRaft(2, []uint64{1, 2, 3}, 10, 1, NewMemoryStorage())
  c := newTestRaft(3, []uint64{1, 2, 3}, 10, 1, NewMemoryStorage())

  a.becomeFollower(1, None)
  b.becomeFollower(1, None)
  c.becomeFollower(1, None)

  a.preVote = true
  b.preVote = true
  c.preVote = true

  // cause a network partition to isolate node 3
  nt := newNetwork(a, b, c)
  nt.cut(1, 3)
  nt.cut(2, 3)

  // start a few elections to bump the term values
  nt.send(pb.Message{From: 1, To: 1, Type: pb.MsgHup})
  nt.send(pb.Message{From: 3, To: 3, Type: pb.MsgHup})

  sm := nt.peers[1].(*raft)
  if sm.state != StateLeader {
    t.Errorf("peer 1 state: %s, want %s", sm.state, StateLeader)
  }

  sm = nt.peers[2].(*raft)
  if sm.state != StateFollower {
    t.Errorf("peer 2 state: %s, want %s", sm.state, StateFollower)
  }
  sm = nt.peers[3].(*raft)
  if sm.state != StatePreCandidate {
    t.Errorf("peer 3 state: %s, want %s", sm.state, StatePreCandidate)
  }

  nt.send(pb.Message{From: 2, To: 2, Type: pb.MsgHup})
  nt.send(pb.Message{From: 1, To: 1, Type: pb.MsgHup})
  nt.send(pb.Message{From: 2, To: 2, Type: pb.MsgHup})
  nt.send(pb.Message{From: 2, To: 2, Type: pb.MsgProp, Entries: []pb.Entry{{Data: []byte("some data")}}})

  // check whether the term values are expected
  // a.Term == 5
  // b.Term == 5
  // c.Term == 1
  sm = nt.peers[1].(*raft)
  if sm.Term != 5 {
    t.Errorf("peer 1 term: %d, want %d", sm.Term, 5)
  }

  sm = nt.peers[2].(*raft)
  if sm.Term != 5 {
    t.Errorf("peer 2 term: %d, want %d", sm.Term, 5)
  }

  sm = nt.peers[3].(*raft)
  if sm.Term != 1 {
    t.Errorf("peer 3 term: %d, want %d", sm.Term, 1)
  }

  // check state
  // a == follower
  // b == leader
  // c == pre-candidate
  sm = nt.peers[1].(*raft)
  if sm.state != StateFollower {
    t.Errorf("peer 1 state: %s, want %s", sm.state, StateFollower)
  }
  sm = nt.peers[2].(*raft)
  if sm.state != StateLeader {
    t.Errorf("peer 2 state: %s, want %s", sm.state, StateLeader)
  }
  sm = nt.peers[3].(*raft)
  if sm.state != StatePreCandidate {
    t.Errorf("peer 3 state: %s, want %s", sm.state, StatePreCandidate)
  }

  sm.logger.Infof("going to bring back peer 3 and kill peer 2")
  // recover the network then immediately isolate b which is currently
  // the leader, this is to emulate the crash of b.
  nt.recover()
  nt.cut(2, 1)
  nt.cut(2, 3)

  // call for election
  nt.send(pb.Message{From: 3, To: 3, Type: pb.MsgHup})
  nt.send(pb.Message{From: 1, To: 1, Type: pb.MsgHup})

  // do we have a leader
  sma := nt.peers[1].(*raft)
  smb := nt.peers[3].(*raft)
  if sma.state != StateLeader && smb.state != StateLeader {
    t.Errorf("no leader")
  }
}
```

### PR DESCRIPTION
**Pull request by irfansharif**
Fixes #8243.

`TestNodeWithSmallerTermCanCompleteElection` tests the scenario where a
node that has been partitioned away (and fallen behind) rejoins the
cluster at about the same time the leader node gets partitioned away.
Previously the cluster would come to a standstill when run with PreVote
enabled.

When responding to `Msg{Pre,}Vote` messages we now include the term from
the message, not the local term. To see why consider the case where a
single node was previously partitioned away and it's local term is now
of date. If we include the local term (recall that for pre-votes we
don't update the local term), the (pre-)campaigning node on the other
end will proceed to ignore the message (it ignores all out of date
messages).
The term in the original message and current local term are the same in
the case of regular votes, but different for pre-votes.

NB: Had to change `TestRecvMsgVote` to include `pb.Message.Term` when
sending MsgVote messages. The new sanity checks on `MsgVoteResp`
(`m.Term != 0`) would panic with the old test as `raft.Term` would be equal
to 0 when responding with `MsgVoteResp` messages.

+cc @bdarnell @xiang90.

### CODE REVIEW

File: raft/raft.go [hunk 1]
```diff
@@ -726,12 +727,19 @@ func (r *raft) Step(m pb.Message) error {
 			// but it will not receive MsgApp or MsgHeartbeat, so it will not create
 			// disruptive term increases
 			r.send(pb.Message{To: m.From, Type: pb.MsgAppResp})
-		} else {
+			return nil
+		case m.Type == pb.MsgPreVote || m.Type == pb.MsgPreVoteResp:
+			// If we receive a MsgPreVote from a node with a lower term number,
```
Comment (bdarnell) [inline raft/raft.go]: Why is it important that we reject MsgPreVote instead of dropping it? We just drop MsgVote messages with older terms.

File: raft/raft.go [hunk 2]
```diff
@@ -726,12 +727,19 @@ func (r *raft) Step(m pb.Message) error {
...
+			// we reject it. For a MsgPreVoteResp we simply pass it to our
+			// stepFunc. For a stale MsgPreVoteResp (think of late responses,
+			// we've already transitioned to a leader or follower state) this
```
Comment (bdarnell) [inline raft/raft.go]: But if we've transitioned to follower and then *back* to pre-candidate, there's no other Term check in StepCandidate. We could accept a MsgPreVoteResp for term T as a valid pre-vote in term T+1.

File: raft/raft.go (hunk 1 above)
Comment (irfansharif) [inline raft/raft.go]: It isn't, it can be dropped as well. Rejecting it just puts the slower (previously partitioned) node into the candidate state (which would happen anyway when the faster node sends a MsgPreVote message with a higher term). 
As an aside, why do we just drop MsgVote messages with older terms instead of rejecting them directly?

File: raft/raft.go (hunk 2 above)
Comment (irfansharif) [inline raft/raft.go]: > there's no other Term check in StepCandidate

Isn't this then an existing problem for MsgVoteResp? We could accept granted MsgVoteResps from earlier elections? I see nothing in `raft.go: *raft.poll` that does this check.

File: raft/raft.go (hunk 1 above)
Comment (bdarnell) [inline raft/raft.go]: How does rejecting a message lead to a transition from pre-candidate to candidate? 

As for why we drop instead of reject MsgVotes with low terms, I don't think there's any deep reason for it. It's just easier to drop since we drop all other messages with lower terms.

File: raft/raft.go (hunk 2 above)
Comment (bdarnell) [inline raft/raft.go]: No, because they're dropped by this block (the term check at line 713). `Step` handles all messages from other terms, so that the `stepState` methods  can safely assume that the message is for the current term (with the exception of preVotes, which may have a higher term).

File: raft/raft.go (hunk 1 above)
Comment (irfansharif) [inline raft/raft.go]: Mistyped. Meant transition back to follower state.

File: raft/raft.go (hunk 2 above)
Comment (irfansharif) [inline raft/raft.go]: I see. Short of augmenting `pb.Message` I see no solution to this (unless I'm missing something). Say I have a three node cluster (A, B & C) where there is an asymmetric partition between A & C in that it C can _receive_ incoming messages but cannot deliver _outgoing_ ones to A. Consider the following:

- A campaigns, send out a MsgPreVote to C
- C responds with MsgPreVoteResp, doesn't deliver (yet)
- A returns back to follower state (B wins election)
   ...
- Timeout, A campaigns again (later term), sends out MsgPreVote to C
- C responds with _another_ MsgPreVoteResp, doesn't deliver (yet)
[partition heals]
- A receives two MsgPreVoteResp messagess, cannot distinguish which one is in response to which election. (This is because C doesn't change terms when it receives MsgPreVote messages, pb.Message.Term in each MsgPreVoteResp message is simply C's term when it received said message.)

Ignored is the fact that in this specific example with the three node cluster necessarily C's term has increased between the two messages. Point stands where we still have no good way to determine what election cycle each MsgPreVoteResp message is from.

Comment (bdarnell) [inline raft/raft.go]: It's true that there's an ambiguity in pre-votes - because they don't increment the term, two consecutive pre-vote election cycles look identical. But it's OK if there are (rare) false positives here - all that will happen is that we'll continue to a full election, which is slightly disruptive but will guarantee that only an up-to-date node can become the new leader.

Comment (irfansharif) [inline raft/raft.go]: To clarify, you're OK with granted MsgPreVoteResp messages from earlier election cycles count towards the total # votes needed to pass the PreVote phase? (With a comment to this effect of course).

Comment (bdarnell) [inline raft/raft.go]: Yeah. There are other possibilities for false positives too (for example, a node may grant pre-vote requests to two different nodes in the same term, but only one of them can win the real election).

**Comment by bdarnell** [comment]
When we send the MsgPreVoteResp at the end of r.Step, we use r.Term (which is out of date). This is the problem: the PreVoteResp is dropped because it is out of date when the (pre-)campaigning node receives it. Vote responses should use the term from the message, not the node's local term (these are the same for regular votes, but different for pre-votes).

**Comment by irfansharif** [comment]
PTAL.

File: raft/raft.go [hunk 3]
```diff
@@ -774,7 +775,24 @@ func (r *raft) Step(m pb.Message) error {
...
+			// When responding to Msg{Pre,}Vote messages we include the term
+			// from the message, not the local term. To see why consider the
+			// case where a single node was previously partitioned away and
+			// it's local term is now of date. If we include the local term
+			// (recall that for pre-votes we don't update the local term), the
+			// (pre-)campaigning node on the other end will proceed to ignore
+			// the message (it ignores all out of date messages).
+			// The term in the original message and current local term are the
+			// same in the case of regular votes, but different for pre-votes.
+			if m.Type == pb.MsgVote || m.Type == pb.MsgPreVote {
```
Comment (bdarnell) [inline raft/raft.go]: This condition is redundant, we're already in `case pb.MsgVote, pb.MsgPreVote:`.

Comment (irfansharif) [inline raft/raft.go]: whoops.

**Comment by xiang90** [comment]
LGTM. Thanks for fixing this!
