### PR TITLE
clientv3: use Endpoints[0] to initialize grpc creds

### LINKED ISSUE #8008: 3.2 Rc1 - Unable to connect using latest etcdctl
`etcdctl version: 3.2.0-rc.1+git`

We are running 3 member setup that's fronted with an Haproxy.  We have been using _LetsEncrypt_ for SSL which terminates at the haproxy.  I built the binaries against master for testing and noticed I wasn't able to connect any longer.

When specifying --debug, I get:
 `grpc: transport: http2Client.notifyError got notified that the client transport was broken EOF.`

I have a suspicion that it may be due to this PR.
https://github.com/coreos/etcd/pull/7687/files  

I would note, that I can connect just fine using earlier versions of `etcdctl`

Thoughts?

### PR DESCRIPTION
**Pull request by heyitsanthony**
Dialing out without specifying TLS creds but giving https uses some
default behavior that depends on passing an endpoint with https to
Dial(), so it's not enough to completely rely on the balancer to supply
endpoints.

Fixes #8008

### CODE REVIEW

File: clientv3/client.go [hunk 1]
```diff
@@ -367,7 +367,9 @@ func newClient(cfg *Config) (*Client, error) {
 	}
 
 	client.balancer = newSimpleBalancer(cfg.Endpoints)
-	conn, err := client.dial("", grpc.WithBalancer(client.balancer))
+	// use Endpoints[0] so that for https:// without any tls config given, then
+	// grpc will assume the ServerName is in the endpoint.
+	conn, err := client.dial(cfg.Endpoints[0], grpc.WithBalancer(client.balancer))
```
Comment (gyuho) [inline clientv3/client.go]: This should fix this wrong-parameter client endpoints here https://github.com/coreos/etcd/issues/7807.
Not the root cause, though, which I assume is from Go runtime or OS.

Comment (heyitsanthony) [inline clientv3/client.go]: This is a 3.2 regression, though; the `Endpoints[0]` bit is in 3.1
