### PR TITLE
*: allow dbSizeInUse not to equal to dbSize when growing

### LINKED ISSUE #9302: TestMetricDbSizeDefrag fails in proxy test mode
```
--- FAIL: TestMetricDbSizeDefrag (2.51s)
	metrics_test.go:84: when db size is growing, db size (196608) and db size in use (192512) is expected to be equal
```

https://jenkins-etcd.prod.coreos.systems/job/etcd-proxy/4091/console

in proxy tests

### PR DESCRIPTION
**Pull request by yudai**
Due to boltdb behavior, dbSizeInUse can be unequal to dbSize even when
dbSize is growing in some conditions. The possible gap between the sizes
is up to a couple of pages.

Closes #9302

### CODE REVIEW

File: integration/metrics_test.go [hunk 1]
```diff
@@ -80,8 +82,8 @@ func TestMetricDbSizeDefrag(t *testing.T) {
 	if err != nil {
 		t.Fatal(err)
 	}
-	if biu != bv {
-		t.Fatalf("when db size is growing, db size (%d) and db size in use (%d) is expected to be equal", bv, biu)
+	if biu < expected {
+		t.Fatalf("expected db size in use is grater than %d, got %d", expected, biu)
```
Comment (hexfusion) [inline integration/metrics_test.go]: s/grater/greater

Comment (yudai) [reply integration/metrics_test.go]: thanks. Fixed

**Comment by yudai** [comment]
retest this please
(hope this works)
