### PR TITLE
etcdmain: stop accepting client conns when it reachs limit

### LINKED ISSUE #2477: etcd fatal because it has no file descriptor to open WAL/snapshot
This happens in several situations:
1.
(a) etcd listens on the port, but has not started to serving
(b) client requests eat up all file descriptors
(c) etcd fails to open WAL and fatal
2.
(a) etcd is running
(b) client requests eat up all file descriptors
(c) etcd fails to save snapshot and fatal

This is met by functional tests and #2471

### PR DESCRIPTION
**Pull request by yichengq**
This solves the problem that etcd may fatal because its critical path
cannot get file descriptor resource when the number of clients is too
big. The PR lets the client listener stop accepting connections when
the file descriptor usage in the process reaches some pre-set limit, so
it ensures that the internal critical path could always get file
descriptor when it needs.

Client which arrives after the listener hits the limit is queued at the
kernel. For more details, you could check `man listen`.

When there are tons to clients connecting to the server, the original
behavior is like this:

```
2015/08/4 16:42:08 etcdserver: cannot monitor file descriptor usage
(open /proc/self/fd: too many open files)
2015/08/4 16:42:33 etcdserver: failed to purge snap file open
default2.etcd/member/snap: too many open files
[halted]
```

Current behavior is like this:

```
2015/08/4 17:39:29 etcdserver: 80% of the file descriptor limit is used
[used = 974, limit = 1024]
```

It is available at linux system today because pkg/runtime only has linux
support.

fixes #2477

### CODE REVIEW

File: pkg/transport/limited_conn_listener.go [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+func (l *LimitedConnListener) Accept() (net.Conn, error) {
+	for {
+		n, err := runtime.FDUsage()
+		if err != nil {
+			break
+		}
+		if n < l.RuntimeFDLimit {
+			break
+		}
+		time.Sleep(10 * time.Millisecond)
```
Comment (xiang90) [inline pkg/transport/limited_conn_listener.go]: i think we can simply deny the request.

File: etcdmain/etcd.go [hunk 2]
```diff
@@ -188,6 +201,9 @@ func startEtcd(cfg *config) (<-chan struct{}, error) {
 		if err != nil {
 			return nil, err
 		}
+		if fdLimit, err := runtimeutil.FDLimit(); err == nil {
+			l = &transport.LimitedConnListener{Listener: l, RuntimeFDLimit: fdLimit - reservedInternalFDNum}
```
Comment (xiang90) [inline etcdmain/etcd.go]: you need to make sure fdLimit is greater than reservedInternalFdNum

File: pkg/transport/limited_conn_listener.go (hunk 1 above)
Comment (yichengq) [inline pkg/transport/limited_conn_listener.go]: It is doable and the deny becomes a Do() error on the client side.

**Comment by yichengq** [comment]
Change the behavior to reject connections directly. PTAL

File: pkg/transport/limited_conn_listener.go [hunk 3]
```diff
@@ -0,0 +1,46 @@
...
+
+func (l *LimitedConnListener) Accept() (net.Conn, error) {
+	for {
+		conn, err := l.Listener.Accept()
+		if err != nil {
+			return nil, err
+		}
+
+		n, err := runtime.FDUsage()
+		if err != nil {
```
Comment (xiang90) [inline pkg/transport/limited_conn_listener.go]: add a comment for this behavior. (why do we ignore the error)

File: pkg/transport/limited_conn_listener.go [hunk 4]
```diff
@@ -0,0 +1,46 @@
...
+	"github.com/coreos/etcd/pkg/runtime"
+)
+
+type LimitedConnListener struct {
+	net.Listener
+	RuntimeFDLimit uint64
+}
+
+func (l *LimitedConnListener) Accept() (net.Conn, error) {
+	for {
```
Comment (xiang90) [inline pkg/transport/limited_conn_listener.go]: why do we still need the for loop?

File: pkg/transport/limited_conn_listener.go [hunk 5]
```diff
@@ -0,0 +1,46 @@
...
+		conn, err := l.Listener.Accept()
```
Comment (xiang90) [inline pkg/transport/limited_conn_listener.go]: shouldn't we check the limitation first then try to accept?

Comment (yichengq) [inline pkg/transport/limited_conn_listener.go]: This is not a problem because: Accept is called one after one, so it could take one fd only. And the listener closes conn even if fdUsage == RuntimeFDLimit, so it is fine.

We plan to reject the connection, so it needs to be accepted first.

File: pkg/transport/limited_conn_listener.go (hunk 4 above)
Comment (yichengq) [inline pkg/transport/limited_conn_listener.go]: The Accept should always return a valid connection and nil error, or some error. And http.Server.Serve() uses this assumption: https://golang.org/src/net/http/server.go#L1724

Accept is supposed to wait for the next call and return a general conn, so it is reasonable for it to be blocked.

File: pkg/transport/limited_conn_listener.go (hunk 5 above)
Comment (xiang90) [inline pkg/transport/limited_conn_listener.go]: ok.

File: pkg/transport/limited_conn_listener.go (hunk 4 above)
Comment (xiang90) [inline pkg/transport/limited_conn_listener.go]: We should return a temp error.

**Comment by yichengq** [comment]
updated.

**Comment by xiang90** [comment]
LGTM
