### PR TITLE
etcdctl: return exitcode 2 if can't connect to any peer urls

### LINKED ISSUE #4053: etcdctl returns 4 instead of 2 even though cluster is not reachable
```
core@infra0 ~ $ etcdctl --peers http://xxx:2379 --endpoint http://xxx:2379 get test123
Error:  client: etcd cluster is unavailable or misconfigured
error #0: dial tcp: lookup xxx: No address associated with hostname
```

```
core@infra0 ~ $ echo $?
4
```

etcdctl version 2.2.0

### PR DESCRIPTION
**Pull request by heyitsanthony**
Fixes #4053

### CODE REVIEW

**Comment by gyuho** [comment]
LGTM.

**Comment by xiang90** [comment]
Actually I have some other thoughts on this pull request. I will comment soon.

File: etcdctl/command/util.go [hunk 1]
```diff
@@ -213,9 +213,13 @@ func mustNewClient(c *cli.Context) client.Client {
 
 			// fail-back to try sync cluster with peer API. this is for making etcdctl work with etcd 0.4.x.
 			// TODO: remove this when we deprecate the support for etcd 0.4.
-			eps, serr := syncWithPeerAPI(c, ctx, hc.Endpoints())
-			if serr != nil {
-				handleError(ExitServerError, serr)
+			eps, trerr, serr := syncWithPeerAPI(c, ctx, hc.Endpoints())
```
Comment (xiang90) [inline etcdctl/command/util.go]: this is the backward compatibility path. If the original error is not client.ErrNoEndpoints, we probably should also exit with badconnection.

File: etcdctl/command/util.go [hunk 2]
```diff
@@ -286,10 +290,10 @@ func contextWithTotalTimeout(c *cli.Context) (context.Context, context.CancelFun
 // syncWithPeerAPI syncs cluster with peer API defined at
 // https://github.com/coreos/etcd/blob/v0.4.9/server/server.go#L311.
 // This exists for backward compatibility with etcd 0.4.x.
-func syncWithPeerAPI(c *cli.Context, ctx context.Context, knownPeers []string) ([]string, error) {
-	tr, err := getTransport(c)
-	if err != nil {
-		return nil, err
+func syncWithPeerAPI(c *cli.Context, ctx context.Context, knownPeers []string) (eps []string, trerr error, serr error) {
```
Comment (xiang90) [inline etcdctl/command/util.go]: I feel the error returned by this function are all connection error. Then only possible server error is that the returned eps cannot be parsed (not valid endpoints)

File: etcdctl/command/util.go [hunk 3]
```diff
@@ -213,9 +213,13 @@ func mustNewClient(c *cli.Context) client.Client {
 
 			// fail-back to try sync cluster with peer API. this is for making etcdctl work with etcd 0.4.x.
 			// TODO: remove this when we deprecate the support for etcd 0.4.
-			eps, serr := syncWithPeerAPI(c, ctx, hc.Endpoints())
-			if serr != nil {
-				handleError(ExitServerError, serr)
+			eps, trerr, serr := syncWithPeerAPI(c, ctx, hc.Endpoints())
+			if eps == nil {
+				if serr != nil {
```
Comment (xiang90) [inline etcdctl/command/util.go]: 0.4 errors should not overwrite 2.0 ones. If 0.4 syncWithPeerAPI succeeds, then it is good. If it fails, we should parse the old error with the assumption that the cluster is a 2.0 one.

File: etcdctl/command/util.go (hunk 2 above)
Comment (heyitsanthony) [inline etcdctl/command/util.go]: If it's pointed at a server that doesn't understand the request or the read is abnormally terminated, it should give "failed to connect" instead of giving a 400 error? Is "failed to connect to host" a failure to connect to an etcd server or is it a failure to connect to a server in general?

**Comment by heyitsanthony** [comment]
reworked this patch so it's less invasive w/r/t v0.4 fallback logic, /cc @xiang90

File: etcdctl/command/util.go [hunk 4]
```diff
@@ -211,6 +211,12 @@ func mustNewClient(c *cli.Context) client.Client {
...
 
+			if cerr, ok := err.(*client.ClusterError); ok {
+				if cerr.IsBadConnection() {
+					handleError(ExitBadConnection, err)
+				}
+			}
+
 			// fail-back to try sync cluster with peer API. this is for making etcdctl work with etcd 0.4.x.
 			// TODO: remove this when we deprecate the support for etcd 0.4.
 			eps, serr := syncWithPeerAPI(c, ctx, hc.Endpoints())
```
Comment (xiang90) [inline etcdctl/command/util.go]: let's also check the serr here?

File: client/cluster_error.go [hunk 5]
```diff
@@ -31,3 +36,31 @@ func (ce *ClusterError) Detail() string {
...
+
+// IsBadConnection returns true if all the Errors are related to failure
+// to connect to servers.
+func (ce *ClusterError) IsBadConnection() bool {
+	for _, err := range ce.Errors {
+		switch typedErr := (err).(type) {
+		case *net.OpError:
+			switch opErr := (typedErr.Err).(type) {
+			case *net.DNSError:
+				// couldn't resolve name
```
Comment (xiang90) [inline client/cluster_error.go]: fall through? go case will not fall through by default

File: etcdctl/command/util.go (hunk 4 above)
Comment (heyitsanthony) [inline etcdctl/command/util.go]: `serr` already gets checked on the line following `syncWithPeer`

File: client/cluster_error.go (hunk 5 above)
Comment (heyitsanthony) [inline client/cluster_error.go]: added some `continues` to make flow clearer

File: etcdctl/command/util.go (hunk 4 above)
Comment (heyitsanthony) [inline etcdctl/command/util.go]: added bad connection check after `syncWithPeerAPI` in case connections went down between first try and fallback

File: etcdctl/command/util.go [hunk 6]
```diff
@@ -211,10 +211,18 @@ func mustNewClient(c *cli.Context) client.Client {
...
+			if cerr, ok := err.(*client.ClusterError); ok && cerr.IsBadConnection() {
+				handleError(ExitBadConnection, err)
+			}
+
 			// fail-back to try sync cluster with peer API. this is for making etcdctl work with etcd 0.4.x.
 			// TODO: remove this when we deprecate the support for etcd 0.4.
 			eps, serr := syncWithPeerAPI(c, ctx, hc.Endpoints())
 			if serr != nil {
+				// connections might go down when retrying for etcd 0.4
+				if cerr, ok := serr.(*client.ClusterError); ok && cerr.IsBadConnection() {
```
Comment (xiang90) [inline etcdctl/command/util.go]: we do not need the assertion here. this will return a normal error from standard http library: https://github.com/coreos/etcd/blob/master/etcdctl/command/util.go#L319.

Comment (xiang90) [inline etcdctl/command/util.go]: probably we need to add another function like `isConnectionError(err error) bool`.

**Comment by xiang90** [comment]
This does not seem like a very reliable way to detect a connection error, but better than what it is today.

File: client/cluster_error.go [hunk 7]
```diff
@@ -31,3 +36,39 @@ func (ce *ClusterError) Detail() string {
 	}
 	return s
 }
+
+// IsBadConnection returns true if all the Errors are related to failure
+// to connect to servers.
+// TODO: find a more reliable way to detect this
+func (ce *ClusterError) IsBadConnection() bool {
+	for _, err := range ce.Errors {
+		switch typedErr := (err).(type) {
```
Comment (xiang90) [inline client/cluster_error.go]: switch typeErr := err.(type) should be good enough?

File: client/cluster_error.go [hunk 8]
```diff
@@ -31,3 +36,39 @@ func (ce *ClusterError) Detail() string {
...
+			case *net.DNSError:
+				// couldn't resolve name
+				continue
+			case *os.SyscallError:
+				if strings.Contains(opErr.Error(), "connection refused") {
+					// port not open
+					continue
+				}
+				return false
+			default:
```
Comment (xiang90) [inline client/cluster_error.go]: I am not sure if timeout should also count as a connection error. we can try net.OpError.Timeout()?

File: client/cluster_error.go [hunk 9]
```diff
@@ -31,3 +36,39 @@ func (ce *ClusterError) Detail() string {
...
+				// error unrelated to connecting
+				return false
+			}
+		default:
+			// in case passed a errors.errorString
+			if strings.Contains(err.Error(), "exceeded header timeout") {
```
Comment (xiang90) [inline client/cluster_error.go]: there might be a context timeout too.  `context deadline exceeded`

Comment (xiang90) [inline client/cluster_error.go]: not sure if we should count that for a bad connection though.

**Comment by xiang90** [comment]
My general feeling is that we should probably not distinguish connection error in the next version of etcdctl for etcd3.

**Comment by heyitsanthony** [comment]
simplified a bit; this one should be the best one yet /cc xiang90

**Comment by xiang90** [comment]
LGTM
