### PR TITLE
etcdmain: improve log when join discovery fails

### LINKED ISSUE #3423: discovery fails with 'etcdmain: client: etcd cluster is unavailable or misconfigured'
see gist: https://gist.githubusercontent.com/iancoffey/6ef42f03eede2a7ba635/raw/e10728223b2e0b13b88913b478674e386f5fb8ba/gistfile1.txt

I think it happens due to the TODO here: https://github.com/coreos/etcd/blob/master/discovery/discovery.go#L160

### PR DESCRIPTION
**Pull request by yichengq**
[Updated]

Before this PR, the log is

```
2015/09/1 13:18:31 etcdmain: client: etcd cluster is unavailable or
misconfigured
```

It is quite hard for people to understand what happens.

Now we print out the exact reason for the failure, and explains the way
to handle it.

```
2015-09-28 23:22:49.080239 E | etcdmain: failed to join discovery cluster (client: etcd cluster is unavailable or misconfigured)
2015-09-28 23:22:49.080245 I | etcdmain: discovery token http://localhost:5001/v2 was used, but failed to bootstrap the cluster.
2015-09-28 23:22:49.080250 I | etcdmain: please generate a new discovery token and try to bootstrap again.
```

fixes #3423

### CODE REVIEW

File: etcdserver/server.go [hunk 1]
```diff
@@ -247,7 +247,7 @@ func NewServer(cfg *ServerConfig) (*EtcdServer, error) {
 			var err error
 			str, err = discovery.JoinCluster(cfg.DiscoveryURL, cfg.DiscoveryProxy, m.ID, cfg.InitialPeerURLsMap.String())
 			if err != nil {
-				return nil, err
+				return nil, fmt.Errorf("error joining discovery cluster (%v)", err)
```
Comment (xiang90) [inline etcdserver/server.go]: can we define an error string here?

File: etcdmain/etcd.go [hunk 2]
```diff
@@ -160,6 +160,12 @@ func Main() {
 				}
 				os.Exit(1)
 			}
+			if strings.Contains(err.Error(), "error joining discovery cluster") {
+				plog.Errorf("%v", err)
+				plog.Infof("Please check that discovery service functions well,")
```
Comment (xiang90) [inline etcdmain/etcd.go]: one line with 165?

Comment (xiang90) [inline etcdmain/etcd.go]: or there might be a connection issue with the discovery service?

File: etcdserver/server.go (hunk 1 above)
Comment (yichengq) [inline etcdserver/server.go]: I want to display the exact reason that joining cluster failed, so people could dig into it. Do you mention to define the constant part `error joining discovery cluster` as an error string?

Comment (xiang90) [inline etcdserver/server.go]: yes. then the String.contains part will be more clear. Or we can actually have a function called IsDiscoveryError in discovery pkg.

File: etcdmain/etcd.go (hunk 2 above)
Comment (yichengq) [inline etcdmain/etcd.go]: Originally i thought that users should know about this through the error message. Will improve.

**Comment by yichengq** [comment]
Updated. PTAL

File: etcdmain/etcd.go [hunk 3]
```diff
@@ -160,6 +160,12 @@ func Main() {
 				}
 				os.Exit(1)
 			}
+			if etcdserver.IsDiscoveryError(err) {
+				plog.Errorf("%v", err)
+				plog.Infof("Interaction with discovery service failed, possibly due to connection down.")
```
Comment (xiang90) [inline etcdmain/etcd.go]: I think all we need to say here is that this discovery failed and you have to generate a new token rather than reuse the old one.

Comment (yichengq) [inline etcdmain/etcd.go]: sure. changed.

**Comment by yichengq** [comment]
updated. The first sentence talks about current situation caused by the error, and the second sentence talked about the method to handle the error.

**Comment by xiang90** [comment]
LGTM
