### PR TITLE
*: fix a bug in handling unix socket urls

### LINKED ISSUE #7644: etcd handles unix socket url wrongly, and may cleanup current directory
Since that:

- https://github.com/coreos/etcd/blob/2724c3946eb2f3def5ed38a127be982b62c81779/pkg/transport/unix_listener.go#L25
- https://github.com/coreos/etcd/blob/2724c3946eb2f3def5ed38a127be982b62c81779/pkg/transport/unix_listener.go#L36

use ``os.ReamoveAll()`` to cleanup socket file before listening and closing.

And:

``u.Host`` is used to denote the unix socket path.

When I pass a bad url like ``unix://./localhost.2333``, etcd will try to open socket file at `.`. Normally, this will be the deployment directory, definitely fails. ``os.RemoveAll`` will cleanup my deployment directory.

:(

Possible fix: 

- DO NOT use ``os.RemoveAll()``
- use host+path as unix socket path

ref: https://golang.org/doc/go1.8

> Following RFC 3986, Parse now rejects URLs like this_that:other/thing instead of interpreting them as relative paths (this_that is not a valid scheme). To force interpretation as a relative path, such URLs should be prefixed with “./”. The URL.String method now inserts this prefix as needed.

### PR DESCRIPTION
**Pull request by andelf**
Now use url.Host + url.Path as unix socket path

Fixes #7644

Related: https://github.com/pingcap/pd/issues/595

### CODE REVIEW

File: pkg/transport/unix_listener.go [hunk 1]
```diff
@@ -17,12 +17,13 @@ package transport
...
 	"net"
 	"os"
+	"strings"
 )
 
 type unixListener struct{ net.Listener }
 
 func NewUnixListener(addr string) (net.Listener, error) {
-	if err := os.RemoveAll(addr); err != nil {
+	if err := safeRemove(addr); err != nil {
```
Comment (heyitsanthony) [inline pkg/transport/unix_listener.go]: `if err := os.Remove(addr); err != nil && !os.IsNotExist(err)`

File: pkg/transport/unix_listener.go [hunk 2]
```diff
@@ -33,8 +34,17 @@ func NewUnixListener(addr string) (net.Listener, error) {
 }
 
 func (ul *unixListener) Close() error {
-	if err := os.RemoveAll(ul.Addr().String()); err != nil {
+	if err := safeRemove(ul.Addr().String()); err != nil {
```
Comment (heyitsanthony) [inline pkg/transport/unix_listener.go]: if err := os.Remove(addr); err != nil && !os.IsNotExist(err)

**Comment by heyitsanthony** [comment]
thanks for finding/fixing this

**Comment by heyitsanthony** [comment]
Please squash the commits and this should be good to merge. Thanks!

File: pkg/transport/unix_listener.go [hunk 3]
```diff
@@ -22,7 +22,7 @@ import (
 type unixListener struct{ net.Listener }
 
 func NewUnixListener(addr string) (net.Listener, error) {
-	if err := os.RemoveAll(addr); err != nil {
+	if err := os.Remove(addr); err != nil && !os.IsNotExist(err) {
```
Comment (fanminshi) [inline pkg/transport/unix_listener.go]: why not use `os.IsExist()` function here?

Comment (heyitsanthony) [inline pkg/transport/unix_listener.go]: For example?

Comment (fanminshi) [inline pkg/transport/unix_listener.go]: `!os.IsNotExist(err)` is same as `os.IsExist(err)`?

Comment (heyitsanthony) [inline pkg/transport/unix_listener.go]: No. `os.IsNotExist(err)` is true if and only if the file to delete doesn't exist. `!os.IsExist(err)` would be true if and only if the operation failed for a reason other than the file existing (e.g., it would be true if the file did not exist). They're not interchangeable.

Comment (fanminshi) [inline pkg/transport/unix_listener.go]: make sense. ty.

File: embed/etcd.go [hunk 4]
```diff
@@ -257,19 +257,21 @@ func startClientListeners(cfg *Config) (sctxs map[string]*serveCtx, err error) {
 		}
 
 		proto := "tcp"
+		addr := u.Host
 		if u.Scheme == "unix" || u.Scheme == "unixs" {
 			proto = "unix"
+			addr = u.Host + u.Path
```
Comment (fanminshi) [inline embed/etcd.go]: should you also update `sctxs` with `addr` too? https://github.com/coreos/etcd/blob/master/embed/etcd.go#L306

Comment (andelf) [inline embed/etcd.go]: ???

Comment (heyitsanthony) [inline embed/etcd.go]: https://github.com/coreos/etcd/pull/7646/files#diff-d7a47eb75475dba263540eb7f8456e50R308 should be `sctxs[addr] = sctx`?

**Comment by fanminshi** [comment]
lgtm

File: embed/etcd.go (hunk 4 above)
Comment (andelf) [inline embed/etcd.go]: ok, fixed
