### PR TITLE
pkg/testutil: ForceGosched -> WaitSchedule

### LINKED ISSUE #2936: data race in TestApplySnapshotAndCommittedEntries
```
==================
WARNING: DATA RACE
Write by goroutine 12:
  github.com/coreos/etcd/etcdserver.(*raftNode).run()
      github.com/coreos/etcd/etcdserver/_test/_obj_test/raft.go:90 +0x9d
Previous read by goroutine 11:
  github.com/coreos/etcd/etcdserver.func·003()
      github.com/coreos/etcd/etcdserver/_test/_obj_test/server.go:472 +0x7e
  github.com/coreos/etcd/etcdserver.(*EtcdServer).run()
      github.com/coreos/etcd/etcdserver/_test/_obj_test/server.go:556 +0x171d
Goroutine 12 (running) created at:
  github.com/coreos/etcd/etcdserver.(*EtcdServer).run()
      github.com/coreos/etcd/etcdserver/_test/_obj_test/server.go:469 +0x338
Goroutine 11 (running) created at:
  github.com/coreos/etcd/etcdserver.(*EtcdServer).start()
      github.com/coreos/etcd/etcdserver/_test/_obj_test/server.go:386 +0x58f
  github.com/coreos/etcd/etcdserver.TestApplySnapshotAndCommittedEntries()
      /home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server_test.go:821 +0x614
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:447 +0x133
==================
panic: test timed out after 3m0s
goroutine 75 [running]:
testing.func·008()
	/usr/local/go/src/testing/testing.go:681 +0x168
created by time.goFunc
	/usr/local/go/src/time/sleep.go:129 +0x59
goroutine 1 [chan receive]:
testing.RunTests(0xaebf78, 0x16020c0, 0x35, 0x35, 0xc208068201)
	/usr/local/go/src/testing/testing.go:556 +0xdc3
testing.(*M).Run(0xc20806a320, 0x160cc60)
	/usr/local/go/src/testing/testing.go:485 +0xe1
main.main()
	github.com/coreos/etcd/etcdserver/_test/_testmain.go:218 +0x382
goroutine 86 [chan send (nil chan)]:
github.com/coreos/etcd/etcdserver.func·003()
	github.com/coreos/etcd/etcdserver/_test/_obj_test/server.go:472 +0xa9
github.com/coreos/etcd/etcdserver.(*EtcdServer).run(0xc208167440)
	github.com/coreos/etcd/etcdserver/_test/_obj_test/server.go:556 +0x171e
created by github.com/coreos/etcd/etcdserver.(*EtcdServer).start
	github.com/coreos/etcd/etcdserver/_test/_obj_test/server.go:386 +0x58f
goroutine 85 [chan receive]:
github.com/coreos/etcd/etcdserver.(*EtcdServer).Stop(0xc208167440)
	github.com/coreos/etcd/etcdserver/_test/_obj_test/server.go:571 +0x188
github.com/coreos/etcd/etcdserver.TestApplySnapshotAndCommittedEntries(0xc208138900)
	/home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server_test.go:831 +0x85c
testing.tRunner(0xc208138900, 0x16024c8)
	/usr/local/go/src/testing/testing.go:447 +0x134
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:555 +0xd4e
goroutine 87 [select]:
github.com/coreos/etcd/etcdserver.(*raftNode).run(0xc208167450)
	github.com/coreos/etcd/etcdserver/_test/_obj_test/raft.go:128 +0xd9b
created by github.com/coreos/etcd/etcdserver.(*EtcdServer).run
	github.com/coreos/etcd/etcdserver/_test/_obj_test/server.go:469 +0x338
FAIL	github.com/coreos/etcd/etcdserver	180.023s
```

### PR DESCRIPTION
**Pull request by yichengq**
ForceGosched() performs bad when GOMAXPROCS>1. When GOMAXPROCS=1, it
could promise that other goroutines run long enough to the block point
because it always yield the processor to other goroutines. But it cannot
yield processor to goroutine running on other processors. So when
GOMAXPROCS>1, the yield may finish when goroutine running on the other
processor has not run to block point.

Here is a test to confirm the case:

```
package main

import (
	"fmt"
	"runtime"
	"testing"
)

func ForceGosched() {
	// possibility enough to sched up to 10 go routines.
	for i := 0; i < 10000; i++ {
		runtime.Gosched()
	}
}

var d int

func loop(c chan struct{}) {
	for {
		select {
		case <-c:
			for i := 0; i < 1000; i++ {
				fmt.Sprintf("come to time %d", i)
			}
			d++
		}
	}
}

func TestLoop(t *testing.T) {
	c := make(chan struct{}, 1)
	go loop(c)
	c <- struct{}{}
	ForceGosched()
	if d != 1 {
		t.Fatal("d is not incremented")
	}
}
```

`go test -v -race` runs well, but `GOMAXPROCS=2 go test -v -race` fails.

Change the functionality to waiting for other goroutines to be blocked.

fixes #2936 #2935 

/cc @jonboulle

### CODE REVIEW

**Comment by xiang90** [comment]
@yichengq Unfortunately, this does not seem to fix everything. The test is still failing.

File: pkg/testutil/testutil.go [hunk 1]
```diff
@@ -17,15 +17,33 @@ package testutil
...
+	"time"
 )
 
-// WARNING: This is a hack.
-// Remove this when we are able to block/check the status of the go-routines.
-func ForceGosched() {
-	// possibility enough to sched up to 10 go routines.
-	for i := 0; i < 10000; i++ {
-		runtime.Gosched()
+func runnableGoroutineNumber() int {
```
Comment (xiang90) [inline pkg/testutil/testutil.go]: without a comment, i have no idea how this works (why split by \n\n, etc.).

and i am wondering if there is a simpler way.

Comment (yichengq) [inline pkg/testutil/testutil.go]: comment added. It refers the net pkg test function: https://github.com/golang/go/blob/b016eba489820b9091e4f39610a84f697d8eb0f9/src/net/http/main_test.go#L26

I have browsed through the runtime library and find no luck. Hopefully go will expose the state of goroutines explicitly.

**Comment by yichengq** [comment]
still dig into the left failure. That failure is not related to this PR in high probability because the failed test doesn't call ForceGosched func.

**Comment by xiang90** [comment]
@yichengq Can we simply lock the os thread to fix the issue? we simply want to sched to another running routine.

File: pkg/testutil/testutil.go (hunk 1 above)
Comment (jonboulle) [inline pkg/testutil/testutil.go]: FWIW @yichengq this is the same approach I would have taken. It sucks. ;-)

Comment (xiang90) [inline pkg/testutil/testutil.go]: @jonboulle This is a too heavy solution in my opinion. We basically only wants to switch to another routine and let it run for a while... We do not need to wait until all routines to be blocked.

Comment (jonboulle) [inline pkg/testutil/testutil.go]: I agree but I just don't know of any other way to get the level of introspection. My alternative/initial suggestion to Yicheng was to inject another dummy channel into all the potential blocking points that is used only in tests.

Comment (xiang90) [inline pkg/testutil/testutil.go]: @jonboulle My suggestion is to simply sleep for 5ms for now... There is basically no simple way to do it (or the effort might not worth the outcome). And we have been trying too hard to solve it with some hacks.

**Comment by yichengq** [comment]
Change it to simple sleep per xiang's suggestion. This is the simplest way to make the hack, and it works on local and travis.

The LockOSThread is not a good solution because it is not used for schedule.

File: pkg/testutil/testutil.go [hunk 2]
```diff
@@ -16,17 +16,13 @@ package testutil
...
-// WARNING: This is a hack.
-// Remove this when we are able to block/check the status of the go-routines.
-func ForceGosched() {
-	// possibility enough to sched up to 10 go routines.
-	for i := 0; i < 10000; i++ {
-		runtime.Gosched()
-	}
+// TODO: improve this when we are able to know the schedule or status of target go-routine.
+func WaitSchedule() {
+	time.Sleep(time.Millisecond)
```
Comment (xiang90) [inline pkg/testutil/testutil.go]: we know 1ms works. but can we set it to 3 ms for safety?

Comment (yichengq) [inline pkg/testutil/testutil.go]: sure

**Comment by xiang90** [comment]
LGTM
