### PR TITLE
etcd/auth: fix range handling bugs.

### LINKED ISSUE #6359: etcdctl/ctlv3: auth: how to create /home/ directory ?
Related to the wilcard '*' discussion on #6355 #5896:

I have a set of clients. I would like to give each a /home/ sub-directory, so that they may write and read in their home directory. They should be able to read other people's home directories, but not write. For example:

```
/home/jason
/home/xiang
/home/hitoshi
```

So the permissions I would like to grant to each of my users would be:

role `user` can read on `/home/*`

while individual users can write on `/home/$USER/*`, where $USER is the current user.
I would be fine, if really necessary, with creating a new role for each user,
in order to assign that role the write permission, for example: role jason would have write permission on `/home/jason/*`. This does seem a little tedious though.

I am simply organizing my client-server communication using a model
that most users will be familiar with. Namely, the unix file system /home/
directory conventions.

Without `*` wildcard support, I don't see a way to do this. Could you
suggest a workaround, or consider implementing `*` wildcard support?

### PR DESCRIPTION
**Pull request by glycerine**
As discussed in #6359, I found some range handling
bugs and fixed them while looking at how to add
prefix based auth. I had a few minutes and put
together this cherry picked pr that contains only
the bug fixes, and no prefix expansion.

Test 15, counting from zero, in TestGetMergedPerms
in etcd/auth/range_perm_cache_test.go, was trying
incorrectly assert that [a, b) merged with [b, "")
should be [a, b). Added a test specifically for
this. This patch also fixes the incorrect larger test
and the bugs in the code that it was hiding.

Fixes #6359

### CODE REVIEW

File: auth/range_perm_cache.go [hunk 1]
```diff
@@ -22,19 +22,24 @@ import (
...
+// Given intervals [a1,a2) and [b1,b2), is
+// the a interval a subset of b?
 func isSubset(a, b *rangePerm) bool {
 	switch {
 	case len(a.end) == 0 && len(b.end) == 0:
 		// a, b are both keys
 		return bytes.Equal(a.begin, b.begin)
 	case len(b.end) == 0:
-		// b is a key, a is a range
+		// b is a key, a is a range (even a prefix range has infinite membership)
```
Comment (mitake) [inline auth/range_perm_cache.go]: Maybe the part `(even a prefix range has infinite membership)` is outdated?

**Comment by mitake** [comment]
Thanks a lot! I commented on two points which would need to be fixed.

**Comment by mitake** [comment]
Also, please update the commit log title to `auth: fix range handling bugs`.

File: auth/range_perm_cache_test.go [hunk 2]
```diff
@@ -123,7 +127,7 @@ func TestGetMergedPerms(t *testing.T) {
 	for i, tt := range tests {
 		result := mergeRangePerms(tt.params)
 		if !isPermsEqual(result, tt.want) {
-			t.Errorf("#%d: result=%q, want=%q", i, result, tt.want)
+			t.Fatalf("#%d: result=%q, want=%q", i, result, tt.want)
```
Comment (xiang90) [inline auth/range_perm_cache_test.go]: we should change back to errorf. if there is one case fails, we should continue to execute the next case. then we can detect multiple failures in one round of test.

**Comment by jaten-saucelabs** [comment]
all requested updates were made.

**Comment by glycerine** [comment]
all requested updates done.

**Comment by xiang90** [comment]
lgtm

**Comment by xiang90** [comment]
@glycerine Thanks a lot!

**Comment by mitake** [comment]
@glycerine thanks!
