### PR TITLE
clientv3/integration: fix TestKVPutStoppedServerAndClose

### LINKED ISSUE #6252: test: TestKVPutStoppedServerAndClose
```
--- FAIL: TestKVPutStoppedServerAndClose (0.14s)
	kv_test.go:663: rpc error: code = 13 desc = transport: write unix @->localhost:node2889073888245090141.sock.bridge: write: broken pipe
```

### PR DESCRIPTION
**Pull request by xiang90**
Fix #6252

### CODE REVIEW

**Comment by xiang90** [comment]
@heyitsanthony PTAL

File: clientv3/integration/kv_test.go [hunk 1]
```diff
@@ -648,16 +648,47 @@ func TestKVGetCancel(t *testing.T) {
 	}
 }
 
+// TestKVPutStoppedServerAndClose ensures closing after a failed Get works.
```
Comment (heyitsanthony) [inline clientv3/integration/kv_test.go]: s/PutStopped/GetStopped

**Comment by heyitsanthony** [comment]
lgtm
