### PR TITLE
etcdserver: initialize raftNode with constructor

### LINKED ISSUE #7668: TestSpeedyTerminate: cluster took too long to terminate
via https://semaphoreci.com/coreos/etcd/branches/master/builds/1756
```
--- FAIL: TestSpeedyTerminate (10.23s)
	cluster_test.go:587: cluster took too long to terminate
```

looks like there are a few more places that need etcdserver.ctx

### PR DESCRIPTION
**Pull request by heyitsanthony**
raftNode was being initialized in start(), which was causing
hangs when trying to stop the etcd server since the stop channel
would not be initialized in time for the stop call. Instead,
setup non-configurable bits in a constructor.

Fixes #7668

### CODE REVIEW

File: etcdserver/raft.go [hunk 1]
```diff
@@ -94,14 +94,7 @@ type raftNode struct {
 	term  uint64
 	lead  uint64
 
-	mu sync.Mutex
-	// last lead elected time
-	lt time.Time
```
Comment (xiang90) [inline etcdserver/raft.go]: why do we need to move this variable around in this pr?

Comment (heyitsanthony) [inline etcdserver/raft.go]: Copying the structure around copies the mutex which causes the static checks to complain.

**Comment by xiang90** [comment]
lgtm
