### PR TITLE
etcdserver: not apply stale conf change

### LINKED ISSUE #2437: panic on removing unknown peer
The cluster doesn't have that peer when apply remove confchange.
This is because it gets the latest info from the remote peer instead of recovering from the snapshot, which may be have smaller index.

```
docker[7011]: 2015/03/04 21:49:14 etcd: listening for peers on http://10.0.0.39:7001
docker[7011]: 2015/03/04 21:49:14 etcd: listening for client requests on http://10.0.0.39:4001
docker[7011]: 2015/03/04 21:49:14 etcd: listening for client requests on http://127.0.0.1:4001
docker[7011]: 2015/03/04 21:49:14 etcdserver: name = discovery2
docker[7011]: 2015/03/04 21:49:14 etcdserver: data dir = /data
docker[7011]: 2015/03/04 21:49:14 etcdserver: member dir = /data/member
docker[7011]: 2015/03/04 21:49:14 etcdserver: heartbeat = 100ms
docker[7011]: 2015/03/04 21:49:14 etcdserver: election = 1000ms
docker[7011]: 2015/03/04 21:49:14 etcdserver: snapshot count = 10000
docker[7011]: 2015/03/04 21:49:14 etcdserver: advertise client URLs = http://10.0.0.39:4001,http://127.0.0.1:4001
docker[7011]: 2015/03/04 21:49:14 etcdserver: start member 59de04f120e59e7e in cluster 4bb8fe835d0002
docker[7011]: 2015/03/04 21:49:14 raft: 59de04f120e59e7e became follower at term 0
docker[7011]: 2015/03/04 21:49:14 raft: newRaft 59de04f120e59e7e [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
docker[7011]: 2015/03/04 21:49:14 raft: 59de04f120e59e7e became follower at term 1
docker[7011]: 2015/03/04 21:49:14 raft: 59de04f120e59e7e [term: 1] received a MsgHeartbeat message with higher term from 4bb8fe835d0001 [term: 1022313]
docker[7011]: 2015/03/04 21:49:14 raft: 59de04f120e59e7e became follower at term 1022313
docker[7011]: 2015/03/04 21:49:14 raft.node: 59de04f120e59e7e elected leader 4bb8fe835d0001 at term 1022313
docker[7011]: 2015/03/04 21:49:14 raft: 59de04f120e59e7e [logterm: 0, index: 733078680] rejected msgApp [logterm: 1022313, index: 733078680] from 4bb8fe835d0001
docker[7011]: 2015/03/04 21:49:14 raft: 59de04f120e59e7e [commit: 0, lastindex: 0, lastterm: 0] starts to restore snapshot [index: 733069300, term: 1022311]
docker[7011]: 2015/03/04 21:49:14 raftlog: log [committed=1, applied=0, unstable.offset=0, len(unstable.Entries)=0] starts to restore snapshot [index: 733069300, term: 1022311]
docker[7011]: 2015/03/04 21:49:14 raft: 59de04f120e59e7e restored progress of 4bb8bfabd60001 [next = 733069301, match = 0, wait = 0]
docker[7011]: 2015/03/04 21:49:14 raft: 59de04f120e59e7e [commit: 0] restored snapshot [index: 733069300, term: 1022311]
docker[7011]: 2015/03/04 21:49:14 etcdserver: saved incoming snapshot at index 733069300
docker[7011]: 2015/03/04 21:49:14 rafthttp: starting client stream to 4bb8fe835d0001 at term 1022313
docker[7011]: 2015/03/04 21:49:15 etcdserver: recovered from incoming snapshot at index 733069300
docker[7011]: 2015/03/04 21:49:15 raft: 59de04f120e59e7e [commit: 733069300] ignored snapshot [index: 733069300, term: 1022311]
docker[7011]: 2015/03/04 21:49:15 rafthttp: unexpected removal of unknown peer '21313756614492161'
docker[7011]: 2015/03/04 21:49:15 rafthttp: encountered error reading the client log stream: read tcp 10.0.0.12:7001: use of closed network connection
docker[7011]: 2015/03/04 21:49:15 rafthttp: client streaming to 4bb8fe835d0001 at term 1022313 has been stopped
docker[7011]: panic: rafthttp: unexpected removal of unknown peer '21313756614492161'
docker[7011]: goroutine 15 [running]:
docker[7011]: log.Panicf(0x8df6b0, 0x31, 0xc20bd534f8, 0x1, 0x1)
docker[7011]: /home/core/go/src/log/log.go:314 +0xd0
docker[7011]: github.com/coreos/etcd/rafthttp.(*transport).removePeer(0xc208088fc0, 0x4bb8bfabd60001)
docker[7011]: /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/rafthttp/transport.go:152 +0x1c3
docker[7011]: github.com/coreos/etcd/rafthttp.(*transport).RemovePeer(0xc208088fc0, 0x4bb8bfabd60001)
docker[7011]: /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/rafthttp/transport.go:136 +0x77
docker[7011]: github.com/coreos/etcd/etcdserver.(*EtcdServer).applyConfChange(0xc208048200, 0x0, 0x1, 0x4bb8bfabd60001, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
docker[7011]: /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:790 +0x81e
docker[7011]: github.com/coreos/etcd/etcdserver.(*EtcdServer).apply(0xc208048200, 0xc20b544000, 0x24a4, 0x24e3, 0xc20803bda0, 0x0, 0x0)
docker[7011]: /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:698 +0x399
docker[7011]: github.com/coreos/etcd/etcdserver.(*EtcdServer).run(0xc208048200)
docker[7011]: /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:429 +0xf4c
docker[7011]: created by github.com/coreos/etcd/etcdserver.(*EtcdServer).start
docker[7011]: /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:297 +0x294
docker[7011]: goroutine 1 [runnable]:
docker[7011]: github.com/coreos/etcd/etcdmain.Main()
docker[7011]: /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:79 +0x64d
docker[7011]: main.main()
docker[7011]: /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/main.go:48 +0x1de
docker[7011]: goroutine 5 [syscall]:
docker[7011]: os/signal.loop()
docker[7011]: /home/core/go/src/os/signal/signal_unix.go:21 +0x1f
docker[7011]: created by os/signal.init·1
docker[7011]: /home/core/go/src/os/signal/signal_unix.go:27 +0x35
docker[7011]: goroutine 16 [runnable]:
docker[7011]: github.com/coreos/etcd/etcdserver.(*EtcdServer).Do(0xc208048200, 0x7fa6918b9290, 0xc20805ac60, 0x7e4be6c39ce30001, 0x846780, 0x3, 0xc20803bf50, 0x26, 0xc20805aba0, 0x54, ...)
docker[7011]: /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:495 +0x5df
docker[7011]: github.com/coreos/etcd/etcdserver.(*EtcdServer).publish(0xc208048200, 0x12a05f200)
docker[7011]: /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:657 +0x30b
docker[7011]: created by github.com/coreos/etcd/etcdserver.(*EtcdServer).Start
docker[7011]: /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:278 +0x4f
docker[7011]: goroutine 17 [runnable]:
docker[7011]: github.com/coreos/etcd/etcdserver.(*EtcdServer).purgeFile(0xc208048200)
docker[7011]: /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:308 +0x48c
docker[7011]: created by github.com/coreos/etcd/etcdserver.(*EtcdServer).Start
docker[7011]: /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:279 +0x69
docker[7011]: goroutine 18 [IO wait]:
docker[7011]: net.(*pollDesc).Wait(0xc208088530, 0x72, 0x0, 0x0)
docker[7011]: /home/core/go/src/net/fd_poll_runtime.go:84 +0x47
docker[7011]: net.(*pollDesc).WaitRead(0xc208088530, 0x0, 0x0)
docker[7011]: /home/core/go/src/net/fd_poll_runtime.go:89 +0x43
docker[7011]: net.(*netFD).accept(0xc2080884d0, 0x0, 0x7fa6918b6c98, 0xc20800add8)
docker[7011]: /home/core/go/src/net/fd_unix.go:419 +0x40b
docker[7011]: net.(*TCPListener).AcceptTCP(0xc208034038, 0x7fa6918b93d0, 0x0, 0x0)
docker[7011]: /home/core/go/src/net/tcpsock_posix.go:234 +0x4e
docker[7011]: net.(*TCPListener).Accept(0xc208034038, 0x0, 0x0, 0x0, 0x0)
docker[7011]: /home/core/go/src/net/tcpsock_posix.go:244 +0x4c
docker[7011]: github.com/coreos/etcd/pkg/transport.(*rwTimeoutListener).Accept(0xc20801fbc0, 0x0, 0x0, 0x0, 0x0)
docker[7011]: /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/transport/timeout_listener.go:44 +0x7a
docker[7011]: net/http.(*Server).Serve(0xc20805ade0, 0x7fa6918b84c0, 0xc20801fbc0, 0x0, 0x0)
docker[7011]: /home/core/go/src/net/http/server.go:1728 +0x92
docker[7011]: github.com/coreos/etcd/etcdmain.serveHTTP(0x7fa6918b84c0, 0xc20801fbc0, 0x7fa6918b9180, 0xc20803bd40, 0x45d964b800, 0x0, 0x0)
docker[7011]: /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdmain/http.go:36 +0x1be
docker[7011]: github.com/coreos/etcd/etcdmain.func·005(0x7fa6918b84c0, 0xc20801fbc0)
docker[7011]: /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:180 +0x5a
docker[7011]: created by github.com/coreos/etcd/etcdmain.startEtcd
docker[7011]: /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:181 +0x1af4
docker[7011]: goroutine 19 [IO wait]:
docker[7011]: net.(*pollDesc).Wait(0xc208088610, 0x72, 0x0, 0x0)
docker[7011]: /home/core/go/src/net/fd_poll_runtime.go:84 +0x47
docker[7011]: net.(*pollDesc).WaitRead(0xc208088610, 0x0, 0x0)
docker[7011]: /home/core/go/src/net/fd_poll_runtime.go:89 +0x43
docker[7011]: net.(*netFD).accept(0xc2080885b0, 0x0, 0x7fa6918b6c98, 0xc20800b720)
docker[7011]: /home/core/go/src/net/fd_unix.go:419 +0x40b
docker[7011]: net.(*TCPListener).AcceptTCP(0xc208034040, 0x0, 0x0, 0x0)
docker[7011]: /home/core/go/src/net/tcpsock_posix.go:234 +0x4e
docker[7011]: net.(*TCPListener).Accept(0xc208034040, 0x0, 0x0, 0x0, 0x0)
docker[7011]: /home/core/go/src/net/tcpsock_posix.go:244 +0x4c
docker[7011]: github.com/coreos/etcd/pkg/transport.(*keepaliveListener).Accept(0xc20800b6f0, 0x0, 0x0, 0x0, 0x0)
docker[7011]: /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/transport/keepalive_listener.go:48 +0x71
docker[7011]: net/http.(*Server).Serve(0xc20805ae40, 0x7fa6918b84f8, 0xc20800b6f0, 0x0, 0x0)
docker[7011]: /home/core/go/src/net/http/server.go:1728 +0x92
docker[7011]: github.com/coreos/etcd/etcdmain.serveHTTP(0x7fa6918b84f8, 0xc20800b6f0, 0x7fa6918b92d0, 0xc20801ed80, 0x0, 0x0, 0x0)
docker[7011]: /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdmain/http.go:36 +0x1be
docker[7011]: github.com/coreos/etcd/etcdmain.func·006(0x7fa6918b84f8, 0xc20800b6f0)
docker[7011]: /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:188 +0x80
docker[7011]: created by github.com/coreos/etcd/etcdmain.startEtcd
docker[7011]: /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:189 +0x1c40
docker[7011]: goroutine 20 [IO wait]:
docker[7011]: net.(*pollDesc).Wait(0xc2080886f0, 0x72, 0x0, 0x0)
docker[7011]: /home/core/go/src/net/fd_poll_runtime.go:84 +0x47
docker[7011]: net.(*pollDesc).WaitRead(0xc2080886f0, 0x0, 0x0)
docker[7011]: /home/core/go/src/net/fd_poll_runtime.go:89 +0x43
docker[7011]: net.(*netFD).accept(0xc208088690, 0x0, 0x7fa6918b6c98, 0xc20800b760)
docker[7011]: /home/core/go/src/net/fd_unix.go:419 +0x40b
docker[7011]: net.(*TCPListener).AcceptTCP(0xc208034048, 0x0, 0x0, 0x0)
docker[7011]: /home/core/go/src/net/tcpsock_posix.go:234 +0x4e
docker[7011]: net.(*TCPListener).Accept(0xc208034048, 0x0, 0x0, 0x0, 0x0)
docker[7011]: /home/core/go/src/net/tcpsock_posix.go:244 +0x4c
docker[7011]: github.com/coreos/etcd/pkg/transport.(*keepaliveListener).Accept(0xc20800b770, 0x0, 0x0, 0x0, 0x0)
docker[7011]: /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/transport/keepalive_listener.go:48 +0x71
docker[7011]: net/http.(*Server).Serve(0xc20805aea0, 0x7fa6918b84f8, 0xc20800b770, 0x0, 0x0)
docker[7011]: /home/core/go/src/net/http/server.go:1728 +0x92
docker[7011]: github.com/coreos/etcd/etcdmain.serveHTTP(0x7fa6918b84f8, 0xc20800b770, 0x7fa6918b92d0, 0xc20801ed80, 0x0, 0x0, 0x0)
docker[7011]: /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdmain/http.go:36 +0x1be
docker[7011]: github.com/coreos/etcd/etcdmain.func·006(0x7fa6918b84f8, 0xc20800b770)
docker[7011]: /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:188 +0x80
docker[7011]: created by github.com/coreos/etcd/etcdmain.startEtcd
docker[7011]: /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:189 +0x1c40
docker[7011]: goroutine 21 [chan receive]:
docker[7011]: github.com/coreos/etcd/pkg/osutil.func·001()
docker[7011]: /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/osutil/interrupt_unix.go:53 +0x68
docker[7011]: created by github.com/coreos/etcd/pkg/osutil.HandleInterrupts
docker[7011]: /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/osutil/interrupt_unix.go:74 +0x1f6
docker[7011]: goroutine 22 [runnable]:
docker[7011]: github.com/coreos/etcd/pkg/fileutil.func·001()
docker[7011]: /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/fileutil/purge.go:69 +0x658
systemd[1]: etcd2.service: main process exited, code=exited, status=2/INVALIDARGUMENT
docker[7011]: created by github.com/coreos/etcd/pkg/fileutil.PurgeFile
docker[7011]: /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/fileutil/purge.go:75 +0x231
docker[7011]: goroutine 23 [runnable]:
docker[7011]: github.com/coreos/etcd/pkg/fileutil.func·001()
docker[7011]: /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/fileutil/purge.go:69 +0x658
docker[7011]: created by github.com/coreos/etcd/pkg/fileutil.PurgeFile
docker[7011]: /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/fileutil/purge.go:75 +0x231
docker[7011]: goroutine 24 [IO wait]:
docker[7011]: net.(*pollDesc).Wait(0xc2080891e0, 0x72, 0x0, 0x0)
docker[7011]: /home/core/go/src/net/fd_poll_runtime.go:84 +0x47
docker[7011]: net.(*pollDesc).WaitRead(0xc2080891e0, 0x0, 0x0)
docker[7011]: /home/core/go/src/net/fd_poll_runtime.go:89 +0x43
docker[7011]: net.(*netFD).Read(0xc208089180, 0xc2080c0000, 0x1000, 0x1000, 0x0, 0x7fa6918b6c98, 0xc20af45018)
docker[7011]: /home/core/go/src/net/fd_unix.go:242 +0x40f
docker[7011]: net.(*conn).Read(0xc208034138, 0xc2080c0000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
docker[7011]: /home/core/go/src/net/net.go:121 +0xdc
docker[7011]: github.com/coreos/etcd/pkg/transport.timeoutConn.Read(0x7fa6918b8748, 0xc208034138, 0x12a05f200, 0x12a05f200, 0xc2080c0000, 0x1000, 0x1000, 0x100000000, 0x0, 0x0)
docker[7011]: /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/transport/timeout_conn.go:43 +0x165
docker[7011]: github.com/coreos/etcd/pkg/transport.(*timeoutConn).Read(0xc20801f100, 0xc2080c0000, 0x1000, 0x1000, 0x3, 0x0, 0x0)
docker[7011]: <autogenerated>:21 +0xd6
docker[7011]: net/http.(*liveSwitchReader).Read(0xc2080684a8, 0xc2080c0000, 0x1000, 0x1000, 0x2, 0x0, 0x0)
docker[7011]: /home/core/go/src/net/http/server.go:214 +0xab
docker[7011]: io.(*LimitedReader).Read(0xc20801f120, 0xc2080c0000, 0x1000, 0x1000, 0x2, 0x0, 0x0)
docker[7011]: /home/core/go/src/io/io.go:408 +0xce
docker[7011]: bufio.(*Reader).fill(0xc20805afc0)
docker[7011]: /home/core/go/src/bufio/bufio.go:97 +0x1ce
docker[7011]: bufio.(*Reader).ReadSlice(0xc20805afc0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
docker[7011]: /home/core/go/src/bufio/bufio.go:295 +0x257
docker[7011]: bufio.(*Reader).ReadLine(0xc20805afc0, 0x0, 0x0, 0x0, 0xc208089100, 0x0, 0x0)
docker[7011]: /home/core/go/src/bufio/bufio.go:324 +0x62
docker[7011]: net/textproto.(*Reader).readLineSlice(0xc20a104240, 0x0, 0x0, 0x0, 0x0, 0x0)
docker[7011]: /home/core/go/src/net/textproto/reader.go:55 +0x9e
docker[7011]: net/textproto.(*Reader).ReadLine(0xc20a104240, 0x0, 0x0, 0x0, 0x0)
docker[7011]: /home/core/go/src/net/textproto/reader.go:36 +0x4f
docker[7011]: net/http.ReadRequest(0xc20805afc0, 0xc20b2a9c70, 0x0, 0x0)
docker[7011]: /home/core/go/src/net/http/request.go:598 +0xcb
docker[7011]: net/http.(*conn).readRequest(0xc208068460, 0x0, 0x0, 0x0)
docker[7011]: /home/core/go/src/net/http/server.go:586 +0x26f
docker[7011]: net/http.(*conn).serve(0xc208068460)
docker[7011]: /home/core/go/src/net/http/server.go:1162 +0x69e
docker[7011]: created by net/http.(*Server).Serve
docker[7011]: /home/core/go/src/net/http/server.go:1751 +0x35e
docker[7011]: goroutine 28 [IO wait]:
docker[7011]: net.(*pollDesc).Wait(0xc208088060, 0x72, 0x0, 0x0)
docker[7011]: /home/core/go/src/net/fd_poll_runtime.go:84 +0x47
docker[7011]: net.(*pollDesc).WaitRead(0xc208088060, 0x0, 0x0)
docker[7011]: /home/core/go/src/net/fd_poll_runtime.go:89 +0x43
docker[7011]: net.(*netFD).Read(0xc208088000, 0xc2080c4000, 0x1000, 0x1000, 0x0, 0x7fa6918b6c98, 0xc20800ab38)
docker[7011]: /home/core/go/src/net/fd_unix.go:242 +0x40f
docker[7011]: net.(*conn).Read(0xc208034020, 0xc2080c4000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
docker[7011]: /home/core/go/src/net/net.go:121 +0xdc
docker[7011]: github.com/coreos/etcd/pkg/transport.timeoutConn.Read(0x7fa6918b8748, 0xc208034020, 0x12a05f200, 0x12a05f200, 0xc2080c4000, 0x1000, 0x1000, 0x100000000, 0x0, 0x0)
docker[7011]: /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/transport/timeout_conn.go:43 +0x165
docker[7011]: github.com/coreos/etcd/pkg/transport.(*timeoutConn).Read(0xc20801e440, 0xc2080c4000, 0x1000, 0x1000, 0x3, 0x0, 0x0)
docker[7011]: <autogenerated>:21 +0xd6
docker[7011]: net/http.(*liveSwitchReader).Read(0xc208068188, 0xc2080c4000, 0x1000, 0x1000, 0x2, 0x0, 0x0)
docker[7011]: /home/core/go/src/net/http/server.go:214 +0xab
docker[7011]: io.(*LimitedReader).Read(0xc20801e460, 0xc2080c4000, 0x1000, 0x1000, 0x41c1aa, 0x0, 0x0)
docker[7011]: /home/core/go/src/io/io.go:408 +0xce
docker[7011]: bufio.(*Reader).fill(0xc20805a0c0)
docker[7011]: /home/core/go/src/bufio/bufio.go:97 +0x1ce
docker[7011]: bufio.(*Reader).ReadSlice(0xc20805a0c0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
docker[7011]: /home/core/go/src/bufio/bufio.go:295 +0x257
docker[7011]: bufio.(*Reader).ReadLine(0xc20805a0c0, 0x0, 0x0, 0x0, 0xc208088000, 0x0, 0x0)
docker[7011]: /home/core/go/src/bufio/bufio.go:324 +0x62
docker[7011]: net/textproto.(*Reader).readLineSlice(0xc2080ba0f0, 0x0, 0x0, 0x0, 0x0, 0x0)
docker[7011]: /home/core/go/src/net/textproto/reader.go:55 +0x9e
docker[7011]: net/textproto.(*Reader).ReadLine(0xc2080ba0f0, 0x0, 0x0, 0x0, 0x0)
docker[7011]: /home/core/go/src/net/textproto/reader.go:36 +0x4f
docker[7011]: net/http.ReadRequest(0xc20805a0c0, 0xc209052410, 0x0, 0x0)
docker[7011]: /home/core/go/src/net/http/request.go:598 +0xcb
docker[7011]: net/http.(*conn).readRequest(0xc208068140, 0x0, 0x0, 0x0)
docker[7011]: /home/core/go/src/net/http/server.go:586 +0x26f
docker[7011]: net/http.(*conn).serve(0xc208068140)
docker[7011]: /home/core/go/src/net/http/server.go:1162 +0x69e
docker[7011]: created by net/http.(*Server).Serve
docker[7011]: /home/core/go/src/net/http/server.go:1751 +0x35e
docker[7011]: goroutine 35 [runnable]:
docker[7011]: net.(*pollDesc).Wait(0xc20b2b52c0, 0x72, 0x0, 0x0)
docker[7011]: /home/core/go/src/net/fd_poll_runtime.go:84 +0x47
docker[7011]: net.(*pollDesc).WaitRead(0xc20b2b52c0, 0x0, 0x0)
docker[7011]: /home/core/go/src/net/fd_poll_runtime.go:89 +0x43
docker[7011]: net.(*netFD).Read(0xc20b2b5260, 0xc20b53a000, 0x1000, 0x1000, 0x0, 0x7fa6918b6c98, 0xc20b3894a8)
docker[7011]: /home/core/go/src/net/fd_unix.go:242 +0x40f
docker[7011]: net.(*conn).Read(0xc20b1b33d8, 0xc20b53a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
docker[7011]: /home/core/go/src/net/net.go:121 +0xdc
docker[7011]: github.com/coreos/etcd/pkg/transport.timeoutConn.Read(0x7fa6918b8748, 0xc20b1b33d8, 0x12a05f200, 0x12a05f200, 0xc20b53a000, 0x1000, 0x1000, 0xc20b541d98, 0x0, 0x0)
docker[7011]: /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/transport/timeout_conn.go:43 +0x165
docker[7011]: github.com/coreos/etcd/pkg/transport.(*timeoutConn).Read(0xc20b328560, 0xc20b53a000, 0x1000, 0x1000, 0x846760, 0x0, 0x0)
docker[7011]: <autogenerated>:21 +0xd6
docker[7011]: net/http.noteEOFReader.Read(0x7fa6918b8808, 0xc20b328560, 0xc208032aa8, 0xc20b53a000, 0x1000, 0x1000, 0xc20805d480, 0x0, 0x0)
docker[7011]: /home/core/go/src/net/http/transport.go:1270 +0x6e
docker[7011]: net/http.(*noteEOFReader).Read(0xc20b328580, 0xc20b53a000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
docker[7011]: <autogenerated>:125 +0xd4
docker[7011]: bufio.(*Reader).fill(0xc20b324cc0)
docker[7011]: /home/core/go/src/bufio/bufio.go:97 +0x1ce
docker[7011]: bufio.(*Reader).Peek(0xc20b324cc0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
docker[7011]: /home/core/go/src/bufio/bufio.go:132 +0xf0
docker[7011]: net/http.(*persistConn).readLoop(0xc208032a50)
docker[7011]: /home/core/go/src/net/http/transport.go:842 +0xa4
docker[7011]: created by net/http.(*Transport).dialConn
docker[7011]: /home/core/go/src/net/http/transport.go:660 +0xc9f
docker[7011]: goroutine 33 [runnable]:
docker[7011]: net.(*pollDesc).Wait(0xc20b2b5330, 0x72, 0x0, 0x0)
docker[7011]: /home/core/go/src/net/fd_poll_runtime.go:84 +0x47
docker[7011]: net.(*pollDesc).WaitRead(0xc20b2b5330, 0x0, 0x0)
docker[7011]: /home/core/go/src/net/fd_poll_runtime.go:89 +0x43
docker[7011]: net.(*netFD).Read(0xc20b2b52d0, 0xc20b536000, 0x1000, 0x1000, 0x0, 0x7fa6918b6c98, 0xc20b318418)
docker[7011]: /home/core/go/src/net/fd_unix.go:242 +0x40f
docker[7011]: net.(*conn).Read(0xc20b1b33c8, 0xc20b536000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
docker[7011]: /home/core/go/src/net/net.go:121 +0xdc
docker[7011]: github.com/coreos/etcd/pkg/transport.timeoutConn.Read(0x7fa6918b8748, 0xc20b1b33c8, 0x12a05f200, 0x12a05f200, 0xc20b536000, 0x1000, 0x1000, 0xc2080b3d98, 0x0, 0x0)
docker[7011]: /home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/transport/timeout_conn.go:43 +0x165
docker[7011]: github.com/coreos/etcd/pkg/transport.(*timeoutConn).Read(0xc20b3284a0, 0xc20b536000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
docker[7011]: <autogenerated>:21 +0xd6
docker[7011]: net/http.noteEOFReader.Read(0x7fa6918b8808, 0xc20b3284a0, 0xc208032b58, 0xc20b536000, 0x1000, 0x1000, 0xc20b321500, 0x0, 0x0)
docker[7011]: /home/core/go/src/net/http/transport.go:1270 +0x6e
docker[7011]: net/http.(*noteEOFReader).Read(0xc20b3284c0, 0xc20b536000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
docker[7011]: <autogenerated>:125 +0xd4
docker[7011]: bufio.(*Reader).fill(0xc20b324ba0)
docker[7011]: /home/core/go/src/bufio/bufio.go:97 +0x1ce
docker[7011]: bufio.(*Reader).Peek(0xc20b324ba0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
docker[7011]: /home/core/go/src/bufio/bufio.go:132 +0xf0
docker[7011]: net/http.(*persistConn).readLoop(0xc208032b00)
docker[7011]: /home/core/go/src/net/http/transport.go:842 +0xa4
docker[7011]: created by net/http.(*Transport).dialConn
docker[7011]: /home/core/go/src/net/http/transport.go:660 +0xc9f
docker[7011]: goroutine 34 [runnable]:
docker[7011]: net/http.(*persistConn).writeLoop(0xc208032b00)
docker[7011]: /home/core/go/src/net/http/transport.go:945 +0x41d
docker[7011]: created by net/http.(*Transport).dialConn
docker[7011]: /home/core/go/src/net/http/transport.go:661 +0xcbc
docker[7011]: goroutine 36 [runnable]:
docker[7011]: net/http.(*persistConn).writeLoop(0xc208032a50)
docker[7011]: /home/core/go/src/net/http/transport.go:945 +0x41d
docker[7011]: created by net/http.(*Transport).dialConn
docker[7011]: /home/core/go/src/net/http/transport.go:661 +0xcbc
docker[7033]: etcd2
systemd[1]: Unit etcd2.service entered failed state.
systemd[1]: etcd2.service failed.
docker[7042]: etcd2
```

/cc @jedsmith

### PR DESCRIPTION
**Pull request by yichengq**
fixes #2437

### CODE REVIEW

File: etcdserver/cluster.go [hunk 1]
```diff
@@ -316,22 +317,33 @@ func (c *Cluster) AddMember(m *Member) {
 	if _, err := c.store.Create(p, false, string(b), false, store.Permanent); err != nil {
 		log.Panicf("create raftAttributes should never fail: %v", err)
 	}
-	c.members[m.ID] = m
+	if index > c.index {
```
Comment (xiang90) [inline etcdserver/cluster.go]: update c.index

File: etcdserver/cluster.go [hunk 2]
```diff
@@ -316,22 +317,33 @@ func (c *Cluster) AddMember(m *Member) {
...
 	defer c.Unlock()
 	if _, err := c.store.Delete(memberStoreKey(id), true, true); err != nil {
 		log.Panicf("delete member should never fail: %v", err)
 	}
-	delete(c.members, id)
 	if _, err := c.store.Create(removedMemberStoreKey(id), false, "", false, store.Permanent); err != nil {
 		log.Panicf("create removedMember should never fail: %v", err)
 	}
-	c.removed[id] = true
+	if index > c.index {
```
Comment (xiang90) [inline etcdserver/cluster.go]: update c.index

File: etcdserver/cluster.go [hunk 3]
```diff
@@ -352,7 +366,9 @@ func (c *Cluster) UpdateRaftAttributes(id types.ID, raftAttr RaftAttributes) {
 	if _, err := c.store.Update(p, string(b), store.Permanent); err != nil {
 		log.Panicf("update raftAttributes should never fail: %v", err)
 	}
-	c.members[id].RaftAttributes = raftAttr
+	if index > c.index {
```
Comment (xiang90) [inline etcdserver/cluster.go]: update c.index

File: etcdserver/server.go [hunk 4]
```diff
@@ -750,22 +750,28 @@ func (s *EtcdServer) applyConfChange(cc raftpb.ConfChange, confState *raftpb.Con
...
-		s.Cluster.RemoveMember(id)
+		s.Cluster.RemoveMember(id, index)
 		if id == s.id {
 			return true, nil
 		} else {
-			s.r.transport.RemovePeer(id)
 			log.Printf("etcdserver: removed member %s from cluster %s", id, s.Cluster.ID())
 		}
+		if index > s.Cluster.index && id != s.id {
+			s.r.transport.RemovePeer(id)
```
Comment (xiang90) [inline etcdserver/server.go]: move trans into cluster if possible

**Comment by yichengq** [comment]
PTAL

File: etcdserver/cluster.go [hunk 5]
```diff
@@ -316,22 +340,41 @@ func (c *Cluster) AddMember(m *Member) {
...
 		log.Panicf("create removedMember should never fail: %v", err)
 	}
-	c.removed[id] = true
+	if index > c.index {
+		if _, ok := c.members[id]; !ok {
+			log.Panicf("member %s should exist in the cluster", id)
+		}
+		delete(c.members, id)
+		c.removed[id] = true
+		if id != c.memberID {
```
Comment (xiang90) [inline etcdserver/cluster.go]: we can move this logic to transport.

File: etcdserver/cluster.go [hunk 6]
```diff
@@ -66,6 +67,9 @@ type Cluster struct {
 	// TODO: upgrade it as last modified index
 	index uint64
 
+	memberID  types.ID
+	transport rafthttp.Transporter
```
Comment (xiang90) [inline etcdserver/cluster.go]: // transport and members maintains the view of the cluster at index. This might be more upto date than what stores in the store since...

**Comment by yichengq** [comment]
PTAL

File: etcdserver/server.go [hunk 7]
```diff
@@ -258,13 +258,8 @@ func NewServer(cfg *ServerConfig) (*EtcdServer, error) {
...
 
 	tr := rafthttp.NewTransporter(cfg.Transport, id, cfg.Cluster.ID(), srv, srv.errorc, sstats, lstats)
-	// add all the remote members into sendhub
-	for _, m := range cfg.Cluster.Members() {
-		if m.ID != id {
-			tr.AddPeer(m.ID, m.PeerURLs)
-		}
-	}
 	srv.r.transport = tr
+	srv.Cluster.InitTransport(tr)
```
Comment (xiang90) [inline etcdserver/server.go]: cluster.SetTransport

File: etcdserver/cluster.go [hunk 8]
```diff
@@ -66,6 +67,10 @@ type Cluster struct {
 	// TODO: upgrade it as last modified index
 	index uint64
 
+	// transport and members maintains the view of the cluster at index.
+	// This might be more upto date than what stores in the store since
+	// the index may be bigger than store index.
```
Comment (xiang90) [inline etcdserver/cluster.go]: higher

Comment (xiang90) [inline etcdserver/cluster.go]: why it can be higher. add some explanation would be nicer.

Comment (yichengq) [inline etcdserver/cluster.go]: It is mentioned once in the comment for index, but it makes it more explicit to explain it here too.

**Comment by yichengq** [comment]
ptal

**Comment by xiang90** [comment]
LGTM
