### PR TITLE
Reuse a bytes buffer as proxy request body.

### LINKED ISSUE #2895: Proxy Closes Body on First Failure
Hi all. I am running a CoreOS cluster with a core etcd cluster of five instances. All of the other cluster members are running etcd in proxy mode.

The proxies lose connectivity with the etcd cluster frequently. What happens is the proxy will attempt to connect to the first endpoint and fail with `read tcp etcd1:2379: use of closed network connection`. The remaining endpoints then fail with `http: invalid Read on closed Body`.

This appears to be a bug in the way the reverseProxy's ServeHTTP function reuses the request. The `http.Transport.RoundTrip` function (called at https://github.com/coreos/etcd/blob/master/proxy/reverse.go#L101) closes the body on error. Thus if the first endpoint fails due to a transport issue all remaining endpoints will also fail.

Here's a log of this happening in my cluster:

    Jun 01 16:46:18 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:18 proxy: marked endpoint http://etcd4:2379 available
    Jun 01 16:46:18 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:18 proxy: marked endpoint http://etcd5:2379 available
    Jun 01 16:46:18 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:18 proxy: marked endpoint http://etcd1:2379 available
    Jun 01 16:46:18 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:18 proxy: marked endpoint http://etcd2:2379 available
    Jun 01 16:46:18 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:18 proxy: marked endpoint http://etcd3:2379 available
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: failed to direct request to http://etcd3:2379: read tcp etcd3:2379: use of closed network connection
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: marked endpoint http://etcd3:2379 unavailable
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: failed to direct request to http://etcd3:2379: read tcp etcd3:2379: use of closed network connection
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: failed to direct request to http://etcd3:2379: read tcp etcd3:2379: use of closed network connection
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: failed to direct request to http://etcd3:2379: read tcp etcd3:2379: use of closed network connection
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: failed to direct request to http://etcd1:2379: http: invalid Read on closed Body
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: marked endpoint http://etcd1:2379 unavailable
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: failed to direct request to http://etcd1:2379: http: invalid Read on closed Body
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: failed to direct request to http://etcd2:2379: http: invalid Read on closed Body
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: marked endpoint http://etcd2:2379 unavailable
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: failed to direct request to http://etcd1:2379: http: invalid Read on closed Body
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: failed to direct request to http://etcd1:2379: http: invalid Read on closed Body
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: failed to direct request to http://etcd2:2379: http: invalid Read on closed Body
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: failed to direct request to http://etcd5:2379: http: invalid Read on closed Body
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: marked endpoint http://etcd5:2379 unavailable
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: failed to direct request to http://etcd4:2379: http: invalid Read on closed Body
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: marked endpoint http://etcd4:2379 unavailable
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: unable to get response from 5 endpoint(s)
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: failed to direct request to http://etcd5:2379: http: invalid Read on closed Body
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: failed to direct request to http://etcd4:2379: http: invalid Read on closed Body
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: unable to get response from 5 endpoint(s)
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: failed to direct request to http://etcd2:2379: http: invalid Read on closed Body
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: failed to direct request to http://etcd2:2379: http: invalid Read on closed Body
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: failed to direct request to http://etcd5:2379: http: invalid Read on closed Body
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: failed to direct request to http://etcd5:2379: http: invalid Read on closed Body
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: failed to direct request to http://etcd4:2379: http: invalid Read on closed Body
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: unable to get response from 5 endpoint(s)
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: failed to direct request to http://etcd4:2379: http: invalid Read on closed Body
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: unable to get response from 5 endpoint(s)
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: zero endpoints currently available
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: zero endpoints currently available
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: zero endpoints currently available

My etcd version:

    $ etcd2 --version
    etcd Version: 2.0.11
    Git SHA: 0678329
    Go Version: go1.4.2
    Go OS/Arch: linux/amd64

I should note that the other endpoints were indeed available during the above occurrence.

### PR DESCRIPTION
**Pull request by BlueDragonX**
Fixes #2895.

### CODE REVIEW

File: proxy/reverse.go [hunk 1]
```diff
@@ -55,6 +57,19 @@ func (p *reverseProxy) ServeHTTP(rw http.ResponseWriter, clientreq *http.Request
 	proxyreq := new(http.Request)
 	*proxyreq = *clientreq
 
+	var proxybody []byte
```
Comment (xiang90) [inline proxy/reverse.go]: what i have done before it to wrap the original body with a reset closer. the closer will simply reset the reader offset to 0.

**Comment by xiang90** [comment]
@BlueDragonX This looks good to me. But can you try to idea I mentioned? Also I would prefer making the "unnecessary" change in a separate pull request.

File: proxy/reverse.go (hunk 1 above)
Comment (BlueDragonX) [inline proxy/reverse.go]: Around the bytes.Buffer? Is there an existing `ResetClose` in the etcd codebase that I could re-use? Did some quick grep'ing but I didn't see anything.

If you mean around the clientreq's `Body` it would still require us to buffer the request someplace. This was the simplest method to do that.

**Comment by BlueDragonX** [comment]
Another PR or another commit? It's as a result of this change.

File: proxy/reverse.go (hunk 1 above)
Comment (xiang90) [inline proxy/reverse.go]: >  I could re-use?

No. 

But then we can move the body reset out of the for loop, not a huge deal though.

**Comment by BlueDragonX** [comment]
I've restored the `req.Close = false` line.

File: proxy/reverse.go [hunk 2]
```diff
@@ -55,6 +57,19 @@ func (p *reverseProxy) ServeHTTP(rw http.ResponseWriter, clientreq *http.Request
...
+	var err error
```
Comment (xiang90) [inline proxy/reverse.go]: nit: var (
    err error
    proxybody []byte
)

**Comment by xiang90** [comment]
@BlueDragonX Can you please change the commit message to `proxy: reuse body ...` (add a pkg prefix). 

LGTM. Thanks.

**Comment by BlueDragonX** [comment]
Done and done!

**Comment by xiang90** [comment]
@BlueDragonX  Thank you so much!

**Comment by xiang90** [comment]
@BlueDragonX Hmm... Seems like gofmt checking failed. Can you run ./test to fix that?
