### PR TITLE
clientv3: fix current watcher reconnection

### LINKED ISSUE #4502: TestWatchReconnRequest fails
```
--- FAIL: TestWatchReconnRequest (5.35s)
	watch_test.go:281: watch timed out
```

### PR DESCRIPTION
**Pull request by heyitsanthony**
If a current watcher didn't receive any events, a reconnect cycle would
advance its revision to the store's current revision. Instead, reconnect
using the watcher's creation header revision if the watcher hasn't received
any events.

Fixes #4502

### CODE REVIEW

File: clientv3/watch.go [hunk 1]
```diff
@@ -198,6 +198,12 @@ func (w *watcher) addStream(resp *pb.WatchResponse, pendingReq *watchRequest) {
 		resumec: make(chan int64),
 	}
 
+	if pendingReq.rev == 0 {
+		// note the header revision so that a put following a current watcher
+		// disconnect will arrive on the watcher channel after reconnect
+		ws.lastRev = resp.Header.Revision
```
Comment (xiang90) [inline clientv3/watch.go]: should we update the rev of the initReq of ws directly?

File: clientv3/integration/watch_test.go [hunk 2]
```diff
@@ -163,13 +163,18 @@ func TestWatchReconnRequest(t *testing.T) {
...
+	donec, stopc := make(chan struct{}), make(chan struct{}, 1)
 	go func() {
+		timer := time.After(2 * time.Second)
+		defer close(donec)
+		// take down watcher connection
 		for {
 			wctx.wclient.ActiveConnection().Close()
 			select {
-			case <-donec:
+			case <-timer:
```
Comment (xiang90) [inline clientv3/integration/watch_test.go]: just <-time.After(2 * time.Second)?

**Comment by xiang90** [comment]
LGTM.

File: clientv3/integration/watch_test.go (hunk 2 above)
Comment (heyitsanthony) [inline clientv3/integration/watch_test.go]: no, that'll restart the timer on every loop

File: clientv3/watch.go (hunk 1 above)
Comment (heyitsanthony) [inline clientv3/watch.go]: yeah, that's cleaner

**Comment by heyitsanthony** [comment]
merging on greenlight
