### PR TITLE
client: return correct error for 50x response

### LINKED ISSUE #3012: discovery not trying forever
The code makes it seem like discovery should retry forever but it doesn't in practice. Trying to hunt this one down myself...

```
13:03:00 etcd1 | Starting etcd1 on port 5000
13:03:00 etcd2 | Starting etcd2 on port 5001
13:03:00 etcd2 | 2015/06/19 13:03:00 etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 4
13:03:00 etcd2 | 2015/06/19 13:03:00 etcdmain: no data-dir provided, using default data-dir ./infra2.etcd
13:03:00 etcd1 | 2015/06/19 13:03:00 etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 4
13:03:00 etcd1 | 2015/06/19 13:03:00 etcdmain: no data-dir provided, using default data-dir ./infra1.etcd
13:03:00 etcd2 | 2015/06/19 13:03:00 etcdmain: listening for peers on http://127.0.0.1:7002
13:03:00 etcd2 | 2015/06/19 13:03:00 etcdmain: listening for client requests on http://127.0.0.1:4002
13:03:00 etcd1 | 2015/06/19 13:03:00 etcdmain: listening for peers on http://127.0.0.1:7001
13:03:00 etcd1 | 2015/06/19 13:03:00 etcdmain: listening for client requests on http://127.0.0.1:4001
13:03:05 etcd2 | 2015/06/19 13:03:05 discovery: duringcluster status checkconnection tohttps://discovery.etcd.iotimed out, retrying in2s
13:03:05 etcd1 | 2015/06/19 13:03:05 discovery: duringcluster status checkconnection tohttps://discovery.etcd.iotimed out, retrying in2s
13:03:15 etcd1 | 2015/06/19 13:03:15 discovery: found self ef911c27b232ea14 in the cluster
13:03:15 etcd1 | 2015/06/19 13:03:15 discovery: found peer 1d1be50d7bc0ab50 in the cluster
13:03:15 etcd1 | 2015/06/19 13:03:15 discovery: found 2 peer(s), waiting for 1 more
13:03:20 etcd2 | 2015/06/19 13:03:20 discovery: found peer ef911c27b232ea14 in the cluster
13:03:20 etcd2 | 2015/06/19 13:03:20 discovery: found self 1d1be50d7bc0ab50 in the cluster
13:03:20 etcd2 | 2015/06/19 13:03:20 discovery: found 2 peer(s), waiting for 1 more
13:04:16 etcd1 | 2015/06/19 13:04:16 etcdmain: stopping listening for client requests on http://127.0.0.1:4001
13:04:16 etcd1 | 2015/06/19 13:04:16 etcdmain: stopping listening for peers on http://127.0.0.1:7001
13:04:16 etcd1 | 2015/06/19 13:04:16 etcdmain: unexpected end of JSON input
13:04:16 etcd1 | Terminating etcd1
13:04:21 etcd2 | 2015/06/19 13:04:21 etcdmain: stopping listening for client requests on http://127.0.0.1:4002
13:04:21 etcd2 | 2015/06/19 13:04:21 etcdmain: stopping listening for peers on http://127.0.0.1:7002
13:04:21 etcd2 | 2015/06/19 13:04:21 etcdmain: unexpected end of JSON input
```

### PR DESCRIPTION
**Pull request by yichengq**
[Updated]

etcd always returns 500/503 response when it may have no leader.
So we should log the other 50x response in a normal way.

This helps to log correctly when discovery meets 504 error. Before this
PR, it logs like this:

```
18:31:58 etcd2 | 2015/08/4 18:31:58 discovery: error #0: client: etcd
member https://discovery.etcd.io has no leader
18:31:58 etcd2 | 2015/08/4 18:31:58 discovery: waiting for other nodes:
error connecting to https://discovery.etcd.io, retrying in 4s
```

After this PR:

```
22:20:25 etcd2 | 2015/08/4 22:20:25 discovery: error #0: client: etcd
member https://discovery.etcd.io returns server error [Gateway Timeout]
22:20:25 etcd2 | 2015/08/4 22:20:25 discovery: waiting for other nodes:
error connecting to https://discovery.etcd.io, retrying in 4s
```

fixes #3012

### CODE REVIEW

File: client/client.go [hunk 1]
```diff
@@ -245,8 +245,13 @@ func (c *httpClusterClient) Do(ctx context.Context, act httpAction) (*http.Respo
...
 		}
 		if resp.StatusCode/100 == 5 {
-			// TODO: make sure this is a no leader response
-			cerr.Errors = append(cerr.Errors, fmt.Errorf("client: etcd member %s has no leader", eps[k].String()))
+			switch resp.StatusCode {
+			case http.StatusInternalServerError:
+				// TODO: make sure this is a no leader response
+				cerr.Errors = append(cerr.Errors, fmt.Errorf("client: etcd member %s has no leader", eps[k].String()))
+			default:
+				cerr.Errors = append(cerr.Errors, fmt.Errorf("client: etcd member %s returns server error [%s] with body [%s]", eps[k].String(), http.StatusText(resp.StatusCode), body))
```
Comment (xiang90) [inline client/client.go]: 1. I do no think we should return the full body.
2. We should not retry in some of the cases. If you want to fully resolve the TODO, you need to think carefully about this.

Comment (yichengq) [inline client/client.go]: 1. ok

2. I check the no-leader response again, and find out that http.StatusServiceUnavailable could be returned at no-leader case too when GET /v2/members too. So it needs to be improved.

It is hard to fully resolve the TODO here because no-leader response cannot be recognized from others. It is always `{message: Internal Server Error}`. I could tackle this as follow-up.

What cases do you refer that we should not retry? I go through all server error HTTP status, and think all could retry. If some server has some internal error, other servers may work well. If it is a no-leader error, we could wait some time before retry.

Comment (xiang90) [inline client/client.go]: > What cases do you refer that we should not retry?

OK... We never retry actually... So we should probably retry on leader election error and not others. But we can do this in another pull request.

**Comment by yichengq** [comment]
Have updated log line. PTAL

**Comment by xiang90** [comment]
LGTM
