### PR TITLE
etcdserver: get rid of unreliable WaitSchedule

### LINKED ISSUE #3793: TestRecvSnapshot-4 possibly fails on semaphore CI
--- FAIL: TestRecvSnapshot-4 (0.10s)
	server_test.go:858: store action = [], want [{Recovery []}]
	server_test.go:862: storage action = [], want [{SaveSnap []} {Save []}]

Go 1.4, on semaphore CI

### PR DESCRIPTION
**Pull request by xiang90**
In this case, we know we are waiting for an action happened on
storage. We can do a busy wait instead of calling waitSchedule.

The test previously failed on CI with no observed actions.

Fix #3793.

### CODE REVIEW

**Comment by gyuho** [comment]
LGTM.

File: etcdserver/server_test.go [hunk 1]
```diff
@@ -849,8 +849,15 @@ func TestRecvSnapshot(t *testing.T) {
 
 	s.start()
 	n.readyc <- raft.Ready{Snapshot: raftpb.Snapshot{Metadata: raftpb.SnapshotMetadata{Index: 1}}}
-	// make goroutines move forward to receive snapshot
-	testutil.WaitSchedule()
+
+	// wait for actions happened on the storage
+	for {
```
Comment (jonboulle) [inline etcdserver/server_test.go]: `for len(p.Action()) == 0` :stuck_out_tongue:
