### PR TITLE
etcd-tester: increase compaction timeout limit

### LINKED ISSUE #6805: functional-tester: compaction exceeds deadline
3 nodes functional tester returns the following error.

```
2016-11-04 09:23:05.517964 I | etcd-tester: [round#510] compacting storage (current revision 199789338, compact revision 199779338)
2016-11-04 09:23:05.518034 I | etcd-tester: [compact kv #0] starting (endpoint http://10.240.0.2:2379)
2016-11-04 09:23:24.518289 W | etcd-tester: [compact kv #0] error rpc error: code = 4 desc = context deadline exceeded (endpoint http://10.240.0.2:2379)
2016-11-04 09:23:24.518380 I | etcd-tester: [compact kv #1] starting (endpoint http://10.240.0.3:2379)
2016-11-04 09:23:24.765114 I | etcd-tester: [compact kv #1] already compacted (endpoint http://10.240.0.3:2379)
2016-11-04 09:23:24.765142 I | etcd-tester: [compact kv #1] done (endpoint http://10.240.0.3:2379)
2016-11-04 09:23:24.765202 I | etcd-tester: [compact kv #2] starting (endpoint http://10.240.0.4:2379)
2016-11-04 09:23:24.780259 I | etcd-tester: [compact kv #2] already compacted (endpoint http://10.240.0.4:2379)
2016-11-04 09:23:24.780274 I | etcd-tester: [compact kv #2] done (endpoint http://10.240.0.4:2379)
2016-11-04 09:23:24.780302 W | etcd-tester: [round#510] functional-tester compact got error (rpc error: code = 4 desc = context deadline exceeded)
```

### PR DESCRIPTION
**Pull request by fanminshi**
functional tester sometime experiences timeout during compaction phase. I crease the timeout limit.

FIX #6805

### CODE REVIEW

**Comment by fanminshi** [comment]
@gyuho we probably should run this code from my branch before we merge into master.

**Comment by xiang90** [comment]
Do we understand why it times out at the first place? Like why it is OK before we add the lease tester?

**Comment by heyitsanthony** [comment]
why does compaction need twice the time? the same rate limiter is shared among the stressers

**Comment by fanminshi** [comment]
All fixed. PTAL. cc @xiang90 @heyitsanthony @gyuho

File: tools/functional-tester/etcd-tester/key_stresser.go [hunk 1]
```diff
@@ -67,16 +67,18 @@ func (s *keyStresser) Stress() error {
 
 	kvc := pb.NewKVClient(conn)
 
+	s.keyOps = 0
+
 	var stressEntries = []stressEntry{
-		{weight: 0.7, f: newStressPut(kvc, s.keySuffixRange, s.keySize)},
+		{weight: 0.7, f: newStressPut(kvc, s.keySuffixRange, s.keySize, s)},
```
Comment (heyitsanthony) [inline tools/functional-tester/etcd-tester/key_stresser.go]: why add `s` everywhere? just change `stressFunc` to return the number of modified keys and do the atomic add in `run`? it would be less code overall

File: tools/functional-tester/etcd-tester/lease_stresser.go [hunk 2]
```diff
@@ -366,6 +368,8 @@ func (ls *leaseStresser) attachKeysWithLease(leaseID int64) error {
 		txn := &pb.TxnRequest{Success: txnPuts}
 		_, err := ls.kvc.Txn(ls.ctx, txn)
 		if err == nil {
+			// since all created keys will be deleted too, the number of operations on keys will be roughly 2x the number of created keys
```
Comment (heyitsanthony) [inline tools/functional-tester/etcd-tester/lease_stresser.go]: should the rate limiting be updated to account for deletes?

File: tools/functional-tester/etcd-tester/stresser.go [hunk 3]
```diff
@@ -30,8 +30,8 @@ type Stresser interface {
 	Stress() error
 	// Cancel cancels the stress test on the etcd cluster
 	Cancel()
-	// Report reports the success and failure of the stress test
-	Report() (success int, failure int)
+	// Report reports the number of entries created and deleted during the stress test
```
Comment (heyitsanthony) [inline tools/functional-tester/etcd-tester/stresser.go]: s/entries/keys

File: tools/functional-tester/etcd-tester/key_stresser.go [hunk 4]
```diff
@@ -67,16 +67,18 @@ func (s *keyStresser) Stress() error {
 
 	kvc := pb.NewKVClient(conn)
 
+	s.keyOps = 0
```
Comment (heyitsanthony) [inline tools/functional-tester/etcd-tester/key_stresser.go]: don't reset this; it should be cumulative

File: tools/functional-tester/etcd-tester/lease_stresser.go [hunk 5]
```diff
@@ -145,6 +146,7 @@ func (ls *leaseStresser) Stress() error {
 
 func (ls *leaseStresser) run() {
 	defer ls.runWg.Done()
+	ls.keyOps = 0
```
Comment (heyitsanthony) [inline tools/functional-tester/etcd-tester/lease_stresser.go]: don't reset this, it should be cumulative

File: tools/functional-tester/etcd-tester/stresser.go [hunk 6]
```diff
@@ -30,8 +30,8 @@ type Stresser interface {
...
+	Report() int64
```
Comment (heyitsanthony) [inline tools/functional-tester/etcd-tester/stresser.go]: If you're changing the interface, this could use a more descriptive name. `ModifiedKeys()` or something.

File: tools/functional-tester/etcd-tester/tester.go [hunk 7]
```diff
@@ -22,6 +22,9 @@ import (
 type tester struct {
 	cluster *cluster
 	limit   int
+	// entries records the number of entries created and deleted during a round
+	// it is used to calulate timeout for compaction
+	entries int64
```
Comment (heyitsanthony) [inline tools/functional-tester/etcd-tester/tester.go]: this shouldn't be in the tester structure, it never crosses a function boundary

File: tools/functional-tester/etcd-tester/key_stresser.go [hunk 8]
```diff
@@ -46,9 +47,8 @@ type keyStresser struct {
 
 	cancel func()
 	conn   *grpc.ClientConn
-
-	success int
-	failure int
+	// keyOps records the number of keys created and deleted during a test case
```
Comment (heyitsanthony) [inline tools/functional-tester/etcd-tester/key_stresser.go]: s/during a test case/by the stresser.

the stresser doesn't know about test cases

File: tools/functional-tester/etcd-tester/v2_stresser.go [hunk 9]
```diff
@@ -77,24 +76,21 @@ func (s *v2Stresser) Stress() error {
...
+	s.keyOps = 0
 	for {
 		if err := s.rateLimiter.Wait(ctx); err == context.Canceled {
 			return
 		}
 		setctx, setcancel := context.WithTimeout(ctx, clientV2.DefaultRequestTimeout)
 		key := fmt.Sprintf("foo%016x", rand.Intn(s.keySuffixRange))
 		_, err := kv.Set(setctx, key, string(randBytes(s.keySize)), nil)
+		if err == nil {
+			s.keyOps++
```
Comment (heyitsanthony) [inline tools/functional-tester/etcd-tester/v2_stresser.go]: what happened to the mutex?

Comment (fanminshi) [inline tools/functional-tester/etcd-tester/v2_stresser.go]: probably should use atomic.

File: tools/functional-tester/etcd-tester/stresser.go (hunk 6 above)
Comment (fanminshi) [inline tools/functional-tester/etcd-tester/stresser.go]: Is `ModifiedKeys()` too specific? i was thinking about use generic term in the interface. But i have no objection in using a more specific term.

File: tools/functional-tester/etcd-tester/stresser.go (hunk 3 above)
Comment (fanminshi) [inline tools/functional-tester/etcd-tester/stresser.go]: i thought using entries is more generic.

**Comment by xiang90** [comment]
Probably we should rename Report to KeyCreated or something more descriptive?

File: tools/functional-tester/etcd-tester/lease_stresser.go (hunk 5 above)
Comment (fanminshi) [inline tools/functional-tester/etcd-tester/lease_stresser.go]: my original though was that `keyOps` only records number of operation per test case. the tester accumulate that number for the entire round. that's why i reset it every test case. 

an alternate approach is that, we never reset `keyOps` and let it accumulate. 
then we let tester to figure the total keyOps for a round by find the difference from `KeyOps` of last round and current `keyOps`.

**Comment by fanminshi** [comment]
@xiang90 Anthony suggested renaming Report() too. I'll change it to a more descriptive name.

File: tools/functional-tester/etcd-tester/stresser.go (hunk 3 above)
Comment (heyitsanthony) [inline tools/functional-tester/etcd-tester/stresser.go]: the function only concerns keys; entries is vague

File: tools/functional-tester/etcd-tester/stresser.go (hunk 6 above)
Comment (heyitsanthony) [inline tools/functional-tester/etcd-tester/stresser.go]: it only talks about keys right now, what else do you have in mind?

File: tools/functional-tester/etcd-tester/lease_stresser.go (hunk 5 above)
Comment (heyitsanthony) [inline tools/functional-tester/etcd-tester/lease_stresser.go]: please keep it cumulative...

Comment (fanminshi) [inline tools/functional-tester/etcd-tester/lease_stresser.go]: @heyitsanthony will do!

File: tools/functional-tester/etcd-tester/stresser.go (hunk 3 above)
Comment (fanminshi) [inline tools/functional-tester/etcd-tester/stresser.go]: will be more specific.

File: tools/functional-tester/etcd-tester/lease_stresser.go (hunk 2 above)
Comment (fanminshi) [inline tools/functional-tester/etcd-tester/lease_stresser.go]: from my test, the current rate limiting strategy is pushing the system hard enough. i think we are fine for now.

**Comment by fanminshi** [comment]
All fixed. PTAL @xiang90 @heyitsanthony  @gyuho

File: tools/functional-tester/etcd-tester/key_stresser.go [hunk 10]
```diff
@@ -46,9 +47,8 @@ type keyStresser struct {
 
 	cancel func()
 	conn   *grpc.ClientConn
-
-	success int
-	failure int
+	// keyOps records the number of keys created and deleted by the stresser.
+	keyOps int64
```
Comment (xiang90) [inline tools/functional-tester/etcd-tester/key_stresser.go]: atomicModifiedKeys instead of keyOps?

Comment (fanminshi) [inline tools/functional-tester/etcd-tester/key_stresser.go]: done!

File: tools/functional-tester/etcd-tester/lease_stresser.go [hunk 11]
```diff
@@ -43,9 +45,8 @@ type leaseStresser struct {
 	ctx      context.Context
 
 	rateLimiter *rate.Limiter
-
-	success      int
-	failure      int
+	// keyOps records the number of keys created and deleted during a test case
+	keyOps       int64
```
Comment (xiang90) [inline tools/functional-tester/etcd-tester/lease_stresser.go]: atomicModifiedKeys?

File: tools/functional-tester/etcd-tester/lease_stresser.go (hunk 5 above)
Comment (xiang90) [inline tools/functional-tester/etcd-tester/lease_stresser.go]: @fanminshi Can we get this fixed?

File: tools/functional-tester/etcd-tester/tester.go [hunk 12]
```diff
@@ -48,11 +48,11 @@ func (tt *tester) runLoop() {
 	}
 
 	if err := tt.resetStressCheck(); err != nil {
-		plog.Errorf("%s failed to start stresser (%v)", err)
+		plog.Errorf("%s failed to start stresser (%v)", tt.logPrefix(), err)
 		return
 	}
 
-	var prevCompactRev int64
+	var preKeyOps int64
```
Comment (xiang90) [inline tools/functional-tester/etcd-tester/tester.go]: use modifiedKey all over the place? we still use KeyOps here and there.

**Comment by xiang90** [comment]
@fanminshi LGTM in general. Still a few minor issues to clean up. Defer to @heyitsanthony

File: tools/functional-tester/etcd-tester/tester.go (hunk 12 above)
Comment (fanminshi) [inline tools/functional-tester/etcd-tester/tester.go]: will change

**Comment by fanminshi** [comment]
ALL fixed. PTAL

File: tools/functional-tester/etcd-tester/lease_stresser.go (hunk 2 above)
Comment (heyitsanthony) [inline tools/functional-tester/etcd-tester/lease_stresser.go]: Huh? Since this is counting deletes as an operation as well, shouldn't `err := ls.rateLimiter.WaitN(ls.ctx, ls.numLeases*ls.keysPerLease)` in `leaseStresser.run` be changed to `err := ls.rateLimiter.WaitN(ls.ctx, ls.numLeases*2*ls.keysPerLease)` to account for that?

**Comment by heyitsanthony** [comment]
lgtm aside from the rate limit nit

File: tools/functional-tester/etcd-tester/lease_stresser.go (hunk 2 above)
Comment (fanminshi) [inline tools/functional-tester/etcd-tester/lease_stresser.go]: yeah, you are right. i'll update the limiter logic.

File: tools/functional-tester/etcd-tester/v2_stresser.go [hunk 13]
```diff
@@ -23,6 +23,8 @@ import (
 	"sync"
 	"time"
 
+	"sync/atomic"
```
Comment (xiang90) [inline tools/functional-tester/etcd-tester/v2_stresser.go]: move this close to line 24

**Comment by fanminshi** [comment]
ALL fixed.

**Comment by xiang90** [comment]
Let's get this merged. Thanks!
