### PR TITLE
clientv3: handle URL scheme when given in endpoint

### LINKED ISSUE #5427: V2 vs V3 http:// prefixes?
I suppose I'm a bit confused about the V2 -> V3 transition. It used to be that http:// prefixes were required for the client endpoints, but now they seem to cause:

```
2016/05/22 03:57:56 grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp: too many colons in address http://localhost:2379"; Reconnecting to "http://localhost:2379"
```

Similarly are peerUrls and clientUrls (in the golang API) supposed to have these or not? It's a little inconsistent in my mind, so some clarity would help. Or perhaps I'm just awake for too long.

Thanks

### PR DESCRIPTION
**Pull request by heyitsanthony**
Fixes #5427

### CODE REVIEW

**Comment by gyuho** [comment]
lgtm.

File: clientv3/client.go [hunk 1]
```diff
@@ -157,16 +158,22 @@ func (c *Client) Dial(endpoint string) (*grpc.ClientConn, error) {
...
-	if url, uerr := url.Parse(endpoint); uerr == nil && url.Scheme == "unix" {
-		proto = "unix"
-		// strip unix:// prefix so certs work
+	if url, uerr := url.Parse(endpoint); uerr == nil {
+		switch url.Scheme {
+		case "unix":
+			proto = "unix"
+		case "http":
+			c.creds = nil
+		case "https":
```
Comment (xiang90) [inline clientv3/client.go]: i think if user provides https without creds, we should use the default empty tls config as https://github.com/coreos/etcd/blob/master/etcdctl/ctlv3/command/global.go#L142

File: clientv3/client.go [hunk 2]
```diff
@@ -157,16 +158,22 @@ func (c *Client) Dial(endpoint string) (*grpc.ClientConn, error) {
...
-	} else {
-		opts = append(opts, grpc.WithInsecure())
-	}
 
 	proto := "tcp"
-	if url, uerr := url.Parse(endpoint); uerr == nil && url.Scheme == "unix" {
-		proto = "unix"
-		// strip unix:// prefix so certs work
+	if url, uerr := url.Parse(endpoint); uerr == nil {
+		switch url.Scheme {
```
Comment (xiang90) [inline clientv3/client.go]: shall we still allow empty scheme?

Comment (heyitsanthony) [inline clientv3/client.go]: yes, I think so-- will fix

File: clientv3/client.go (hunk 1 above)
Comment (heyitsanthony) [inline clientv3/client.go]: ok

Comment (heyitsanthony) [inline clientv3/client.go]: turns out --insecure-transport=false is broken
should it be defaulting to false (instead of true) anyway?

Comment (xiang90) [inline clientv3/client.go]: it should be defaulting to true until etcd enables tls by default.

**Comment by heyitsanthony** [comment]
all fixed up, the auto tls problem was because I had http instead of https for the advertised client url

File: clientv3/client.go [hunk 3]
```diff
@@ -157,16 +159,25 @@ func (c *Client) Dial(endpoint string) (*grpc.ClientConn, error) {
...
+	creds := c.creds
+	if url, uerr := url.Parse(endpoint); uerr == nil && strings.Contains(endpoint, "://") {
+		switch url.Scheme {
+		case "unix":
+			proto = "unix"
+		case "http":
+			creds = nil
+		case "https":
+			if creds == nil {
+				tlsconfig := &tls.Config{InsecureSkipVerify: true}
```
Comment (xiang90) [inline clientv3/client.go]: not sure we should skip cert checking by default.

**Comment by xiang90** [comment]
LGTM

File: clientv3/client.go (hunk 3 above)
Comment (heyitsanthony) [inline clientv3/client.go]: It's autogenerating the certs in this case-- should `ETCDCTL_API=3 ./etcdctl  --endpoints="https://localhost:2379" get a` fail without `--insecure-skip-verify`? I don't think there's a clean way to pass this flag to the client in general-- if there's some clientv3 consumer that's not etcdctl, it seems like it should `--insecure-skip-verify` by default if no credentials are given.

Comment (xiang90) [inline clientv3/client.go]: > I don't think there's a clean way to pass this flag to the client in general

They can pass in an empty tlsconf with insecure-skip set themselve. Yea, I do not think this is an issue. We just need to document this behavior.

Comment (heyitsanthony) [inline clientv3/client.go]: Thought about it some more-- if there's a TLS config in the client config then it'll use that as the credentials instead of creating an empty TLS for the https:// scheme case. I don't think verifying the certs makes sense if there's no given TLS config since there's no user-provided CA to compare against anyway.
