### PR TITLE
mvcc: fix TestHashKVWhenCompacting hash mismatch

### LINKED ISSUE #8311: TestHashKVWhenCompacting: hashes differ
via https://semaphoreci.com/coreos/etcd/branches/master/builds/2189

```
--- FAIL: TestHashKVWhenCompacting (1.28s)
	kvstore_test.go:561: Hashes differ (current 3655990207) != (saved 597152871)
```

/cc @fanminshi

### PR DESCRIPTION
**Pull request by fanminshi**
fixes #8311

### CODE REVIEW

**Comment by fanminshi** [comment]
this pr allows HashKV to get compaction Keep without modifying the treeIndex.

File: mvcc/index.go [hunk 1]
```diff
@@ -179,6 +180,19 @@ func (ti *treeIndex) Compact(rev int64) map[revision]struct{} {
 	return available
 }
 
+// Keep finds all revisions to be kept for a Compaction at the given rev.
+func (ti *treeIndex) Keep(rev int64) map[revision]struct{} {
+	available := make(map[revision]struct{})
+	ti.Lock()
```
Comment (heyitsanthony) [inline mvcc/index.go]: why isn't this `RLock`?

File: mvcc/key_index.go [hunk 2]
```diff
@@ -210,18 +223,21 @@ func (ki *keyIndex) compact(atRev int64, available map[revision]struct{}) {
 
 	if !g.isEmpty() {
 		n := g.walk(f)
-		// remove the previous contents.
-		if n != -1 {
-			g.revs = g.revs[n:]
-		}
 		// remove any tombstone
-		if len(g.revs) == 1 && i != len(ki.generations)-1 {
+		if len(g.revs)-1 == n && i != len(ki.generations)-1 {
```
Comment (heyitsanthony) [inline mvcc/key_index.go]: swapping the order of the if's doesn't look like it preserves the meaning; if `n > 0` then `delete(available, g.revs[0])` is not the same as the current code

File: mvcc/key_index.go [hunk 3]
```diff
@@ -187,6 +187,19 @@ func (ki *keyIndex) compact(atRev int64, available map[revision]struct{}) {
...
+// keep finds the revision to be kept if compact is called at given atRev.
+func (ki *keyIndex) keep(atRev int64, available map[revision]struct{}) {
+	if ki.isEmpty() {
+		return
+	}
+
+	ki.doCompact(atRev, available, false)
+}
+
+func (ki *keyIndex) doCompact(atRev int64, available map[revision]struct{}, doModify bool) {
```
Comment (heyitsanthony) [inline mvcc/key_index.go]: it's not good practice to have boolean arguments; possibly have
`func (ki *keyIndex) doCompact(atRev int64, available map[revision]struct{}) (genIdx int,  revIndex int)` and handle the modification after calling doCompact

File: mvcc/kvstore_test.go [hunk 4]
```diff
@@ -767,6 +767,10 @@ func (i *fakeIndex) Compact(rev int64) map[revision]struct{} {
 	i.Recorder.Record(testutil.Action{Name: "compact", Params: []interface{}{rev}})
 	return <-i.indexCompactRespc
 }
+func (i *fakeIndex) Keep(rev int64) map[revision]struct{} {
```
Comment (heyitsanthony) [inline mvcc/kvstore_test.go]: this should be in the same commit as the test update

File: mvcc/key_index.go (hunk 2 above)
Comment (fanminshi) [inline mvcc/key_index.go]: yeah, the code should be `delete(available, g.revs[n])` instead of `delete(available, g.revs[0])`.

Comment (heyitsanthony) [inline mvcc/key_index.go]: why wasn't this caught by unit tests?

Comment (fanminshi) [inline mvcc/key_index.go]: The unit tests calls Compact before Keep where Compaction on tombstone clears out the generation. Then the subsequent Keep on the same tombstone rev will not even hit `if len(g.revs)-1 == n && i != len(ki.generations)-1 {` since `if !g.isEmpty() {` will be empty.

e.g
```go
// Init Tree.
// key: "foo"
// rev: 16
// generations:
//    {empty}
//    {{14, 0}[1], {14, 1}[2], {16, 0}(t)[3]}
//    {{8, 0}[1], {10, 0}[2], {12, 0}(t)[3]}
//    {{2, 0}[1], {4, 0}[2], {6, 0}(t)[3]}

// Call Compact(12) keep = {}
// generations:
//    {empty}
//    {{14, 0}[1], {14, 1}[2], {16, 0}(t)[3]}

// Call Keep(12) keep = {} since there is no generation that contains rev 12.
```

File: mvcc/kvstore.go [hunk 5]
```diff
@@ -183,15 +177,7 @@ func (s *store) HashByRev(rev int64) (hash uint32, currentRev int64, compactRev
...
-	s.keepMu.Lock()
-	if s.keep == nil {
-		// ForceCommit ensures that txnRead begins after backend
-		// has committed all the changes from the prev completed compaction.
-		s.b.ForceCommit()
-		s.keep = emptyKeep
-	}
-	keep := s.keep
-	s.keepMu.Unlock()
+	keep := s.kvindex.Keep(rev)
```
Comment (heyitsanthony) [inline mvcc/kvstore.go]: only need to acquire `s.mu.RLock` instead of `s.mu.Lock` now?

**Comment by fanminshi** [comment]
all fixed. PTAL.

File: mvcc/key_index_test.go [hunk 6]
```diff
@@ -483,6 +510,22 @@ func TestKeyIndexCompact(t *testing.T) {
...
+func cloneKeyIndex(ki *keyIndex) *keyIndex {
+	generations := make([]generation, len(ki.generations))
+	for i, gen := range ki.generations {
+		generations[i] = *cloneGeneration(&gen)
+	}
+	return &keyIndex{ki.key, ki.modified, generations}
+}
+
+func cloneGeneration(g *generation) *generation {
+	var tmp []revision
```
Comment (heyitsanthony) [inline mvcc/key_index_test.go]: use go built-ins:
```go
tmp := make([]revision, len(g.revs))
copy(tmp, g.revs)
```

Comment (fanminshi) [inline mvcc/key_index_test.go]: If `g.revs` is nil, the above code will create a non nil tmp which causes comparison failures.
```sh
--- FAIL: TestKeyIndexCompactAndKeep (0.00s)
	key_index_test.go:451: #0: ki = g: created[{2 0}] ver[3], revs []mvcc.revision{mvcc.revision{main:2, sub:0}, mvcc.revision{main:4, sub:0}, mvcc.revision{main:6, sub:0}}
		g: created[{8 0}] ver[3], revs []mvcc.revision{mvcc.revision{main:8, sub:0}, mvcc.revision{main:10, sub:0}, mvcc.revision{main:12, sub:0}}
		g: created[{14 0}] ver[3], revs []mvcc.revision{mvcc.revision{main:14, sub:0}, mvcc.revision{main:14, sub:1}, mvcc.revision{main:16, sub:0}}
		g: created[{0 0}] ver[0], revs []mvcc.revision(nil)
		, want g: created[{2 0}] ver[3], revs []mvcc.revision{mvcc.revision{main:2, sub:0}, mvcc.revision{main:4, sub:0}, mvcc.revision{main:6, sub:0}}
		g: created[{8 0}] ver[3], revs []mvcc.revision{mvcc.revision{main:8, sub:0}, mvcc.revision{main:10, sub:0}, mvcc.revision{main:12, sub:0}}
		g: created[{14 0}] ver[3], revs []mvcc.revision{mvcc.revision{main:14, sub:0}, mvcc.revision{main:14, sub:1}, mvcc.revision{main:16, sub:0}}
		g: created[{0 0}] ver[0], revs []mvcc.revision{}
```

Comment (heyitsanthony) [inline mvcc/key_index_test.go]: OK:
```go
if len(g.revs) == nil {
    // preserve nils
    return nil
}
tmp := make([]revision, len(g.revs))
copy(tmp, g.revs)
return tmp
```

Comment (fanminshi) [inline mvcc/key_index_test.go]: the return type is `*generation`

I have the following

```go
func cloneGeneration(g *generation) *generation {
	if g.revs == nil {
		return &generation{g.ver, g.created, nil}
	}
	tmp := make([]revision, len(g.revs))
	copy(tmp, g.revs)
	return &generation{g.ver, g.created, tmp}
}
```

Comment (heyitsanthony) [inline mvcc/key_index_test.go]: ok..

**Comment by fanminshi** [comment]
via https://jenkins-etcd-public.prod.coreos.systems/job/etcd-ci-ppc64/1743/console

```sh
2017-08-01 03:15:30.669672 I | etcdserver/api/v3rpc: get error from resetTransport context canceled, transportMonitor returning
2017-08-01 03:15:30.669691 I | etcdserver/api/v3rpc: grpc: addrConn.transportMonitor exits due to: context canceled
Too many goroutines running after all test(s).
1 instances of:
google.golang.org/grpc.(*ClientConn).lbWatcher(...)
	/var/jenkins_home/workspace/etcd-ci-ppc64/gopath/src/google.golang.org/grpc/clientconn.go:499 +0x78
created by google.golang.org/grpc.DialContext.func3
	/var/jenkins_home/workspace/etcd-ci-ppc64/gopath/src/google.golang.org/grpc/clientconn.go:409 +0x194
1 instances of:
google.golang.org/grpc.(*addrConn).resetTransport(...)
	/var/jenkins_home/workspace/etcd-ci-ppc64/gopath/src/google.golang.org/grpc/clientconn.go:903 +0x754
google.golang.org/grpc.(*addrConn).transportMonitor(...)
	/var/jenkins_home/workspace/etcd-ci-ppc64/gopath/src/google.golang.org/grpc/clientconn.go:999 +0x460
google.golang.org/grpc.(*ClientConn).resetAddrConn.func1(...)
	/var/jenkins_home/workspace/etcd-ci-ppc64/gopath/src/google.golang.org/grpc/clientconn.go:640 +0x1bc
created by google.golang.org/grpc.(*ClientConn).resetAddrConn
	/var/jenkins_home/workspace/etcd-ci-ppc64/gopath/src/google.golang.org/grpc/clientconn.go:641 +0x5dc
exit status 1
FAIL	github.com/coreos/etcd/clientv3/integration	230.527s
```

Leaky test. I don't think it is related to this pr.

**Comment by heyitsanthony** [comment]
that's a grpc leak, fine to ignore

**Comment by fanminshi** [comment]
proxy-ci fails via https://github.com/coreos/etcd/issues/6934.
I don't believe this is cause by this pr.
