### PR TITLE
discovery: add upper limit for waiting on a retry

### LINKED ISSUE #6648: No upper limit on discovery
Discovery is failing with the following:

```
discovery: error #0: x509: failed to load system roots and no roots provided
```

This failure is understood and expected. The backoff, however, isn't behaving reasonably:

```
discovery: error #0: x509: failed to load system roots and no roots provided
discovery: cluster status check: error connecting to https://discovery.etcd.io, retrying in 34m8s
discovery: error #0: x509: failed to load system roots and no roots provided
discovery: cluster status check: error connecting to https://discovery.etcd.io, retrying in 1h8m16s
```

There should be a max backoff for any single attempt in addition to a maximum number of attempts before failure.

### PR DESCRIPTION
**Pull request by fanminshi**
Adding upper limit ensures that expoential backoff doesn't reach more than 5 min on a re-try.

FIX #6648

### CODE REVIEW

**Comment by fanminshi** [comment]
PLTAL cc/ @xiang90 @crawford

File: discovery/discovery.go [hunk 1]
```diff
@@ -268,9 +269,15 @@ func (d *discovery) checkCluster() ([]*client.Node, int, uint64, error) {
 
 func (d *discovery) logAndBackoffForRetry(step string) {
 	d.retries++
-	retryTime := time.Second * (0x1 << d.retries)
+	var retryTime uint
+	// logAndBackoffForRetry stops exponential backoff after the 8th try which is around 256 second. Afterward, it does a constant backoff.
+	if d.retries < 9 {
```
Comment (xiang90) [inline discovery/discovery.go]: use floor(log2(maxWaitInSeconds)) instead?

Comment (fanminshi) [inline discovery/discovery.go]: yep, that's better

Comment (xiang90) [inline discovery/discovery.go]: ok. sure.

**Comment by fanminshi** [comment]
PTAL cc @xiang90

**Comment by xiang90** [comment]
lgtm.

**Comment by crawford** [comment]
I prefer something closer to https://github.com/coreos/ignition/blob/5dd13c9c174b40dfefb09d777d2bd890e8ba6fa7/internal/resource/http.go#L31. That way you can actually keep track of the number of attempts. It's probably okay though.

**Comment by fanminshi** [comment]
@crawford My code does not modify the retries counter. So I could still track number of the failed attempts.
https://github.com/fanminshi/etcd/blob/discovery_max_wait/discovery/discovery.go#L271-L273

**Comment by crawford** [comment]
Okay. This is no longer an exponential backoff.

**Comment by fanminshi** [comment]
@crawford  yeah, the exponential back off stops at 8th retry attempt. every retry afterward will be a  constant backoff about 2^8 = 256 second. Is this a reasonable backoff strategy?

**Comment by crawford** [comment]
It's linear not exponential though. Unless I'm missing something.

File: discovery/discovery.go [hunk 2]
```diff
@@ -268,9 +269,14 @@ func (d *discovery) checkCluster() ([]*client.Node, int, uint64, error) {
...
 	d.retries++
-	retryTime := time.Second * (0x1 << d.retries)
-	plog.Infof("%s: error connecting to %s, retrying in %s", step, d.url, retryTime)
-	d.clock.Sleep(retryTime)
+	// logAndBackoffForRetry stops exponential backoff when the retries are more than maxExpoentialRetries and is set to a constant backoff afterward.
+	retries := d.retries
+	if retries > maxExpoentialRetries {
+		retries = maxExpoentialRetries
+	}
+	retryTimeInSecond := time.Duration(retries) * time.Second
```
Comment (xiang90) [inline discovery/discovery.go]: this should still be (0x1 << retries)

**Comment by xiang90** [comment]
@crawford @fanminshi 

For the first N retries, wait time grows exponentially. After that the wait time should fixed. The upper bound is 1 << N seconds.

File: discovery/discovery.go (hunk 2 above)
Comment (fanminshi) [inline discovery/discovery.go]: good catch

**Comment by fanminshi** [comment]
All Fixed. PTAL cc/@xiang90 @crawford

**Comment by crawford** [comment]
LGTM

**Comment by xiang90** [comment]
CI fails due to https://github.com/coreos/etcd/issues/6535. So not relevant to this PR.
