### PR TITLE
fix context time-out failure on travis

### LINKED ISSUE #1949: context time-out failure on travis
We need to dig into that problem a little bit.
never happened on my local machine though

### PR DESCRIPTION
**Pull request by yichengq**
fixes #1949 
It passes travis tests in 40 times.

I set `ETCD_ELECTION_TIMEOUT_TICKS` environment as 200 in travis to extend election timeout, which avoids unexpected leader election due to instability of travis.

### CODE REVIEW

File: etcdserver/server.go [hunk 1]
```diff
@@ -63,6 +63,8 @@ const (
 	StoreKeysPrefix  = "/1"
 
 	purgeFileInterval = 30 * time.Second
+
+	StopDelay = 10 * 100 * time.Millisecond
```
Comment (xiang90) [inline etcdserver/server.go]: stopDelayInMs

**Comment by xiang90** [comment]
lgtm
