### PR TITLE
integration: permit background watch streams in TestWatchCancelOnServer

### LINKED ISSUE #7272: grpcproxy: TestWatchCancelOnServer: expected 0 watchers, got 1
via https://jenkins-etcd.prod.coreos.systems/job/etcd-proxy/633/console
```
--- FAIL: TestWatchCancelOnServer (1.53s)
	watch_test.go:829: expected 0 watchers, got "1"
```

### PR DESCRIPTION
**Pull request by heyitsanthony**
Fixes #7272

### CODE REVIEW

File: clientv3/integration/watch_test.go [hunk 1]
```diff
@@ -804,21 +804,39 @@ func TestWatchCancelOnServer(t *testing.T) {
...
-		t.Fatalf("expected 0 watchers, got %q", watchers)
+
+	maxWatchV, minWatchV := 0, 0
+	n, serr := fmt.Sscanf(maxWatches+" "+minWatches, "%d %d", &maxWatchV, &minWatchV)
+	if n != 2 || serr != nil {
+		t.Fatalf("expected n=2 and err=nil, got n=%d and err=%v", n, serr)
+	}
+
+	if maxWatchV-minWatchV != numWatches {
+		t.Fatalf("expected 0 outstanding watchers, got %d", maxWatchV-minWatchV)
```
Comment (gyuho) [inline clientv3/integration/watch_test.go]: Did we mean to say `expected %d ...", numWatches`?

Comment (heyitsanthony) [inline clientv3/integration/watch_test.go]: oh, yeah this error string doesn't make sense.

**Comment by gyuho** [comment]
LGTM. Thanks!
