### PR TITLE
etcdctl: better logging for sync process

### LINKED ISSUE #3402: `client: no endpoints available` when using etcdctl
Start 3-member etcd cluster, and set `-listen-peer-urls` to some value unrelated, so etcd cluster cannot talk to each other.

```
$./bin/etcdctl -C 127.0.0.1:4001 --debug cluster-health
Error:  client: no endpoints available
```

There is no more details about the failure, which is hard to explain and reason about. Actually, this fails because it fails to sync when creating client struct. My thought is to print out the fact that it is syncing and curl command when Sync members.

/cc @mischief

### PR DESCRIPTION
**Pull request by yichengq**
Original issue reveals the problem that users don't even know that etcdctl is doing sync and fails on sync process. So we add more logs for sync process.

After this PR, failure case:

```
$ ./bin/etcdctl --debug set foo bar
start to sync cluster using endpoints(http://127.0.0.1:2379,http://127.0.0.1:4001)
cURL Command: curl -X GET http://127.0.0.1:2379/v2/members
cURL Command: curl -X GET http://127.0.0.1:4001/v2/members
Error:  client: etcd cluster is unavailable or misconfigured
error #0: dial tcp 127.0.0.1:2379: getsockopt: connection refused
error #1: dial tcp 127.0.0.1:4001: getsockopt: connection refused
```

success case:
```
start to sync cluster using endpoints(http://127.0.0.1:4001,http://127.0.0.1:2379)
cURL Command: curl -X GET http://127.0.0.1:4001/v2/members
got endpoints(http://localhost:2379,http://localhost:4001) after sync
Cluster-Endpoints: http://localhost:2379, http://localhost:4001
cURL Command: curl -X PUT http://localhost:2379/v2/keys/foo -d "value=bar"
bar
```

fixes #3402

### CODE REVIEW

File: etcdctl/command/util.go [hunk 1]
```diff
@@ -217,6 +222,9 @@ func mustNewClient(c *cli.Context) client.Client {
 	}
 
 	if !c.GlobalBool("no-sync") {
+		if c.GlobalBool("debug") {
+			fmt.Fprintf(os.Stderr, "fetching the whole set of advertised client urls as cluster endpoints\n")
```
Comment (xiang90) [inline etcdctl/command/util.go]: can we simply print out something like "start to sync cluster" and print out the result of sync?

**Comment by yichengq** [comment]
updated. PTAL

**Comment by xiang90** [comment]
LGTM
