### PR TITLE
gateway: fix the dns discovery method

### LINKED ISSUE #7452: ETCD Gateway does not work with DNS discovery
ETCD Gateway seems not to strip the http:// or https:// schema from the discovered hostnames.

This one does not work:

```shell
etcd gateway start --discovery-srv="k8s-cluster.intern" --insecure-discovery=true
2017-03-08 14:13:53.928749 I | etcdmain: discovered the cluster [http://etcd-node-3.:2379 http://etcd-node-2.:2379 http://etcd-node-1.:2379] from k8s-cluster.intern
2017-03-08 14:13:53.929070 I | proxy/tcpproxy: ready to proxy client requests to [127.0.0.1:2379]
```

With TLS

```shell
etcd gateway start --discovery-srv="k8s-cluster.intern" --listen-addr="0.0.0.0:2379"
2017-03-08 14:29:52.158063 I | etcdmain: discovered the cluster [https://etcd-node-3.k8s-cluster.intern.:2379 https://etcd-node-2.k8s-cluster.intern.:2379 https://etcd-node-1.k8s-cluster.intern.:2379] from k8s-cluster.intern
2017-03-08 14:29:52.158241 I | etcdmain: validating discovered endpoints [https://etcd-node-3.k8s-cluster.intern.:2379 https://etcd-node-2.k8s-cluster.intern.:2379 https://etcd-node-1.k8s-cluster.intern.:2379]
2017-03-08 14:29:52.165461 I | etcdmain: using discovered endpoints [https://etcd-node-3.k8s-cluster.intern.:2379 https://etcd-node-2.k8s-cluster.intern.:2379 https://etcd-node-1.k8s-cluster.intern.:2379]
2017-03-08 14:29:52.165668 I | proxy/tcpproxy: ready to proxy client requests to [https://etcd-node-3.k8s-cluster.intern.:2379 https://etcd-node-2.k8s-cluster.intern.:2379 https://etcd-node-1.k8s-cluster.intern.:2379]
2017-03-08 14:30:46.745443 W | proxy/tcpproxy: deactivated endpoint [https://etcd-node-3.k8s-cluster.intern.:2379] due to dial tcp: too many colons in address https://etcd-node-3.k8s-cluster.intern.:2379 for 1m0s
2017-03-08 14:30:46.745498 W | proxy/tcpproxy: deactivated endpoint [https://etcd-node-2.k8s-cluster.intern.:2379] due to dial tcp: too many colons in address https://etcd-node-2.k8s-cluster.intern.:2379 for 1m0s
2017-03-08 14:30:46.745528 W | proxy/tcpproxy: deactivated endpoint [https://etcd-node-1.k8s-cluster.intern.:2379] due to dial tcp: too many colons in address https://etcd-node-1.k8s-cluster.intern.:2379 for 1m0s
2017-03-08 14:30:52.166168 W | proxy/tcpproxy: failed to activate endpoint [https://etcd-node-1.k8s-cluster.intern.:2379] due to dial tcp: too many colons in address https://etcd-node-1.k8s-cluster.intern.:2379 (stay inactive for another 1m0s)
2017-03-08 14:30:52.166236 W | proxy/tcpproxy: failed to activate endpoint [https://etcd-node-3.k8s-cluster.intern.:2379] due to dial tcp: too many colons in address https://etcd-node-3.k8s-cluster.intern.:2379 (stay inactive for another 1m0s)
2017-03-08 14:30:52.166277 W | proxy/tcpproxy: failed to activate endpoint [https://etcd-node-2.k8s-cluster.intern.:2379] due to dial tcp: too many colons in address https://etcd-node-2.k8s-cluster.intern.:2379 (stay inactive for another 1m0s)
```

Specifying the endpoints manually without the scheme works:

```shell
etcd gateway start --endpoints="etcd-node-1:2379,etcd-node-2:2379,etcd-node-3:2379"  --listen-addr="0.0.0.0:2379"
2017-03-08 14:18:05.391698 I | proxy/tcpproxy: ready to proxy client requests to [etcd-node-1:2379 etcd-node-2:2379 etcd-node-3:2379]
```

### PR DESCRIPTION
**Pull request by bdudelsack**
strip the scheme from the endpoints to have a clean hostname for TCP proxy

Fixes #7452

### CODE REVIEW

File: etcdmain/gateway.go [hunk 1]
```diff
@@ -77,6 +78,23 @@ func newGatewayStartCommand() *cobra.Command {
 	return &cmd
 }
 
+func stripSchema(eps []string) []string {
+	var endpoints []string
+
+	for _, ep := range eps {
+
+		if strings.HasPrefix(ep, "https://") {
```
Comment (heyitsanthony) [inline etcdmain/gateway.go]: use the url library instead?
```go
if u, err := url.Parse(ep); err != nil {
    ep = u.Host
}
endpoints = append(endpoints, ep)
```

File: etcdmain/gateway.go [hunk 2]
```diff
@@ -24,6 +24,7 @@ import (
 	"github.com/coreos/etcd/pkg/transport"
 	"github.com/coreos/etcd/proxy/tcpproxy"
 	"github.com/spf13/cobra"
+	"strings"
```
Comment (heyitsanthony) [inline etcdmain/gateway.go]: standard library packages (e.g., net, os, strings) should be group together at the beginning of the import

File: etcdmain/gateway.go [hunk 3]
```diff
@@ -77,6 +78,23 @@ func newGatewayStartCommand() *cobra.Command {
 	return &cmd
 }
 
+func stripSchema(eps []string) []string {
```
Comment (fanminshi) [inline etcdmain/gateway.go]: Can we add unit tests for this function? I would like to increase the etcd coverage.

Comment (heyitsanthony) [inline etcdmain/gateway.go]: the discovery stuff should eventually be covered by e2e tests; I don't think a unit test is necessary here

File: etcdmain/gateway.go (hunk 1 above)
Comment (bdudelsack) [inline etcdmain/gateway.go]: I wanted it to be general and parse the endpoints passed by "--endpoints" param too. I think it could be a common mistake to add "http://" or "https://" to that parameter. 

I could use the url library, but then parse only the endpoints which come from the dns discovery, or use this method for both. I don't think url method would work with correct hostnames like "etcd-node:2379" without further checks.

Comment (heyitsanthony) [inline etcdmain/gateway.go]: Oh, sorry. I meant:
```go
if u, err := url.Parse(ep); err == nil {
    ep = u.Host
}
endpoints = append(endpoints, ep)
```
It'll strip the schema off a valid url and leave anything else (e.g., etcd-node:2379) alone.

Comment (bdudelsack) [inline etcdmain/gateway.go]: `url.Parse` seems to treat it like a relative path, so my tests are failing:

```
--- FAIL: TestStripSchema (0.00s)
        gateway_test.go:24: Expected stripSchema to return 'etcd-node:2379' from 'etcd-node:2379' but got ''
        gateway_test.go:24: Expected stripSchema to return 'etcd-node' from 'etcd-node' but got ''
```

Comment (heyitsanthony) [inline etcdmain/gateway.go]: OK, so `if u, err := url.Parse(ep); err == nil && u.Host != ""`?

File: etcdmain/gateway_test.go [hunk 4]
```diff
@@ -0,0 +1,27 @@
+package etcdmain
```
Comment (heyitsanthony) [inline etcdmain/gateway_test.go]: I don't think this test is necessary...

File: etcdmain/gateway.go (hunk 1 above)
Comment (bdudelsack) [inline etcdmain/gateway.go]: That would work :ok_hand:

File: etcdmain/gateway.go (hunk 3 above)
Comment (fanminshi) [inline etcdmain/gateway.go]: @bdudelsack  heyitsanthony is right about not having the unit test. The test path should be covered in e2e test where the correct behavior gateway should be verified. Sorry for the wrong suggestion.

**Comment by bdudelsack** [comment]
Build failed couse of

```
$WORK/github.com/coreos/etcd/integration/_test/integration.test: no space left on device
```

**Comment by fanminshi** [comment]
lgtm Thanks!
