### PR TITLE
embed: Delay setting initial cluster

### LINKED ISSUE #7516: Multiple discovery flags error with valid config file
A valid config file triggers a config verification bug about multiple discovery/boot strap flags.

In my example, I'm clearly **only** specifying `discovery-srv`.

Bug is present in latest release (3.1.3) and also with all the older 3.0 releases I've tried (3.0.15, 3.0.17).

## Example

Given a config file:

`config.json`:
```json
{
    "advertise-client-urls": "http://etcd.test:2379",
    "discovery-srv": "test",
    "initial-advertise-peer-urls": "http://etcd.test:2380",
    "initial-cluster-state": "new",
    "initial-cluster-token": "token",
    "listen-client-urls": "http://etcd1.test:2379",
    "listen-peer-urls": "http://etcd1.test:2380",
    "name": "etcd1"
}
```

And trying to start etcd:

```
> etcd-v3.1.3-darwin-amd64/etcd --config-file config.json
2017-03-16 12:05:21.978435 I | etcdmain: Loading server configuration from "config.json"
2017-03-16 12:05:21.978858 W | embed: expected IP in URL for binding (http://etcd1.test:2380)
2017-03-16 12:05:21.978869 W | embed: expected IP in URL for binding (http://etcd1.test:2379)
2017-03-16 12:05:21.978875 E | etcdmain: error verifying flags, multiple discovery or bootstrap flags are set. Choose one of "initial-cluster", "discovery" or "discovery-srv". See 'etcd --help'.
```

The equivalent invocation using CLI flags works just fine however:

```
./etcd-v3.1.3-darwin-amd64/etcd \
    --name "etcd1" \
    --discovery-srv "test" \
    --advertise-client-urls "http://etcd.test:2379" \
    --initial-advertise-peer-urls "http://etcd.test:2380" \
    --initial-cluster-state "new" \
    --initial-cluster-token "token" \
    --listen-client-urls "http://etcd1.test:2379" \
    --listen-peer-urls "http://etcd1.test:2380"
```

## Hack fix

The only way to get etcd to accept this config is by adding an empty `initial-cluster` string, which contradicts the error message (I have `initial-cluster` **and** `discovery-srv` specified).

`hacked-config.json`:
```json
{
    "advertise-client-urls": "http://etcd.test:2379",
    "discovery-srv": "test",
    "initial-advertise-peer-urls": "http://etcd.test:2380",
    "initial-cluster": "",
    "initial-cluster-state": "new",
    "initial-cluster-token": "token",
    "listen-client-urls": "http://etcd1.test:2379",
    "listen-peer-urls": "http://etcd1.test:2380",
    "name": "etcd1"
}
```

and now etcd will start:

```
> etcd-v3.1.3-darwin-amd64/etcd --config-file config.json
2017-03-16 12:07:55.997893 I | etcdmain: Loading server configuration from "config.json"
2017-03-16 12:07:55.998342 W | embed: expected IP in URL for binding (http://etcd1.test:2380)
2017-03-16 12:07:55.998353 W | embed: expected IP in URL for binding (http://etcd1.test:2379)
2017-03-16 12:07:55.998477 I | etcdmain: etcd Version: 3.1.3
2017-03-16 12:07:55.998483 I | etcdmain: Git SHA: 21fdcc6
2017-03-16 12:07:55.998486 I | etcdmain: Go Version: go1.7.5
2017-03-16 12:07:55.998488 I | etcdmain: Go OS/Arch: darwin/amd64
2017-03-16 12:07:55.998493 I | etcdmain: setting maximum number of CPUs to 8, total number of available CPUs is 8
2017-03-16 12:07:55.998498 N | etcdmain: failed to detect default host (default host not supported on darwin_amd64)
2017-03-16 12:07:55.998504 W | etcdmain: no data-dir provided, using default data-dir ./etcd1.etcd
```

### PR DESCRIPTION
**Pull request by jsok**
`embed.NewConfig()` sets the initial cluster from name but we should clear it in the event that another discovery option has been specified.

Fixes #7516

### CODE REVIEW

File: embed/config.go [hunk 1]
```diff
@@ -246,6 +245,9 @@ func (cfg *configYAML) configFromFile(path string) error {
 		cfg.ACUrls = []url.URL(u)
 	}
 
+	if (cfg.Durl == "" && cfg.DNSCluster == "") && cfg.InitialCluster == "" {
```
Comment (heyitsanthony) [inline embed/config.go]: probably have `cfg.InitialCluster == cfg.InitialClusterFromName(DefaultName)` instead of `== ""` and keep the `InitialCluster` line in `NewConfig`? otherwise the default will be blank for non-yaml cases

Comment (jsok) [inline embed/config.go]: 👍 
Have left the default and instead clear it once we have parsed the config.

**Comment by heyitsanthony** [comment]
lgtm
