### PR TITLE
storage: use creation revision to compute txn event types

### LINKED ISSUE #4688: TestDoubleBarrier fails
https://semaphoreci.com/coreos/etcd/branches/pull-request-4687/builds/2

```
=== RUN   TestDoubleBarrier
--- FAIL: TestDoubleBarrier (1.23s)
	v3_double_barrier_test.go:62: barrier enter timed out
	v3_double_barrier_test.go:41: could not leave on barrier (context canceled)
	v3_double_barrier_test.go:41: could not leave on barrier (context canceled)
	v3_double_barrier_test.go:41: could not leave on barrier (context canceled)
	v3_double_barrier_test.go:41: could not leave on barrier (context canceled)
	v3_double_barrier_test.go:41: could not leave on barrier (context canceled)
	v3_double_barrier_test.go:41: could not leave on barrier (context canceled)
	v3_double_barrier_test.go:41: could not leave on barrier (context canceled)
```

### PR DESCRIPTION
**Pull request by heyitsanthony**
Fixes #4688

### CODE REVIEW

File: storage/watchable_store.go [hunk 1]
```diff
@@ -138,8 +138,8 @@ func (s *watchableStore) TxnEnd(txnID int64) error {
 	rev := s.store.Rev()
 	evs := make([]storagepb.Event, len(changes))
 	for i, change := range changes {
-		switch change.Value {
-		case nil:
+		switch change.CreateRevision {
```
Comment (xiang90) [inline storage/watchable_store.go]: unit test for this?

**Comment by xiang90** [comment]
lgtm

**Comment by heyitsanthony** [comment]
added test; will merge on greenlight
