### PR TITLE
grpcproxy: only return ctx error in chan stream if recvc is empty

### LINKED ISSUE #7340: grpcproxy: TestGRPCStreamRequireLeader  err = context canceled
via https://jenkins-etcd-public.prod.coreos.systems/job/etcd-proxy/693/
```
--- FAIL: TestGRPCStreamRequireLeader (1.25s)
	v3_grpc_test.go:1391: err = context canceled, want etcdserver: no leader
```

### PR DESCRIPTION
**Pull request by heyitsanthony**
Since select{} won't prioritize, ctx.Done() can sometimes override
a pending message on recvc. Loop if recvc has messages instead.

Fixes #7340

### CODE REVIEW

File: proxy/grpcproxy/chan_stream.go [hunk 1]
```diff
@@ -116,17 +116,24 @@ func (s *chanStream) SendMsg(m interface{}) error {
...
 	v := m.(*interface{})
-	select {
-	case msg, ok := <-s.recvc:
-		if !ok {
-			return grpc.ErrClientConnClosing
+	for {
+		select {
+		case msg, ok := <-s.recvc:
+			if !ok {
+				s.cancel()
```
Comment (gyuho) [inline proxy/grpcproxy/chan_stream.go]: This makes sense.
Did we just forget to cancel this context before? And now it fixes?

Comment (heyitsanthony) [inline proxy/grpcproxy/chan_stream.go]: That bit is just extra paranoia. The problem from recvc being buffered and doing:
```go
ch <- x
cancel()
```
which leads to the `select{}` here having both `<-s.recvc` and `<-s.ctx.Done()` available for reading. Since go won't prioritize selects, it would randomly choose `s.ctx.Done` over `s.recvc` and return a context canceled error.

Comment (heyitsanthony) [inline proxy/grpcproxy/chan_stream.go]: Changing it back since it's not relevant to the fix

**Comment by gyuho** [comment]
LGTM
