### PR TITLE
integration: permit dropping intermediate leader values on observe

### LINKED ISSUE #7749: TestV3ElectionObserve: got observe value "9", expected "5"
https://semaphoreci.com/coreos/etcd/branches/master/builds/1809

```
--- FAIL: TestV3ElectionObserve (0.83s)
	v3election_grpc_test.go:114: got observe value "9", expected "5"
```

### PR DESCRIPTION
**Pull request by heyitsanthony**
Weaken TestV3ElectionObserve so it only checks that it observes a strictly
monotonically ascending leader transition sequence following the first
observed leader. First, the Observe will issue the leader channel before
getting a response for its first get; the election revision is only bound
after returning the channel. So, Observe can't be expected to always
return the leader at the time it was started.  Second, Observe fetches
the current leader based on its create revision, but begins watching on its
ModRevision; this is important so that elections still work in case the
leader issues proclamations following a compaction that exceeds its
creation revision. So, Observe can't be expected to return the entire
proclamation sequence for a single leader.

Fixes #7749

### CODE REVIEW

**Comment by xiang90** [comment]
> So, Observe can't be expected to return the entire
proclamation sequence for a single leader.

This makes application life harder. Most users would assume the observer will return ALL leader proposal values as we doced here: https://github.com/coreos/etcd/blob/master/clientv3/concurrency/election.go#L151.

I feel it is OK to close the chan and return error if there is a compaction. it is similar to watch case.

**Comment by heyitsanthony** [comment]
@xiang90 OK, well it doesn't behave like that now. We could change the godoc. Making assumptions that people expect error behaviors and will write application logic to recover from that hasn't really worked out great in the past.

**Comment by heyitsanthony** [comment]
Plus, I doubt there's going to be any sort of recovery logic that would be anything besides reopen the election and get the greatest value. There's also revision information in the GetResponse, so it's possible to see if there was a missed proclamation as it is now.

**Comment by xiang90** [comment]
> Making assumptions that people expect error behaviors and will write application logic to recover from that hasn't really worked out great in the past.

I feel silently dropping proposals is more difficult to handle. That is why we close watch chan when it get compacted. If we can successfully recover from failure when etcd cluster is healthy again, i agree we should hide all the errors. but i think this case is different.

**Comment by heyitsanthony** [comment]
@xiang90 they're not silently dropped, though-- it's possible to tell based on the GetResponse by checking the key version. Watch is different because there's no way to reliably discern whether there were intermediate events based on the event data in general (e.g., if watching on multiple keys or if there was a create / delete / create on a single key). Elections now will drop old proclamations from a leader, but it will not have the create / delete / create issue or missing intermediate key issue. Trying to support this case will only force elections to error out more often / force the client to consume more data than it typically needs when it usually only cares about the most recent leader and most recent leader value.

**Comment by xiang90** [comment]
@heyitsanthony 

OK, thanks for the explanation. Now I understand it better. I will think about this more, and let you know.

**Comment by heyitsanthony** [comment]
An even more aggressive approach to unneeded election values:

Currently `Observe` fetches the next leader based on the delete revision of the former leader. This guarantees the observer always sees the last value of each leader.

The fetch policy can potentially be relaxed further to get the current leader using the current revision. It would silently skip intermediate leaders but have better performance / less chance of compaction errors. This would be useful in cases where the client really only cares about the most recent leader and there were a bunch of leaders that resigned between the last leader and the current leader. Whether this is an effective optimization in practice is debatable since I would assume the last leader delete revision is approximately the current revision unless the client is really far behind or there's a lot of election churn.

Essentially, there are different levels of delivery guarantees for election observation; it's not really clear what's the best.

**Comment by xiang90** [comment]
@heyitsanthony Let us fix this by a better documentation? We can wait to see users' feedback. I am not sure what they expect either. I do not know if it is a valid use case to ask for all proposals.

File: clientv3/concurrency/election.go [hunk 1]
```diff
@@ -148,9 +148,10 @@ func (e *Election) Leader(ctx context.Context) (*v3.GetResponse, error) {
 	return resp, nil
 }
 
-// Observe returns a channel that observes all leader proposal values as
-// GetResponse values on the current leader key. The channel closes when
-// the context is cancelled or the underlying watcher is otherwise disrupted.
+// Observe returns a channel that reliably observes ordered leader proposals
```
Comment (xiang90) [inline clientv3/concurrency/election.go]: maybe mention when we might miss a proposal?

**Comment by xiang90** [comment]
LGTM
